os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_stat.c File Reference
bad_stat.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static int badbuf_fstat (struct stat *sb)
static int badbuf_lstat (struct stat *sb)
static int badbuf_stat (struct stat *sb)
static void common_badbuf (int(*statfunc)(struct stat *), void *ptr, const char *call, const char *ptrdesc)
static void any_badbuf (int(*statfunc)(struct stat *), const char *call)
static void any_empty (int(*statfunc)(const char *, struct stat *), const char *call)
void test_fstat (void)
void test_lstat (void)
void test_stat (void)
Function Documentation
any_badbuf()
static void any_badbuf (int(*)(struct stat *) statfunc, const char * call) static
Definition at line 83 of file bad_stat.c.
References common_badbuf(), and NULL.
Referenced by test_fstat(), test_lstat(), and test_stat().
any_empty()
static void any_empty (int(*)(const char *, struct stat *) statfunc, const char * call) static
Definition at line 94 of file bad_stat.c.
References EINVAL, errno, report_begin(), report_check2(), and sb.
Referenced by test_lstat(), and test_stat().
badbuf_fstat()
static int badbuf_fstat (struct stat * sb) static
Definition at line 50 of file bad_stat.c.
References fstat(), sb, and STDIN_FILENO.
Referenced by test_fstat().
badbuf_lstat()
static int badbuf_lstat (struct stat * sb) static
Definition at line 57 of file bad_stat.c.
References lstat(), and sb.
Referenced by test_lstat().
badbuf_stat()
static int badbuf_stat (struct stat * sb) static
Definition at line 64 of file bad_stat.c.
References sb, and stat().
Referenced by test_stat().
common_badbuf()
static void common_badbuf (int(*)(struct stat *) statfunc, void * ptr, const char * call, const char * ptrdesc) static
Definition at line 71 of file bad_stat.c.
References EFAULT, errno, report_begin(), and report_check().
Referenced by any_badbuf().
test_fstat()
void test_fstat (void)
Definition at line 107 of file bad_stat.c.
References any_badbuf(), badbuf_fstat(), and test_fstat_fd().
test_lstat()
void test_lstat (void)
Definition at line 114 of file bad_stat.c.
References any_badbuf(), any_empty(), badbuf_lstat(), lstat(), and test_lstat_path().
test_stat()
void test_stat (void)
Definition at line 122 of file bad_stat.c.
References any_badbuf(), any_empty(), badbuf_stat(), and test_stat_path().