os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/vm/addrspace.c File Reference
addrspace.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <addrspace.h>
#include <vm.h>
#include <proc.h>
Functions
struct addrspace * as_create (void)
int as_copy (struct addrspace *old, struct addrspace **ret)
void as_destroy (struct addrspace *as)
void as_activate (void)
void as_deactivate (void)
int as_define_region (struct addrspace *as, vaddr_t vaddr, size_t memsize, int readable, int writeable, int executable)
int as_prepare_load (struct addrspace *as)
int as_complete_load (struct addrspace *as)
int as_define_stack (struct addrspace *as, vaddr_t *stackptr)
Function Documentation
as_activate()
void as_activate (void)
Definition at line 91 of file addrspace.c.
References NULL, NUM_TLB, proc_getas(), splhigh(), splx(), tlb_write(), TLBHI_INVALID, and TLBLO_INVALID.
as_complete_load()
int as_complete_load (struct addrspace * as)
Definition at line 158 of file addrspace.c.
References dumbvm_can_sleep().
as_copy()
int as_copy (struct addrspace * old, struct addrspace ** ret)
Definition at line 61 of file addrspace.c.
References as_create(), as_destroy(), as_prepare_load(), dumbvm_can_sleep(), DUMBVM_STACKPAGES, ENOMEM, KASSERT, memmove(), NULL, PADDR_TO_KVADDR, and PAGE_SIZE.
as_create()
struct addrspace* as_create (void)
Definition at line 44 of file addrspace.c.
References kmalloc(), and NULL.
Referenced by as_copy().
as_deactivate()
void as_deactivate (void)
Definition at line 110 of file addrspace.c.
as_define_region()
int as_define_region (struct addrspace * as, vaddr_t vaddr, size_t memsize, int readable, int writeable, int executable)
Definition at line 130 of file addrspace.c.
References dumbvm_can_sleep(), ENOSYS, kprintf(), PAGE_FRAME, and PAGE_SIZE.
as_define_stack()
int as_define_stack (struct addrspace * as, vaddr_t * stackptr)
Definition at line 169 of file addrspace.c.
References KASSERT, and USERSTACK.
as_destroy()
void as_destroy (struct addrspace * as)
Definition at line 81 of file addrspace.c.
References dumbvm_can_sleep(), and kfree().
as_prepare_load()
int as_prepare_load (struct addrspace * as)
Definition at line 147 of file addrspace.c.
References as_zero_region(), dumbvm_can_sleep(), DUMBVM_STACKPAGES, ENOMEM, getppages(), and KASSERT.