os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/fs/semfs/semfs_fsops.c File Reference
semfs_fsops.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <synch.h>
#include <vfs.h>
#include <fs.h>
#include <vnode.h>
#include "semfs.h"
Functions
static int semfs_sync (struct fs *fs)
static const char * semfs_getvolname (struct fs *fs)
static int semfs_getroot (struct fs *fs, struct vnode **ret)
static void semfs_destroy (struct semfs *semfs)
static int semfs_unmount (struct fs *fs)
static struct semfs * semfs_create (void)
void semfs_bootstrap (void)
Variables
static const struct fs_ops semfs_fsops
Function Documentation
semfs_bootstrap()
void semfs_bootstrap (void)
Definition at line 213 of file semfs_fsops.c.
References NULL, panic(), semfs::semfs_absfs, semfs_create(), strerror(), and vfs_addfs().
Referenced by vfs_bootstrap().
semfs_create()
static struct semfs* semfs_create (void) static
Definition at line 159 of file semfs_fsops.c.
References fs::fs_data, fs::fs_ops, kfree(), kmalloc(), lock_create(), lock_destroy(), NULL, semfs::semfs_absfs, semfs::semfs_dents, semfs::semfs_dirlock, semfs_fsops, semfs::semfs_sems, semfs::semfs_tablelock, and semfs::semfs_vnodes.
Referenced by semfs_bootstrap().
semfs_destroy()
static void semfs_destroy (struct semfs * semfs) static
Definition at line 94 of file semfs_fsops.c.
References kfree(), lock_destroy(), num, semfs::semfs_dents, semfs_direntry_destroy(), semfs::semfs_dirlock, semfs_sem_destroy(), semfs::semfs_sems, semfs::semfs_tablelock, and semfs::semfs_vnodes.
Referenced by semfs_unmount().
semfs_getroot()
static int semfs_getroot (struct fs * fs, struct vnode ** ret) static
Definition at line 69 of file semfs_fsops.c.
References fs::fs_data, kprintf(), semfs_getvnode(), SEMFS_ROOTDIR, and strerror().
semfs_getvolname()
static const char* semfs_getvolname (struct fs * fs) static
Definition at line 58 of file semfs_fsops.c.
semfs_sync()
static int semfs_sync (struct fs * fs) static
Definition at line 47 of file semfs_fsops.c.
semfs_unmount()
static int semfs_unmount (struct fs * fs) static
Definition at line 128 of file semfs_fsops.c.
References EBUSY, fs::fs_data, lock_acquire(), lock_release(), semfs_destroy(), semfs::semfs_tablelock, and semfs::semfs_vnodes.
Variable Documentation
semfs_fsops
const struct fs_ops semfs_fsops static
Initial value:
= {
    .fsop_sync = semfs_sync,
    .fsop_getvolname = semfs_getvolname,
    .fsop_getroot = semfs_getroot,
    .fsop_unmount = semfs_unmount,
}
Definition at line 147 of file semfs_fsops.c.
Referenced by semfs_create().