os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/dev/lamebus/emu.c File Reference
emu.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <stat.h>
#include <lib.h>
#include <array.h>
#include <uio.h>
#include <membar.h>
#include <synch.h>
#include <lamebus/emu.h>
#include <platform/bus.h>
#include <vfs.h>
#include <emufs.h>
#include "autoconf.h"
Macros
#define REG_HANDLE 0
#define REG_OFFSET 4
#define REG_IOLEN 8
#define REG_OPER 12
#define REG_RESULT 16
#define EMU_BUFFER 32768
#define EMU_OP_OPEN 1
#define EMU_OP_CREATE 2
#define EMU_OP_EXCLCREATE 3
#define EMU_OP_CLOSE 4
#define EMU_OP_READ 5
#define EMU_OP_READDIR 6
#define EMU_OP_WRITE 7
#define EMU_OP_GETSIZE 8
#define EMU_OP_TRUNC 9
#define EMU_RES_SUCCESS 1
#define EMU_RES_BADHANDLE 2
#define EMU_RES_BADOP 3
#define EMU_RES_BADPATH 4
#define EMU_RES_BADSIZE 5
#define EMU_RES_EXISTS 6
#define EMU_RES_ISDIR 7
#define EMU_RES_MEDIA 8
#define EMU_RES_NOHANDLES 9
#define EMU_RES_NOSPACE 10
#define EMU_RES_NOTDIR 11
#define EMU_RES_UNKNOWN 12
#define EMU_RES_UNSUPP 13
Functions
static uint32_t emu_rreg (struct emu_softc *sc, uint32_t reg)
static void emu_wreg (struct emu_softc *sc, uint32_t reg, uint32_t val)
void emu_irq (void *dev)
static uint32_t translate_err (struct emu_softc *sc, uint32_t code)
static int emu_waitdone (struct emu_softc *sc)
static int emu_open (struct emu_softc *sc, uint32_t handle, const char *name, bool create, bool excl, mode_t mode, uint32_t *newhandle, int *newisdir)
static int emu_close (struct emu_softc *sc, uint32_t handle)
static int emu_doread (struct emu_softc *sc, uint32_t handle, uint32_t len, uint32_t op, struct uio *uio)
static int emu_read (struct emu_softc *sc, uint32_t handle, uint32_t len, struct uio *uio)
static int emu_readdir (struct emu_softc *sc, uint32_t handle, uint32_t len, struct uio *uio)
static int emu_write (struct emu_softc *sc, uint32_t handle, uint32_t len, struct uio *uio)
static int emu_getsize (struct emu_softc *sc, uint32_t handle, off_t *retval)
static int emu_trunc (struct emu_softc *sc, uint32_t handle, off_t len)
static int emufs_loadvnode (struct emufs_fs *ef, uint32_t handle, int isdir, struct emufs_vnode **ret)
static int emufs_eachopen (struct vnode *v, int openflags)
static int emufs_eachopendir (struct vnode *v, int openflags)
static int emufs_reclaim (struct vnode *v)
static int emufs_read (struct vnode *v, struct uio *uio)
static int emufs_getdirentry (struct vnode *v, struct uio *uio)
static int emufs_write (struct vnode *v, struct uio *uio)
static int emufs_ioctl (struct vnode *v, int op, userptr_t data)
static int emufs_stat (struct vnode *v, struct stat *statbuf)
static int emufs_file_gettype (struct vnode *v, uint32_t *result)
static int emufs_dir_gettype (struct vnode *v, uint32_t *result)
static bool emufs_isseekable (struct vnode *v)
static int emufs_fsync (struct vnode *v)
static int emufs_truncate (struct vnode *v, off_t len)
static int emufs_creat (struct vnode *dir, const char *name, bool excl, mode_t mode, struct vnode **ret)
static int emufs_lookup (struct vnode *dir, char *pathname, struct vnode **ret)
static int emufs_lookparent (struct vnode *dir, char *pathname, struct vnode **ret, char *buf, size_t len)
static int emufs_namefile (struct vnode *v, struct uio *uio)
static int emufs_mmap (struct vnode *v)
static int emufs_symlink (struct vnode *v, const char *contents, const char *name)
static int emufs_mkdir (struct vnode *v, const char *name, mode_t mode)
static int emufs_link (struct vnode *v, const char *name, struct vnode *target)
static int emufs_remove (struct vnode *v, const char *name)
static int emufs_rmdir (struct vnode *v, const char *name)
static int emufs_rename (struct vnode *v1, const char *n1, struct vnode *v2, const char *n2)
static int emufs_void_op_isdir (struct vnode *v)
static int emufs_uio_op_isdir (struct vnode *v, struct uio *uio)
static int emufs_uio_op_notdir (struct vnode *v, struct uio *uio)
static int emufs_name_op_notdir (struct vnode *v, const char *name)
static int emufs_readlink_notlink (struct vnode *v, struct uio *uio)
static int emufs_creat_notdir (struct vnode *v, const char *name, bool excl, mode_t mode, struct vnode **retval)
static int emufs_symlink_notdir (struct vnode *v, const char *contents, const char *name)
static int emufs_mkdir_notdir (struct vnode *v, const char *name, mode_t mode)
static int emufs_link_notdir (struct vnode *v, const char *name, struct vnode *target)
static int emufs_rename_notdir (struct vnode *v1, const char *n1, struct vnode *v2, const char *n2)
static int emufs_lookup_notdir (struct vnode *v, char *pathname, struct vnode **result)
static int emufs_lookparent_notdir (struct vnode *v, char *pathname, struct vnode **result, char *buf, size_t len)
static int emufs_truncate_isdir (struct vnode *v, off_t len)
static int emufs_sync (struct fs *fs)
static const char * emufs_getvolname (struct fs *fs)
static int emufs_getroot (struct fs *fs, struct vnode **ret)
static int emufs_unmount (struct fs *fs)
static int emufs_addtovfs (struct emu_softc *sc, const char *devname)
int config_emu (struct emu_softc *sc, int emuno)
Variables
static const struct vnode_ops emufs_fileops
static const struct vnode_ops emufs_dirops
static const struct fs_ops emufs_fsops
Macro Definition Documentation
EMU_BUFFER
#define EMU_BUFFER 32768
Definition at line 66 of file emu.c.
EMU_OP_CLOSE
#define EMU_OP_CLOSE 4
Definition at line 72 of file emu.c.
EMU_OP_CREATE
#define EMU_OP_CREATE 2
Definition at line 70 of file emu.c.
EMU_OP_EXCLCREATE
#define EMU_OP_EXCLCREATE 3
Definition at line 71 of file emu.c.
EMU_OP_GETSIZE
#define EMU_OP_GETSIZE 8
Definition at line 76 of file emu.c.
EMU_OP_OPEN
#define EMU_OP_OPEN 1
Definition at line 69 of file emu.c.
EMU_OP_READ
#define EMU_OP_READ 5
Definition at line 73 of file emu.c.
EMU_OP_READDIR
#define EMU_OP_READDIR 6
Definition at line 74 of file emu.c.
EMU_OP_TRUNC
#define EMU_OP_TRUNC 9
Definition at line 77 of file emu.c.
EMU_OP_WRITE
#define EMU_OP_WRITE 7
Definition at line 75 of file emu.c.
EMU_RES_BADHANDLE
#define EMU_RES_BADHANDLE 2
Definition at line 81 of file emu.c.
EMU_RES_BADOP
#define EMU_RES_BADOP 3
Definition at line 82 of file emu.c.
EMU_RES_BADPATH
#define EMU_RES_BADPATH 4
Definition at line 83 of file emu.c.
EMU_RES_BADSIZE
#define EMU_RES_BADSIZE 5
Definition at line 84 of file emu.c.
EMU_RES_EXISTS
#define EMU_RES_EXISTS 6
Definition at line 85 of file emu.c.
EMU_RES_ISDIR
#define EMU_RES_ISDIR 7
Definition at line 86 of file emu.c.
EMU_RES_MEDIA
#define EMU_RES_MEDIA 8
Definition at line 87 of file emu.c.
EMU_RES_NOHANDLES
#define EMU_RES_NOHANDLES 9
Definition at line 88 of file emu.c.
EMU_RES_NOSPACE
#define EMU_RES_NOSPACE 10
Definition at line 89 of file emu.c.
EMU_RES_NOTDIR
#define EMU_RES_NOTDIR 11
Definition at line 90 of file emu.c.
EMU_RES_SUCCESS
#define EMU_RES_SUCCESS 1
Definition at line 80 of file emu.c.
EMU_RES_UNKNOWN
#define EMU_RES_UNKNOWN 12
Definition at line 91 of file emu.c.
EMU_RES_UNSUPP
#define EMU_RES_UNSUPP 13
Definition at line 92 of file emu.c.
REG_HANDLE
#define REG_HANDLE 0
Definition at line 59 of file emu.c.
REG_IOLEN
#define REG_IOLEN 8
Definition at line 61 of file emu.c.
REG_OFFSET
#define REG_OFFSET 4
Definition at line 60 of file emu.c.
REG_OPER
#define REG_OPER 12
Definition at line 62 of file emu.c.
REG_RESULT
#define REG_RESULT 16
Definition at line 63 of file emu.c.
Function Documentation
config_emu()
int config_emu (struct emu_softc * sc, int emuno)
Definition at line 1338 of file emu.c.
References bus_map_area, emu_softc::e_busdata, emu_softc::e_buspos, emu_softc::e_iobuf, emu_softc::e_lock, emu_softc::e_sem, EMU_BUFFER, emufs_addtovfs(), ENOMEM, lock_create(), lock_destroy(), name, NULL, sem_create(), and snprintf().
Referenced by tryattach_emu_to_lamebus().
emu_close()
static int emu_close (struct emu_softc * sc, uint32_t handle) static
Definition at line 231 of file emu.c.
References emu_softc::e_lock, emu_softc::e_unit, EIO, EMU_OP_CLOSE, emu_waitdone(), emu_wreg(), kprintf(), lock_acquire(), lock_do_i_hold(), lock_release(), REG_HANDLE, and REG_OPER.
Referenced by emufs_creat(), emufs_lookup(), and emufs_reclaim().
emu_doread()
static int emu_doread (struct emu_softc * sc, uint32_t handle, uint32_t len, uint32_t op, struct uio * uio) static
Definition at line 269 of file emu.c.
References emu_softc::e_iobuf, emu_softc::e_lock, emu_rreg(), emu_waitdone(), emu_wreg(), KASSERT, lock_acquire(), lock_release(), membar_load_load(), REG_HANDLE, REG_IOLEN, REG_OFFSET, REG_OPER, uio::uio_offset, UIO_READ, uio::uio_rw, and uiomove().
Referenced by emu_read(), and emu_readdir().
emu_getsize()
static int emu_getsize (struct emu_softc * sc, uint32_t handle, off_t * retval) static
Definition at line 365 of file emu.c.
References emu_softc::e_lock, EMU_OP_GETSIZE, emu_rreg(), emu_waitdone(), emu_wreg(), lock_acquire(), lock_release(), REG_HANDLE, REG_IOLEN, and REG_OPER.
Referenced by emufs_stat().
emu_irq()
void emu_irq (void * dev)
Definition at line 125 of file emu.c.
References emu_softc::e_result, emu_softc::e_sem, emu_rreg(), emu_wreg(), REG_RESULT, and V().
Referenced by attach_emu_to_lamebus().
emu_open()
static int emu_open (struct emu_softc * sc, uint32_t handle, const char * name, bool create, bool excl, mode_t mode, uint32_t * newhandle, int * newisdir) static
Definition at line 182 of file emu.c.
References emu_softc::e_iobuf, emu_softc::e_lock, EMU_MAXIO, EMU_OP_CREATE, EMU_OP_EXCLCREATE, EMU_OP_OPEN, emu_rreg(), emu_waitdone(), emu_wreg(), ENAMETOOLONG, lock_acquire(), lock_release(), membar_store_store(), name, REG_HANDLE, REG_IOLEN, REG_OPER, strcpy(), and strlen().
Referenced by emufs_creat(), and emufs_lookup().
emu_read()
static int emu_read (struct emu_softc * sc, uint32_t handle, uint32_t len, struct uio * uio) static
Definition at line 307 of file emu.c.
References emu_doread(), and EMU_OP_READ.
Referenced by emufs_read().
emu_readdir()
static int emu_readdir (struct emu_softc * sc, uint32_t handle, uint32_t len, struct uio * uio) static
Definition at line 318 of file emu.c.
References emu_doread(), and EMU_OP_READDIR.
Referenced by emufs_getdirentry().
emu_rreg()
static uint32_t emu_rreg (struct emu_softc * sc, uint32_t reg) inline static
Definition at line 105 of file emu.c.
References bus_read_register, emu_softc::e_busdata, and emu_softc::e_buspos.
Referenced by emu_doread(), emu_getsize(), emu_irq(), and emu_open().
emu_trunc()
static int emu_trunc (struct emu_softc * sc, uint32_t handle, off_t len) static
Definition at line 387 of file emu.c.
References emu_softc::e_lock, EMU_OP_TRUNC, emu_waitdone(), emu_wreg(), KASSERT, lock_acquire(), lock_release(), REG_HANDLE, REG_IOLEN, and REG_OPER.
Referenced by emufs_truncate().
emu_waitdone()
static int emu_waitdone (struct emu_softc * sc) static
Definition at line 168 of file emu.c.
References emu_softc::e_result, emu_softc::e_sem, P(), and translate_err().
Referenced by emu_close(), emu_doread(), emu_getsize(), emu_open(), emu_trunc(), and emu_write().
emu_wreg()
static void emu_wreg (struct emu_softc * sc, uint32_t reg, uint32_t val) inline static
Definition at line 116 of file emu.c.
References bus_write_register, emu_softc::e_busdata, and emu_softc::e_buspos.
Referenced by emu_close(), emu_doread(), emu_getsize(), emu_irq(), emu_open(), emu_trunc(), and emu_write().
emu_write()
static int emu_write (struct emu_softc * sc, uint32_t handle, uint32_t len, struct uio * uio) static
Definition at line 329 of file emu.c.
References emu_softc::e_iobuf, emu_softc::e_lock, EFBIG, EMU_OP_WRITE, emu_waitdone(), emu_wreg(), KASSERT, lock_acquire(), lock_release(), membar_store_store(), REG_HANDLE, REG_IOLEN, REG_OFFSET, REG_OPER, uio::uio_offset, uio::uio_rw, UIO_WRITE, and uiomove().
Referenced by emufs_write().
emufs_addtovfs()
static int emufs_addtovfs (struct emu_softc * sc, const char * devname) static
Definition at line 1292 of file emu.c.
References emufs_fs::ef_emu, emufs_fs::ef_fs, emufs_fs::ef_root, emufs_fs::ef_vnodes, EMU_ROOTHANDLE, emufs_fsops, emufs_loadvnode(), ENOMEM, emufs_vnode::ev_v, fs::fs_data, fs::fs_ops, KASSERT, kfree(), kmalloc(), NULL, vfs_addfs(), and VOP_DECREF.
Referenced by config_emu().
emufs_creat()
static int emufs_creat (struct vnode * dir, const char * name, bool excl, mode_t mode, struct vnode ** ret) static
Definition at line 736 of file emu.c.
References emu_close(), emu_open(), emufs_loadvnode(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, emufs_vnode::ev_v, isdir(), and name.
emufs_creat_notdir()
static int emufs_creat_notdir (struct vnode * v, const char * name, bool excl, mode_t mode, struct vnode ** retval) static
Definition at line 984 of file emu.c.
References ENOTDIR, and name.
emufs_dir_gettype()
static int emufs_dir_gettype (struct vnode * v, uint32_t * result) static
Definition at line 691 of file emu.c.
References S_IFDIR.
emufs_eachopen()
static int emufs_eachopen (struct vnode * v, int openflags) static
Definition at line 422 of file emu.c.
emufs_eachopendir()
static int emufs_eachopendir (struct vnode * v, int openflags) static
Definition at line 443 of file emu.c.
References EISDIR, O_ACCMODE, O_APPEND, O_RDONLY, O_RDWR, and O_WRONLY.
emufs_file_gettype()
static int emufs_file_gettype (struct vnode * v, uint32_t * result) static
Definition at line 679 of file emu.c.
References S_IFREG.
emufs_fsync()
static int emufs_fsync (struct vnode * v) static
Definition at line 714 of file emu.c.
emufs_getdirentry()
static int emufs_getdirentry (struct vnode * v, struct uio * uio) static
Definition at line 577 of file emu.c.
References EMU_MAXIO, emu_readdir(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, KASSERT, UIO_READ, uio::uio_resid, uio::uio_rw, and vnode::vn_data.
emufs_getroot()
static int emufs_getroot (struct fs * fs, struct vnode ** ret) static
Definition at line 1245 of file emu.c.
References emufs_fs::ef_root, emufs_vnode::ev_v, fs::fs_data, KASSERT, NULL, and VOP_INCREF.
emufs_getvolname()
static const char* emufs_getvolname (struct fs * fs) static
Definition at line 1233 of file emu.c.
References NULL.
emufs_ioctl()
static int emufs_ioctl (struct vnode * v, int op, userptr_t data) static
Definition at line 633 of file emu.c.
References EINVAL.
emufs_isseekable()
static bool emufs_isseekable (struct vnode * v) static
Definition at line 703 of file emu.c.
emufs_link()
static int emufs_link (struct vnode * v, const char * name, struct vnode * target) static
Definition at line 885 of file emu.c.
References ENOSYS, and name.
emufs_link_notdir()
static int emufs_link_notdir (struct vnode * v, const char * name, struct vnode * target) static
Definition at line 1017 of file emu.c.
References ENOTDIR, and name.
emufs_loadvnode()
static int emufs_loadvnode (struct emufs_fs * ef, uint32_t handle, int isdir, struct emufs_vnode ** ret) static
Definition at line 1145 of file emu.c.
References emu_softc::e_lock, emufs_fs::ef_emu, emufs_fs::ef_fs, emufs_fs::ef_vnodes, emufs_dirops, emufs_fileops, ENOMEM, emufs_vnode::ev_emu, emufs_vnode::ev_handle, emufs_vnode::ev_v, isdir(), kfree(), kmalloc(), lock_acquire(), lock_release(), NULL, num, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, vnode_cleanup(), vnode_init(), and VOP_INCREF.
Referenced by emufs_addtovfs(), emufs_creat(), and emufs_lookup().
emufs_lookparent()
static int emufs_lookparent (struct vnode * dir, char * pathname, struct vnode ** ret, char * buf, size_t len) static
Definition at line 797 of file emu.c.
References buf, emufs_lookup(), ENAMETOOLONG, NULL, strcpy(), strlen(), strrchr(), and VOP_INCREF.
emufs_lookparent_notdir()
static int emufs_lookparent_notdir (struct vnode * v, char * pathname, struct vnode ** result, char * buf, size_t len) static
Definition at line 1049 of file emu.c.
References buf, and ENOTDIR.
emufs_lookup()
static int emufs_lookup (struct vnode * dir, char * pathname, struct vnode ** ret) static
Definition at line 767 of file emu.c.
References emu_close(), emu_open(), emufs_loadvnode(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, emufs_vnode::ev_v, and isdir().
Referenced by emufs_lookparent().
emufs_lookup_notdir()
static int emufs_lookup_notdir (struct vnode * v, char * pathname, struct vnode ** result) static
Definition at line 1039 of file emu.c.
References ENOTDIR.
emufs_mkdir()
static int emufs_mkdir (struct vnode * v, const char * name, mode_t mode) static
Definition at line 875 of file emu.c.
References ENOSYS, and name.
emufs_mkdir_notdir()
static int emufs_mkdir_notdir (struct vnode * v, const char * name, mode_t mode) static
Definition at line 1007 of file emu.c.
References ENOTDIR, and name.
emufs_mmap()
static int emufs_mmap (struct vnode * v) static
Definition at line 851 of file emu.c.
References ENOSYS.
emufs_name_op_notdir()
static int emufs_name_op_notdir (struct vnode * v, const char * name) static
Definition at line 966 of file emu.c.
References ENOTDIR, and name.
emufs_namefile()
static int emufs_namefile (struct vnode * v, struct uio * uio) static
Definition at line 829 of file emu.c.
References emufs_fs::ef_root, ENOSYS, fs::fs_data, vnode::vn_data, and vnode::vn_fs.
emufs_read()
static int emufs_read (struct vnode * v, struct uio * uio) static
Definition at line 541 of file emu.c.
References EMU_MAXIO, emu_read(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, KASSERT, UIO_READ, uio::uio_resid, uio::uio_rw, and vnode::vn_data.
emufs_readlink_notlink()
static int emufs_readlink_notlink (struct vnode * v, struct uio * uio) static
Definition at line 975 of file emu.c.
References EINVAL.
emufs_reclaim()
static int emufs_reclaim (struct vnode * v) static
Definition at line 468 of file emu.c.
References emu_softc::e_lock, emu_softc::e_unit, EBUSY, emufs_fs::ef_emu, emufs_fs::ef_vnodes, emu_close(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, emufs_vnode::ev_v, fs::fs_data, KASSERT, kfree(), lock_acquire(), lock_release(), num, panic(), spinlock_acquire(), spinlock_release(), vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_countlock, vnode::vn_data, vnode::vn_fs, vnode::vn_refcount, and vnode_cleanup().
emufs_remove()
static int emufs_remove (struct vnode * v, const char * name) static
Definition at line 895 of file emu.c.
References ENOSYS, and name.
emufs_rename()
static int emufs_rename (struct vnode * v1, const char * n1, struct vnode * v2, const char * n2) static
Definition at line 913 of file emu.c.
References ENOSYS, and v1.
emufs_rename_notdir()
static int emufs_rename_notdir (struct vnode * v1, const char * n1, struct vnode * v2, const char * n2) static
Definition at line 1027 of file emu.c.
References ENOTDIR, and v1.
emufs_rmdir()
static int emufs_rmdir (struct vnode * v, const char * name) static
Definition at line 904 of file emu.c.
References ENOSYS, and name.
emufs_stat()
static int emufs_stat (struct vnode * v, struct stat * statbuf) static
Definition at line 651 of file emu.c.
References bzero(), emu_getsize(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, stat::st_blocks, stat::st_mode, stat::st_nlink, stat::st_size, vnode::vn_data, and VOP_GETTYPE.
emufs_symlink()
static int emufs_symlink (struct vnode * v, const char * contents, const char * name) static
Definition at line 865 of file emu.c.
References ENOSYS, and name.
emufs_symlink_notdir()
static int emufs_symlink_notdir (struct vnode * v, const char * contents, const char * name) static
Definition at line 997 of file emu.c.
References ENOTDIR, and name.
emufs_sync()
static int emufs_sync (struct fs * fs) static
Definition at line 1222 of file emu.c.
emufs_truncate()
static int emufs_truncate (struct vnode * v, off_t len) static
Definition at line 725 of file emu.c.
References emu_trunc(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, and vnode::vn_data.
emufs_truncate_isdir()
static int emufs_truncate_isdir (struct vnode * v, off_t len) static
Definition at line 1063 of file emu.c.
References ENOTDIR.
emufs_uio_op_isdir()
static int emufs_uio_op_isdir (struct vnode * v, struct uio * uio) static
Definition at line 948 of file emu.c.
References EISDIR.
emufs_uio_op_notdir()
static int emufs_uio_op_notdir (struct vnode * v, struct uio * uio) static
Definition at line 957 of file emu.c.
References ENOTDIR.
emufs_unmount()
static int emufs_unmount (struct fs * fs) static
Definition at line 1266 of file emu.c.
References EBUSY.
emufs_void_op_isdir()
static int emufs_void_op_isdir (struct vnode * v) static
Definition at line 940 of file emu.c.
References EISDIR.
emufs_write()
static int emufs_write (struct vnode * v, struct uio * uio) static
Definition at line 597 of file emu.c.
References EMU_MAXIO, emu_write(), emufs_vnode::ev_emu, emufs_vnode::ev_handle, KASSERT, uio::uio_resid, uio::uio_rw, UIO_WRITE, and vnode::vn_data.
translate_err()
static uint32_t translate_err (struct emu_softc * sc, uint32_t code) static
Definition at line 141 of file emu.c.
References emu_softc::e_unit, EAGAIN, EEXIST, EIO, EISDIR, EMU_RES_BADHANDLE, EMU_RES_BADOP, EMU_RES_BADPATH, EMU_RES_BADSIZE, EMU_RES_EXISTS, EMU_RES_ISDIR, EMU_RES_MEDIA, EMU_RES_NOHANDLES, EMU_RES_NOSPACE, EMU_RES_NOTDIR, EMU_RES_SUCCESS, EMU_RES_UNKNOWN, EMU_RES_UNSUPP, ENFILE, ENOENT, ENOSPC, ENOSYS, ENOTDIR, kprintf(), and panic().
Referenced by emu_waitdone().
Variable Documentation
emufs_dirops
const struct vnode_ops emufs_dirops static
Initial value:
= {
    .vop_magic = VOP_MAGIC,
    .vop_eachopen = emufs_eachopendir,
    .vop_reclaim = emufs_reclaim,
    .vop_read = emufs_uio_op_isdir,
    .vop_readlink = emufs_uio_op_isdir,
    .vop_getdirentry = emufs_getdirentry,
    .vop_write = emufs_uio_op_isdir,
    .vop_ioctl = emufs_ioctl,
    .vop_stat = emufs_stat,
    .vop_gettype = emufs_dir_gettype,
    .vop_isseekable = emufs_isseekable,
    .vop_fsync = emufs_void_op_isdir,
    .vop_mmap = emufs_void_op_isdir,
    .vop_truncate = emufs_truncate_isdir,
    .vop_namefile = emufs_namefile,
    .vop_creat = emufs_creat,
    .vop_symlink = emufs_symlink,
    .vop_mkdir = emufs_mkdir,
    .vop_link = emufs_link,
    .vop_remove = emufs_remove,
    .vop_rmdir = emufs_rmdir,
    .vop_rename = emufs_rename,
    .vop_lookup = emufs_lookup,
    .vop_lookparent = emufs_lookparent,
}
Definition at line 1109 of file emu.c.
Referenced by emufs_loadvnode().
emufs_fileops
const struct vnode_ops emufs_fileops static
Initial value:
= {
    .vop_magic = VOP_MAGIC,
    .vop_eachopen = emufs_eachopen,
    .vop_reclaim = emufs_reclaim,
    .vop_read = emufs_read,
    .vop_readlink = emufs_readlink_notlink,
    .vop_getdirentry = emufs_uio_op_notdir,
    .vop_write = emufs_write,
    .vop_ioctl = emufs_ioctl,
    .vop_stat = emufs_stat,
    .vop_gettype = emufs_file_gettype,
    .vop_isseekable = emufs_isseekable,
    .vop_fsync = emufs_fsync,
    .vop_mmap = emufs_mmap,
    .vop_truncate = emufs_truncate,
    .vop_namefile = emufs_uio_op_notdir,
    .vop_creat = emufs_creat_notdir,
    .vop_symlink = emufs_symlink_notdir,
    .vop_mkdir = emufs_mkdir_notdir,
    .vop_link = emufs_link_notdir,
    .vop_remove = emufs_name_op_notdir,
    .vop_rmdir = emufs_name_op_notdir,
    .vop_rename = emufs_rename_notdir,
    .vop_lookup = emufs_lookup_notdir,
    .vop_lookparent = emufs_lookparent_notdir,
}
Definition at line 1075 of file emu.c.
Referenced by emufs_loadvnode().
emufs_fsops
const struct fs_ops emufs_fsops static
Initial value:
= {
    .fsop_sync = emufs_sync,
    .fsop_getvolname = emufs_getvolname,
    .fsop_getroot = emufs_getroot,
    .fsop_unmount = emufs_unmount,
}
Definition at line 1276 of file emu.c.
Referenced by emufs_addtovfs().