os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/fs/sfs/sfs_vnops.c File Reference
sfs_vnops.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <stat.h>
#include <lib.h>
#include <uio.h>
#include <vfs.h>
#include <sfs.h>
#include "sfsprivate.h"
Functions
static int sfs_eachopen (struct vnode *v, int openflags)
static int sfs_eachopendir (struct vnode *v, int openflags)
static int sfs_read (struct vnode *v, struct uio *uio)
static int sfs_write (struct vnode *v, struct uio *uio)
static int sfs_ioctl (struct vnode *v, int op, userptr_t data)
static int sfs_stat (struct vnode *v, struct stat *statbuf)
static int sfs_gettype (struct vnode *v, uint32_t *ret)
static bool sfs_isseekable (struct vnode *v)
static int sfs_fsync (struct vnode *v)
static int sfs_mmap (struct vnode *v)
static int sfs_truncate (struct vnode *v, off_t len)
static int sfs_namefile (struct vnode *vv, struct uio *uio)
static int sfs_creat (struct vnode *v, const char *name, bool excl, mode_t mode, struct vnode **ret)
static int sfs_link (struct vnode *dir, const char *name, struct vnode *file)
static int sfs_remove (struct vnode *dir, const char *name)
static int sfs_rename (struct vnode *d1, const char *n1, struct vnode *d2, const char *n2)
static int sfs_lookparent (struct vnode *v, char *path, struct vnode **ret, char *buf, size_t buflen)
static int sfs_lookup (struct vnode *v, char *path, struct vnode **ret)
Variables
const struct vnode_ops sfs_fileops
const struct vnode_ops sfs_dirops
Function Documentation
sfs_creat()
static int sfs_creat (struct vnode * v, const char * name, bool excl, mode_t mode, struct vnode ** ret) static
Definition at line 283 of file sfs_vnops.c.
References EEXIST, ENOENT, fs::fs_data, name, NULL, sfs_dinode::sfi_linkcount, sfs_dir_findname(), sfs_dir_link(), sfs_loadvnode(), sfs_makeobj(), SFS_TYPE_FILE, SFS_TYPE_INVAL, sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, vnode::vn_fs, and VOP_DECREF.
sfs_eachopen()
static int sfs_eachopen (struct vnode * v, int openflags) static
Definition at line 53 of file sfs_vnops.c.
sfs_eachopendir()
static int sfs_eachopendir (struct vnode * v, int openflags) static
Definition at line 75 of file sfs_vnops.c.
References EISDIR, O_ACCMODE, O_APPEND, O_RDONLY, O_RDWR, and O_WRONLY.
sfs_fsync()
static int sfs_fsync (struct vnode * v) static
Definition at line 222 of file sfs_vnops.c.
References sfs_sync_inode(), vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_data.
sfs_gettype()
static int sfs_gettype (struct vnode * v, uint32_t * ret) static
Definition at line 183 of file sfs_vnops.c.
References EINVAL, fs::fs_data, panic(), S_IFDIR, S_IFREG, sfs_superblock::sb_volname, sfs_dinode::sfi_type, sfs_fs::sfs_sb, SFS_TYPE_DIR, SFS_TYPE_FILE, sfs_vnode::sv_i, sfs_vnode::sv_ino, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, and vnode::vn_fs.
sfs_ioctl()
static int sfs_ioctl (struct vnode * v, int op, userptr_t data) static
Definition at line 136 of file sfs_vnops.c.
References EINVAL.
sfs_isseekable()
static bool sfs_isseekable (struct vnode * v) static
Definition at line 210 of file sfs_vnops.c.
sfs_link()
static int sfs_link (struct vnode * dir, const char * name, struct vnode * file) static
Definition at line 356 of file sfs_vnops.c.
References EINVAL, f, KASSERT, name, NULL, sfs_dir_link(), SFS_TYPE_DIR, vfs_biglock_acquire(), and vfs_biglock_release().
sfs_lookparent()
static int sfs_lookparent (struct vnode * v, char * path, struct vnode ** ret, char * buf, size_t buflen) static
Definition at line 523 of file sfs_vnops.c.
References buf, ENAMETOOLONG, ENOTDIR, sfs_dinode::sfi_type, SFS_TYPE_DIR, strcpy(), strlen(), sfs_vnode::sv_absvn, sfs_vnode::sv_i, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, and VOP_INCREF.
sfs_lookup()
static int sfs_lookup (struct vnode * v, char * path, struct vnode ** ret) static
Definition at line 556 of file sfs_vnops.c.
References ENOTDIR, NULL, sfs_dinode::sfi_type, sfs_lookonce(), SFS_TYPE_DIR, sfs_vnode::sv_i, vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_data.
sfs_mmap()
static int sfs_mmap (struct vnode * v) static
Definition at line 239 of file sfs_vnops.c.
References ENOSYS.
sfs_namefile()
static int sfs_namefile (struct vnode * vv, struct uio * uio) static
Definition at line 265 of file sfs_vnops.c.
References KASSERT, SFS_ROOTDIR_INO, sfs_vnode::sv_ino, and vnode::vn_data.
sfs_read()
static int sfs_read (struct vnode * v, struct uio * uio) static
Definition at line 98 of file sfs_vnops.c.
References KASSERT, sfs_io(), UIO_READ, uio::uio_rw, vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_data.
sfs_remove()
static int sfs_remove (struct vnode * dir, const char * name) static
Definition at line 392 of file sfs_vnops.c.
References KASSERT, name, sfs_dinode::sfi_linkcount, sfs_dir_unlink(), sfs_lookonce(), sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, vfs_biglock_acquire(), vfs_biglock_release(), and VOP_DECREF.
sfs_rename()
static int sfs_rename (struct vnode * d1, const char * n1, struct vnode * d2, const char * n2) static
Definition at line 432 of file sfs_vnops.c.
References fs::fs_data, KASSERT, kprintf(), panic(), sfs_superblock::sb_volname, sfs_dinode::sfi_linkcount, sfs_dinode::sfi_type, sfs_dir_link(), sfs_dir_unlink(), sfs_lookonce(), SFS_ROOTDIR_INO, sfs_fs::sfs_sb, SFS_TYPE_FILE, strerror(), sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_data, vnode::vn_fs, and VOP_DECREF.
sfs_stat()
static int sfs_stat (struct vnode * v, struct stat * statbuf) static
Definition at line 154 of file sfs_vnops.c.
References bzero(), sfs_dinode::sfi_linkcount, sfs_dinode::sfi_size, stat::st_blocks, stat::st_mode, stat::st_nlink, stat::st_size, sfs_vnode::sv_i, vnode::vn_data, and VOP_GETTYPE.
sfs_truncate()
static int sfs_truncate (struct vnode * v, off_t len) static
Definition at line 250 of file sfs_vnops.c.
References sfs_itrunc(), and vnode::vn_data.
sfs_write()
static int sfs_write (struct vnode * v, struct uio * uio) static
Definition at line 117 of file sfs_vnops.c.
References KASSERT, sfs_io(), uio::uio_rw, UIO_WRITE, vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_data.
Variable Documentation
sfs_dirops
const struct vnode_ops sfs_dirops
Initial value:
= {
    .vop_magic = VOP_MAGIC,
    .vop_eachopen = sfs_eachopendir,
    .vop_reclaim = sfs_reclaim,
    .vop_read = vopfail_uio_isdir,
    .vop_readlink = vopfail_uio_inval,
    .vop_getdirentry = vopfail_uio_nosys,
    .vop_write = vopfail_uio_isdir,
    .vop_ioctl = sfs_ioctl,
    .vop_stat = sfs_stat,
    .vop_gettype = sfs_gettype,
    .vop_isseekable = sfs_isseekable,
    .vop_fsync = sfs_fsync,
    .vop_mmap = vopfail_mmap_isdir,
    .vop_truncate = vopfail_truncate_isdir,
    .vop_namefile = sfs_namefile,
    .vop_creat = sfs_creat,
    .vop_symlink = vopfail_symlink_nosys,
    .vop_mkdir = vopfail_mkdir_nosys,
    .vop_link = sfs_link,
    .vop_remove = sfs_remove,
    .vop_rmdir = vopfail_string_nosys,
    .vop_rename = sfs_rename,
    .vop_lookup = sfs_lookup,
    .vop_lookparent = sfs_lookparent,
}
Definition at line 621 of file sfs_vnops.c.
Referenced by sfs_loadvnode().
sfs_fileops
const struct vnode_ops sfs_fileops
Initial value:
= {
    .vop_magic = VOP_MAGIC,
    .vop_eachopen = sfs_eachopen,
    .vop_reclaim = sfs_reclaim,
    .vop_read = sfs_read,
    .vop_readlink = vopfail_uio_notdir,
    .vop_getdirentry = vopfail_uio_notdir,
    .vop_write = sfs_write,
    .vop_ioctl = sfs_ioctl,
    .vop_stat = sfs_stat,
    .vop_gettype = sfs_gettype,
    .vop_isseekable = sfs_isseekable,
    .vop_fsync = sfs_fsync,
    .vop_mmap = sfs_mmap,
    .vop_truncate = sfs_truncate,
    .vop_namefile = vopfail_uio_notdir,
    .vop_creat = vopfail_creat_notdir,
    .vop_symlink = vopfail_symlink_notdir,
    .vop_mkdir = vopfail_mkdir_notdir,
    .vop_link = vopfail_link_notdir,
    .vop_remove = vopfail_string_notdir,
    .vop_rmdir = vopfail_string_notdir,
    .vop_rename = vopfail_rename_notdir,
    .vop_lookup = vopfail_lookup_notdir,
    .vop_lookparent = vopfail_lookparent_notdir,
}
Definition at line 587 of file sfs_vnops.c.
Referenced by sfs_loadvnode().