os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/fs/sfs/sfs_bmap.c File Reference
sfs_bmap.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <vfs.h>
#include <sfs.h>
#include "sfsprivate.h"
Functions
int sfs_bmap (struct sfs_vnode *sv, uint32_t fileblock, bool doalloc, daddr_t *diskblock)
int sfs_itrunc (struct sfs_vnode *sv, off_t len)
Function Documentation
sfs_bmap()
int sfs_bmap (struct sfs_vnode * sv, uint32_t fileblock, bool doalloc, daddr_t * diskblock)
Definition at line 49 of file sfs_bmap.c.
References bzero(), EFBIG, fs::fs_data, KASSERT, panic(), sfs_superblock::sb_volname, sfs_dinode::sfi_direct, sfs_dinode::sfi_indirect, sfs_balloc(), SFS_BLOCKSIZE, sfs_bused(), SFS_DBPERIDB, SFS_NDIRECT, SFS_NINDIRECT, sfs_readblock(), sfs_fs::sfs_sb, sfs_writeblock(), sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, vfs_biglock_do_i_hold(), and vnode::vn_fs.
Referenced by sfs_blockio(), sfs_metaio(), and sfs_partialio().
sfs_itrunc()
int sfs_itrunc (struct sfs_vnode * sv, off_t len)
Definition at line 204 of file sfs_bmap.c.
References DIVROUNDUP, fs::fs_data, KASSERT, sfs_dinode::sfi_direct, sfs_dinode::sfi_indirect, sfs_dinode::sfi_size, sfs_bfree(), SFS_BLOCKSIZE, SFS_DBPERIDB, SFS_NDIRECT, sfs_readblock(), sfs_writeblock(), sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_fs.
Referenced by sfs_reclaim(), and sfs_truncate().