os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/lib/libc/stdlib/system.c File Reference
system.c File Reference
#include <errno.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
Macros
#define MAXCMDSIZE 2048
#define MAXARGS 128
Functions
int system (const char *cmd)
Macro Definition Documentation
MAXARGS
#define MAXARGS 128
Definition at line 42 of file system.c.
MAXCMDSIZE
#define MAXCMDSIZE 2048
Definition at line 41 of file system.c.
Function Documentation
system()
int system (const char * cmd)
Definition at line 45 of file system.c.
References _exit(), E2BIG, errno, execv(), fork(), MAXARGS, MAXCMDSIZE, NULL, pid, strcpy(), strlen(), strtok(), and waitpid().