os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/multiexec/multiexec.c File Reference
multiexec.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
Data Structures
struct usem
Macros
#define SUBARGC_MAX 64
Functions
static void semcreate (const char *tag, struct usem *sem)
static void semopen (struct usem *sem)
static void semclose (struct usem *sem)
static void semdestroy (struct usem *sem)
static void semP (struct usem *sem, size_t num)
static void semV (struct usem *sem, size_t num)
static void spawn (int njobs)
int main (int argc, char *argv[])
Variables
static char * subargv [SUBARGC_MAX]
static int subargc = 0
Macro Definition Documentation
SUBARGC_MAX
#define SUBARGC_MAX 64
Definition at line 157 of file multiexec.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 236 of file multiexec.c.
References atoi(), errx(), NULL, spawn(), strcmp(), subargc, SUBARGC_MAX, and subargv.
semclose()
static void semclose (struct usem * sem) static
Definition at line 116 of file multiexec.c.
References close(), and usem::fd.
Referenced by spawn().
semcreate()
static void semcreate (const char * tag, struct usem * sem) static
Definition at line 90 of file multiexec.c.
References close(), err(), fd, getpid(), usem::name, O_CREAT, O_TRUNC, O_WRONLY, open(), and snprintf().
Referenced by spawn().
semdestroy()
static void semdestroy (struct usem * sem) static
Definition at line 123 of file multiexec.c.
References usem::name, and remove().
Referenced by spawn().
semopen()
static void semopen (struct usem * sem) static
Definition at line 106 of file multiexec.c.
References err(), usem::fd, usem::name, O_RDWR, and open().
Referenced by spawn().
semP()
static void semP (struct usem * sem, size_t num) static
Definition at line 130 of file multiexec.c.
References err(), usem::fd, usem::name, num, and read().
Referenced by spawn().
semV()
static void semV (struct usem * sem, size_t num) static
Definition at line 142 of file multiexec.c.
References err(), usem::fd, memset(), usem::name, num, and write().
Referenced by spawn().
spawn()
static void spawn (int njobs) static
Definition at line 163 of file multiexec.c.
References _exit(), execv(), fork(), pids, printf(), s1, s2, semclose(), semcreate(), semdestroy(), semopen(), semP(), semV(), subargv, waitpid(), warn(), warnx(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
Referenced by main().
Variable Documentation
subargc
int subargc = 0 static
Definition at line 159 of file multiexec.c.
Referenced by main().
subargv
char* subargv[SUBARGC_MAX] static
Definition at line 158 of file multiexec.c.
Referenced by main(), and spawn().