os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/dumpsfs/dumpsfs.c File Reference
dumpsfs.c File Reference
#include <sys/types.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <assert.h>
#include <limits.h>
#include <err.h>
#include "support.h"
#include "kern/sfs.h"
#include "disk.h"
Macros
#define SWAP64(x) (x)
#define SWAP32(x) (x)
#define SWAP16(x) (x)
#define ARRAYCOUNT(a) (sizeof(a) / sizeof((a)[0]))
#define DIVROUNDUP(a, b) (((a) + (b) - 1) / (b))
Functions
static void dumpval (const char *desc, const char *val)
static void dumpvalf (const char *desc, const char *valf,...)
static void dumplval (const char *desc, const char *lval)
static void dumpinode (uint32_t ino, const char *name)
static uint32_t readsb (void)
static void dumpsb (void)
static void dumpfreemap (uint32_t fsblocks)
static void dumpindirect (uint32_t block)
static uint32_t traverse_ib (uint32_t fileblock, uint32_t numblocks, uint32_t block, void(*doblock)(uint32_t, uint32_t))
static void traverse (const struct sfs_dinode *sfi, void(*doblock)(uint32_t, uint32_t))
static void dumpdirblock (uint32_t fileblock, uint32_t diskblock)
static void dumpdir (uint32_t ino, const struct sfs_dinode *sfi)
static void recursedirblock (uint32_t fileblock, uint32_t diskblock)
static void recursedir (uint32_t ino, const struct sfs_dinode *sfi)
static void dumpfileblock (uint32_t fileblock, uint32_t diskblock)
static void dumpfile (uint32_t ino, const struct sfs_dinode *sfi)
static void usage (void)
int main (int argc, char **argv)
Variables
static bool dofiles
static bool dodirs
static bool doindirect
static bool recurse
static unsigned dumppos
Macro Definition Documentation
ARRAYCOUNT
#define ARRAYCOUNT (a) (sizeof(a) / sizeof((a)[0]))
Definition at line 69 of file dumpsfs.c.
DIVROUNDUP
#define DIVROUNDUP (a, b) (((a) + (b) - 1) / (b))
Definition at line 70 of file dumpsfs.c.
SWAP16
#define SWAP16 (x) (x)
Definition at line 63 of file dumpsfs.c.
SWAP32
#define SWAP32 (x) (x)
Definition at line 62 of file dumpsfs.c.
SWAP64
#define SWAP64 (x) (x)
Definition at line 61 of file dumpsfs.c.
Function Documentation
dumpdir()
static void dumpdir (uint32_t ino, const struct sfs_dinode * sfi) static
Definition at line 329 of file dumpsfs.c.
References dumpdirblock(), printf(), sfs_dinode::sfi_size, SWAP32, traverse(), and warnx().
Referenced by dumpinode().
dumpdirblock()
static void dumpdirblock (uint32_t fileblock, uint32_t diskblock) static
Definition at line 301 of file dumpsfs.c.
References diskread(), printf(), sfs_direntry::sfd_ino, sfs_direntry::sfd_name, SFS_BLOCKSIZE, SFS_NAMELEN, SFS_NOINO, and SWAP32.
Referenced by dumpdir().
dumpfile()
static void dumpfile (uint32_t ino, const struct sfs_dinode * sfi) static
Definition at line 420 of file dumpsfs.c.
References dumpfileblock(), printf(), and traverse().
Referenced by dumpinode().
dumpfileblock()
static void dumpfileblock (uint32_t fileblock, uint32_t diskblock) static
Definition at line 378 of file dumpsfs.c.
References diskread(), printf(), putchar(), SFS_BLOCKSIZE, and snprintf().
Referenced by dumpfile().
dumpfreemap()
static void dumpfreemap (uint32_t fsblocks) static
Definition at line 178 of file dumpsfs.c.
References diskread(), printf(), putchar(), SFS_BITSPERBLOCK, SFS_BLOCKSIZE, SFS_FREEMAP_START, SFS_FREEMAPBLOCKS, and snprintf().
Referenced by main().
dumpindirect()
static void dumpindirect (uint32_t block) static
Definition at line 233 of file dumpsfs.c.
References ARRAYCOUNT, diskread(), printf(), SFS_BLOCKSIZE, snprintf(), and SWAP32.
Referenced by dumpinode().
dumpinode()
static void dumpinode (uint32_t ino, const char * name) static
Definition at line 428 of file dumpsfs.c.
References ARRAYCOUNT, diskread(), dodirs, dofiles, doindirect, dumpdir(), dumpfile(), dumpindirect(), dumpvalf(), name, NULL, printf(), recurse, recursedir(), sfs_dinode::sfi_direct, sfs_dinode::sfi_indirect, sfs_dinode::sfi_linkcount, sfs_dinode::sfi_size, sfs_dinode::sfi_type, sfs_dinode::sfi_waste, SFS_NDIRECT, SFS_TYPE_DIR, SFS_TYPE_FILE, snprintf(), SWAP16, and SWAP32.
Referenced by main(), and recursedirblock().
dumplval()
static void dumplval (const char * desc, const char * lval) static
Definition at line 120 of file dumpsfs.c.
References desc, dumppos, and printf().
Referenced by dumpsb().
dumpsb()
static void dumpsb (void) static
Definition at line 150 of file dumpsfs.c.
References ARRAYCOUNT, diskread(), dumplval(), dumpvalf(), printf(), sfs_superblock::reserved, sb, sfs_superblock::sb_magic, sfs_superblock::sb_nblocks, sfs_superblock::sb_volname, SFS_BLOCKSIZE, SFS_FREEMAPBLOCKS, SFS_SUPER_BLOCK, and SWAP32.
Referenced by main().
dumpval()
static void dumpval (const char * desc, const char * val) static
Definition at line 83 of file dumpsfs.c.
References desc, dumppos, printf(), putchar(), and strlen().
Referenced by dumpvalf().
dumpvalf()
static void dumpvalf (const char * desc, const char * valf, ...) static
Definition at line 107 of file dumpsfs.c.
References buf, desc, dumpval(), va_end, va_start, and vsnprintf().
Referenced by dumpinode(), and dumpsb().
main()
int main (int argc, char ** argv)
Definition at line 521 of file dumpsfs.c.
References atoi(), closedisk(), dodirs, dofiles, doindirect, dumpfreemap(), dumpinode(), dumpsb(), hostcompat_progname, nblocks, NULL, opendisk(), readsb(), recurse, SFS_ROOTDIR_INO, strlen(), and usage().
readsb()
static uint32_t readsb (void) static
Definition at line 137 of file dumpsfs.c.
References diskread(), errx(), sb, sfs_superblock::sb_magic, sfs_superblock::sb_nblocks, SFS_MAGIC, SFS_SUPER_BLOCK, and SWAP32.
Referenced by main().
recursedir()
static void recursedir (uint32_t ino, const struct sfs_dinode * sfi) static
Definition at line 367 of file dumpsfs.c.
References printf(), recursedirblock(), sfs_dinode::sfi_size, SWAP32, and traverse().
Referenced by dumpinode().
recursedirblock()
static void recursedirblock (uint32_t fileblock, uint32_t diskblock) static
Definition at line 343 of file dumpsfs.c.
References diskread(), dumpinode(), sfs_direntry::sfd_ino, sfs_direntry::sfd_name, SFS_BLOCKSIZE, SFS_NAMELEN, SFS_NOINO, and SWAP32.
Referenced by recursedir().
traverse()
static void traverse (const struct sfs_dinode * sfi, void(*)(uint32_t, uint32_t) doblock) static
Definition at line 280 of file dumpsfs.c.
References assert, DIVROUNDUP, sfs_dinode::sfi_direct, sfs_dinode::sfi_indirect, sfs_dinode::sfi_size, SFS_BLOCKSIZE, SFS_NDIRECT, SWAP32, and traverse_ib().
Referenced by dumpdir(), dumpfile(), and recursedir().
traverse_ib()
static uint32_t traverse_ib (uint32_t fileblock, uint32_t numblocks, uint32_t block, void(*)(uint32_t, uint32_t) doblock) static
Definition at line 260 of file dumpsfs.c.
References ARRAYCOUNT, diskread(), memset(), SFS_BLOCKSIZE, and SWAP32.
Referenced by traverse().
usage()
static void usage (void) static
Definition at line 506 of file dumpsfs.c.
References errx(), and warnx().
Referenced by main().
Variable Documentation
dodirs
bool dodirs static
Definition at line 72 of file dumpsfs.c.
Referenced by dumpinode(), and main().
dofiles
bool dofiles static
Definition at line 72 of file dumpsfs.c.
Referenced by dumpinode(), and main().
doindirect
bool doindirect static
Definition at line 73 of file dumpsfs.c.
Referenced by dumpinode(), and main().
dumppos
unsigned dumppos static
Definition at line 79 of file dumpsfs.c.
Referenced by dumplval(), and dumpval().
recurse
bool recurse static
Definition at line 74 of file dumpsfs.c.
Referenced by dumpinode(), and main().