os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/cpu.h File Reference
cpu.h File Reference
#include <spinlock.h>
#include <threadlist.h>
#include <machine/vm.h>
Data Structures
struct cpu
Macros
#define IPI_PANIC 0 /* System has called panic() */
#define IPI_OFFLINE 1 /* CPU is requested to go offline */
#define IPI_UNIDLE 2 /* Runnable threads are available */
#define IPI_TLBSHOOTDOWN 3 /* MMU mapping(s) need invalidation */
Functions
struct cpu * cpu_create (unsigned hardware_number)
void cpu_machdep_init (struct cpu *)
void cpu_start_secondary (void)
void cpu_hatch (unsigned software_number)
void cpu_identify (char *buf, size_t max)
void cpu_irqoff (void)
void cpu_irqon (void)
void cpu_idle (void)
void cpu_halt (void)
void ipi_send (struct cpu *target, int code)
void ipi_broadcast (int code)
void ipi_tlbshootdown (struct cpu *target, const struct tlbshootdown *mapping)
void interprocessor_interrupt (void)
Macro Definition Documentation
IPI_OFFLINE
#define IPI_OFFLINE 1 /* CPU is requested to go offline */
Definition at line 165 of file cpu.h.
IPI_PANIC
#define IPI_PANIC 0 /* System has called panic() */
Definition at line 164 of file cpu.h.
IPI_TLBSHOOTDOWN
#define IPI_TLBSHOOTDOWN 3 /* MMU mapping(s) need invalidation */
Definition at line 167 of file cpu.h.
IPI_UNIDLE
#define IPI_UNIDLE 2 /* Runnable threads are available */
Definition at line 166 of file cpu.h.
Function Documentation
cpu_create()
struct cpu* cpu_create (unsigned hardware_number)
Definition at line 164 of file thread.c.
References allcpus, cpu::c_curthread, cpu::c_hardclocks, cpu::c_hardware_number, cpu::c_ipi_lock, cpu::c_ipi_pending, cpu::c_isidle, cpu::c_number, cpu::c_numshootdown, cpu::c_runqueue, cpu::c_runqueue_lock, cpu::c_self, cpu::c_spinlocks, cpu::c_zombies, cpu_machdep_init(), HANGMAN_ACTORINIT, INIT_CURCPU, kmalloc(), kproc, NULL, panic(), proc_addthread(), snprintf(), spinlock_init(), STACK_SIZE, strerror(), thread::t_cpu, thread::t_stack, thread_checkstack_init(), thread_create(), and threadlist_init().
Referenced by lamebus_find_cpus(), and thread_bootstrap().
cpu_halt()
void cpu_halt (void)
Definition at line 303 of file cpu.c.
References cpu_irqoff(), and wait().
Referenced by interprocessor_interrupt(), lamebus_poweroff(), and mainbus_halt().
cpu_hatch()
void cpu_hatch (unsigned software_number)
Definition at line 406 of file thread.c.
References buf, cpu_identify(), cpu_startup_sem, KASSERT, kprintf(), NULL, spl0(), thread_exit(), and V().
cpu_identify()
void cpu_identify (char * buf, size_t max)
Definition at line 152 of file cpu.c.
References buf, cpu_getfeatures(), cpu_getifeatures(), cpu_getprid(), kprintf(), snprintf(), SYS161_PRID_2X, and SYS161_PRID_ORIG.
Referenced by cpu_hatch(), and thread_start_cpus().
cpu_idle()
void cpu_idle (void)
Definition at line 293 of file cpu.c.
References cpu_irqonoff(), and wait().
Referenced by thread_switch().
cpu_irqoff()
void cpu_irqoff (void)
Definition at line 223 of file cpu.c.
References CST_IEc, GET_STATUS, and SET_STATUS.
Referenced by cpu_halt(), lamebus_poweroff(), mips_trap(), mips_usermode(), and splraise().
cpu_irqon()
void cpu_irqon (void)
Definition at line 210 of file cpu.c.
References CST_IEc, GET_STATUS, and SET_STATUS.
Referenced by spllower().
cpu_machdep_init()
void cpu_machdep_init (struct cpu *)
Definition at line 76 of file cpu.c.
References cpu::c_curthread, cpu::c_number, cpustacks, cputhreads, KASSERT, MAXCPUS, NULL, STACK_SIZE, and thread::t_stack.
Referenced by cpu_create().
cpu_start_secondary()
void cpu_start_secondary (void)
Referenced by lamebus_start_cpus().
interprocessor_interrupt()
void interprocessor_interrupt (void)
Definition at line 1167 of file thread.c.
References cpu_halt(), IPI_OFFLINE, IPI_PANIC, IPI_TLBSHOOTDOWN, IPI_UNIDLE, kprintf(), spinlock_acquire(), spinlock_release(), and vm_tlbshootdown().
Referenced by mainbus_interrupt().
ipi_broadcast()
void ipi_broadcast (int code)
Definition at line 1116 of file thread.c.
References allcpus, cpu::c_self, and ipi_send().
Referenced by thread_panic(), and thread_shutdown().
ipi_send()
void ipi_send (struct cpu * target, int code)
Definition at line 1102 of file thread.c.
References cpu::c_ipi_lock, cpu::c_ipi_pending, KASSERT, mainbus_send_ipi(), spinlock_acquire(), and spinlock_release().
Referenced by ipi_broadcast(), thread_consider_migration(), and thread_make_runnable().
ipi_tlbshootdown()
void ipi_tlbshootdown (struct cpu * target, const struct tlbshootdown * mapping)
Definition at line 1133 of file thread.c.
References cpu::c_ipi_lock, cpu::c_ipi_pending, cpu::c_numshootdown, cpu::c_shootdown, IPI_TLBSHOOTDOWN, mainbus_send_ipi(), panic(), spinlock_acquire(), spinlock_release(), and TLBSHOOTDOWN_MAX.