os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/driver.c File Reference
driver.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Macros
#define LOWEST 'a'
#define HIGHEST '|'
Functions
int open_testfile (const char *string)
int create_testfile (void)
int reopen_testfile (int openflags)
int create_testdir (void)
int create_testlink (void)
static void menu (void)
static void runit (int op)
int main (int argc, char **argv)
Variables
struct {
int ch
int asst
const char * name
void(* f)(void)
} ops []
Macro Definition Documentation
HIGHEST
#define HIGHEST '|'
Definition at line 193 of file driver.c.
LOWEST
#define LOWEST 'a'
Definition at line 192 of file driver.c.
Function Documentation
create_testdir()
int create_testdir (void)
Definition at line 121 of file driver.c.
References ENOSYS, errno, mkdir(), report_aborted(), report_saw_enosys(), report_skipped(), report_warn(), report_warnx(), and TESTDIR.
Referenced by link_empty2(), remove_dir(), and rename_empty2().
create_testfile()
int create_testfile (void)
Definition at line 84 of file driver.c.
References close(), fd, NULL, open_testfile(), report_warn(), and TESTFILE.
Referenced by common_badpath(), and rmdir_file().
create_testlink()
int create_testlink (void)
Definition at line 141 of file driver.c.
References report_warn(), symlink(), and TESTLINK.
Referenced by readlink_setup().
main()
int main (int argc, char ** argv)
Definition at line 260 of file driver.c.
References EOF, getchar(), HIGHEST, LOWEST, menu(), printf(), and runit().
menu()
static void menu (void) static
Definition at line 197 of file driver.c.
References ch, name, ops, and printf().
Referenced by main(), and runit().
open_testfile()
int open_testfile (const char * string)
Definition at line 46 of file driver.c.
References close(), fd, lseek(), O_CREAT, O_RDWR, O_TRUNC, open(), remove(), report_warn(), SEEK_SET, strlen(), TESTFILE, and write().
Referenced by create_testfile(), ftruncate_size_neg(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), read_setup(), readlink_file(), wait_siblings(), and write_setup().
reopen_testfile()
int reopen_testfile (int openflags)
Definition at line 103 of file driver.c.
References fd, open(), report_warn(), and TESTFILE.
Referenced by runtest().
runit()
static void runit (int op) static
Definition at line 219 of file driver.c.
References asst, exit(), HIGHEST, menu(), name, ops, and printf().
Referenced by main().
Variable Documentation
asst
int asst
Definition at line 157 of file driver.c.
Referenced by runit(), and trycalls().
ch
int ch
Definition at line 156 of file driver.c.
Referenced by __pf_getnum(), __pf_modifier(), __pf_send(), __pf_setbase(), check_buffer(), con_input(), con_io(), doargs(), getchar(), getcmd(), geti(), kgets(), loudthread(), lscreen_char(), lscreen_irq(), lscreen_write(), lser_irq(), lser_write(), lser_writepolled(), main(), memchr(), memset(), menu(), option(), putch(), putch_delayed(), putch_intr(), putch_polled(), putchar(), quietthread(), rotate(), strchr(), and strrchr().
f
void(* f) (void)
Definition at line 159 of file driver.c.
Referenced by __pf_fill(), file_randomwrite(), op_close(), op_truncate(), op_write(), qsort(), random_unlocked(), sfs_link(), wl_append(), wl_appendandtruncpartly(), wl_appendandtrunczero(), wl_fillhole(), wl_randupdate(), wl_rmfiledelayed(), wl_rmfiledelayedappend(), wl_truncfill(), wl_trunclargersize(), wl_trunconeblock(), wl_truncsmallersize(), wl_trunczero(), writeemptyfile(), writeholeyfile(), and writeoutfile().
name
const char* name
Definition at line 158 of file driver.c.
Referenced by menu(), and runit().
ops
struct { ... } ops[]
Referenced by menu(), runit(), sfs_loadvnode(), and vnode_init().