os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/vfs/devnull.c File Reference
devnull.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <uio.h>
#include <vfs.h>
#include <device.h>
Functions
static int nullopen (struct device *dev, int openflags)
static int nullio (struct device *dev, struct uio *uio)
static int nullioctl (struct device *dev, int op, userptr_t data)
void devnull_create (void)
Variables
static const struct device_ops null_devops
Function Documentation
devnull_create()
void devnull_create (void)
Definition at line 101 of file devnull.c.
References device::d_blocks, device::d_blocksize, device::d_data, device::d_devnumber, device::d_ops, kmalloc(), NULL, null_devops, panic(), strerror(), and vfs_adddev().
Referenced by vfs_bootstrap().
nullio()
static int nullio (struct device * dev, struct uio * uio) static
Definition at line 55 of file devnull.c.
References uio::uio_resid, uio::uio_rw, and UIO_WRITE.
nullioctl()
static int nullioctl (struct device * dev, int op, userptr_t data) static
Definition at line 78 of file devnull.c.
References EINVAL.
nullopen()
static int nullopen (struct device * dev, int openflags) static
Definition at line 44 of file devnull.c.
Variable Documentation
null_devops
const struct device_ops null_devops static
Initial value:
= {
    .devop_eachopen = nullopen,
    .devop_io = nullio,
    .devop_ioctl = nullioctl,
}
Definition at line 91 of file devnull.c.
Referenced by devnull_create().