os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/fs/sfs/sfs_balloc.c File Reference
sfs_balloc.c File Reference
#include <types.h>
#include <lib.h>
#include <bitmap.h>
#include <sfs.h>
#include "sfsprivate.h"
Functions
static int sfs_clearblock (struct sfs_fs *sfs, daddr_t block)
int sfs_balloc (struct sfs_fs *sfs, daddr_t *diskblock)
void sfs_bfree (struct sfs_fs *sfs, daddr_t diskblock)
int sfs_bused (struct sfs_fs *sfs, daddr_t diskblock)
Function Documentation
sfs_balloc()
int sfs_balloc (struct sfs_fs * sfs, daddr_t * diskblock)
Definition at line 58 of file sfs_balloc.c.
References bitmap_alloc(), bitmap_unmark(), panic(), sfs_superblock::sb_nblocks, sfs_superblock::sb_volname, sfs_clearblock(), sfs_fs::sfs_freemap, sfs_fs::sfs_freemapdirty, and sfs_fs::sfs_sb.
Referenced by sfs_bmap(), and sfs_makeobj().
sfs_bfree()
void sfs_bfree (struct sfs_fs * sfs, daddr_t diskblock)
Definition at line 85 of file sfs_balloc.c.
References bitmap_unmark(), sfs_fs::sfs_freemap, and sfs_fs::sfs_freemapdirty.
Referenced by sfs_itrunc(), sfs_makeobj(), and sfs_reclaim().
sfs_bused()
int sfs_bused (struct sfs_fs * sfs, daddr_t diskblock)
Definition at line 95 of file sfs_balloc.c.
References bitmap_isset(), panic(), sfs_superblock::sb_nblocks, sfs_superblock::sb_volname, sfs_fs::sfs_freemap, and sfs_fs::sfs_sb.
Referenced by sfs_bmap(), and sfs_loadvnode().
sfs_clearblock()
static int sfs_clearblock (struct sfs_fs * sfs, daddr_t block) static
Definition at line 46 of file sfs_balloc.c.
References SFS_BLOCKSIZE, and sfs_writeblock().
Referenced by sfs_balloc().