os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/arch/mips/vm/dumbvm.c File Reference
dumbvm.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <spl.h>
#include <cpu.h>
#include <spinlock.h>
#include <proc.h>
#include <current.h>
#include <mips/tlb.h>
#include <addrspace.h>
#include <vm.h>
Macros
#define DUMBVM_STACKPAGES 18
Functions
void vm_bootstrap (void)
static void dumbvm_can_sleep (void)
static paddr_t getppages (unsigned long npages)
vaddr_t alloc_kpages (unsigned npages)
void free_kpages (vaddr_t addr)
void vm_tlbshootdown (const struct tlbshootdown *ts)
int vm_fault (int faulttype, vaddr_t faultaddress)
struct addrspace * as_create (void)
void as_destroy (struct addrspace *as)
void as_activate (void)
void as_deactivate (void)
int as_define_region (struct addrspace *as, vaddr_t vaddr, size_t sz, int readable, int writeable, int executable)
static void as_zero_region (paddr_t paddr, unsigned npages)
int as_prepare_load (struct addrspace *as)
int as_complete_load (struct addrspace *as)
int as_define_stack (struct addrspace *as, vaddr_t *stackptr)
int as_copy (struct addrspace *old, struct addrspace **ret)
Variables
static struct spinlock stealmem_lock = SPINLOCK_INITIALIZER
Macro Definition Documentation
DUMBVM_STACKPAGES
#define DUMBVM_STACKPAGES 18
Definition at line 60 of file dumbvm.c.
Function Documentation
alloc_kpages()
vaddr_t alloc_kpages (unsigned npages)
Definition at line 109 of file dumbvm.c.
References dumbvm_can_sleep(), getppages(), and PADDR_TO_KVADDR.
Referenced by allocpagerefpage(), kmalloc(), and subpage_kmalloc().
as_activate()
void as_activate (void)
Definition at line 264 of file dumbvm.c.
Referenced by runprogram(), thread_startup(), and thread_switch().
as_complete_load()
int as_complete_load (struct addrspace * as)
Definition at line 370 of file dumbvm.c.
Referenced by load_elf().
as_copy()
int as_copy (struct addrspace * old, struct addrspace ** ret)
Definition at line 387 of file dumbvm.c.
as_create()
struct addrspace* as_create (void)
Definition at line 238 of file dumbvm.c.
Referenced by as_copy(), and runprogram().
as_deactivate()
void as_deactivate (void)
Definition at line 285 of file dumbvm.c.
Referenced by proc_destroy().
as_define_region()
int as_define_region (struct addrspace * as, vaddr_t vaddr, size_t sz, int readable, int writeable, int executable)
Definition at line 291 of file dumbvm.c.
Referenced by load_elf().
as_define_stack()
int as_define_stack (struct addrspace * as, vaddr_t * stackptr)
Definition at line 378 of file dumbvm.c.
Referenced by runprogram().
as_destroy()
void as_destroy (struct addrspace * as)
Definition at line 257 of file dumbvm.c.
Referenced by as_copy(), and proc_destroy().
as_prepare_load()
int as_prepare_load (struct addrspace * as)
Definition at line 339 of file dumbvm.c.
Referenced by as_copy(), and load_elf().
as_zero_region()
static void as_zero_region (paddr_t paddr, unsigned npages) static
Definition at line 333 of file dumbvm.c.
References bzero(), PADDR_TO_KVADDR, and PAGE_SIZE.
Referenced by as_prepare_load().
dumbvm_can_sleep()
static void dumbvm_can_sleep (void) static
Definition at line 82 of file dumbvm.c.
References KASSERT.
Referenced by alloc_kpages(), as_complete_load(), as_copy(), as_define_region(), as_destroy(), and as_prepare_load().
free_kpages()
void free_kpages (vaddr_t addr)
Definition at line 122 of file dumbvm.c.
Referenced by allocpagerefpage(), kfree(), subpage_kfree(), and subpage_kmalloc().
getppages()
static paddr_t getppages (unsigned long npages) static
Definition at line 95 of file dumbvm.c.
References ram_stealmem(), spinlock_acquire(), spinlock_release(), and stealmem_lock.
Referenced by alloc_kpages(), and as_prepare_load().
vm_bootstrap()
void vm_bootstrap (void)
Definition at line 68 of file dumbvm.c.
Referenced by boot().
vm_fault()
int vm_fault (int faulttype, vaddr_t faultaddress)
Definition at line 137 of file dumbvm.c.
References curproc, DB_VM, DEBUG, DUMBVM_STACKPAGES, EFAULT, EINVAL, KASSERT, kprintf(), NULL, NUM_TLB, PAGE_FRAME, PAGE_SIZE, panic(), proc_getas(), splhigh(), splx(), tlb_read(), tlb_write(), TLBLO_DIRTY, TLBLO_VALID, USERSTACK, VM_FAULT_READ, VM_FAULT_READONLY, and VM_FAULT_WRITE.
Referenced by mips_trap().
vm_tlbshootdown()
void vm_tlbshootdown (const struct tlbshootdown * ts)
Definition at line 130 of file dumbvm.c.
References panic().
Referenced by interprocessor_interrupt().
Variable Documentation
stealmem_lock
struct spinlock stealmem_lock = SPINLOCK_INITIALIZER static
Definition at line 65 of file dumbvm.c.
Referenced by getppages().