os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/arch/mips/include/spinlock.h File Reference
spinlock.h File Reference
#include <cdefs.h>
Macros
#define SPINLOCK_DATA_INITIALIZER 0
Typedefs
typedef unsigned spinlock_data_t
Functions
SPINLOCK_INLINE void spinlock_data_set (volatile spinlock_data_t *sd, unsigned val)
SPINLOCK_INLINE spinlock_data_t spinlock_data_get (volatile spinlock_data_t *sd)
SPINLOCK_INLINE spinlock_data_t spinlock_data_testandset (volatile spinlock_data_t *sd)
Macro Definition Documentation
SPINLOCK_DATA_INITIALIZER
#define SPINLOCK_DATA_INITIALIZER 0
Definition at line 40 of file spinlock.h.
Typedef Documentation
spinlock_data_t
typedef unsigned spinlock_data_t
Definition at line 37 of file spinlock.h.
Function Documentation
spinlock_data_get()
SPINLOCK_INLINE spinlock_data_t spinlock_data_get (volatile spinlock_data_t * sd)
Definition at line 70 of file spinlock.h.
Referenced by spinlock_acquire(), and spinlock_cleanup().
spinlock_data_set()
SPINLOCK_INLINE void spinlock_data_set (volatile spinlock_data_t * sd, unsigned val)
Definition at line 59 of file spinlock.h.
Referenced by spinlock_init(), and spinlock_release().
spinlock_data_testandset()
SPINLOCK_INLINE spinlock_data_t spinlock_data_testandset (volatile spinlock_data_t * sd)
Definition at line 90 of file spinlock.h.
Referenced by spinlock_acquire().