os161-doc: /home/os161user/os161/os161-base-2.0.3/build/install/include/err.h File Reference
err.h File Reference
#include <sys/cdefs.h>
#include <kern/types.h>
Functions
void warn (const char *fmt,...)
void warnx (const char *fmt,...)
__DEAD void err (int exitcode, const char *fmt,...)
__DEAD void errx (int exitcode, const char *fmt,...)
void vwarn (const char *fmt, __va_list)
void vwarnx (const char *fmt, __va_list)
__DEAD void verr (int exitcode, const char *fmt, __va_list)
__DEAD void verrx (int exitcode, const char *fmt, __va_list)
Function Documentation
err()
__DEAD void err (int exitcode, const char * fmt, ...)
Definition at line 176 of file err.c.
Referenced by __malloc_init(), __printf_send(), basetest(), big_file(), cat(), check_sbrk(), check_slogan(), checkallfilecontents(), checkfilezeros(), checkonefilecontents(), chkfile(), cleanup(), closedisk(), closeit(), complain(), conctest(), concur(), copy(), createresultsfile(), createstress_thread(), dir_test(), diskread(), diskwrite(), do_chdir(), do_chdirup(), do_createfile(), do_link(), do_mkdir(), do_opendir(), do_openfile(), do_rename(), do_renamexd(), do_rmdir(), do_truncate(), do_unlink(), do_write(), dobadreads(), docat(), docreatestress(), dodup2(), dofork(), dohardlink(), dolongstress(), dolseek(), doopen(), doread(), doreadat0(), doreadateof(), doreadone(), doreadstress(), doremove(), dorename(), dorm(), dosbrk(), dosymlink(), dowait(), dowrite(), dowritestress(), dowritestress2(), enforce_sbrk(), exec_common_fork(), finish(), firstread(), forkem(), fstest_read(), fstest_remove(), fstest_write(), getnum(), getresult(), getseed(), grind(), inspectdir(), inspectfs(), isdir(), killdir(), lhd_iodone(), listdir(), main(), makeprocs(), mkfile(), moremem(), opendisk(), openit(), openresultsfile(), openscratch(), P(), Pn(), pong_prep(), print(), putresult(), readateof(), readfile(), readfiledata(), readit(), readone(), recursedir(), runop(), runtaskgroup(), self(), semcreate(), semopen(), semP(), semV(), setup(), spawnv(), startup(), subproc_read(), subproc_write(), syscall(), tail(), test2(), test3(), test4(), test5(), test6(), test7(), try(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_reading(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), trymany(), usem_init(), usem_open(), V(), Vn(), vprintf(), vscomplain(), wait_badpid(), and write_slogan().
errx()
__DEAD void errx (int exitcode, const char * fmt, ...)
Definition at line 185 of file err.c.
Referenced by __malloc_init(), __malloc_sbrk(), __malloc_split(), __malloc_trymerge(), big_file(), cat(), check(), check_bss(), check_buffer(), check_data(), check_sbrk(), check_slogan(), checkfilezeros(), chkfile(), dec(), die(), dodup2(), dolseek(), domalloc(), doreadat0(), doreadateof(), doreadone(), dorealloc(), dosbrk(), dowait(), dowrite(), dumpdata(), finishcarry(), firstread(), free(), getnum(), getresult(), getseed(), grind(), initfreemap(), inode_find(), inspectdir(), main(), malloc(), mkfile(), multc(), name_find(), number_init(), opendisk(), option(), P(), Pn(), poolalloc(), putresult(), readateof(), readfiledata(), readit(), readone(), readsb(), runop(), sb_load(), setup(), strtosize(), subproc_read(), test1(), test10(), test12(), test13(), test14(), test15(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), try_reading(), usage(), V(), Vn(), waitall(), wl_compile(), wl_cvsupdate(), write_slogan(), and writesuper().
verr()
__DEAD void verr (int exitcode, const char * fmt, __va_list)
Definition at line 138 of file err.c.
verrx()
__DEAD void verrx (int exitcode, const char * fmt, __va_list)
Definition at line 146 of file err.c.
vwarn()
void vwarn (const char * fmt, __va_list)
Definition at line 124 of file err.c.
vwarnx()
void vwarnx (const char * fmt, __va_list)
Definition at line 131 of file err.c.
warn()
void warn (const char * fmt, ...)
Definition at line 158 of file err.c.
Referenced by cat(), closeresultsfile(), cmd_chdir(), createresultsfile(), destroyresultsfile(), do_closedir(), do_closefile(), do_sync(), docommand(), dofork(), dorm(), dowait(), forkoff(), getdirentry_setup(), main(), makeprocs(), spawn(), usem_close(), and waitall().
warnx()
void warnx (const char * fmt, ...)
Definition at line 167 of file err.c.
Referenced by __malloc_init(), check(), check_bss(), check_data(), check_indirect_block(), check_inode_blocks(), check_sbrk(), check_slogan(), check_timing(), doclose(), docommand(), dorm(), dowait(), dumpargs(), dumpdir(), free(), freemap_blockinuse(), freemap_check(), grind(), inode_adjust_filelinks(), main(), malloc(), number_init(), pass1_dir(), pass1_direntry(), pass1_inode(), pass1_rootdir(), pass2_dir(), reportfreemap(), runop(), runtest(), sb_check(), setup(), sfs_readdirblock(), sfs_writedirblock(), spawn(), stresstest(), test(), test10(), test11(), test3(), test4(), test5(), test9(), test_dup2(), touchmem(), triple(), usage(), and waitall().