os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/main/main.c File Reference
main.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/reboot.h>
#include <kern/unistd.h>
#include <lib.h>
#include <spl.h>
#include <clock.h>
#include <thread.h>
#include <proc.h>
#include <current.h>
#include <synch.h>
#include <vm.h>
#include <mainbus.h>
#include <vfs.h>
#include <device.h>
#include <syscall.h>
#include <test.h>
#include <version.h>
#include "autoconf.h"
Functions
static void boot (void)
static void shutdown (void)
int sys_reboot (int code)
void kmain (char *arguments)
Variables
const int buildversion
const char buildconfig []
static const char harvard_copyright []
Function Documentation
boot()
static void boot (void) static
Definition at line 80 of file main.c.
References BASE_VERSION, buildconfig, buildversion, COMPILE_ASSERT, GROUP_VERSION, hardclock_bootstrap(), harvard_copyright, KASSERT, kheap_nextgeneration(), kprintf(), kprintf_bootstrap(), mainbus_bootstrap(), proc_bootstrap(), pseudoconfig(), ram_bootstrap(), thread_bootstrap(), thread_start_cpus(), vfs_bootstrap(), vfs_setbootfs(), and vm_bootstrap().
Referenced by kmain().
kmain()
void kmain (char * arguments)
Definition at line 209 of file main.c.
References boot(), and menu().
shutdown()
static void shutdown (void) static
Definition at line 148 of file main.c.
References kprintf(), splhigh(), thread_shutdown(), vfs_clearbootfs(), vfs_clearcurdir(), and vfs_unmountall().
Referenced by sys_reboot().
sys_reboot()
int sys_reboot (int code)
Definition at line 172 of file main.c.
References EINVAL, kprintf(), mainbus_halt(), mainbus_poweroff(), mainbus_reboot(), panic(), RB_HALT, RB_POWEROFF, RB_REBOOT, and shutdown().
Referenced by cmd_quit(), and syscall().
Variable Documentation
buildconfig
const char buildconfig[]
Definition at line 3 of file vers.c.
Referenced by boot().
buildversion
const int buildversion
Definition at line 2 of file vers.c.
Referenced by boot().
harvard_copyright
const char harvard_copyright[] static
Initial value:
=
    "Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014\n"
    "   President and Fellows of Harvard College.  All rights reserved.\n"
Definition at line 70 of file main.c.
Referenced by boot().