os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/dev/lamebus/lamebus.h File Reference
lamebus.h File Reference
#include <cpu.h>
#include <spinlock.h>
Data Structures
struct lamebus_softc
Macros
#define LB_VENDOR_CS161 1
#define LBCS161_UPBUSCTL 1
#define LBCS161_TIMER 2
#define LBCS161_DISK 3
#define LBCS161_SERIAL 4
#define LBCS161_SCREEN 5
#define LBCS161_NET 6
#define LBCS161_EMUFS 7
#define LBCS161_TRACE 8
#define LBCS161_RANDOM 9
#define LBCS161_MPBUSCTL 10
#define LB_CONTROLLER_SLOT 31
#define LB_NSLOTS 32
#define LB_CONFIG_SIZE 1024
#define LB_CTLCPU_SIZE 1024
#define LB_CTLCPU_OFFSET 32768
#define LB_SLOT_SIZE 65536
Typedefs
typedef void(* lb_irqfunc) (void *devdata)
Functions
struct lamebus_softc * lamebus_init (void)
void lamebus_find_cpus (struct lamebus_softc *lamebus)
void lamebus_start_cpus (struct lamebus_softc *lamebus)
int lamebus_probe (struct lamebus_softc *, uint32_t vendorid, uint32_t deviceid, uint32_t lowver, uint32_t *version_ret)
void lamebus_mark (struct lamebus_softc *, int slot)
void lamebus_unmark (struct lamebus_softc *, int slot)
void lamebus_attach_interrupt (struct lamebus_softc *, int slot, void *devdata, void(*irqfunc)(void *devdata))
void lamebus_detach_interrupt (struct lamebus_softc *, int slot)
void lamebus_mask_interrupt (struct lamebus_softc *, int slot)
void lamebus_unmask_interrupt (struct lamebus_softc *, int slot)
void lamebus_interrupt (struct lamebus_softc *)
void lamebus_poweroff (struct lamebus_softc *)
size_t lamebus_ramsize (void)
void lamebus_assert_ipi (struct lamebus_softc *, struct cpu *targetcpu)
void lamebus_clear_ipi (struct lamebus_softc *, struct cpu *targetcpu)
uint32_t lamebus_read_register (struct lamebus_softc *, int slot, uint32_t offset)
void lamebus_write_register (struct lamebus_softc *, int slot, uint32_t offset, uint32_t val)
void * lamebus_map_area (struct lamebus_softc *, int slot, uint32_t offset)
Macro Definition Documentation
LB_CONFIG_SIZE
#define LB_CONFIG_SIZE 1024
Definition at line 65 of file lamebus.h.
LB_CONTROLLER_SLOT
#define LB_CONTROLLER_SLOT 31
Definition at line 59 of file lamebus.h.
LB_CTLCPU_OFFSET
#define LB_CTLCPU_OFFSET 32768
Definition at line 71 of file lamebus.h.
LB_CTLCPU_SIZE
#define LB_CTLCPU_SIZE 1024
Definition at line 68 of file lamebus.h.
LB_NSLOTS
#define LB_NSLOTS 32
Definition at line 62 of file lamebus.h.
LB_SLOT_SIZE
#define LB_SLOT_SIZE 65536
Definition at line 74 of file lamebus.h.
LB_VENDOR_CS161
#define LB_VENDOR_CS161 1
Definition at line 44 of file lamebus.h.
LBCS161_DISK
#define LBCS161_DISK 3
Definition at line 49 of file lamebus.h.
LBCS161_EMUFS
#define LBCS161_EMUFS 7
Definition at line 53 of file lamebus.h.
LBCS161_MPBUSCTL
#define LBCS161_MPBUSCTL 10
Definition at line 56 of file lamebus.h.
LBCS161_NET
#define LBCS161_NET 6
Definition at line 52 of file lamebus.h.
LBCS161_RANDOM
#define LBCS161_RANDOM 9
Definition at line 55 of file lamebus.h.
LBCS161_SCREEN
#define LBCS161_SCREEN 5
Definition at line 51 of file lamebus.h.
LBCS161_SERIAL
#define LBCS161_SERIAL 4
Definition at line 50 of file lamebus.h.
LBCS161_TIMER
#define LBCS161_TIMER 2
Definition at line 48 of file lamebus.h.
LBCS161_TRACE
#define LBCS161_TRACE 8
Definition at line 54 of file lamebus.h.
LBCS161_UPBUSCTL
#define LBCS161_UPBUSCTL 1
Definition at line 47 of file lamebus.h.
Typedef Documentation
lb_irqfunc
typedef void(* lb_irqfunc) (void *devdata)
Definition at line 77 of file lamebus.h.
Function Documentation
lamebus_assert_ipi()
void lamebus_assert_ipi (struct lamebus_softc * , struct cpu * targetcpu)
Definition at line 615 of file lamebus.c.
References cpu::c_hardware_number, CTLCPU_CIPI, lamebus, lamebus_softc::ls_uniprocessor, and write_ctlcpu_register().
Referenced by mainbus_send_ipi().
lamebus_attach_interrupt()
void lamebus_attach_interrupt (struct lamebus_softc * , int slot, void * devdata, void(*)(void *devdata) irqfunc)
Definition at line 351 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), spinlock_acquire(), and spinlock_release().
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), and attach_ltimer_to_lamebus().
lamebus_clear_ipi()
void lamebus_clear_ipi (struct lamebus_softc * , struct cpu * targetcpu)
Definition at line 625 of file lamebus.c.
References cpu::c_hardware_number, CTLCPU_CIPI, lamebus, lamebus_softc::ls_uniprocessor, and write_ctlcpu_register().
Referenced by mainbus_interrupt().
lamebus_detach_interrupt()
void lamebus_detach_interrupt (struct lamebus_softc * , int slot)
Definition at line 379 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), spinlock_acquire(), and spinlock_release().
lamebus_find_cpus()
void lamebus_find_cpus (struct lamebus_softc * lamebus)
Definition at line 128 of file lamebus.c.
References CFGREG_DID, CFGREG_VID, cpu_create(), CTLCPU_CIRQE, CTLREG_CPUS, CTLREG_SELF, lamebus, LB_CONTROLLER_SLOT, LB_VENDOR_CS161, LBCS161_UPBUSCTL, lamebus_softc::ls_uniprocessor, read_cfg_register(), read_ctl_register(), and write_ctlcpu_register().
Referenced by mainbus_bootstrap().
lamebus_init()
struct lamebus_softc* lamebus_init (void)
Definition at line 639 of file lamebus.c.
References kmalloc(), lamebus, LB_CONTROLLER_SLOT, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, lamebus_softc::ls_uniprocessor, NULL, panic(), and spinlock_init().
Referenced by mainbus_bootstrap().
lamebus_interrupt()
void lamebus_interrupt (struct lamebus_softc *)
Definition at line 433 of file lamebus.c.
References CTLREG_IRQS, KASSERT, kprintf(), lamebus, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), read_ctl_register(), spinlock_acquire(), and spinlock_release().
Referenced by mainbus_interrupt().
lamebus_map_area()
void* lamebus_map_area (struct lamebus_softc * , int slot, uint32_t offset)
Definition at line 137 of file lamebus_machdep.c.
References KASSERT, LB_BASEADDR, LB_NSLOTS, and LB_SLOT_SIZE.
Referenced by lamebus_read_register(), lamebus_start_cpus(), and lamebus_write_register().
lamebus_mark()
void lamebus_mark (struct lamebus_softc * , int slot)
Definition at line 310 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, panic(), spinlock_acquire(), and spinlock_release().
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), and attach_ltrace_to_lamebus().
lamebus_mask_interrupt()
void lamebus_mask_interrupt (struct lamebus_softc * , int slot)
Definition at line 403 of file lamebus.c.
References CTLREG_IRQE, KASSERT, lamebus, LB_NSLOTS, lamebus_softc::ls_lock, read_ctl_register(), spinlock_acquire(), spinlock_release(), and write_ctl_register().
lamebus_poweroff()
void lamebus_poweroff (struct lamebus_softc *)
Definition at line 582 of file lamebus.c.
References cpu_halt(), cpu_irqoff(), CTLREG_PWR, lamebus, and write_ctl_register().
Referenced by mainbus_poweroff().
lamebus_probe()
int lamebus_probe (struct lamebus_softc * , uint32_t vendorid, uint32_t deviceid, uint32_t lowver, uint32_t * version_ret)
Definition at line 251 of file lamebus.c.
References CFGREG_DID, CFGREG_DRL, CFGREG_VID, LB_NSLOTS, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, read_cfg_register(), spinlock_acquire(), and spinlock_release().
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lnet_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), and attach_ltrace_to_lamebus().
lamebus_ramsize()
size_t lamebus_ramsize (void)
Definition at line 599 of file lamebus.c.
References CTLREG_RAMSZ, NULL, and read_ctl_register().
Referenced by mainbus_ramsize().
lamebus_read_register()
uint32_t lamebus_read_register (struct lamebus_softc * , int slot, uint32_t offset)
Definition at line 153 of file lamebus_machdep.c.
References lamebus_map_area(), and membar_load_load().
Referenced by read_cfg_register().
lamebus_start_cpus()
void lamebus_start_cpus (struct lamebus_softc * lamebus)
Definition at line 197 of file lamebus.c.
References cpu_start_secondary(), CTLCPU_CRAM, CTLREG_CPUE, CTLREG_CPUS, CTLREG_SELF, lamebus, lamebus_map_area(), LB_CONTROLLER_SLOT, LB_CTLCPU_OFFSET, LB_CTLCPU_SIZE, lamebus_softc::ls_uniprocessor, membar_store_store(), read_ctl_register(), and write_ctl_register().
Referenced by mainbus_start_cpus().
lamebus_unmark()
void lamebus_unmark (struct lamebus_softc * , int slot)
Definition at line 330 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, panic(), spinlock_acquire(), and spinlock_release().
lamebus_unmask_interrupt()
void lamebus_unmask_interrupt (struct lamebus_softc * , int slot)
Definition at line 416 of file lamebus.c.
References CTLREG_IRQE, KASSERT, lamebus, LB_NSLOTS, lamebus_softc::ls_lock, read_ctl_register(), spinlock_acquire(), spinlock_release(), and write_ctl_register().
lamebus_write_register()
void lamebus_write_register (struct lamebus_softc * , int slot, uint32_t offset, uint32_t val)
Definition at line 172 of file lamebus_machdep.c.
References lamebus_map_area(), and membar_store_store().
Referenced by write_cfg_register(), and write_ctlcpu_register().