os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/fs/semfs/semfs.h File Reference
semfs.h File Reference
#include <array.h>
#include <fs.h>
#include <vnode.h>
Data Structures
struct semfs_sem
struct semfs_direntry
struct semfs_vnode
struct semfs
Macros
#define SEMFS_INLINE INLINE
#define SEMFS_ROOTDIR 0xffffffffU /* semnum for root dir */
Functions
DECLARRAY (semfs_sem, SEMFS_INLINE)
DECLARRAY (semfs_direntry, SEMFS_INLINE)
DEFARRAY (semfs_sem, SEMFS_INLINE)
DEFARRAY (semfs_direntry, SEMFS_INLINE)
struct semfs_sem * semfs_sem_create (const char *name)
int semfs_sem_insert (struct semfs *, struct semfs_sem *, unsigned *)
void semfs_sem_destroy (struct semfs_sem *)
struct semfs_direntry * semfs_direntry_create (const char *name, unsigned semno)
void semfs_direntry_destroy (struct semfs_direntry *)
int semfs_getvnode (struct semfs *, unsigned, struct vnode **ret)
Macro Definition Documentation
SEMFS_INLINE
#define SEMFS_INLINE INLINE
Definition at line 38 of file semfs.h.
SEMFS_ROOTDIR
#define SEMFS_ROOTDIR 0xffffffffU /* semnum for root dir */
Definition at line 45 of file semfs.h.
Function Documentation
DECLARRAY() [1/2]
DECLARRAY (semfs_direntry , SEMFS_INLINE)
DECLARRAY() [2/2]
DECLARRAY (semfs_sem , SEMFS_INLINE)
DEFARRAY() [1/2]
DEFARRAY (semfs_direntry , SEMFS_INLINE)
DEFARRAY() [2/2]
DEFARRAY (semfs_sem , SEMFS_INLINE)
semfs_direntry_create()
struct semfs_direntry* semfs_direntry_create (const char * name, unsigned semno)
Definition at line 120 of file semfs_obj.c.
References kfree(), kmalloc(), kstrdup(), name, NULL, semfs_direntry::semd_name, and semfs_direntry::semd_semnum.
Referenced by semfs_creat().
semfs_direntry_destroy()
void semfs_direntry_destroy (struct semfs_direntry *)
Definition at line 141 of file semfs_obj.c.
References kfree(), and semfs_direntry::semd_name.
Referenced by semfs_creat(), semfs_destroy(), and semfs_remove().
semfs_getvnode()
int semfs_getvnode (struct semfs * , unsigned , struct vnode ** ret)
Definition at line 753 of file semfs_vnops.c.
References ENOMEM, KASSERT, lock_acquire(), lock_release(), NULL, num, SEMFS_ROOTDIR, semfs::semfs_sems, semfs::semfs_tablelock, semfs_vnode_create(), semfs_vnode_destroy(), semfs::semfs_vnodes, semfs_sem::sems_hasvnode, semfs_vnode::semv_absvn, semfs_vnode::semv_semnum, vnode::vn_data, and VOP_INCREF.
Referenced by semfs_creat(), semfs_getroot(), and semfs_lookup().
semfs_sem_create()
struct semfs_sem* semfs_sem_create (const char * name)
Definition at line 44 of file semfs_obj.c.
References cv_create(), kfree(), kmalloc(), lock_create(), lock_destroy(), name, NULL, semfs_sem::sems_count, semfs_sem::sems_cv, semfs_sem::sems_hasvnode, semfs_sem::sems_linked, semfs_sem::sems_lock, and snprintf().
Referenced by semfs_creat().
semfs_sem_destroy()
void semfs_sem_destroy (struct semfs_sem *)
Definition at line 82 of file semfs_obj.c.
References cv_destroy(), kfree(), lock_destroy(), semfs_sem::sems_cv, and semfs_sem::sems_lock.
Referenced by semfs_creat(), semfs_destroy(), semfs_reclaim(), and semfs_remove().
semfs_sem_insert()
int semfs_sem_insert (struct semfs * , struct semfs_sem * , unsigned *)
Definition at line 93 of file semfs_obj.c.
References ENOSPC, KASSERT, lock_do_i_hold(), NULL, num, SEMFS_ROOTDIR, semfs::semfs_sems, and semfs::semfs_tablelock.
Referenced by semfs_creat().