os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/threadlist.h File Reference
threadlist.h File Reference
Data Structures
struct threadlistnode
struct threadlist
Macros
#define THREADLIST_FORALL(itervar, tl)
#define THREADLIST_FORALL_REV(itervar, tl)
Functions
void threadlistnode_init (struct threadlistnode *tln, struct thread *self)
void threadlistnode_cleanup (struct threadlistnode *tln)
void threadlist_init (struct threadlist *tl)
void threadlist_cleanup (struct threadlist *tl)
bool threadlist_isempty (struct threadlist *tl)
void threadlist_addhead (struct threadlist *tl, struct thread *t)
void threadlist_addtail (struct threadlist *tl, struct thread *t)
struct thread * threadlist_remhead (struct threadlist *tl)
struct thread * threadlist_remtail (struct threadlist *tl)
void threadlist_insertafter (struct threadlist *tl, struct thread *onlist, struct thread *addee)
void threadlist_insertbefore (struct threadlist *tl, struct thread *addee, struct thread *onlist)
void threadlist_remove (struct threadlist *tl, struct thread *t)
Macro Definition Documentation
THREADLIST_FORALL
#define THREADLIST_FORALL (itervar, tl)
Value:
    for ((itervar) = (tl).tl_head.tln_next->tln_self; \
         (itervar) != NULL; \
         (itervar) = (itervar)->t_listnode.tln_next->tln_self)
Definition at line 94 of file threadlist.h.
THREADLIST_FORALL_REV
#define THREADLIST_FORALL_REV (itervar, tl)
Value:
    for ((itervar) = (tl).tl_tail.tln_prev->tln_self; \
         (itervar) != NULL; \
         (itervar) = (itervar)->t_listnode.tln_prev->tln_self)
Definition at line 99 of file threadlist.h.
Function Documentation
threadlist_addhead()
void threadlist_addhead (struct threadlist * tl, struct thread * t)
Definition at line 163 of file threadlist.c.
References DEBUGASSERT, NULL, threadlist_insertafternode(), threadlist::tl_count, and threadlist::tl_head.
Referenced by thread_consider_migration(), threadlisttest_b(), threadlisttest_c(), threadlisttest_d(), and threadlisttest_e().
threadlist_addtail()
void threadlist_addtail (struct threadlist * tl, struct thread * t)
Definition at line 173 of file threadlist.c.
References DEBUGASSERT, NULL, threadlist_insertbeforenode(), threadlist::tl_count, and threadlist::tl_tail.
Referenced by thread_consider_migration(), thread_make_runnable(), thread_switch(), threadlisttest_b(), threadlisttest_c(), threadlisttest_d(), threadlisttest_e(), threadlisttest_f(), and wchan_wakeall().
threadlist_cleanup()
void threadlist_cleanup (struct threadlist * tl)
Definition at line 75 of file threadlist.c.
References DEBUGASSERT, KASSERT, NULL, threadlist_isempty(), threadlist::tl_count, threadlist::tl_head, threadlist::tl_tail, threadlistnode::tln_next, threadlistnode::tln_prev, and threadlistnode::tln_self.
Referenced by thread_consider_migration(), threadlisttest_a(), threadlisttest_b(), threadlisttest_c(), threadlisttest_d(), threadlisttest_e(), wchan_destroy(), and wchan_wakeall().
threadlist_init()
void threadlist_init (struct threadlist * tl)
Definition at line 61 of file threadlist.c.
References DEBUGASSERT, NULL, threadlist::tl_count, threadlist::tl_head, threadlist::tl_tail, threadlistnode::tln_next, threadlistnode::tln_prev, and threadlistnode::tln_self.
Referenced by cpu_create(), thread_consider_migration(), threadlisttest_a(), threadlisttest_b(), threadlisttest_c(), threadlisttest_d(), threadlisttest_e(), threadlisttest_f(), wchan_create(), and wchan_wakeall().
threadlist_insertafter()
void threadlist_insertafter (struct threadlist * tl, struct thread * onlist, struct thread * addee)
Definition at line 219 of file threadlist.c.
References thread::t_listnode, threadlist_insertafternode(), and threadlist::tl_count.
Referenced by threadlisttest_e().
threadlist_insertbefore()
void threadlist_insertbefore (struct threadlist * tl, struct thread * addee, struct thread * onlist)
Definition at line 227 of file threadlist.c.
References thread::t_listnode, threadlist_insertbeforenode(), and threadlist::tl_count.
Referenced by threadlisttest_e().
threadlist_isempty()
bool threadlist_isempty (struct threadlist * tl)
Definition at line 92 of file threadlist.c.
References DEBUGASSERT, NULL, and threadlist::tl_count.
Referenced by thread_consider_migration(), thread_switch(), threadlist_cleanup(), threadlisttest_a(), and wchan_isempty().
threadlist_remhead()
struct thread* threadlist_remhead (struct threadlist * tl)
Definition at line 183 of file threadlist.c.
References DEBUGASSERT, NULL, threadlist_removenode(), threadlist::tl_count, threadlist::tl_head, threadlistnode::tln_next, and threadlistnode::tln_self.
Referenced by exorcise(), thread_consider_migration(), thread_switch(), threadlisttest_b(), threadlisttest_c(), threadlisttest_d(), threadlisttest_e(), threadlisttest_f(), wchan_wakeall(), and wchan_wakeone().
threadlist_remove()
void threadlist_remove (struct threadlist * tl, struct thread * t)
Definition at line 235 of file threadlist.c.
References DEBUGASSERT, thread::t_listnode, threadlist_removenode(), and threadlist::tl_count.
threadlist_remtail()
struct thread* threadlist_remtail (struct threadlist * tl)
Definition at line 201 of file threadlist.c.
References DEBUGASSERT, NULL, threadlist_removenode(), threadlist::tl_count, threadlist::tl_tail, threadlistnode::tln_prev, and threadlistnode::tln_self.
Referenced by thread_consider_migration(), threadlisttest_b(), threadlisttest_c(), and threadlisttest_d().
threadlistnode_cleanup()
void threadlistnode_cleanup (struct threadlistnode * tln)
Definition at line 51 of file threadlist.c.
References DEBUGASSERT, KASSERT, NULL, threadlistnode::tln_next, threadlistnode::tln_prev, and threadlistnode::tln_self.
Referenced by fakethread_destroy(), and thread_destroy().
threadlistnode_init()
void threadlistnode_init (struct threadlistnode * tln, struct thread * self)
Definition at line 40 of file threadlist.c.
References DEBUGASSERT, KASSERT, NULL, threadlistnode::tln_next, threadlistnode::tln_prev, and threadlistnode::tln_self.
Referenced by fakethread_create(), and thread_create().