os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/thread.h File Reference
thread.h File Reference
#include <array.h>
#include <spinlock.h>
#include <threadlist.h>
#include <machine/thread.h>
Data Structures
struct thread
Macros
#define STACK_SIZE 4096
#define STACK_MASK (~(vaddr_t)(STACK_SIZE-1))
#define SAME_STACK(p1, p2) (((p1) & STACK_MASK) == ((p2) & STACK_MASK))
#define THREADINLINE INLINE
Enumerations
enum threadstate_t { S_RUN, S_READY, S_SLEEP, S_ZOMBIE }
Functions
DECLARRAY (thread, THREADINLINE)
DEFARRAY (thread, THREADINLINE)
void thread_bootstrap (void)
void thread_start_cpus (void)
void thread_panic (void)
void thread_shutdown (void)
int thread_fork (const char *name, struct proc *proc, void(*func)(void *, unsigned long), void *data1, unsigned long data2)
__DEAD void thread_exit (void)
void thread_yield (void)
void schedule (void)
void thread_consider_migration (void)
Macro Definition Documentation
SAME_STACK
#define SAME_STACK (p1, p2) (((p1) & STACK_MASK) == ((p2) & STACK_MASK))
Definition at line 56 of file thread.h.
STACK_MASK
#define STACK_MASK (~(vaddr_t)(STACK_SIZE-1))
Definition at line 53 of file thread.h.
STACK_SIZE
#define STACK_SIZE 4096
Definition at line 50 of file thread.h.
THREADINLINE
#define THREADINLINE INLINE
Definition at line 116 of file thread.h.
Enumeration Type Documentation
threadstate_t
enum threadstate_t
Enumerator
S_RUN
S_READY
S_SLEEP
S_ZOMBIE
Definition at line 60 of file thread.h.
Function Documentation
DECLARRAY()
DECLARRAY (thread , THREADINLINE)
DEFARRAY()
DEFARRAY (thread , THREADINLINE)
schedule()
void schedule (void)
Definition at line 822 of file thread.c.
Referenced by hardclock().
thread_bootstrap()
void thread_bootstrap (void)
Definition at line 372 of file thread.c.
References allcpus, cpu_create(), KASSERT, kproc, and NULL.
Referenced by boot().
thread_consider_migration()
void thread_consider_migration (void)
Definition at line 848 of file thread.c.
References allcpus, cpu::c_isidle, cpu::c_number, cpu::c_runqueue, cpu::c_runqueue_lock, cpu::c_self, DB_THREADS, DEBUG, DIVROUNDUP, ipi_send(), IPI_UNIDLE, KASSERT, NULL, spinlock_acquire(), spinlock_release(), thread::t_cpu, thread::t_name, threadlist_addhead(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_isempty(), threadlist_remhead(), threadlist_remtail(), and threadlist::tl_count.
Referenced by hardclock().
thread_exit()
__DEAD void thread_exit (void)
Definition at line 779 of file thread.c.
References KASSERT, NULL, panic(), proc_remthread(), S_ZOMBIE, splhigh(), thread::t_proc, thread_checkstack(), and thread_switch().
Referenced by cmd_quit(), cpu_hatch(), cvtestthread(), fail(), and thread_startup().
thread_fork()
int thread_fork (const char * name, struct proc * proc, void(*)(void *, unsigned long) func, void * data1, unsigned long data2)
Referenced by cmd_deadlock(), common_prog(), cvtest(), cvtest2(), docreatestress(), dolongstress(), doreadstress(), dowritestress(), dowritestress2(), kmallocstress(), kmalloctest4(), locktest(), make_computes(), make_sleepalots(), makewaiter(), runthreads(), semtest(), semu17(), and semu19().
thread_panic()
void thread_panic (void)
Definition at line 315 of file thread.c.
References ipi_broadcast(), and IPI_PANIC.
Referenced by panic().
thread_shutdown()
void thread_shutdown (void)
Definition at line 357 of file thread.c.
References ipi_broadcast(), and IPI_OFFLINE.
Referenced by shutdown().
thread_start_cpus()
void thread_start_cpus (void)
Definition at line 427 of file thread.c.
References allcpus, buf, cpu_identify(), cpu_startup_sem, kprintf(), mainbus_start_cpus(), NULL, P(), sem_create(), and sem_destroy().
Referenced by boot().
thread_yield()
void thread_yield (void)
Definition at line 807 of file thread.c.
References NULL, S_READY, and thread_switch().
Referenced by compute_thread(), hardclock(), and waker_thread().