os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/main/menu.c File Reference
menu.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/reboot.h>
#include <kern/unistd.h>
#include <limits.h>
#include <lib.h>
#include <uio.h>
#include <clock.h>
#include <mainbus.h>
#include <synch.h>
#include <thread.h>
#include <proc.h>
#include <vfs.h>
#include <sfs.h>
#include <syscall.h>
#include <test.h>
#include "opt-sfs.h"
#include "opt-net.h"
Data Structures
struct deadlock
Macros
#define _PATH_SHELL "/bin/sh"
#define MAXMENUARGS 16
Functions
static void cmd_progthread (void *ptr, unsigned long nargs)
static int common_prog (int nargs, char **args)
static int cmd_prog (int nargs, char **args)
static int cmd_shell (int nargs, char **args)
static int cmd_chdir (int nargs, char **args)
static int cmd_pwd (int nargs, char **args)
static int cmd_sync (int nargs, char **args)
static int cmd_debug (int nargs, char **args)
static int cmd_panic (int nargs, char **args)
static void cmd_deadlockthread (void *ptr, unsigned long num)
static int cmd_deadlock (int nargs, char **args)
static int cmd_quit (int nargs, char **args)
static int cmd_mount (int nargs, char **args)
static int cmd_unmount (int nargs, char **args)
static int cmd_bootfs (int nargs, char **args)
static int cmd_kheapstats (int nargs, char **args)
static int cmd_kheapgeneration (int nargs, char **args)
static int cmd_kheapdump (int nargs, char **args)
static void showmenu (const char *name, const char *x[])
static int cmd_opsmenu (int n, char **a)
static int cmd_testmenu (int n, char **a)
static int cmd_mainmenu (int n, char **a)
static int cmd_dispatch (char *cmd)
static void menu_execute (char *line, int isargs)
void menu (char *args)
Variables
struct {
const char * name
int(* func)(const char *device)
} mounttable []
static const char * opsmenu []
static const char * testmenu []
static const char * mainmenu []
struct {
const char * name
int(* func)(int nargs, char **args)
} cmdtable []
Macro Definition Documentation
_PATH_SHELL
#define _PATH_SHELL "/bin/sh"
Definition at line 53 of file menu.c.
MAXMENUARGS
#define MAXMENUARGS 16
Definition at line 55 of file menu.c.
Function Documentation
cmd_bootfs()
static int cmd_bootfs (int nargs, char ** args) static
Definition at line 437 of file menu.c.
References EINVAL, kprintf(), strlen(), and vfs_setbootfs().
cmd_chdir()
static int cmd_chdir (int nargs, char ** args) static
Definition at line 186 of file menu.c.
References EINVAL, kprintf(), and vfs_chdir().
cmd_deadlock()
static int cmd_deadlock (int nargs, char ** args) static
Definition at line 302 of file menu.c.
References cmd_deadlockthread(), ENOMEM, kprintf(), deadlock::lock1, deadlock::lock2, lock_acquire(), lock_create(), lock_destroy(), lock_release(), NULL, strerror(), and thread_fork().
cmd_deadlockthread()
static void cmd_deadlockthread (void * ptr, unsigned long num) static
Definition at line 281 of file menu.c.
References kprintf(), deadlock::lock1, deadlock::lock2, lock_acquire(), lock_release(), and num.
Referenced by cmd_deadlock().
cmd_debug()
static int cmd_debug (int nargs, char ** args) static
Definition at line 247 of file menu.c.
References mainbus_debugger().
cmd_dispatch()
static int cmd_dispatch (char * cmd) static
Definition at line 718 of file menu.c.
References cmdtable, E2BIG, EINVAL, func, gettime(), KASSERT, kprintf(), MAXMENUARGS, name, NULL, strcmp(), strtok_r(), timespec_sub(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by menu_execute().
cmd_kheapdump()
static int cmd_kheapdump (int nargs, char ** args) static
Definition at line 482 of file menu.c.
References kheap_dump(), kheap_dumpall(), kprintf(), and strcmp().
cmd_kheapgeneration()
static int cmd_kheapgeneration (int nargs, char ** args) static
Definition at line 470 of file menu.c.
References kheap_nextgeneration().
cmd_kheapstats()
static int cmd_kheapstats (int nargs, char ** args) static
Definition at line 458 of file menu.c.
References kheap_printstats().
cmd_mainmenu()
static int cmd_mainmenu (int n, char ** a) static
Definition at line 610 of file menu.c.
References mainmenu, and showmenu().
cmd_mount()
static int cmd_mount (int nargs, char ** args) static
Definition at line 378 of file menu.c.
References ARRAYCOUNT, EINVAL, kprintf(), mounttable, name, strcmp(), and strlen().
cmd_opsmenu()
static int cmd_opsmenu (int n, char ** a) static
Definition at line 545 of file menu.c.
References opsmenu, and showmenu().
cmd_panic()
static int cmd_panic (int nargs, char ** args) static
Definition at line 262 of file menu.c.
References panic().
cmd_prog()
static int cmd_prog (int nargs, char ** args) static
Definition at line 149 of file menu.c.
References common_prog(), EINVAL, and kprintf().
cmd_progthread()
static void cmd_progthread (void * ptr, unsigned long nargs) static
Definition at line 74 of file menu.c.
References KASSERT, kprintf(), progname, runprogram(), strcpy(), strerror(), and strlen().
Referenced by common_prog().
cmd_pwd()
static int cmd_pwd (int nargs, char ** args) static
Definition at line 201 of file menu.c.
References buf, kprintf(), PATH_MAX, strerror(), uio_kinit(), UIO_READ, uio::uio_resid, and vfs_getcwd().
cmd_quit()
static int cmd_quit (int nargs, char ** args) static
Definition at line 351 of file menu.c.
References RB_POWEROFF, sys_reboot(), thread_exit(), and vfs_sync().
cmd_shell()
static int cmd_shell (int nargs, char ** args) static
Definition at line 168 of file menu.c.
References _PATH_SHELL, common_prog(), EINVAL, and kprintf().
cmd_sync()
static int cmd_sync (int nargs, char ** args) static
Definition at line 232 of file menu.c.
References vfs_sync().
cmd_testmenu()
static int cmd_testmenu (int n, char ** a) static
Definition at line 585 of file menu.c.
References kprintf(), showmenu(), and testmenu.
cmd_unmount()
static int cmd_unmount (int nargs, char ** args) static
Definition at line 408 of file menu.c.
References EINVAL, kprintf(), strlen(), and vfs_unmount().
common_prog()
static int common_prog (int nargs, char ** args) static
Definition at line 115 of file menu.c.
References cmd_progthread(), ENOMEM, kprintf(), NULL, proc_create_runprogram(), proc_destroy(), strerror(), and thread_fork().
Referenced by cmd_prog(), and cmd_shell().
menu()
void menu (char * args)
Definition at line 816 of file menu.c.
References buf, kgets(), kprintf(), and menu_execute().
Referenced by kmain(), and main().
menu_execute()
static void menu_execute (char * line, int isargs) static
Definition at line 774 of file menu.c.
References cmd_dispatch(), kprintf(), NULL, panic(), strerror(), and strtok_r().
Referenced by menu().
showmenu()
static void showmenu (const char * name, const char * x[]) static
Definition at line 503 of file menu.c.
References kprintf(), and name.
Referenced by cmd_mainmenu(), cmd_opsmenu(), and cmd_testmenu().
Variable Documentation
cmdtable
struct { ... } cmdtable[]
Referenced by cmd_dispatch().
func
int(* func) (int nargs, char **args)
Definition at line 369 of file menu.c.
Referenced by cmd_dispatch().
mainmenu
const char* mainmenu[] static
Initial value:
= {
    "[?o] Operations menu                ",
    "[?t] Tests menu                     ",
    "[kh] Kernel heap stats              ",
    "[khgen] Next kernel heap generation ",
    "[khdump] Dump kernel heap           ",
    "[q] Quit and shut down              ",
    NULL
}
Definition at line 598 of file menu.c.
Referenced by cmd_mainmenu().
mounttable
const { ... } mounttable[]
Initial value:
= {
}
Referenced by cmd_mount().
name
const char* name
Definition at line 368 of file menu.c.
Referenced by bin(), check_chdir(), check_closefile(), check_createfile(), check_mkdir(), check_openfile(), check_rmdir(), check_truncate(), check_unlink(), check_write(), cleanup_rmdir(), cmd_dispatch(), cmd_mount(), config_emu(), config_lhd(), createstress_thread(), cv_create(), do_chdir(), do_closedir(), do_closefile(), do_createfile(), do_mkdir(), do_opendir(), do_openfile(), do_rmdir(), do_semu1011(), do_semu89(), do_truncate(), do_unlink(), do_write(), docat(), dolseek(), domkdir(), doread(), dormdir(), dovalidate(), dowrite(), dowritestress2(), dumpinode(), emu_open(), emufs_creat(), emufs_creat_notdir(), emufs_link(), emufs_link_notdir(), emufs_mkdir(), emufs_mkdir_notdir(), emufs_name_op_notdir(), emufs_remove(), emufs_rmdir(), emufs_symlink(), emufs_symlink_notdir(), fakethread_create(), fc_create_creat(), fc_create_mkdir(), fc_create_rmdir(), fc_create_unlink(), fill(), findworkload(), fsdir_find_entry(), fsdir_remove_entry(), fsdirent_create(), fstest_read(), fstest_remove(), fstest_write(), lock_create(), lstat_badpath(), make_computes(), make_sleepalots(), mergebins(), mkdir_proc(), mkrawname(), model_finddir(), model_findfile(), model_isdir(), model_isfile(), name_get(), op_chdir(), op_mkdir(), op_open(), op_opendir(), op_rmdir(), op_unlink(), openscratch(), printworkloads(), proc_create(), proc_create_runprogram(), readfile(), rmdir_proc(), runthreads(), seekmyplace(), sem_create(), semfs_creat(), semfs_direntry_create(), semfs_remove(), semfs_sem_create(), semu1(), semu1213(), semu18(), semu19(), sfs_creat(), sfs_dir_findname(), sfs_dir_link(), sfs_link(), sfs_lookonce(), sfs_remove(), sfsdir_tryadd(), showmenu(), sortbins(), stat_badpath(), thread_create(), thread_fork(), validate(), vfs_doadd(), vfs_getcwd(), vfs_mkdir(), vfs_open(), vfs_remove(), vfs_rmdir(), vopfail_creat_notdir(), vopfail_link_nosys(), vopfail_link_notdir(), vopfail_mkdir_nosys(), vopfail_mkdir_notdir(), vopfail_string_nosys(), vopfail_string_notdir(), vopfail_symlink_nosys(), vopfail_symlink_notdir(), and wchan_create().
opsmenu
const char* opsmenu[] static
Initial value:
= {
    "[s]       Shell                     ",
    "[p]       Other program             ",
    "[mount]   Mount a filesystem        ",
    "[unmount] Unmount a filesystem      ",
    "[bootfs]  Set \"boot\" filesystem     ",
    "[pf]      Print a file              ",
    "[cd]      Change directory          ",
    "[pwd]     Print current directory   ",
    "[sync]    Sync filesystems          ",
    "[debug]   Drop to debugger          ",
    "[panic]   Intentional panic         ",
    "[deadlock] Intentional deadlock     ",
    "[q]       Quit and shut down        ",
    NULL
}
Definition at line 526 of file menu.c.
Referenced by cmd_opsmenu().
testmenu
const char* testmenu[] static
Initial value:
= {
    "[at]  Array test                    ",
    "[at2] Large array test              ",
    "[bt]  Bitmap test                   ",
    "[tlt] Threadlist test               ",
    "[km1] Kernel malloc test            ",
    "[km2] kmalloc stress test           ",
    "[km3] Large kmalloc test            ",
    "[km4] Multipage kmalloc test        ",
    "[tt1] Thread test 1                 ",
    "[tt2] Thread test 2                 ",
    "[tt3] Thread test 3                 ",
    "[sy1] Semaphore test                ",
    "[sy2] Lock test             (1)     ",
    "[sy3] CV test               (1)     ",
    "[sy4] CV test #2            (1)     ",
    "[semu1-22] Semaphore unit tests     ",
    "[fs1] Filesystem test               ",
    "[fs2] FS read stress                ",
    "[fs3] FS write stress               ",
    "[fs4] FS write stress 2             ",
    "[fs5] FS long stress                ",
    "[fs6] FS create stress              ",
    NULL
}
Definition at line 554 of file menu.c.
Referenced by cmd_testmenu().