os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/test.h File Reference
test.h File Reference
Macros
#define TESTFILE "badcallfile"
#define TESTDIR "badcalldir"
#define TESTLINK "badcalllink"
#define PF(a, b)
Functions
int open_testfile (const char *str)
int reopen_testfile (int openflags)
int create_testfile (void)
int create_testdir (void)
int create_testlink (void)
PF (1, 2) void report_begin(const char *descfmt
void report_hassubs (void)
void report_result (int rv, int error)
void report_saw_enosys (void)
void report_passed (void)
void report_failure (void)
void report_skipped (void)
void report_aborted (void)
void report_survival (int rv, int error)
void report_check (int rv, int error, int right_error)
void report_check2 (int rv, int error, int okerr1, int okerr2)
void report_check3 (int rv, int error, int okerr1, int okerr2, int okerr3)
void test_read_buf (void)
void test_write_buf (void)
void test_getdirentry_buf (void)
void test_getcwd_buf (void)
void test_readlink_buf (void)
void test_read_fd (void)
void test_write_fd (void)
void test_close_fd (void)
void test_ioctl_fd (void)
void test_lseek_fd (void)
void test_fsync_fd (void)
void test_ftruncate_fd (void)
void test_fstat_fd (void)
void test_getdirentry_fd (void)
void test_dup2_fd (void)
void test_open_path (void)
void test_remove_path (void)
void test_rename_paths (void)
void test_link_paths (void)
void test_mkdir_path (void)
void test_rmdir_path (void)
void test_chdir_path (void)
void test_symlink_paths (void)
void test_readlink_path (void)
void test_stat_path (void)
void test_lstat_path (void)
void test_execv (void)
void test_waitpid (void)
void test_open (void)
void test_read (void)
void test_write (void)
void test_close (void)
void test_reboot (void)
void test_sbrk (void)
void test_ioctl (void)
void test_lseek (void)
void test_fsync (void)
void test_ftruncate (void)
void test_fstat (void)
void test_remove (void)
void test_rename (void)
void test_link (void)
void test_mkdir (void)
void test_rmdir (void)
void test_chdir (void)
void test_getdirentry (void)
void test_symlink (void)
void test_readlink (void)
void test_dup2 (void)
void test_pipe (void)
void test_time (void)
void test_getcwd (void)
void test_stat (void)
void test_lstat (void)
Macro Definition Documentation
PF
#define PF (a, b)
Definition at line 37 of file test.h.
TESTDIR
#define TESTDIR "badcalldir"
Definition at line 31 of file test.h.
TESTFILE
#define TESTFILE "badcallfile"
Definition at line 30 of file test.h.
TESTLINK
#define TESTLINK "badcalllink"
Definition at line 32 of file test.h.
Function Documentation
create_testdir()
int create_testdir (void)
Definition at line 121 of file driver.c.
References ENOSYS, errno, mkdir(), report_aborted(), report_saw_enosys(), report_skipped(), report_warn(), report_warnx(), and TESTDIR.
Referenced by link_empty2(), remove_dir(), and rename_empty2().
create_testfile()
int create_testfile (void)
Definition at line 84 of file driver.c.
References close(), fd, NULL, open_testfile(), report_warn(), and TESTFILE.
Referenced by common_badpath(), and rmdir_file().
create_testlink()
int create_testlink (void)
Definition at line 141 of file driver.c.
References report_warn(), symlink(), and TESTLINK.
Referenced by readlink_setup().
open_testfile()
int open_testfile (const char * str)
Definition at line 46 of file driver.c.
References close(), fd, lseek(), O_CREAT, O_RDWR, O_TRUNC, open(), remove(), report_warn(), SEEK_SET, strlen(), TESTFILE, and write().
Referenced by create_testfile(), ftruncate_size_neg(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), read_setup(), readlink_file(), wait_siblings(), and write_setup().
PF()
PF (1 , 2) const
reopen_testfile()
int reopen_testfile (int openflags)
Definition at line 103 of file driver.c.
References fd, open(), report_warn(), and TESTFILE.
Referenced by runtest().
report_aborted()
void report_aborted (void)
Definition at line 272 of file report.c.
References report_end().
Referenced by common_badpath(), create_testdir(), dup2_self(), exec_common_fork(), ftruncate_fd_device(), ftruncate_size_neg(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), readlink_file(), rmdir_file(), wait_badflags(), wait_badstatus(), wait_nullstatus(), wait_parent(), wait_siblings(), and wait_unaligned().
report_check()
void report_check (int rv, int error, int right_error)
Definition at line 326 of file report.c.
References report_checkN().
Referenced by any_badfd(), common_badbuf(), common_badpath(), dup2_fd2(), enforce_sbrk(), exec_badargs(), exec_badprog(), exec_onearg(), ftruncate_fd_device(), ftruncate_size_neg(), ioctl_badcode(), link_dir(), link_empty1(), link_empty2(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_whence_inval(), mkdir_dot(), mkdir_dotdot(), mkdir_empty(), one_ioctl_badbuf(), open_badflags(), open_empty(), pipe_badptr(), readlink_dir(), readlink_file(), reboot_badflags(), remove_dir(), rename_dot(), rename_dotdot(), rmdir_dot(), rmdir_empty(), rmdir_file(), symlink_empty2(), time_badnsecs(), time_badsecs(), wait_badflags(), wait_badstatus(), and wait_nullstatus().
report_check2()
void report_check2 (int rv, int error, int okerr1, int okerr2)
Definition at line 332 of file report.c.
References ok(), and report_checkN().
Referenced by any_empty(), chdir_empty(), exec_emptyprog(), readlink_empty(), remove_dot(), remove_dotdot(), remove_empty(), rename_empty1(), rename_empty2(), rmdir_dotdot(), sbrk_unalignedneg(), sbrk_unalignedpos(), symlink_empty1(), and wait_badpid().
report_check3()
void report_check3 (int rv, int error, int okerr1, int okerr2, int okerr3)
Definition at line 342 of file report.c.
References ok(), and report_checkN().
report_failure()
void report_failure (void)
Definition at line 260 of file report.c.
References report_end().
Referenced by dup2_self(), exec_common_fork(), lseek_loc_pasteof(), and report_checkN().
report_hassubs()
void report_hassubs (void)
Definition at line 143 of file report.c.
References flush(), horizpos, say(), and subpos.
Referenced by wait_parent(), and wait_siblings().
report_passed()
void report_passed (void)
Definition at line 254 of file report.c.
References report_end().
Referenced by dup2_self(), lseek_loc_pasteof(), report_checkN(), report_survival(), and wait_siblings().
report_result()
void report_result (int rv, int error)
Definition at line 211 of file report.c.
References say(), and strerror().
Referenced by dup2_self(), exec_common_fork(), report_checkN(), and report_survival().
report_saw_enosys()
void report_saw_enosys (void)
Definition at line 231 of file report.c.
References horizpos, indent_to(), and pos.
Referenced by create_testdir(), dup2_self(), report_checkN(), and wait_badpid().
report_skipped()
void report_skipped (void)
Definition at line 266 of file report.c.
References report_end().
Referenced by create_testdir(), dup2_self(), lseek_file_stdin(), and report_checkN().
report_survival()
void report_survival (int rv, int error)
Definition at line 286 of file report.c.
References report_passed(), and report_result().
Referenced by pipe_unaligned(), wait_parent(), wait_self(), wait_siblings_child(), and wait_unaligned().
test_chdir()
void test_chdir (void)
Definition at line 56 of file bad_chdir.c.
References chdir_empty(), and test_chdir_path().
test_chdir_path()
void test_chdir_path (void)
Referenced by test_chdir().
test_close()
void test_close (void)
Definition at line 37 of file bad_close.c.
References test_close_fd().
test_close_fd()
void test_close_fd (void)
Referenced by test_close().
test_dup2()
void test_dup2 (void)
Definition at line 126 of file bad_dup2.c.
References dup2_fd2(), dup2_self(), IMPOSSIBLE_FD, OPEN_MAX, test_dup2_fd(), and warnx().
test_dup2_fd()
void test_dup2_fd (void)
Referenced by test_dup2().
test_execv()
void test_execv (void)
Definition at line 167 of file bad_execv.c.
References exec_badargs(), exec_badprog(), exec_emptyprog(), exec_onearg(), and NULL.
test_fstat()
void test_fstat (void)
Definition at line 107 of file bad_stat.c.
References any_badbuf(), badbuf_fstat(), and test_fstat_fd().
test_fstat_fd()
void test_fstat_fd (void)
Referenced by test_fstat().
test_fsync()
void test_fsync (void)
Definition at line 37 of file bad_fsync.c.
References test_fsync_fd().
test_fsync_fd()
void test_fsync_fd (void)
Referenced by test_fsync().
test_ftruncate()
void test_ftruncate (void)
Definition at line 89 of file bad_ftruncate.c.
References ftruncate_fd_device(), ftruncate_size_neg(), and test_ftruncate_fd().
test_ftruncate_fd()
void test_ftruncate_fd (void)
Referenced by test_ftruncate().
test_getcwd()
void test_getcwd (void)
Definition at line 37 of file bad_getcwd.c.
References test_getcwd_buf().
test_getcwd_buf()
void test_getcwd_buf (void)
Referenced by test_getcwd().
test_getdirentry()
void test_getdirentry (void)
Definition at line 37 of file bad_getdirentry.c.
References test_getdirentry_buf(), and test_getdirentry_fd().
test_getdirentry_buf()
void test_getdirentry_buf (void)
Referenced by test_getdirentry().
test_getdirentry_fd()
void test_getdirentry_fd (void)
Referenced by test_getdirentry().
test_ioctl()
void test_ioctl (void)
Definition at line 96 of file bad_ioctl.c.
References ioctl_badbuf(), ioctl_badcode(), and test_ioctl_fd().
test_ioctl_fd()
void test_ioctl_fd (void)
Referenced by test_ioctl().
test_link()
void test_link (void)
Definition at line 82 of file bad_link.c.
References link_dir(), link_empty1(), link_empty2(), and test_link_paths().
test_link_paths()
void test_link_paths (void)
Referenced by test_link().
test_lseek()
void test_lseek (void)
Definition at line 269 of file bad_lseek.c.
References lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), and test_lseek_fd().
test_lseek_fd()
void test_lseek_fd (void)
Referenced by test_lseek().
test_lstat()
void test_lstat (void)
Definition at line 114 of file bad_stat.c.
References any_badbuf(), any_empty(), badbuf_lstat(), lstat(), and test_lstat_path().
test_lstat_path()
void test_lstat_path (void)
Referenced by test_lstat().
test_mkdir()
void test_mkdir (void)
Definition at line 80 of file bad_mkdir.c.
References mkdir_dot(), mkdir_dotdot(), mkdir_empty(), and test_mkdir_path().
test_mkdir_path()
void test_mkdir_path (void)
Referenced by test_mkdir().
test_open()
void test_open (void)
Definition at line 72 of file bad_open.c.
References open_badflags(), open_empty(), and test_open_path().
test_open_path()
void test_open_path (void)
Referenced by test_open().
test_pipe()
void test_pipe (void)
Definition at line 79 of file bad_pipe.c.
References NULL, pipe_badptr(), and pipe_unaligned().
test_read()
void test_read (void)
Definition at line 37 of file bad_read.c.
References test_read_buf(), and test_read_fd().
test_read_buf()
void test_read_buf (void)
Referenced by test_read().
test_read_fd()
void test_read_fd (void)
Referenced by test_read().
test_readlink()
void test_readlink (void)
Definition at line 83 of file bad_readlink.c.
References readlink_dir(), readlink_empty(), readlink_file(), test_readlink_buf(), and test_readlink_path().
test_readlink_buf()
void test_readlink_buf (void)
Referenced by test_readlink().
test_readlink_path()
void test_readlink_path (void)
Referenced by test_readlink().
test_reboot()
void test_reboot (void)
Definition at line 59 of file bad_reboot.c.
References reboot_badflags().
test_remove()
void test_remove (void)
Definition at line 98 of file bad_remove.c.
References remove_dir(), remove_dot(), remove_dotdot(), remove_empty(), and test_remove_path().
test_remove_path()
void test_remove_path (void)
Referenced by test_remove().
test_rename()
void test_rename (void)
Definition at line 102 of file bad_rename.c.
References rename_dot(), rename_dotdot(), rename_empty1(), rename_empty2(), and test_rename_paths().
test_rename_paths()
void test_rename_paths (void)
Referenced by test_rename().
test_rmdir()
void test_rmdir (void)
Definition at line 96 of file bad_rmdir.c.
References rmdir_dot(), rmdir_dotdot(), rmdir_empty(), rmdir_file(), and test_rmdir_path().
test_rmdir_path()
void test_rmdir_path (void)
Referenced by test_rmdir().
test_sbrk()
void test_sbrk (void)
Definition at line 117 of file bad_sbrk.c.
References sbrk_bigneg(), sbrk_bigpos(), sbrk_neg(), sbrk_unalignedneg(), and sbrk_unalignedpos().
test_stat()
void test_stat (void)
Definition at line 122 of file bad_stat.c.
References any_badbuf(), any_empty(), badbuf_stat(), and test_stat_path().
test_stat_path()
void test_stat_path (void)
Referenced by test_stat().
test_symlink()
void test_symlink (void)
Definition at line 63 of file bad_symlink.c.
References symlink_empty1(), symlink_empty2(), and test_symlink_paths().
test_symlink_paths()
void test_symlink_paths (void)
Referenced by test_symlink().
test_time()
void test_time (void)
Definition at line 69 of file bad_time.c.
References time_badnsecs(), and time_badsecs().
test_waitpid()
void test_waitpid (void)
Definition at line 405 of file bad_waitpid.c.
References NONEXIST_PID, wait_badflags(), wait_badpid(), wait_badstatus(), wait_nullstatus(), wait_parent(), wait_self(), wait_siblings(), and wait_unaligned().
test_write()
void test_write (void)
Definition at line 37 of file bad_write.c.
References test_write_buf(), and test_write_fd().
test_write_buf()
void test_write_buf (void)
Referenced by test_write().
test_write_fd()
void test_write_fd (void)
Referenced by test_write().