os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/lib/libc/stdlib/random.c File Reference
random.c File Reference
#include <assert.h>
#include <errno.h>
#include <stdlib.h>
Macros
#define LOCKME()
#define UNLOCKME()
#define TYPE_0 0 /* linear congruential */
#define BREAK_0 8
#define DEG_0 0
#define SEP_0 0
#define TYPE_1 1 /* x**7 + x**3 + 1 */
#define BREAK_1 32
#define DEG_1 7
#define SEP_1 3
#define TYPE_2 2 /* x**15 + x + 1 */
#define BREAK_2 64
#define DEG_2 15
#define SEP_2 1
#define TYPE_3 3 /* x**31 + x**3 + 1 */
#define BREAK_3 128
#define DEG_3 31
#define SEP_3 3
#define TYPE_4 4 /* x**63 + x + 1 */
#define BREAK_4 256
#define DEG_4 63
#define SEP_4 1
#define MAX_TYPES 5 /* max number of types above */
Functions
static void srandom_unlocked (unsigned long)
static long random_unlocked (void)
void srandom (unsigned long x)
char * initstate (unsigned long seed, char *arg_state, size_t n)
char * setstate (char *arg_state)
long random (void)
Variables
static const int degrees [MAX_TYPES] = { DEG_0, DEG_1, DEG_2, DEG_3, DEG_4 }
static const int seps [MAX_TYPES] = { SEP_0, SEP_1, SEP_2, SEP_3, SEP_4 }
static long randtbl [DEG_3+1]
static long * fptr = &randtbl[SEP_3 + 1]
static long * rptr = &randtbl[1]
static long * state = &randtbl[1]
static long rand_type = TYPE_3
static int rand_deg = DEG_3
static int rand_sep = SEP_3
static long * end_ptr = &randtbl[DEG_3 + 1]
Macro Definition Documentation
BREAK_0
#define BREAK_0 8
Definition at line 123 of file random.c.
BREAK_1
#define BREAK_1 32
Definition at line 128 of file random.c.
BREAK_2
#define BREAK_2 64
Definition at line 133 of file random.c.
BREAK_3
#define BREAK_3 128
Definition at line 138 of file random.c.
BREAK_4
#define BREAK_4 256
Definition at line 143 of file random.c.
DEG_0
#define DEG_0 0
Definition at line 124 of file random.c.
DEG_1
#define DEG_1 7
Definition at line 129 of file random.c.
DEG_2
#define DEG_2 15
Definition at line 134 of file random.c.
DEG_3
#define DEG_3 31
Definition at line 139 of file random.c.
DEG_4
#define DEG_4 63
Definition at line 144 of file random.c.
LOCKME
#define LOCKME ()
Definition at line 49 of file random.c.
MAX_TYPES
#define MAX_TYPES 5 /* max number of types above */
Definition at line 151 of file random.c.
SEP_0
#define SEP_0 0
Definition at line 125 of file random.c.
SEP_1
#define SEP_1 3
Definition at line 130 of file random.c.
SEP_2
#define SEP_2 1
Definition at line 135 of file random.c.
SEP_3
#define SEP_3 3
Definition at line 140 of file random.c.
SEP_4
#define SEP_4 1
Definition at line 145 of file random.c.
TYPE_0
#define TYPE_0 0 /* linear congruential */
Definition at line 122 of file random.c.
TYPE_1
#define TYPE_1 1 /* x**7 + x**3 + 1 */
Definition at line 127 of file random.c.
TYPE_2
#define TYPE_2 2 /* x**15 + x + 1 */
Definition at line 132 of file random.c.
TYPE_3
#define TYPE_3 3 /* x**31 + x**3 + 1 */
Definition at line 137 of file random.c.
TYPE_4
#define TYPE_4 4 /* x**63 + x + 1 */
Definition at line 142 of file random.c.
UNLOCKME
#define UNLOCKME ()
Definition at line 50 of file random.c.
Function Documentation
initstate()
char* initstate (unsigned long seed, char * arg_state, size_t n)
Definition at line 282 of file random.c.
References assert, BREAK_0, BREAK_1, BREAK_2, BREAK_3, BREAK_4, DEG_0, DEG_1, DEG_2, DEG_3, DEG_4, end_ptr, LOCKME, MAX_TYPES, NULL, rand_deg, rand_sep, rand_type, rptr, SEP_0, SEP_1, SEP_2, SEP_3, SEP_4, srandom_unlocked(), state, TYPE_0, TYPE_1, TYPE_2, TYPE_3, TYPE_4, and UNLOCKME.
random()
long random (void)
Definition at line 445 of file random.c.
References LOCKME, NULL, panic(), random_unlocked(), random_softc::rs_devdata, random_softc::rs_random, the_random, and UNLOCKME.
Referenced by bitmaptest(), choose_name(), compute_thread(), file_randomwrite(), fill(), genkeys(), genkeys_sub(), grind(), init(), initarray(), mkrandtree_sub(), pickpage(), randchar(), randop(), randsize(), randtruncate(), randwrite(), readallrandomly(), rmrandtree_sub(), sleepalot_thread(), stresstest(), test567(), testa(), waker_thread(), wl_diropseq(), wl_genseq(), wl_linkunlinkseq(), wl_mkrandtree(), wl_mkrmseq(), wl_renameseq(), wl_rmrandtree(), wl_writefileseq(), and wl_writetruncseq().
random_unlocked()
static long random_unlocked (void) static
Definition at line 415 of file random.c.
References end_ptr, f, fptr, L, rand_type, rptr, state, and TYPE_0.
Referenced by random(), and srandom_unlocked().
setstate()
char* setstate (char * arg_state)
Definition at line 354 of file random.c.
References assert, degrees, end_ptr, fptr, LOCKME, MAX_TYPES, NULL, rand_deg, rand_sep, rand_type, rptr, seps, state, TYPE_0, TYPE_1, TYPE_2, TYPE_3, TYPE_4, and UNLOCKME.
srandom()
void srandom (unsigned long x)
Definition at line 250 of file random.c.
References LOCKME, srandom_unlocked(), and UNLOCKME.
Referenced by genkeys(), genkeys_sub(), grind(), init(), initarray(), main(), prepwords(), readallrandomly(), stresstest(), test567(), wl_diropseq(), wl_fillhole(), wl_genseq(), wl_linkunlinkseq(), wl_mkrandtree(), wl_mkrmseq(), wl_randupdate(), wl_renameseq(), wl_rmrandtree(), wl_truncfill(), wl_writefileseq(), and wl_writetruncseq().
srandom_unlocked()
static void srandom_unlocked (unsigned long x) static
Definition at line 232 of file random.c.
References fptr, L, rand_deg, rand_sep, rand_type, random_unlocked(), rptr, state, and TYPE_0.
Referenced by initstate(), and srandom().
Variable Documentation
degrees
const int degrees[MAX_TYPES] = { DEG_0, DEG_1, DEG_2, DEG_3, DEG_4 } static
Definition at line 153 of file random.c.
Referenced by setstate().
end_ptr
long* end_ptr = &randtbl[DEG_3 + 1] static
Definition at line 216 of file random.c.
Referenced by initstate(), random_unlocked(), and setstate().
fptr
long* fptr = &randtbl[SEP_3 + 1] static
Definition at line 199 of file random.c.
Referenced by random_unlocked(), setstate(), and srandom_unlocked().
rand_deg
int rand_deg = DEG_3 static
Definition at line 214 of file random.c.
Referenced by initstate(), setstate(), and srandom_unlocked().
rand_sep
int rand_sep = SEP_3 static
Definition at line 215 of file random.c.
Referenced by initstate(), setstate(), and srandom_unlocked().
rand_type
long rand_type = TYPE_3 static
Definition at line 213 of file random.c.
Referenced by initstate(), random_unlocked(), setstate(), and srandom_unlocked().
randtbl
long randtbl[DEG_3+1] static
Initial value:
= {
    TYPE_3,
    (long)0x9a319039L, (long)0x32d9c024L, (long)0x9b663182L,
    (long)0x5da1f342L, (long)0xde3b81e0L, (long)0xdf0a6fb5L,
    (long)0xf103bc02L, (long)0x48f340fbL, (long)0x7449e56bL,
    (long)0xbeb1dbb0L, (long)0xab5c5918L, (long)0x946554fdL,
    (long)0x8c2e680fL, (long)0xeb3d799fL, (long)0xb11ee0b7L,
    (long)0x2d436b86L, (long)0xda672e2aL, (long)0x1588ca88L,
    (long)0xe369735dL, (long)0x904f35f7L, (long)0xd7158fd6L,
    (long)0x6fa6f051L, (long)0x616e6b96L, (long)0xac94efdcL,
    (long)0x36413f93L, (long)0xc622c298L, (long)0xf5a42ab8L,
    (long)0x8a88d77bL, (long)0xf5ad9d0eL, (long)0x8999220bL,
    (long)0x27fb47b9L,
}
Definition at line 170 of file random.c.
rptr
long* rptr = &randtbl[1] static
Definition at line 200 of file random.c.
Referenced by initstate(), random_unlocked(), setstate(), and srandom_unlocked().
seps
const int seps[MAX_TYPES] = { SEP_0, SEP_1, SEP_2, SEP_3, SEP_4 } static
Definition at line 154 of file random.c.
Referenced by setstate(), strtok(), and strtok_r().
state
long* state = &randtbl[1] static
Definition at line 212 of file random.c.
Referenced by initstate(), random_unlocked(), setstate(), and srandom_unlocked().