os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/test/tt3.c File Reference
tt3.c File Reference
#include <types.h>
#include <lib.h>
#include <wchan.h>
#include <thread.h>
#include <synch.h>
#include <test.h>
Macros
#define DIM 70
#define SLEEPALOT_PRINTS 20 /* number of printouts */
#define SLEEPALOT_ITERS 4 /* iterations per printout */
#define WAKER_WAKES 100
#define COMPUTE_ITERS 10
#define NWAITCHANS 12
Functions
static void setup (void)
static void sleepalot_thread (void *junk, unsigned long num)
static void waker_thread (void *junk1, unsigned long junk2)
static void make_sleepalots (int howmany)
static void compute_thread (void *junk1, unsigned long num)
static void make_computes (int howmany)
static void finish (int howmanytotal)
static void runtest3 (int nsleeps, int ncomputes)
int threadtest3 (int nargs, char **args)
Variables
static struct spinlock spinlocks [NWAITCHANS]
static struct wchan * waitchans [NWAITCHANS]
static volatile int wakerdone
static struct semaphore * wakersem
static struct semaphore * donesem
Macro Definition Documentation
COMPUTE_ITERS
#define COMPUTE_ITERS 10
Definition at line 50 of file tt3.c.
DIM
#define DIM 70
Definition at line 42 of file tt3.c.
NWAITCHANS
#define NWAITCHANS 12
Definition at line 53 of file tt3.c.
SLEEPALOT_ITERS
#define SLEEPALOT_ITERS 4 /* iterations per printout */
Definition at line 46 of file tt3.c.
SLEEPALOT_PRINTS
#define SLEEPALOT_PRINTS 20 /* number of printouts */
Definition at line 45 of file tt3.c.
WAKER_WAKES
#define WAKER_WAKES 100
Definition at line 48 of file tt3.c.
Function Documentation
compute_thread()
static void compute_thread (void * junk1, unsigned long num) static
Definition at line 163 of file tt3.c.
References COMPUTE_ITERS, DIM, donesem, KASSERT, kfree(), kmalloc(), kprintf(), m1, m2, m3, NULL, num, random(), thread_yield(), and V().
Referenced by make_computes().
finish()
static void finish (int howmanytotal) static
Definition at line 236 of file tt3.c.
References donesem, P(), V(), wakerdone, and wakersem.
Referenced by runtest3().
make_computes()
static void make_computes (int howmany) static
Definition at line 220 of file tt3.c.
References compute_thread(), name, NULL, panic(), snprintf(), strerror(), and thread_fork().
Referenced by runtest3().
make_sleepalots()
static void make_sleepalots (int howmany) static
Definition at line 143 of file tt3.c.
References name, NULL, panic(), sleepalot_thread(), snprintf(), strerror(), thread_fork(), and waker_thread().
Referenced by runtest3().
runtest3()
static void runtest3 (int nsleeps, int ncomputes) static
Definition at line 250 of file tt3.c.
References finish(), kprintf(), make_computes(), make_sleepalots(), and setup().
Referenced by threadtest3().
setup()
static void setup (void) static
Definition at line 63 of file tt3.c.
References donesem, kstrdup(), NULL, NWAITCHANS, sem_create(), snprintf(), spinlock_init(), spinlocks, waitchans, wakerdone, wakersem, and wchan_create().
Referenced by runtest3().
sleepalot_thread()
static void sleepalot_thread (void * junk, unsigned long num) static
Definition at line 82 of file tt3.c.
References donesem, kprintf(), num, NWAITCHANS, random(), SLEEPALOT_ITERS, SLEEPALOT_PRINTS, spinlock_acquire(), spinlock_release(), spinlocks, V(), waitchans, and wchan_sleep().
Referenced by make_sleepalots().
threadtest3()
int threadtest3 (int nargs, char ** args)
Definition at line 263 of file tt3.c.
References atoi(), kprintf(), and runtest3().
waker_thread()
static void waker_thread (void * junk1, unsigned long junk2) static
Definition at line 108 of file tt3.c.
References donesem, NWAITCHANS, P(), random(), spinlock_acquire(), spinlock_release(), spinlocks, thread_yield(), V(), waitchans, WAKER_WAKES, wakerdone, wakersem, and wchan_wakeall().
Referenced by make_sleepalots().
Variable Documentation
donesem
struct semaphore* donesem static
Definition at line 59 of file tt3.c.
Referenced by compute_thread(), finish(), setup(), sleepalot_thread(), and waker_thread().
spinlocks
struct spinlock spinlocks[NWAITCHANS] static
Definition at line 54 of file tt3.c.
Referenced by setup(), sleepalot_thread(), and waker_thread().
waitchans
struct wchan* waitchans[NWAITCHANS] static
Definition at line 55 of file tt3.c.
Referenced by setup(), sleepalot_thread(), and waker_thread().
wakerdone
volatile int wakerdone static
Definition at line 57 of file tt3.c.
Referenced by finish(), setup(), and waker_thread().
wakersem
struct semaphore* wakersem static
Definition at line 58 of file tt3.c.
Referenced by finish(), setup(), and waker_thread().