os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_rmdir.c File Reference
bad_rmdir.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void rmdir_file (void)
static void rmdir_dot (void)
static void rmdir_dotdot (void)
static void rmdir_empty (void)
void test_rmdir (void)
Function Documentation
rmdir_dot()
static void rmdir_dot (void) static
Definition at line 64 of file bad_rmdir.c.
References EINVAL, errno, report_begin(), report_check(), and rmdir().
Referenced by test_rmdir().
rmdir_dotdot()
static void rmdir_dotdot (void) static
Definition at line 75 of file bad_rmdir.c.
References EINVAL, ENOTEMPTY, errno, report_begin(), report_check2(), and rmdir().
Referenced by test_rmdir().
rmdir_empty()
static void rmdir_empty (void) static
Definition at line 86 of file bad_rmdir.c.
References EINVAL, errno, report_begin(), report_check(), and rmdir().
Referenced by test_rmdir().
rmdir_file()
static void rmdir_file (void) static
Definition at line 48 of file bad_rmdir.c.
References create_testfile(), ENOTDIR, errno, remove(), report_aborted(), report_begin(), report_check(), rmdir(), and TESTFILE.
Referenced by test_rmdir().
test_rmdir()
void test_rmdir (void)
Definition at line 96 of file bad_rmdir.c.
References rmdir_dot(), rmdir_dotdot(), rmdir_empty(), rmdir_file(), and test_rmdir_path().