os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/frack/do.c File Reference
do.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
#include "data.h"
#include "name.h"
#include "do.h"
Functions
int do_opendir (unsigned name)
void do_closedir (int fd, unsigned name)
int do_createfile (unsigned name)
int do_openfile (unsigned name, int dotrunc)
void do_closefile (int fd, unsigned name)
void do_write (int fd, unsigned name, unsigned code, unsigned seq, off_t pos, off_t len)
void do_truncate (int fd, unsigned name, off_t len)
void do_mkdir (unsigned name)
void do_rmdir (unsigned name)
void do_unlink (unsigned name)
void do_link (unsigned from, unsigned to)
void do_rename (unsigned from, unsigned to)
void do_renamexd (unsigned fromdir, unsigned from, unsigned todir, unsigned to)
void do_chdir (unsigned name)
void do_chdirup (void)
void do_sync (void)
Function Documentation
do_chdir()
void do_chdir (unsigned name)
Definition at line 223 of file do.c.
References chdir(), err(), name, name_get(), and printf().
Referenced by op_chdir().
do_chdirup()
void do_chdirup (void)
Definition at line 235 of file do.c.
References chdir(), err(), and printf().
Referenced by op_chdirup().
do_closedir()
void do_closedir (int fd, unsigned name)
Definition at line 57 of file do.c.
References close(), fd, name, name_get(), and warn().
Referenced by op_closedir().
do_closefile()
void do_closefile (int fd, unsigned name)
Definition at line 94 of file do.c.
References close(), fd, name, name_get(), and warn().
Referenced by op_close().
do_createfile()
int do_createfile (unsigned name)
Definition at line 65 of file do.c.
References err(), fd, name, name_get(), O_CREAT, O_EXCL, O_WRONLY, open(), and printf().
Referenced by op_open().
do_link()
void do_link (unsigned from, unsigned to)
Definition at line 177 of file do.c.
References err(), link(), name_get(), and printf().
Referenced by op_link().
do_mkdir()
void do_mkdir (unsigned name)
Definition at line 141 of file do.c.
References err(), mkdir(), name, name_get(), and printf().
Referenced by op_mkdir().
do_opendir()
int do_opendir (unsigned name)
Definition at line 43 of file do.c.
References err(), fd, name, name_get(), O_RDONLY, and open().
Referenced by op_opendir().
do_openfile()
int do_openfile (unsigned name, int dotrunc)
Definition at line 80 of file do.c.
References err(), fd, name, name_get(), O_TRUNC, O_WRONLY, and open().
Referenced by op_open().
do_rename()
void do_rename (unsigned from, unsigned to)
Definition at line 190 of file do.c.
References err(), name_get(), printf(), and rename().
Referenced by op_rename().
do_renamexd()
void do_renamexd (unsigned fromdir, unsigned from, unsigned todir, unsigned to)
Definition at line 203 of file do.c.
References err(), fschange::fromdir, name_get(), printf(), rename(), strcat(), strcpy(), and fschange::todir.
Referenced by op_renamexd().
do_rmdir()
void do_rmdir (unsigned name)
Definition at line 153 of file do.c.
References err(), name, name_get(), printf(), and rmdir().
Referenced by op_rmdir().
do_sync()
void do_sync (void)
Definition at line 244 of file do.c.
References printf(), sync(), and warn().
Referenced by op_sync().
do_truncate()
void do_truncate (int fd, unsigned name, off_t len)
Definition at line 129 of file do.c.
References err(), fd, ftruncate(), fschange::len, name, name_get(), and printf().
Referenced by op_truncate().
do_unlink()
void do_unlink (unsigned name)
Definition at line 165 of file do.c.
References err(), name, name_get(), printf(), and remove().
Referenced by op_unlink().
do_write()
void do_write (int fd, unsigned name, unsigned code, unsigned seq, off_t pos, off_t len)
Definition at line 102 of file do.c.
References buf, fschange::code, data_map(), err(), fd, fschange::len, lseek(), name, name_get(), pos, printf(), SEEK_SET, fschange::seq, and write().
Referenced by op_write().