os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/stdarg.h File Reference
stdarg.h File Reference
#include <cdefs.h>
Functions
void vkprintf (const char *fmt, va_list ap) __PF(1
void int vsnprintf (char *buf, size_t maxlen, const char *fmt, va_list ap) __PF(3
void int int __vprintf (void(*func)(void *clientdata, const char *str, size_t len), void *clientdata, const char *format, va_list ap) __PF(3
Function Documentation
__vprintf()
void int int __vprintf (void(*)(void *clientdata, const char *str, size_t len) func, void * clientdata, const char * format, va_list ap)
vkprintf()
void vkprintf (const char * fmt, va_list ap)
vsnprintf()
void int vsnprintf (char * buf, size_t maxlen, const char * fmt, va_list ap)
Definition at line 99 of file snprintf.c.
References __snprintf_send(), __vprintf(), SNP::buf, buf, SNP::buflen, and SNP::bufpos.
Referenced by die(), dumpvalf(), say(), usem_init(), vsay(), and vscomplain().