os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/lib/libc/string/strerror.c File Reference
strerror.c File Reference
#include <string.h>
#include <kern/errmsg.h>
Functions
const char * strerror (int errcode)
Function Documentation
strerror()
const char* strerror (int errcode)
Definition at line 37 of file strerror.c.
References NULL, panic(), sys_errlist, and sys_nerr.
Referenced by __printerr(), cleanup_rmdir(), cmd_deadlock(), cmd_progthread(), cmd_pwd(), common_prog(), cpu_create(), createstress_thread(), cvtest(), dev_create_vnode(), devnull_create(), docreatestress(), dofork(), dolongstress(), domkdir(), doreadstress(), dorename(), dormdir(), dowritestress(), dowritestress2(), fstest_read(), fstest_remove(), fstest_write(), kmallocstress(), kmalloctest4(), locktest(), make_computes(), make_sleepalots(), menu_execute(), printfile(), recursive_cleanup(), report_result(), report_warn(), run(), runthreads(), semfs_bootstrap(), semfs_getroot(), semtest(), setup(), sfs_rename(), tryattach_beep_to_ltimer(), tryattach_con_to_lser(), tryattach_emu_to_lamebus(), tryattach_lhd_to_lamebus(), tryattach_lrandom_to_lamebus(), tryattach_lser_to_lamebus(), tryattach_ltimer_to_lamebus(), tryattach_ltrace_to_lamebus(), tryattach_random_to_lrandom(), tryattach_rtclock_to_ltimer(), vfs_unmountall(), vnode_decref(), and vscomplain().