os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/arch/sys161/dev/lamebus_machdep.c File Reference
lamebus_machdep.c File Reference
#include <types.h>
#include <kern/unistd.h>
#include <lib.h>
#include <mips/specialreg.h>
#include <mips/trapframe.h>
#include <cpu.h>
#include <spl.h>
#include <clock.h>
#include <thread.h>
#include <current.h>
#include <membar.h>
#include <synch.h>
#include <mainbus.h>
#include <sys161/bus.h>
#include <lamebus/lamebus.h>
#include <lamebus/ltrace.h>
#include "autoconf.h"
Macros
#define CPU_FREQUENCY 25000000 /* 25 MHz */
#define LAMEBUS_IRQ_BIT 0x00000400 /* all system bus slots */
#define LAMEBUS_IPI_BIT 0x00000800 /* inter-processor interrupt */
#define MIPS_TIMER_BIT 0x00008000 /* on-chip timer */
Functions
static void mips_timer_set (uint32_t count)
void mainbus_bootstrap (void)
void mainbus_start_cpus (void)
void * lamebus_map_area (struct lamebus_softc *bus, int slot, uint32_t offset)
uint32_t lamebus_read_register (struct lamebus_softc *bus, int slot, uint32_t offset)
void lamebus_write_register (struct lamebus_softc *bus, int slot, uint32_t offset, uint32_t val)
void mainbus_poweroff (void)
void mainbus_reboot (void)
void mainbus_halt (void)
void mainbus_panic (void)
uint32_t mainbus_ramsize (void)
void mainbus_send_ipi (struct cpu *target)
void mainbus_debugger (void)
void mainbus_interrupt (struct trapframe *tf)
Variables
static struct lamebus_softc * lamebus
Macro Definition Documentation
CPU_FREQUENCY
#define CPU_FREQUENCY 25000000 /* 25 MHz */
Definition at line 54 of file lamebus_machdep.c.
LAMEBUS_IPI_BIT
#define LAMEBUS_IPI_BIT 0x00000800 /* inter-processor interrupt */
Definition at line 294 of file lamebus_machdep.c.
LAMEBUS_IRQ_BIT
#define LAMEBUS_IRQ_BIT 0x00000400 /* all system bus slots */
Definition at line 293 of file lamebus_machdep.c.
MIPS_TIMER_BIT
#define MIPS_TIMER_BIT 0x00008000 /* on-chip timer */
Definition at line 295 of file lamebus_machdep.c.
Function Documentation
lamebus_map_area()
void* lamebus_map_area (struct lamebus_softc * bus, int slot, uint32_t offset)
Definition at line 137 of file lamebus_machdep.c.
References KASSERT, LB_BASEADDR, LB_NSLOTS, and LB_SLOT_SIZE.
Referenced by lamebus_read_register(), lamebus_start_cpus(), and lamebus_write_register().
lamebus_read_register()
uint32_t lamebus_read_register (struct lamebus_softc * bus, int slot, uint32_t offset)
Definition at line 153 of file lamebus_machdep.c.
References lamebus_map_area(), and membar_load_load().
Referenced by read_cfg_register().
lamebus_write_register()
void lamebus_write_register (struct lamebus_softc * bus, int slot, uint32_t offset, uint32_t val)
Definition at line 172 of file lamebus_machdep.c.
References lamebus_map_area(), and membar_store_store().
Referenced by write_cfg_register(), and write_ctlcpu_register().
mainbus_bootstrap()
void mainbus_bootstrap (void)
Definition at line 87 of file lamebus_machdep.c.
References autoconf_lamebus(), CPU_FREQUENCY, HZ, KASSERT, kprintf(), lamebus, lamebus_find_cpus(), lamebus_init(), mips_timer_set(), and spl0().
Referenced by boot().
mainbus_debugger()
void mainbus_debugger (void)
Definition at line 283 of file lamebus_machdep.c.
References ltrace_stop().
Referenced by cmd_debug().
mainbus_halt()
void mainbus_halt (void)
Definition at line 226 of file lamebus_machdep.c.
References cpu_halt().
Referenced by sys_reboot().
mainbus_interrupt()
void mainbus_interrupt (struct trapframe * tf)
Definition at line 298 of file lamebus_machdep.c.
References CCA_IRQS, CPU_FREQUENCY, hardclock(), HZ, interprocessor_interrupt(), KASSERT, lamebus, lamebus_clear_ipi(), lamebus_interrupt(), LAMEBUS_IPI_BIT, LAMEBUS_IRQ_BIT, MIPS_TIMER_BIT, mips_timer_set(), panic(), and trapframe::tf_cause.
Referenced by mips_trap().
mainbus_panic()
void mainbus_panic (void)
Definition at line 239 of file lamebus_machdep.c.
References mainbus_poweroff().
Referenced by panic().
mainbus_poweroff()
void mainbus_poweroff (void)
Definition at line 192 of file lamebus_machdep.c.
References lamebus, and lamebus_poweroff().
Referenced by mainbus_panic(), mainbus_reboot(), and sys_reboot().
mainbus_ramsize()
uint32_t mainbus_ramsize (void)
Definition at line 249 of file lamebus_machdep.c.
References lamebus_ramsize().
Referenced by ram_bootstrap().
mainbus_reboot()
void mainbus_reboot (void)
Definition at line 207 of file lamebus_machdep.c.
References kprintf(), and mainbus_poweroff().
Referenced by sys_reboot().
mainbus_send_ipi()
void mainbus_send_ipi (struct cpu * target)
Definition at line 274 of file lamebus_machdep.c.
References lamebus, and lamebus_assert_ipi().
Referenced by ipi_send(), and ipi_tlbshootdown().
mainbus_start_cpus()
void mainbus_start_cpus (void)
Definition at line 126 of file lamebus_machdep.c.
References lamebus, and lamebus_start_cpus().
Referenced by thread_start_cpus().
mips_timer_set()
static void mips_timer_set (uint32_t count) static
Definition at line 65 of file lamebus_machdep.c.
References count.
Referenced by mainbus_bootstrap(), and mainbus_interrupt().
Variable Documentation
lamebus
struct lamebus_softc* lamebus static
Definition at line 84 of file lamebus_machdep.c.
Referenced by lamebus_assert_ipi(), lamebus_clear_ipi(), lamebus_find_cpus(), lamebus_init(), lamebus_interrupt(), lamebus_mask_interrupt(), lamebus_poweroff(), lamebus_start_cpus(), lamebus_unmask_interrupt(), mainbus_bootstrap(), mainbus_interrupt(), mainbus_poweroff(), mainbus_send_ipi(), and mainbus_start_cpus().