os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/fs/sfs/sfs_inode.c File Reference
sfs_inode.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <vfs.h>
#include <sfs.h>
#include "sfsprivate.h"
Functions
int sfs_sync_inode (struct sfs_vnode *sv)
int sfs_reclaim (struct vnode *v)
int sfs_loadvnode (struct sfs_fs *sfs, uint32_t ino, int forcetype, struct sfs_vnode **ret)
int sfs_makeobj (struct sfs_fs *sfs, int type, struct sfs_vnode **ret)
int sfs_getroot (struct fs *fs, struct vnode **ret)
Function Documentation
sfs_getroot()
int sfs_getroot (struct fs * fs, struct vnode ** ret)
Definition at line 293 of file sfs_inode.c.
References EINVAL, fs::fs_data, kprintf(), sfs_superblock::sb_volname, sfs_dinode::sfi_type, sfs_loadvnode(), SFS_ROOTDIR_INO, sfs_fs::sfs_sb, SFS_TYPE_DIR, SFS_TYPE_INVAL, sfs_vnode::sv_absvn, sfs_vnode::sv_i, vfs_biglock_acquire(), and vfs_biglock_release().
sfs_loadvnode()
int sfs_loadvnode (struct sfs_fs * sfs, uint32_t ino, int forcetype, struct sfs_vnode ** ret)
Definition at line 150 of file sfs_inode.c.
References ENOMEM, KASSERT, kfree(), kmalloc(), NULL, num, ops, panic(), sfs_superblock::sb_volname, sfs_dinode::sfi_type, sfs_fs::sfs_absfs, sfs_bused(), sfs_dirops, sfs_fileops, sfs_readblock(), sfs_fs::sfs_sb, SFS_TYPE_DIR, SFS_TYPE_FILE, SFS_TYPE_INVAL, sfs_fs::sfs_vnodes, sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, vnode::vn_data, vnode_cleanup(), vnode_init(), and VOP_INCREF.
Referenced by sfs_creat(), sfs_getroot(), sfs_lookonce(), and sfs_makeobj().
sfs_makeobj()
int sfs_makeobj (struct sfs_fs * sfs, int type, struct sfs_vnode ** ret)
Definition at line 262 of file sfs_inode.c.
References sfs_balloc(), sfs_bfree(), and sfs_loadvnode().
Referenced by sfs_creat().
sfs_reclaim()
int sfs_reclaim (struct vnode * v)
Definition at line 69 of file sfs_inode.c.
References EBUSY, fs::fs_data, KASSERT, kfree(), num, panic(), sfs_superblock::sb_volname, sfs_dinode::sfi_linkcount, sfs_bfree(), sfs_itrunc(), sfs_fs::sfs_sb, sfs_sync_inode(), sfs_fs::sfs_vnodes, spinlock_acquire(), spinlock_release(), sfs_vnode::sv_absvn, sfs_vnode::sv_i, sfs_vnode::sv_ino, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_countlock, vnode::vn_data, vnode::vn_fs, vnode::vn_refcount, and vnode_cleanup().
sfs_sync_inode()
int sfs_sync_inode (struct sfs_vnode * sv)
Definition at line 47 of file sfs_inode.c.
References fs::fs_data, sfs_writeblock(), sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, and vnode::vn_fs.
Referenced by sfs_fsync(), and sfs_reclaim().