os161-doc: /home/os161user/os161/os161-base-2.0.3/build/install/include/stdio.h File Reference
stdio.h File Reference
#include <kern/types.h>
#include <types/size_t.h>
#include <sys/null.h>
Macros
#define EOF (-1)
Functions
int __vprintf (void(*sendfunc)(void *clientdata, const char *, size_t len), void *clientdata, const char *fmt, __va_list ap)
int printf (const char *fmt,...)
int vprintf (const char *fmt, __va_list ap)
int snprintf (char *buf, size_t len, const char *fmt,...)
int vsnprintf (char *buf, size_t len, const char *fmt, __va_list ap)
int puts (const char *)
int __puts (const char *)
int putchar (int)
int getchar (void)
Macro Definition Documentation
EOF
#define EOF (-1)
Definition at line 42 of file stdio.h.
Function Documentation
__puts()
int __puts (const char *)
Definition at line 42 of file __puts.c.
Referenced by puts().
__vprintf()
int __vprintf (void(*)(void *clientdata, const char *, size_t len) sendfunc, void * clientdata, const char * fmt, __va_list ap)
Referenced by __printerr(), kprintf(), panic(), vprintf(), and vsnprintf().
getchar()
int getchar (void)
Definition at line 39 of file getchar.c.
Referenced by ask(), getcmd(), geti(), main(), and read_string().
printf()
int printf (const char * fmt, ...)
Definition at line 56 of file printf.c.
Referenced by ask(), ask_yesno(), big_file(), BladeRunner(), check_sbrk(), checkallfilecontents(), checkblock(), checkfiledata(), checkfilezeros(), checkfs(), checkonefilecontents(), checkpage(), checkpagelight(), cleanup(), cmd_chdir(), cmd_exit(), cmd_wait(), concur(), data_check(), data_matches(), dir_test(), do_chdir(), do_chdirup(), do_createfile(), do_link(), do_mkdir(), do_move(), do_rename(), do_renamexd(), do_rmdir(), do_sync(), do_truncate(), do_unlink(), do_write(), dobadreads(), docommand(), doindent(), doreadat0(), doreadateof(), dotest(), dowait(), dumpdir(), dumpdirblock(), dumpfile(), dumpfileblock(), dumpfreemap(), dumpindirect(), dumpinode(), dumplval(), dumpsb(), dumpval(), firstread(), geti(), interactive(), main(), makeprocs(), markblock(), menu(), pong(), pong_cyclic(), pong_reciprocating(), print(), print_board(), print_instructions(), printdiffs(), printheader(), printsettings(), printstatus(), printworkloads(), readallonebyone(), readallrandomly(), readstatus(), reboot_badflags(), recursedir(), runit(), runop(), setup(), spawn(), stresstest(), subproc_read(), subproc_write(), test1(), test10(), test11(), test12(), test13(), test14(), test15(), test18(), test2(), test21(), test3(), test4(), test5(), test567(), test6(), test7(), test8(), test9(), ThreadRunner(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_seeking(), try_stat(), try_symlink(), try_waitpid(), try_write(), and usage().
putchar()
int putchar (int)
Definition at line 41 of file putchar.c.
Referenced by baseparent(), check_buffer(), concparent(), dumpfileblock(), dumpfreemap(), dumpval(), getcmd(), geti(), main(), pong_cyclic(), pong_reciprocating(), puts(), read_string(), say(), and test().
puts()
int puts (const char *)
Definition at line 37 of file puts.c.
snprintf()
int snprintf (char * buf, size_t len, const char * fmt, ...)
Definition at line 148 of file snprintf.c.
Referenced by __bad_assert(), binname(), blockusagestr(), calcresult(), choose_name(), config_emu(), config_lhd(), cpu_create(), cpu_identify(), createstress_thread(), dotest(), dumpfileblock(), dumpfreemap(), dumpindirect(), dumpinode(), execvp(), fstest_makename(), killdir(), listdir(), longstress_thread(), main(), make_computes(), make_sleepalots(), mergedname(), openfiles(), pass1_dir(), pass1_direntry(), pass1_rootdir(), pass2(), pass2_dir(), prepdata(), recursedir(), recursive_cleanup(), runthreads(), semcreate(), semfs_sem_create(), setup(), test3(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), usem_init(), validname(), vfs_setbootfs(), vscomplain(), wait_siblings(), and writestress_thread().
vprintf()
int vprintf (const char * fmt, __va_list ap)
Definition at line 69 of file printf.c.
vsnprintf()
int vsnprintf (char * buf, size_t len, const char * fmt, __va_list ap)
Definition at line 99 of file snprintf.c.
Referenced by die(), dumpvalf(), say(), usem_init(), vsay(), and vscomplain().