os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/malloctest/malloctest.c File Reference
malloctest.c File Reference
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <assert.h>
#include <err.h>
Data Structures
struct test3
Macros
#define _PATH_RANDOM "random:"
#define SMALLSIZE 72
#define MEDIUMSIZE 896
#define BIGSIZE 16384
#define HUGESIZE (1024 * 1024 * 1024)
#define OVERHEAD 32
#define ABSURD_OVERHEAD 256
Functions
static int geti (void)
static void markblock (volatile void *ptr, size_t size, unsigned bias, int doprint)
static int checkblock (volatile void *ptr, size_t size, unsigned bias, int doprint)
static void test1 (void)
static void test2 (void)
static void test3 (void)
static void test4 (void)
static void test567 (int testno, unsigned long seed)
static void test5 (void)
static void test6 (void)
static void test7 (void)
static int dotest (int tn)
int main (int argc, char *argv[])
Variables
struct {
int num
const char * desc
void(* func)(void)
} tests []
Macro Definition Documentation
_PATH_RANDOM
#define _PATH_RANDOM "random:"
Definition at line 53 of file malloctest.c.
ABSURD_OVERHEAD
#define ABSURD_OVERHEAD 256
Definition at line 64 of file malloctest.c.
BIGSIZE
#define BIGSIZE 16384
Definition at line 57 of file malloctest.c.
HUGESIZE
#define HUGESIZE (1024 * 1024 * 1024)
Definition at line 58 of file malloctest.c.
MEDIUMSIZE
#define MEDIUMSIZE 896
Definition at line 56 of file malloctest.c.
OVERHEAD
#define OVERHEAD 32
Definition at line 61 of file malloctest.c.
SMALLSIZE
#define SMALLSIZE 72
Definition at line 55 of file malloctest.c.
Function Documentation
checkblock()
static int checkblock (volatile void * ptr, size_t size, unsigned bias, int doprint) static
Definition at line 133 of file malloctest.c.
References bias, and printf().
Referenced by test1(), test2(), test3(), and test567().
dotest()
static int dotest (int tn) static
Definition at line 649 of file malloctest.c.
References num, and tests.
Referenced by main().
geti()
static int geti (void) static
Definition at line 68 of file malloctest.c.
References ch, getchar(), printf(), and putchar().
Referenced by main(), and test7().
main()
int main (int argc, char * argv[])
Definition at line 662 of file malloctest.c.
References atoi(), desc, dotest(), geti(), menu(), num, printf(), and tests.
markblock()
static void markblock (volatile void * ptr, size_t size, unsigned bias, int doprint) static
Definition at line 107 of file malloctest.c.
References bias, and printf().
Referenced by test1(), test2(), test3(), and test567().
test1()
static void test1 (void) static
Definition at line 177 of file malloctest.c.
References BIGSIZE, checkblock(), free(), malloc(), markblock(), NULL, and printf().
test2()
static void test2 (void) static
Definition at line 235 of file malloctest.c.
References checkblock(), free(), HUGESIZE, malloc(), markblock(), NULL, and printf().
test3()
static void test3 (void) static
Definition at line 300 of file malloctest.c.
References assert, BIGSIZE, checkblock(), free(), test3::junk, malloc(), markblock(), MEDIUMSIZE, test3::next, NULL, printf(), and SMALLSIZE.
test4()
static void test4 (void) static
Definition at line 395 of file malloctest.c.
References ABSURD_OVERHEAD, free(), malloc(), MEDIUMSIZE, NULL, OVERHEAD, printf(), and SMALLSIZE.
test5()
static void test5 (void) static
Definition at line 585 of file malloctest.c.
References printf(), and test567().
test567()
static void test567 (int testno, unsigned long seed) static
Definition at line 524 of file malloctest.c.
References checkblock(), free(), malloc(), markblock(), NULL, printf(), random(), and srandom().
Referenced by test5(), test6(), and test7().
test6()
static void test6 (void) static
Definition at line 593 of file malloctest.c.
References _PATH_RANDOM, close(), err(), errx(), fd, O_RDONLY, open(), printf(), read(), and test567().
test7()
static void test7 (void) static
Definition at line 618 of file malloctest.c.
References geti(), printf(), and test567().
Variable Documentation
desc
const char* desc
Definition at line 634 of file malloctest.c.
Referenced by dumplval(), dumpval(), dumpvalf(), dup2_fd2(), enforce_sbrk(), exec_badargs(), exec_badprog(), exec_onearg(), main(), pipe_badptr(), time_badnsecs(), time_badsecs(), wait_badpid(), and wait_badstatus().
func
void(* func) (void)
Definition at line 635 of file malloctest.c.
num
int num
Definition at line 633 of file malloctest.c.
Referenced by array_get(), array_preallocate(), array_remove(), array_set(), array_setsize(), badnames(), check_bss(), check_data(), checkmany(), child_plain(), child_with_own_fd(), cmd_deadlockthread(), compute_thread(), createfiles(), createstress_thread(), cvtestthread(), dotest(), dowait(), emufs_loadvnode(), emufs_reclaim(), fail(), findmount(), kmalloctest4thread(), kmallocthread(), locktestthread(), longstress_thread(), loudthread(), main(), poolfree(), qsort(), quietthread(), readstress_thread(), semfs_creat(), semfs_destroy(), semfs_getdirentry(), semfs_getvnode(), semfs_lookup(), semfs_reclaim(), semfs_remove(), semfs_sem_insert(), semP(), semtestthread(), semV(), sfs_loadvnode(), sfs_reclaim(), sfs_sync_vnodes(), sleepalot_thread(), sortints(), touchmem(), try(), trymany(), usem_init(), vfs_getdevname(), vfs_getroot(), vfs_sync(), vfs_unmountall(), writestress2_thread(), and writestress_thread().
tests
struct { ... } tests[]
Initial value:
= {
    { 1, "Simple allocation test", test1 },
    { 2, "Allocate all memory in a big chunk", test2 },
    { 3, "Allocate all memory in small chunks", test3 },
    { 4, "Free list coalescing test (first/next/best-fit only)", test4 },
    { 5, "Stress test", test5 },
    { 6, "Randomized stress test", test6 },
    { 7, "Stress test with particular seed", test7 },
    { -1, NULL, NULL }
}
Referenced by dotest(), and main().