os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/arch/mips/locore/trap.c File Reference
trap.c File Reference
#include <types.h>
#include <signal.h>
#include <lib.h>
#include <mips/specialreg.h>
#include <mips/trapframe.h>
#include <cpu.h>
#include <spl.h>
#include <thread.h>
#include <current.h>
#include <vm.h>
#include <mainbus.h>
#include <syscall.h>
Macros
#define NTRAPCODES 13
Functions
__DEAD void asm_usermode (struct trapframe *tf)
void mips_trap (struct trapframe *tf)
static void kill_curthread (vaddr_t epc, unsigned code, vaddr_t vaddr)
void mips_usermode (struct trapframe *tf)
void enter_new_process (int argc, userptr_t argv, userptr_t env, vaddr_t stack, vaddr_t entry)
Variables
static const char *const trapcodenames [NTRAPCODES]
Macro Definition Documentation
NTRAPCODES
#define NTRAPCODES 13
Definition at line 52 of file trap.c.
Function Documentation
asm_usermode()
__DEAD void asm_usermode (struct trapframe * tf)
Referenced by mips_usermode().
enter_new_process()
void enter_new_process (int argc, userptr_t argv, userptr_t env, vaddr_t stack, vaddr_t entry)
Definition at line 423 of file trap.c.
References bzero(), CST_IEp, CST_IRQMASK, CST_KUp, mips_usermode(), trapframe::tf_a0, trapframe::tf_a1, trapframe::tf_a2, trapframe::tf_epc, trapframe::tf_sp, and trapframe::tf_status.
Referenced by runprogram().
kill_curthread()
static void kill_curthread (vaddr_t epc, unsigned code, vaddr_t vaddr) static
Definition at line 74 of file trap.c.
References EX_ADEL, EX_ADES, EX_BP, EX_CPU, EX_DBE, EX_IBE, EX_IRQ, EX_MOD, EX_OVF, EX_RI, EX_SYS, EX_TLBL, EX_TLBS, KASSERT, kprintf(), NTRAPCODES, panic(), sig, SIGABRT, SIGBUS, SIGFPE, SIGILL, SIGSEGV, SIGTRAP, and trapcodenames.
Referenced by mips_trap().
mips_trap()
void mips_trap (struct trapframe * tf)
Definition at line 126 of file trap.c.
References CCA_CODE, CCA_CODESHIFT, cpu_irqoff(), cpustacks, cputhreads, CST_KUp, DB_SYSCALL, DEBUG, EX_DBE, EX_IBE, EX_IRQ, EX_MOD, EX_SYS, EX_TLBL, EX_TLBS, IPL_HIGH, KASSERT, kill_curthread(), kprintf(), mainbus_interrupt(), NTRAPCODES, NULL, panic(), SAME_STACK, splhigh(), splx(), STACK_SIZE, syscall(), trapframe::tf_a0, trapframe::tf_a1, trapframe::tf_a2, trapframe::tf_a3, trapframe::tf_cause, trapframe::tf_epc, trapframe::tf_status, trapframe::tf_v0, trapframe::tf_vaddr, trapcodenames, vm_fault(), VM_FAULT_READ, VM_FAULT_READONLY, and VM_FAULT_WRITE.
mips_usermode()
void mips_usermode (struct trapframe * tf)
Definition at line 368 of file trap.c.
References asm_usermode(), cpu_irqoff(), cpustacks, cputhreads, KASSERT, SAME_STACK, spl0(), and STACK_SIZE.
Referenced by enter_new_process().
Variable Documentation
trapcodenames
const char* const trapcodenames[NTRAPCODES] static
Initial value:
= {
    "Interrupt",
    "TLB modify trap",
    "TLB miss on load",
    "TLB miss on store",
    "Address error on load",
    "Address error on store",
    "Bus error on code",
    "Bus error on data",
    "System call",
    "Break instruction",
    "Illegal instruction",
    "Coprocessor unusable",
    "Arithmetic overflow",
}
Definition at line 53 of file trap.c.
Referenced by kill_curthread(), and mips_trap().