os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/sfsck/sfs.c File Reference
sfs.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <err.h>
#include "compat.h"
#include <kern/sfs.h>
#include "disk.h"
#include "utils.h"
#include "ibmacros.h"
#include "sfs.h"
#include "main.h"
Functions
void sfs_setup (void)
static void swapsb (struct sfs_superblock *sb)
static void swapbits (uint8_t *bits)
static void swapinode (struct sfs_dinode *sfi)
static void swapdir (struct sfs_direntry *sfd)
static void swapindir (uint32_t *entries)
static uint32_t ibmap (uint32_t iblock, uint32_t offset, uint32_t entrysize)
static uint32_t bmap (const struct sfs_dinode *sfi, uint32_t fileblock)
void sfs_readsb (uint32_t blocknum, struct sfs_superblock *sb)
void sfs_writesb (uint32_t blocknum, struct sfs_superblock *sb)
void sfs_readfreemapblock (uint32_t whichblock, uint8_t *bits)
void sfs_writefreemapblock (uint32_t whichblock, uint8_t *bits)
void sfs_readinode (uint32_t ino, struct sfs_dinode *sfi)
void sfs_writeinode (uint32_t ino, struct sfs_dinode *sfi)
void sfs_readindirect (uint32_t blocknum, uint32_t *entries)
void sfs_writeindirect (uint32_t blocknum, uint32_t *entries)
static void sfs_readdirblock (struct sfs_direntry *d, uint32_t diskblock)
void sfs_readdir (struct sfs_dinode *sfi, struct sfs_direntry *d, unsigned nd)
static void sfs_writedirblock (struct sfs_direntry *d, uint32_t diskblock)
void sfs_writedir (const struct sfs_dinode *sfi, struct sfs_direntry *d, unsigned nd)
static int dirsortfunc (const void *aa, const void *bb)
void sfsdir_sort (struct sfs_direntry *d, unsigned nd, int *vector)
int sfsdir_tryadd (struct sfs_direntry *d, int nd, const char *name, uint32_t ino)
Variables
static struct sfs_direntry * global_sortdirs
Function Documentation
bmap()
static uint32_t bmap (const struct sfs_dinode * sfi, uint32_t fileblock) static
Definition at line 162 of file sfs.c.
References GET_D, GET_I, GET_II, GET_III, ibmap(), INOMAX_D, INOMAX_I, INOMAX_II, INOMAX_III, RANGE_D, RANGE_I, RANGE_II, and RANGE_III.
Referenced by sfs_readdir(), and sfs_writedir().
dirsortfunc()
static int dirsortfunc (const void * aa, const void * bb) static
Definition at line 406 of file sfs.c.
References global_sortdirs, sfs_direntry::sfd_ino, sfs_direntry::sfd_name, SFS_NOINO, and strcmp().
Referenced by sfsdir_sort().
ibmap()
static uint32_t ibmap (uint32_t iblock, uint32_t offset, uint32_t entrysize) static
Definition at line 133 of file sfs.c.
References assert, diskread(), SFS_DBPERIDB, and swapindir().
Referenced by bmap().
sfs_readdir()
void sfs_readdir (struct sfs_dinode * sfi, struct sfs_direntry * d, unsigned nd)
Definition at line 298 of file sfs.c.
References assert, bmap(), buffer, nblocks, SFS_BLOCKSIZE, sfs_readdirblock(), and SFS_ROUNDUP.
sfs_readdirblock()
static void sfs_readdirblock (struct sfs_direntry * d, uint32_t diskblock) static
Definition at line 275 of file sfs.c.
References bzero(), diskread(), SFS_BLOCKSIZE, swapdir(), and warnx().
Referenced by sfs_readdir().
sfs_readfreemapblock()
void sfs_readfreemapblock (uint32_t whichblock, uint8_t * bits)
Definition at line 215 of file sfs.c.
References diskread(), SFS_FREEMAP_START, and swapbits().
Referenced by freemap_check().
sfs_readindirect()
void sfs_readindirect (uint32_t blocknum, uint32_t * entries)
Definition at line 253 of file sfs.c.
References diskread(), and swapindir().
Referenced by check_indirect_block().
sfs_readinode()
void sfs_readinode (uint32_t ino, struct sfs_dinode * sfi)
Definition at line 234 of file sfs.c.
References diskread(), and swapinode().
Referenced by inode_adjust_filelinks(), pass1_dir(), pass1_rootdir(), and pass2_dir().
sfs_readsb()
void sfs_readsb (uint32_t blocknum, struct sfs_superblock * sb)
Definition at line 195 of file sfs.c.
References diskread(), sb, and swapsb().
Referenced by sb_load().
sfs_setup()
void sfs_setup (void)
Definition at line 49 of file sfs.c.
References assert, and SFS_BLOCKSIZE.
Referenced by main().
sfs_writedir()
void sfs_writedir (const struct sfs_dinode * sfi, struct sfs_direntry * d, unsigned nd)
Definition at line 363 of file sfs.c.
References assert, bmap(), buffer, memset(), nblocks, SFS_BLOCKSIZE, SFS_ROUNDUP, and sfs_writedirblock().
sfs_writedirblock()
static void sfs_writedirblock (struct sfs_direntry * d, uint32_t diskblock) static
Definition at line 331 of file sfs.c.
References diskwrite(), EXIT_UNRECOV, setbadness(), sfs_direntry::sfd_ino, sfs_direntry::sfd_name, SFS_BLOCKSIZE, SFS_NOINO, swapdir(), and warnx().
Referenced by sfs_writedir().
sfs_writefreemapblock()
void sfs_writefreemapblock (uint32_t whichblock, uint8_t * bits)
Definition at line 222 of file sfs.c.
References diskwrite(), SFS_FREEMAP_START, and swapbits().
Referenced by freemap_check().
sfs_writeindirect()
void sfs_writeindirect (uint32_t blocknum, uint32_t * entries)
Definition at line 260 of file sfs.c.
References diskwrite(), and swapindir().
Referenced by check_indirect_block().
sfs_writeinode()
void sfs_writeinode (uint32_t ino, struct sfs_dinode * sfi)
Definition at line 241 of file sfs.c.
References diskwrite(), and swapinode().
Referenced by inode_adjust_filelinks(), pass1_inode(), pass1_rootdir(), and pass2_dir().
sfs_writesb()
void sfs_writesb (uint32_t blocknum, struct sfs_superblock * sb)
Definition at line 202 of file sfs.c.
References diskwrite(), sb, and swapsb().
Referenced by sb_check().
sfsdir_sort()
void sfsdir_sort (struct sfs_direntry * d, unsigned nd, int * vector)
Definition at line 433 of file sfs.c.
References dirsortfunc(), global_sortdirs, and qsort().
Referenced by pass2_dir().
sfsdir_tryadd()
int sfsdir_tryadd (struct sfs_direntry * d, int nd, const char * name, uint32_t ino)
Definition at line 452 of file sfs.c.
References assert, name, sfs_direntry::sfd_ino, sfs_direntry::sfd_name, SFS_NOINO, strcpy(), and strlen().
Referenced by pass2_dir().
swapbits()
static void swapbits (uint8_t * bits) static
Definition at line 69 of file sfs.c.
Referenced by sfs_readfreemapblock(), and sfs_writefreemapblock().
swapdir()
static void swapdir (struct sfs_direntry * sfd) static
Definition at line 104 of file sfs.c.
References sfs_direntry::sfd_ino, and SWAP32.
Referenced by sfs_readdirblock(), and sfs_writedirblock().
swapindir()
static void swapindir (uint32_t * entries) static
Definition at line 111 of file sfs.c.
References SFS_DBPERIDB, and SWAP32.
Referenced by ibmap(), sfs_readindirect(), and sfs_writeindirect().
swapinode()
static void swapinode (struct sfs_dinode * sfi) static
Definition at line 77 of file sfs.c.
References GET_D, GET_I, GET_II, GET_III, NUM_D, NUM_I, NUM_II, NUM_III, SET_D, SET_I, SET_II, SET_III, sfs_dinode::sfi_linkcount, sfs_dinode::sfi_size, sfs_dinode::sfi_type, SWAP16, and SWAP32.
Referenced by sfs_readinode(), and sfs_writeinode().
swapsb()
static void swapsb (struct sfs_superblock * sb) static
Definition at line 61 of file sfs.c.
References sb, sfs_superblock::sb_magic, sfs_superblock::sb_nblocks, and SWAP32.
Referenced by sfs_readsb(), and sfs_writesb().
Variable Documentation
global_sortdirs
struct sfs_direntry* global_sortdirs static
Definition at line 398 of file sfs.c.
Referenced by dirsortfunc(), and sfsdir_sort().