os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/dev/lamebus/lrandom.c File Reference
lrandom.c File Reference
#include <types.h>
#include <lib.h>
#include <uio.h>
#include <platform/bus.h>
#include <lamebus/lrandom.h>
#include "autoconf.h"
Macros
#define LR_REG_RAND 0 /* random register */
#define LR_RANDMAX 0xffffffff
Functions
int config_lrandom (struct lrandom_softc *lr, int lrandomno)
uint32_t lrandom_random (void *devdata)
uint32_t lrandom_randmax (void *devdata)
int lrandom_read (void *devdata, struct uio *uio)
Macro Definition Documentation
LR_RANDMAX
#define LR_RANDMAX 0xffffffff
Definition at line 44 of file lrandom.c.
LR_REG_RAND
#define LR_REG_RAND 0 /* random register */
Definition at line 41 of file lrandom.c.
Function Documentation
config_lrandom()
int config_lrandom (struct lrandom_softc * lr, int lrandomno)
Definition at line 47 of file lrandom.c.
Referenced by tryattach_lrandom_to_lamebus().
lrandom_randmax()
uint32_t lrandom_randmax (void * devdata)
Definition at line 62 of file lrandom.c.
References LR_RANDMAX.
Referenced by attach_random_to_lrandom().
lrandom_random()
uint32_t lrandom_random (void * devdata)
Definition at line 55 of file lrandom.c.
References bus_read_register, lrandom_softc::lr_bus, lrandom_softc::lr_buspos, and LR_REG_RAND.
Referenced by attach_random_to_lrandom().
lrandom_read()
int lrandom_read (void * devdata, struct uio * uio)
Definition at line 69 of file lrandom.c.
References bus_read_register, lrandom_softc::lr_bus, lrandom_softc::lr_buspos, LR_REG_RAND, uio::uio_resid, and uiomove().
Referenced by attach_random_to_lrandom().