os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/mksfs/disk.h File Reference
disk.h File Reference
Functions
void opendisk (const char *path)
uint32_t diskblocksize (void)
uint32_t diskblocks (void)
void diskwrite (const void *data, uint32_t block)
void diskread (void *data, uint32_t block)
void closedisk (void)
Function Documentation
closedisk()
void closedisk (void)
Definition at line 193 of file disk.c.
References assert, close(), err(), and fd.
Referenced by main().
diskblocks()
uint32_t diskblocks (void)
Definition at line 111 of file disk.c.
References assert, fd, and nblocks.
Referenced by main(), and poison().
diskblocksize()
uint32_t diskblocksize (void)
Definition at line 101 of file disk.c.
References assert, BLOCKSIZE, and fd.
Referenced by main().
diskread()
void diskread (void * data, uint32_t block)
Definition at line 157 of file disk.c.
References assert, BLOCKSIZE, EAGAIN, EINTR, err(), errno, fd, lseek(), read(), and SEEK_SET.
Referenced by dumpdirblock(), dumpfileblock(), dumpfreemap(), dumpindirect(), dumpinode(), dumpsb(), ibmap(), readsb(), recursedirblock(), sfs_readdirblock(), sfs_readfreemapblock(), sfs_readindirect(), sfs_readinode(), sfs_readsb(), and traverse_ib().
diskwrite()
void diskwrite (const void * data, uint32_t block)
Definition at line 121 of file disk.c.
References assert, BLOCKSIZE, EAGAIN, EINTR, err(), errno, fd, lseek(), SEEK_SET, and write().
Referenced by poison(), sfs_writedirblock(), sfs_writefreemapblock(), sfs_writeindirect(), sfs_writeinode(), sfs_writesb(), writefreemap(), writerootdir(), and writesuper().
opendisk()
void opendisk (const char * path)
Definition at line 58 of file disk.c.
References assert, BLOCKSIZE, buf, EAGAIN, EINTR, err(), errno, errx(), fd, fstat(), HOSTSTRING, nblocks, O_RDWR, open(), read(), stat::st_size, strcmp(), and strlen().
Referenced by main().