os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_waitpid.c File Reference
bad_waitpid.c File Reference
#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void wait_badpid (pid_t pid, const char *desc)
static void wait_nullstatus (void)
static void wait_badstatus (void *ptr, const char *desc)
static void wait_unaligned (void)
static void wait_badflags (void)
static void wait_self (void)
static void wait_parent (void)
static void wait_siblings_child (const char *semname)
static void wait_siblings (void)
void test_waitpid (void)
Function Documentation
test_waitpid()
void test_waitpid (void)
Definition at line 405 of file bad_waitpid.c.
References NONEXIST_PID, wait_badflags(), wait_badpid(), wait_badstatus(), wait_nullstatus(), wait_parent(), wait_self(), wait_siblings(), and wait_unaligned().
wait_badflags()
static void wait_badflags (void) static
Definition at line 150 of file bad_waitpid.c.
References EINVAL, errno, exit(), fork(), pid, report_aborted(), report_begin(), report_check(), report_warn(), and waitpid().
Referenced by test_waitpid().
wait_badpid()
static void wait_badpid (pid_t pid, const char * desc) static
Definition at line 46 of file bad_waitpid.c.
References desc, ECHILD, ENOSYS, err(), errno, ESRCH, pid, report_begin(), report_check2(), report_saw_enosys(), and waitpid().
Referenced by test_waitpid().
wait_badstatus()
static void wait_badstatus (void * ptr, const char * desc) static
Definition at line 92 of file bad_waitpid.c.
References desc, EFAULT, errno, exit(), fork(), pid, report_aborted(), report_begin(), report_check(), report_warn(), and waitpid().
Referenced by test_waitpid().
wait_nullstatus()
static void wait_nullstatus (void) static
Definition at line 67 of file bad_waitpid.c.
References errno, exit(), fork(), NULL, pid, report_aborted(), report_begin(), report_check(), report_warn(), and waitpid().
Referenced by test_waitpid().
wait_parent()
static void wait_parent (void) static
Definition at line 187 of file bad_waitpid.c.
References _exit(), errno, fork(), getpid(), mypid, report_aborted(), report_begin(), report_beginsub(), report_hassubs(), report_survival(), report_warn(), and waitpid().
Referenced by test_waitpid().
wait_self()
static void wait_self (void) static
Definition at line 174 of file bad_waitpid.c.
References errno, getpid(), report_begin(), report_survival(), and waitpid().
Referenced by test_waitpid().
wait_siblings()
static void wait_siblings (void) static
Definition at line 290 of file bad_waitpid.c.
References _exit(), close(), fd, fork(), getpid(), NULL, O_CREAT, O_TRUNC, O_WRONLY, open(), open_testfile(), pids, remove(), report_aborted(), report_begin(), report_beginsub(), report_hassubs(), report_passed(), report_warn(), report_warnx(), snprintf(), TESTFILE, wait_siblings_child(), waitpid(), and write().
Referenced by test_waitpid().
wait_siblings_child()
static void wait_siblings_child (const char * semname) static
Definition at line 218 of file bad_waitpid.c.
References close(), errno, fd, getpid(), lseek(), mypid, O_RDONLY, open(), pids, read(), report_beginsub(), report_survival(), report_warn(), SEEK_SET, TESTFILE, and waitpid().
Referenced by wait_siblings().
wait_unaligned()
static void wait_unaligned (void) static
Definition at line 116 of file bad_waitpid.c.
References errno, exit(), fork(), pid, report_aborted(), report_begin(), report_survival(), report_warn(), and waitpid().
Referenced by test_waitpid().