os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_pipe.c File Reference
bad_pipe.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void pipe_badptr (void *ptr, const char *desc)
static void pipe_unaligned (void)
void test_pipe (void)
Function Documentation
pipe_badptr()
static void pipe_badptr (void * ptr, const char * desc) static
Definition at line 48 of file bad_pipe.c.
References desc, EFAULT, errno, pipe(), report_begin(), and report_check().
Referenced by test_pipe().
pipe_unaligned()
static void pipe_unaligned (void) static
Definition at line 59 of file bad_pipe.c.
References close(), errno, memmove(), pipe(), report_begin(), and report_survival().
Referenced by test_pipe().
test_pipe()
void test_pipe (void)
Definition at line 79 of file bad_pipe.c.
References NULL, pipe_badptr(), and pipe_unaligned().