os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/bin/sh/sh.c File Reference
sh.c File Reference
#include <sys/types.h>
#include <sys/wait.h>
#include <assert.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <limits.h>
#include <errno.h>
#include <err.h>
Data Structures
struct exitinfo
Macros
#define NARG_MAX 1024
#define CMDLINE_MAX 4096
#define MAXBG 128
Functions
static int can_bg (void)
static void remember_bg (pid_t pid)
static void exitinfo_exit (struct exitinfo *ei, int code)
static void readstatus (int status, struct exitinfo *ei)
static void printstatus (const struct exitinfo *ei, int printexitzero)
static void dowait (pid_t pid)
static void cmd_wait (int ac, char *av[], struct exitinfo *ei)
static void cmd_chdir (int ac, char *av[], struct exitinfo *ei)
static void cmd_exit (int ac, char *av[], struct exitinfo *ei)
static void docommand (char *buf, struct exitinfo *ei)
static void getcmd (char *buf, size_t len)
static void interactive (void)
static void check_timing (void)
int main (int argc, char *argv[])
Variables
static int timing = 0
static pid_t bgpids [MAXBG]
struct {
const char * name
void(* func)(int, char **, struct exitinfo *)
} builtins []
Macro Definition Documentation
CMDLINE_MAX
#define CMDLINE_MAX 4096
Definition at line 59 of file sh.c.
MAXBG
#define MAXBG 128
Definition at line 73 of file sh.c.
NARG_MAX
#define NARG_MAX 1024
Definition at line 55 of file sh.c.
Function Documentation
can_bg()
static int can_bg (void) static
Definition at line 82 of file sh.c.
References bgpids, and MAXBG.
Referenced by docommand().
check_timing()
static void check_timing (void) static
Definition at line 549 of file sh.c.
References __time(), timing, and warnx().
Referenced by main().
cmd_chdir()
static void cmd_chdir (int ac, char * av[], struct exitinfo * ei) static
Definition at line 302 of file sh.c.
References chdir(), exitinfo_exit(), printf(), and warn().
cmd_exit()
static void cmd_exit (int ac, char * av[], struct exitinfo * ei) static
Definition at line 324 of file sh.c.
References atoi(), exit(), exitinfo_exit(), and printf().
cmd_wait()
static void cmd_wait (int ac, char * av[], struct exitinfo * ei) static
Definition at line 265 of file sh.c.
References atoi(), bgpids, dowait(), exitinfo_exit(), MAXBG, pid, and printf().
docommand()
static void docommand (char * buf, struct exitinfo * ei) static
Definition at line 367 of file sh.c.
References __time(), _exit(), buf, builtins, can_bg(), execvp(), exitinfo_exit(), fork(), name, NARG_MAX, NULL, pid, printf(), readstatus(), remember_bg(), strcmp(), strtok(), timing, waitpid(), warn(), and warnx().
Referenced by interactive(), and main().
dowait()
static void dowait (pid_t pid) static
Definition at line 197 of file sh.c.
References pid, printf(), printstatus(), readstatus(), waitpid(), and warn().
Referenced by cmd_wait(), main(), and makeprocs().
exitinfo_exit()
static void exitinfo_exit (struct exitinfo * ei, int code) static
Definition at line 119 of file sh.c.
References exitinfo::coredump, exitinfo::signaled, exitinfo::stopped, and exitinfo::val.
Referenced by cmd_chdir(), cmd_exit(), cmd_wait(), and docommand().
getcmd()
static void getcmd (char * buf, size_t len) static
Definition at line 489 of file sh.c.
References buf, ch, getchar(), pos, and putchar().
Referenced by interactive().
interactive()
static void interactive (void) static
Definition at line 531 of file sh.c.
References buf, CMDLINE_MAX, docommand(), getcmd(), printf(), and printstatus().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 565 of file sh.c.
References check_timing(), docommand(), errx(), exit(), hostcompat_init(), interactive(), printstatus(), exitinfo::signaled, exitinfo::stopped, strcmp(), and exitinfo::val.
printstatus()
static void printstatus (const struct exitinfo * ei, int printexitzero) static
Definition at line 175 of file sh.c.
References exitinfo::coredump, printf(), exitinfo::signaled, exitinfo::stopped, and exitinfo::val.
Referenced by dowait(), interactive(), and main().
readstatus()
static void readstatus (int status, struct exitinfo * ei) static
Definition at line 133 of file sh.c.
References exitinfo::coredump, printf(), exitinfo::signaled, exitinfo::stopped, exitinfo::val, WCOREDUMP, WEXITSTATUS, WIFEXITED, WIFSIGNALED, WIFSTOPPED, WSTOPSIG, and WTERMSIG.
Referenced by docommand(), and dowait().
remember_bg()
static void remember_bg (pid_t pid) static
Definition at line 102 of file sh.c.
References assert, bgpids, MAXBG, and pid.
Referenced by docommand().
Variable Documentation
bgpids
pid_t bgpids[MAXBG] static
Definition at line 74 of file sh.c.
Referenced by can_bg(), cmd_wait(), and remember_bg().
builtins
struct { ... } builtins[]
Initial value:
= {
    { "cd",    cmd_chdir },
    { "chdir", cmd_chdir },
    { "exit",  cmd_exit },
    { "wait",  cmd_wait },
    { NULL, NULL }
}
Referenced by docommand().
func
void(* func) (int, char **, struct exitinfo *)
Definition at line 349 of file sh.c.
name
const char* name
Definition at line 348 of file sh.c.
Referenced by docommand().
timing
int timing = 0 static
Definition at line 70 of file sh.c.
Referenced by check_timing(), and docommand().