os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/include/stdlib.h File Reference
stdlib.h File Reference
#include <kern/types.h>
#include <types/size_t.h>
#include <sys/null.h>
Macros
#define RAND_MAX 0x7fffffff
Functions
int atoi (const char *)
void abort (void)
void exit (int code)
char * getenv (const char *var)
int system (const char *command)
long random (void)
void srandom (unsigned long seed)
char * initstate (unsigned long, char *, size_t)
char * setstate (char *)
void * malloc (size_t size)
void free (void *ptr)
void qsort (void *data, unsigned num, size_t size, int(*f)(const void *, const void *))
Macro Definition Documentation
RAND_MAX
#define RAND_MAX 0x7fffffff
Definition at line 67 of file stdlib.h.
Function Documentation
abort()
void abort (void)
Definition at line 42 of file abort.c.
References _exit().
atoi()
int atoi (const char *)
Definition at line 50 of file atoi.c.
References NULL, and strchr().
exit()
void exit (int code)
Definition at line 38 of file exit.c.
References _exit().
free()
void free (void * ptr)
Definition at line 534 of file malloc.c.
References __heapbase, __heaptop, __malloc_deadbeef(), __malloc_trymerge(), errx(), M_DATA, M_NEXT, M_OK, M_PREV, M_SIZE, NULL, and warnx().
getenv()
char* getenv (const char * var)
Definition at line 56 of file getenv.c.
References __default_environ, __environ, memcmp(), NULL, strchr(), and strlen().
initstate()
char* initstate (unsigned long , char * , size_t)
Definition at line 282 of file random.c.
References assert, BREAK_0, BREAK_1, BREAK_2, BREAK_3, BREAK_4, DEG_0, DEG_1, DEG_2, DEG_3, DEG_4, end_ptr, LOCKME, MAX_TYPES, NULL, rand_deg, rand_sep, rand_type, rptr, SEP_0, SEP_1, SEP_2, SEP_3, SEP_4, srandom_unlocked(), state, TYPE_0, TYPE_1, TYPE_2, TYPE_3, TYPE_4, and UNLOCKME.
malloc()
void* malloc (size_t size)
Definition at line 352 of file malloc.c.
References __heapbase, __heaptop, __malloc_init(), __malloc_sbrk(), __malloc_split(), assert, errx(), M_DATA, M_MKFIELD, M_NEXTOFF, M_OK, M_SIZE, NULL, PAGE_SIZE, and warnx().
qsort()
void qsort (void * data, unsigned num, size_t size, int(*)(const void *, const void *) f)
Definition at line 38 of file qsort.c.
References assert, COMPARE, EXCHANGE, f, num, and tail().
random()
long random (void)
Definition at line 143 of file random.c.
References LOCKME, NULL, panic(), random_unlocked(), random_softc::rs_devdata, random_softc::rs_random, the_random, and UNLOCKME.
setstate()
char* setstate (char *)
Definition at line 354 of file random.c.
References assert, degrees, end_ptr, fptr, LOCKME, MAX_TYPES, NULL, rand_deg, rand_sep, rand_type, rptr, seps, state, TYPE_0, TYPE_1, TYPE_2, TYPE_3, TYPE_4, and UNLOCKME.
srandom()
void srandom (unsigned long seed)
Definition at line 250 of file random.c.
References LOCKME, srandom_unlocked(), and UNLOCKME.
system()
int system (const char * command)
Definition at line 45 of file system.c.
References _exit(), E2BIG, errno, execv(), fork(), MAXARGS, MAXCMDSIZE, NULL, pid, strcpy(), strlen(), strtok(), and waitpid().