os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/sbrktest/sbrktest.c File Reference
sbrktest.c File Reference
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
#include <errno.h>
Macros
#define _PATH_RANDOM "random:"
#define PAGE_SIZE 4096
#define HUGESIZE (1024 * 1024 * 1024) /* 1G */
Functions
static int geti (void)
static unsigned long getseed (void)
static pid_t dofork (void)
static void dowait (pid_t pid)
static void say (const char *msg)
static void markpage (volatile void *baseptr, unsigned pageoffset)
static int checkpage (volatile void *baseptr, unsigned pageoffset, bool neednl)
static void markpagelight (volatile void *baseptr, unsigned pageoffset)
static int checkpagelight (volatile void *baseptr, unsigned pageoffset, bool neednl)
static void * dosbrk (ssize_t size)
static void setup (void)
static void test1 (void)
static void test2 (void)
static void test3 (void)
static void test4 (void)
static void test5 (void)
static void test6 (void)
static void test7 (void)
static void test8 (void)
static void test9 (void)
static void test10 (void)
static void test11 (void)
static void test12 (void)
static void test13 (void)
static void test14 (void)
static void test15 (void)
static void stresstest (unsigned long seed, bool large)
static void test16 (void)
static void test17 (void)
static void test18 (void)
static void test19 (void)
static void test20 (void)
static void test21 (void)
static int dotest (int tn)
int main (int argc, char *argv[])
Variables
struct {
int num
const char * desc
void(* func)(void)
} tests []
static const unsigned numtests = sizeof(tests) / sizeof(tests[0])
Macro Definition Documentation
_PATH_RANDOM
#define _PATH_RANDOM "random:"
Definition at line 39 of file sbrktest.c.
HUGESIZE
#define HUGESIZE (1024 * 1024 * 1024) /* 1G */
PAGE_SIZE
#define PAGE_SIZE 4096
Definition at line 46 of file sbrktest.c.
Function Documentation
checkpage()
static int checkpage (volatile void * baseptr, unsigned pageoffset, bool neednl) static
Definition at line 180 of file sbrktest.c.
References PAGE_SIZE, and printf().
Referenced by test1(), test10(), test12(), test13(), test14(), test15(), test2(), test3(), and test4().
checkpagelight()
static int checkpagelight (volatile void * baseptr, unsigned pageoffset, bool neednl) static
Definition at line 233 of file sbrktest.c.
References PAGE_SIZE, and printf().
Referenced by stresstest(), test10(), test11(), and test9().
dofork()
static pid_t dofork (void) static
Definition at line 110 of file sbrktest.c.
References err(), fork(), and pid.
Referenced by test12(), test13(), test14(), and test15().
dosbrk()
static void* dosbrk (ssize_t size) static
Definition at line 260 of file sbrktest.c.
References err(), errx(), NULL, and sbrk().
Referenced by setup(), stresstest(), test1(), test10(), test11(), test12(), test13(), test14(), test15(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
dotest()
static int dotest (int tn) static
Definition at line 1099 of file sbrktest.c.
References num, numtests, and tests.
Referenced by main().
dowait()
static void dowait (pid_t pid) static
Definition at line 123 of file sbrktest.c.
References err(), errx(), pid, waitpid(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
Referenced by test12(), test13(), test14(), and test15().
geti()
static int geti (void) static
Definition at line 53 of file sbrktest.c.
References ch, getchar(), printf(), and putchar().
Referenced by main(), test18(), and test21().
getseed()
static unsigned long getseed (void) static
Definition at line 87 of file sbrktest.c.
References _PATH_RANDOM, close(), err(), errx(), fd, O_RDONLY, open(), and read().
Referenced by test17(), and test20().
main()
int main (int argc, char * argv[])
Definition at line 1113 of file sbrktest.c.
References atoi(), desc, dotest(), geti(), menu(), num, numtests, printf(), setup(), and tests.
markpage()
static void markpage (volatile void * baseptr, unsigned pageoffset) static
Definition at line 156 of file sbrktest.c.
References PAGE_SIZE.
Referenced by test1(), test10(), test12(), test13(), test14(), test15(), test2(), test3(), and test4().
markpagelight()
static void markpagelight (volatile void * baseptr, unsigned pageoffset) static
Definition at line 216 of file sbrktest.c.
References PAGE_SIZE.
Referenced by stresstest(), test10(), test11(), and test9().
say()
static void say (const char * msg) static
Definition at line 142 of file sbrktest.c.
References test::msg, STDOUT_FILENO, strlen(), and write().
Referenced by test12(), and test15().
setup()
static void setup (void) static
Definition at line 279 of file sbrktest.c.
References dosbrk(), errno, errx(), PAGE_SIZE, sbrk(), strerror(), and warnx().
Referenced by main().
stresstest()
static void stresstest (unsigned long seed, bool large) static
Definition at line 958 of file sbrktest.c.
References checkpagelight(), dosbrk(), exit(), markpagelight(), num, PAGE_SIZE, printf(), random(), srandom(), and warnx().
Referenced by test16(), test17(), test18(), test19(), test20(), and test21().
test1()
static void test1 (void) static
Definition at line 316 of file sbrktest.c.
References checkpage(), dosbrk(), errx(), markpage(), PAGE_SIZE, and printf().
test10()
static void test10 (void) static
Definition at line 652 of file sbrktest.c.
References checkpage(), checkpagelight(), dosbrk(), errx(), exit(), markpage(), markpagelight(), PAGE_SIZE, printf(), sbrk(), and warnx().
test11()
static void test11 (void) static
Definition at line 702 of file sbrktest.c.
References checkpagelight(), dosbrk(), exit(), markpagelight(), num, PAGE_SIZE, printf(), and warnx().
test12()
static void test12 (void) static
Definition at line 754 of file sbrktest.c.
References checkpage(), dofork(), dosbrk(), dowait(), errx(), exit(), markpage(), PAGE_SIZE, pid, printf(), and say().
test13()
static void test13 (void) static
Definition at line 789 of file sbrktest.c.
References checkpage(), dofork(), dosbrk(), dowait(), errx(), exit(), markpage(), PAGE_SIZE, pid, and printf().
test14()
static void test14 (void) static
Definition at line 822 of file sbrktest.c.
References checkpage(), dofork(), dosbrk(), dowait(), errx(), exit(), markpage(), PAGE_SIZE, pid, and printf().
test15()
static void test15 (void) static
Definition at line 858 of file sbrktest.c.
References checkpage(), dofork(), dosbrk(), dowait(), errx(), exit(), markpage(), num, PAGE_SIZE, pid, printf(), and say().
test16()
static void test16 (void) static
Definition at line 1023 of file sbrktest.c.
References stresstest().
test17()
static void test17 (void) static
Definition at line 1030 of file sbrktest.c.
References getseed(), and stresstest().
test18()
static void test18 (void) static
Definition at line 1037 of file sbrktest.c.
References geti(), printf(), and stresstest().
test19()
static void test19 (void) static
Definition at line 1045 of file sbrktest.c.
References stresstest().
test2()
static void test2 (void) static
Definition at line 335 of file sbrktest.c.
References checkpage(), dosbrk(), errx(), markpage(), PAGE_SIZE, and printf().
test20()
static void test20 (void) static
Definition at line 1052 of file sbrktest.c.
References getseed(), and stresstest().
test21()
static void test21 (void) static
Definition at line 1059 of file sbrktest.c.
References geti(), printf(), and stresstest().
test3()
static void test3 (void) static
Definition at line 375 of file sbrktest.c.
References checkpage(), dosbrk(), errx(), exit(), markpage(), num, PAGE_SIZE, printf(), and warnx().
test4()
static void test4 (void) static
Definition at line 428 of file sbrktest.c.
References checkpage(), dosbrk(), errx(), exit(), markpage(), num, PAGE_SIZE, printf(), and warnx().
test5()
static void test5 (void) static
Definition at line 490 of file sbrktest.c.
References dosbrk(), errx(), and printf().
test6()
static void test6 (void) static
Definition at line 506 of file sbrktest.c.
References dosbrk(), errx(), PAGE_SIZE, and printf().
test7()
static void test7 (void) static
Definition at line 523 of file sbrktest.c.
References dosbrk(), errx(), PAGE_SIZE, and printf().
test8()
static void test8 (void) static
Definition at line 542 of file sbrktest.c.
References dosbrk(), errx(), PAGE_SIZE, and printf().
test9()
static void test9 (void) static
Definition at line 582 of file sbrktest.c.
References checkpagelight(), dosbrk(), exit(), HUGESIZE, markpagelight(), PAGE_SIZE, printf(), sbrk(), and warnx().
Variable Documentation
desc
const char* desc
Definition at line 1070 of file sbrktest.c.
Referenced by main().
func
void(* func) (void)
Definition at line 1071 of file sbrktest.c.
num
int num
Definition at line 1069 of file sbrktest.c.
Referenced by dotest(), main(), stresstest(), test11(), test15(), test3(), and test4().
numtests
const unsigned numtests = sizeof(tests) / sizeof(tests[0]) static
Definition at line 1095 of file sbrktest.c.
Referenced by dotest(), and main().
tests
const { ... } tests[]
Initial value:
= {
    { 1, "Allocate one page", test1 },
    { 2, "Allocate and free one page", test2 },
    { 3, "Allocate and free several pages", test3 },
    { 4, "Allocate several pages and free them one at a time", test4 },
    { 5, "Check the heap end (crashes)", test5 },
    { 6, "Allocate and check the heap end (crashes)", test6 },
    { 7, "Allocate and free and check the heap end (crashes)", test7 },
    { 8, "Allocate several, free some, check heap end (crashes)", test8 },
    { 9, "Allocate all memory in a big chunk", test9 },
    { 10, "Allocate all memory a page at a time", test10 },
    { 11, "Allocate a lot and intentionally leak it", test11 },
    { 12, "Fork and then allocate", test12 },
    { 13, "Allocate and then fork", test13 },
    { 14, "Allocate and then fork and free", test14 },
    { 15, "Allocate, fork, allocate more, and free (and spam)", test15 },
    { 16, "Small stress test", test16 },
    { 17, "Randomized small stress test", test17 },
    { 18, "Small stress test with particular seed", test18 },
    { 19, "Large stress test", test19 },
    { 20, "Randomized large stress test", test20 },
    { 21, "Large stress test with particular seed", test21 },
}
Referenced by dotest(), and main().