os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/include/string.h File Reference
string.h File Reference
#include <kern/types.h>
#include <types/size_t.h>
#include <sys/null.h>
Functions
char * strcat (char *, const char *)
char * strcpy (char *, const char *)
char * strchr (const char *, int)
char * strrchr (const char *, int)
int strcmp (const char *, const char *)
size_t strlen (const char *)
char * strtok_r (char *, const char *, char **)
char * strtok (char *, const char *)
void * memset (void *, int c, size_t)
void * memcpy (void *, const void *, size_t)
void * memmove (void *, const void *, size_t)
int memcmp (const void *, const void *, size_t)
const char * strerror (int errcode)
void bzero (void *, size_t)
Function Documentation
bzero()
void bzero (void * , size_t)
Definition at line 49 of file bzero.c.
memcmp()
int memcmp (const void * , const void * , size_t)
Definition at line 38 of file memcmp.c.
memcpy()
void* memcpy (void * , const void * , size_t)
Definition at line 48 of file memcpy.c.
memmove()
void* memmove (void * , const void * , size_t)
Definition at line 49 of file memmove.c.
References memcpy().
memset()
void* memset (void * , int c, size_t)
Definition at line 42 of file memset.c.
References ch.
strcat()
char* strcat (char * , const char *)
Definition at line 47 of file strcat.c.
References strcpy(), and strlen().
strchr()
char* strchr (const char * , int)
Definition at line 47 of file strchr.c.
References ch, and NULL.
strcmp()
int strcmp (const char * , const char *)
Definition at line 48 of file strcmp.c.
strcpy()
char* strcpy (char * , const char *)
Definition at line 46 of file strcpy.c.
strerror()
const char* strerror (int errcode)
Definition at line 55 of file misc.c.
References NULL, panic(), sys_errlist, and sys_nerr.
strlen()
size_t strlen (const char *)
Definition at line 47 of file strlen.c.
strrchr()
char* strrchr (const char * , int)
Definition at line 47 of file strrchr.c.
References ch, NULL, and strlen().
strtok()
char* strtok (char * , const char *)
Definition at line 35 of file strtok.c.
References __strtok_context, seps, and strtok_r().
strtok_r()
char* strtok_r (char * , const char * , char **)
Definition at line 50 of file strtok_r.c.
References NULL, seps, strchr(), and tail().