os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/dirseek/dirseek.c File Reference
dirseek.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <err.h>
Macros
#define TESTDIR "seektestdir"
Functions
static int findentry (const char *name)
static void openit (void)
static void closeit (void)
static void readit (void)
static void firstread (void)
static void doreadat0 (void)
static void readone (const char *shouldbe)
static void doreadone (int which)
static void readallonebyone (void)
static void readallrandomly (void)
static void readateof (void)
static void doreadateof (void)
static void inval_read (void)
static void dobadreads (void)
static void dotest (void)
static void mkfile (const char *name)
static void setup (void)
static void cleanup (void)
int main (void)
Variables
struct {
const char * name
int make_it
off_t pos
} testfiles []
static int dirfd
Macro Definition Documentation
TESTDIR
#define TESTDIR "seektestdir"
Definition at line 57 of file dirseek.c.
Function Documentation
cleanup()
static void cleanup (void) static
Definition at line 517 of file dirseek.c.
References chdir(), err(), make_it, name, printf(), remove(), rmdir(), TESTDIR, and testfiles.
Referenced by main().
closeit()
static void closeit (void) static
Definition at line 119 of file dirseek.c.
References close(), dirfd, and err().
Referenced by dotest().
dobadreads()
static void dobadreads (void) static
Definition at line 362 of file dirseek.c.
References dirfd, err(), inval_read(), lseek(), pos, printf(), SEEK_END, SEEK_SET, and testfiles.
Referenced by dotest().
doreadat0()
static void doreadat0 (void) static
Definition at line 215 of file dirseek.c.
References dirfd, err(), errx(), lseek(), pos, printf(), readit(), and SEEK_SET.
Referenced by dotest().
doreadateof()
static void doreadateof (void) static
Definition at line 325 of file dirseek.c.
References dirfd, err(), errx(), lseek(), name, pos, printf(), readateof(), SEEK_END, and testfiles.
Referenced by dotest().
doreadone()
static void doreadone (int which) static
Definition at line 256 of file dirseek.c.
References dirfd, err(), errx(), lseek(), name, pos, readone(), SEEK_SET, and testfiles.
Referenced by readallonebyone(), and readallrandomly().
dotest()
static void dotest (void) static
Definition at line 415 of file dirseek.c.
References closeit(), dobadreads(), doreadat0(), doreadateof(), firstread(), openit(), printf(), readallonebyone(), readallrandomly(), and readateof().
Referenced by main().
findentry()
static int findentry (const char * name) static
Definition at line 95 of file dirseek.c.
References name, strcmp(), and testfiles.
Referenced by readit().
firstread()
static void firstread (void) static
Definition at line 196 of file dirseek.c.
References dirfd, err(), errx(), lseek(), pos, printf(), readit(), and SEEK_CUR.
Referenced by dotest().
inval_read()
static void inval_read (void) static
Definition at line 349 of file dirseek.c.
References buf, dirfd, and getdirentry().
Referenced by dobadreads().
main()
int main (void)
Definition at line 545 of file dirseek.c.
References cleanup(), dotest(), and setup().
mkfile()
static void mkfile (const char * name) static
Definition at line 456 of file dirseek.c.
References buf, close(), err(), errx(), fd, name, O_CREAT, O_EXCL, O_WRONLY, open(), strcat(), strlen(), and write().
Referenced by setup().
openit()
static void openit (void) static
Definition at line 109 of file dirseek.c.
References dirfd, err(), O_RDONLY, and open().
Referenced by dotest().
readallonebyone()
static void readallonebyone (void) static
Definition at line 273 of file dirseek.c.
References doreadone(), printf(), and testfiles.
Referenced by dotest().
readallrandomly()
static void readallrandomly (void) static
Definition at line 285 of file dirseek.c.
References doreadone(), printf(), random(), srandom(), and testfiles.
Referenced by dotest().
readateof()
static void readateof (void) static
Definition at line 303 of file dirseek.c.
References buf, dirfd, err(), errx(), and getdirentry().
Referenced by doreadateof(), and dotest().
readit()
static void readit (void) static
Definition at line 129 of file dirseek.c.
References buf, dirfd, err(), errx(), findentry(), getdirentry(), lseek(), name, pos, SEEK_CUR, and testfiles.
Referenced by doreadat0(), and firstread().
readone()
static void readone (const char * shouldbe) static
Definition at line 234 of file dirseek.c.
References buf, dirfd, err(), errx(), getdirentry(), and strcmp().
Referenced by doreadone().
setup()
static void setup (void) static
Definition at line 488 of file dirseek.c.
References chdir(), err(), make_it, mkdir(), mkfile(), name, printf(), TESTDIR, and testfiles.
Referenced by main().
Variable Documentation
dirfd
int dirfd static
Definition at line 91 of file dirseek.c.
Referenced by closeit(), dobadreads(), doreadat0(), doreadateof(), doreadone(), firstread(), inspectdir(), inval_read(), openit(), readateof(), readit(), and readone().
make_it
int make_it
Definition at line 61 of file dirseek.c.
Referenced by cleanup(), and setup().
name
const char* name
Definition at line 60 of file dirseek.c.
Referenced by cleanup(), doreadateof(), doreadone(), findentry(), mkfile(), readit(), and setup().
pos
off_t pos
Definition at line 62 of file dirseek.c.
Referenced by change_is_present(), check(), check_write(), dec(), dev_tryseek(), do_write(), dobadreads(), dolseek(), doreadat0(), doreadateof(), doreadone(), dumpdata(), fc_create_write(), file_randomwrite(), finishcarry(), firstread(), fstest_write(), getcmd(), getresult(), indent_to(), kgets(), lseek_loc_pasteof(), multc(), number_get(), op_write(), pluseq(), poolfree(), putresult(), randwrite(), readit(), report_saw_enosys(), report_warn(), report_warnx(), semfs_getdirentry(), try_seeking(), uio_kinit(), vopfail_truncate_isdir(), and vscomplain().
testfiles
struct { ... } testfiles[]
Initial value:
= {
    { ".",      0, -1 },
    { "..",     0, -1 },
    { "ridcully",   1, -1 },
    { "weatherwax", 1, -1 },
    { "ogg",    1, -1 },
    { "vorbis", 1, -1 },
    { "verence",    1, -1 },
    { "magrat", 1, -1 },
    { "agnes",  1, -1 },
    { "rincewind",  1, -1 },
    { "angua",  1, -1 },
    { "cherry", 1, -1 },
    { "dorfl",  1, -1 },
    { "nobby",  1, -1 },
    { "carrot", 1, -1 },
    { "vimes",  1, -1 },
    { "detritus",   1, -1 },
    { "twoflower",  1, -1 },
    { "teatime",    1, -1 },
    { "qu",     1, -1 },
    { NULL, 0, 0 }
}
Referenced by cleanup(), dobadreads(), doreadateof(), doreadone(), findentry(), readallonebyone(), readallrandomly(), readit(), and setup().