os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/test/synchtest.c File Reference
synchtest.c File Reference
#include <types.h>
#include <lib.h>
#include <clock.h>
#include <thread.h>
#include <synch.h>
#include <test.h>
Macros
#define NSEMLOOPS 63
#define NLOCKLOOPS 120
#define NCVLOOPS 5
#define NTHREADS 32
#define NCVS 250
#define NLOOPS 40
Functions
static void inititems (void)
static void semtestthread (void *junk, unsigned long num)
int semtest (int nargs, char **args)
static void fail (unsigned long num, const char *msg)
static void locktestthread (void *junk, unsigned long num)
int locktest (int nargs, char **args)
static void cvtestthread (void *junk, unsigned long num)
int cvtest (int nargs, char **args)
static void sleepthread (void *junk1, unsigned long junk2)
static void wakethread (void *junk1, unsigned long junk2)
int cvtest2 (int nargs, char **args)
Variables
static volatile unsigned long testval1
static volatile unsigned long testval2
static volatile unsigned long testval3
static struct semaphore * testsem
static struct lock * testlock
static struct cv * testcv
static struct semaphore * donesem
static struct cv * testcvs [NCVS]
static struct lock * testlocks [NCVS]
static struct semaphore * gatesem
static struct semaphore * exitsem
Macro Definition Documentation
NCVLOOPS
#define NCVLOOPS 5
Definition at line 43 of file synchtest.c.
NCVS
#define NCVS 250
Definition at line 310 of file synchtest.c.
NLOCKLOOPS
#define NLOCKLOOPS 120
Definition at line 42 of file synchtest.c.
NLOOPS
#define NLOOPS 40
Definition at line 311 of file synchtest.c.
NSEMLOOPS
#define NSEMLOOPS 63
Definition at line 41 of file synchtest.c.
NTHREADS
#define NTHREADS 32
Definition at line 44 of file synchtest.c.
Function Documentation
cvtest()
int cvtest (int nargs, char ** args)
Definition at line 270 of file synchtest.c.
References cvtestthread(), donesem, inititems(), kprintf(), NTHREADS, NULL, P(), panic(), strerror(), testval1, and thread_fork().
cvtest2()
int cvtest2 (int nargs, char ** args)
Definition at line 360 of file synchtest.c.
References cv_create(), cv_destroy(), exitsem, gatesem, kprintf(), lock_create(), lock_destroy(), NCVS, NULL, P(), panic(), sem_create(), sem_destroy(), sleepthread(), testcvs, testlocks, thread_fork(), and wakethread().
cvtestthread()
static void cvtestthread (void * junk, unsigned long num) static
Definition at line 225 of file synchtest.c.
References cv_broadcast(), cv_wait(), donesem, gettime(), kprintf(), lock_acquire(), lock_release(), NCVLOOPS, NTHREADS, num, testcv, testlock, testval1, thread_exit(), timespec_sub(), timespec::tv_nsec, timespec::tv_sec, and V().
Referenced by cvtest().
fail()
static void fail (unsigned long num, const char * msg) static
Definition at line 141 of file synchtest.c.
References donesem, kprintf(), lock_release(), test::msg, num, testlock, thread_exit(), and V().
Referenced by locktestthread(), sfs_fs_create(), vfs_doadd(), vfs_swapoff(), and vfs_unmount().
inititems()
static void inititems (void) static
Definition at line 56 of file synchtest.c.
References cv_create(), donesem, lock_create(), NULL, panic(), sem_create(), testcv, testlock, and testsem.
Referenced by cvtest(), locktest(), and semtest().
locktest()
int locktest (int nargs, char ** args)
Definition at line 196 of file synchtest.c.
References donesem, inititems(), kprintf(), locktestthread(), NTHREADS, NULL, P(), panic(), strerror(), and thread_fork().
locktestthread()
static void locktestthread (void * junk, unsigned long num) static
Definition at line 154 of file synchtest.c.
References donesem, fail(), lock_acquire(), lock_release(), NLOCKLOOPS, num, testlock, testval1, testval2, testval3, and V().
Referenced by locktest().
semtest()
int semtest (int nargs, char ** args)
Definition at line 104 of file synchtest.c.
References donesem, inititems(), kprintf(), NTHREADS, NULL, P(), panic(), semtestthread(), strerror(), testsem, thread_fork(), and V().
semtestthread()
static void semtestthread (void * junk, unsigned long num) static
Definition at line 86 of file synchtest.c.
References donesem, kprintf(), NSEMLOOPS, num, P(), testsem, and V().
Referenced by semtest().
sleepthread()
static void sleepthread (void * junk1, unsigned long junk2) static
Definition at line 319 of file synchtest.c.
References cv_wait(), exitsem, gatesem, kprintf(), lock_acquire(), lock_release(), NCVS, NLOOPS, testcvs, testlocks, and V().
Referenced by cvtest2().
wakethread()
static void wakethread (void * junk1, unsigned long junk2) static
Definition at line 340 of file synchtest.c.
References cv_signal(), exitsem, gatesem, kprintf(), lock_acquire(), lock_release(), NCVS, NLOOPS, P(), testcvs, testlocks, and V().
Referenced by cvtest2().
Variable Documentation
donesem
struct semaphore* donesem static
Definition at line 52 of file synchtest.c.
Referenced by cvtest(), cvtestthread(), fail(), inititems(), locktest(), locktestthread(), semtest(), and semtestthread().
exitsem
struct semaphore* exitsem static
Definition at line 315 of file synchtest.c.
Referenced by cvtest2(), sleepthread(), and wakethread().
gatesem
struct semaphore* gatesem static
Definition at line 314 of file synchtest.c.
Referenced by cvtest2(), sleepthread(), and wakethread().
testcv
struct cv* testcv static
Definition at line 51 of file synchtest.c.
Referenced by cvtestthread(), and inititems().
testcvs
struct cv* testcvs[NCVS] static
Definition at line 312 of file synchtest.c.
Referenced by cvtest2(), sleepthread(), and wakethread().
testlock
struct lock* testlock static
Definition at line 50 of file synchtest.c.
Referenced by cvtestthread(), fail(), inititems(), and locktestthread().
testlocks
struct lock* testlocks[NCVS] static
Definition at line 313 of file synchtest.c.
Referenced by cvtest2(), sleepthread(), and wakethread().
testsem
struct semaphore* testsem static
Definition at line 49 of file synchtest.c.
Referenced by inititems(), semtest(), and semtestthread().
testval1
volatile unsigned long testval1 static
Definition at line 46 of file synchtest.c.
Referenced by cvtest(), cvtestthread(), and locktestthread().
testval2
volatile unsigned long testval2 static
Definition at line 47 of file synchtest.c.
Referenced by locktestthread().
testval3
volatile unsigned long testval3 static
Definition at line 48 of file synchtest.c.
Referenced by locktestthread().