os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/syscall/time_syscalls.c File Reference
time_syscalls.c File Reference
#include <types.h>
#include <clock.h>
#include <copyinout.h>
#include <syscall.h>
Functions
int sys___time (userptr_t user_seconds_ptr, userptr_t user_nanoseconds_ptr)
Function Documentation
sys___time()
int sys___time (userptr_t user_seconds_ptr, userptr_t user_nanoseconds_ptr)
Definition at line 39 of file time_syscalls.c.
References copyout(), gettime(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by syscall().