os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/frack/check.h File Reference
check.h File Reference
Functions
int check_createfile (unsigned name)
int check_openfile (unsigned name)
void check_closefile (int handle, unsigned name)
void check_write (int handle, unsigned name, unsigned code, unsigned seq, off_t pos, off_t len)
void check_truncate (int handle, unsigned name, off_t len)
void check_mkdir (unsigned name)
void check_rmdir (unsigned name)
void check_unlink (unsigned name)
void check_link (unsigned from, unsigned to)
void check_rename (unsigned from, unsigned to)
void check_renamexd (unsigned fromdir, unsigned from, unsigned todir, unsigned to)
void check_chdir (unsigned name)
void check_chdirup (void)
void check_sync (void)
void check_setup (void)
void checkfs (void)
Function Documentation
check_chdir()
void check_chdir (unsigned name)
Definition at line 1833 of file check.c.
References cwd, model_finddir(), and name.
Referenced by op_chdir().
check_chdirup()
void check_chdirup (void)
Definition at line 1842 of file check.c.
References cwd, and model_findparent().
Referenced by op_chdirup().
check_closefile()
void check_closefile (int handle, unsigned name)
Definition at line 1635 of file check.c.
References name.
Referenced by op_close().
check_createfile()
int check_createfile (unsigned name)
Definition at line 1610 of file check.c.
References changes_findprevdir(), cwd, fc_attach(), fc_create_creat(), name, and nextfilenum.
Referenced by op_open().
check_link()
void check_link (unsigned from, unsigned to)
Definition at line 1733 of file check.c.
References changes_findprevdir(), changes_findprevfile(), cwd, fc_attach(), fc_create_link(), fschange::fromname, model_findfile(), and fschange::toname.
Referenced by op_link().
check_mkdir()
void check_mkdir (unsigned name)
Definition at line 1687 of file check.c.
References changes_findprevdir(), cwd, fc_attach(), fc_create_mkdir(), name, and nextdirnum.
Referenced by op_mkdir().
check_openfile()
int check_openfile (unsigned name)
Definition at line 1626 of file check.c.
References cwd, model_findfile(), and name.
Referenced by op_open().
check_rename()
void check_rename (unsigned from, unsigned to)
Definition at line 1809 of file check.c.
References common_rename(), and cwd.
Referenced by op_rename().
check_renamexd()
void check_renamexd (unsigned fromdir, unsigned from, unsigned todir, unsigned to)
Definition at line 1818 of file check.c.
References common_rename(), cwd, fschange::fromdir, model_finddir(), and fschange::todir.
Referenced by op_renamexd().
check_rmdir()
void check_rmdir (unsigned name)
Definition at line 1701 of file check.c.
References changes_findprevdir(), cwd, fc_attach(), fc_create_rmdir(), model_finddir(), and name.
Referenced by op_rmdir().
check_setup()
void check_setup (void)
Definition at line 1585 of file check.c.
References apply_change(), assert, changes, cwd, fc_create_newfs(), firstchange, nextdirnum, nextfilenum, NULL, rewindstate(), and state.
Referenced by setcheckmode().
check_sync()
void check_sync (void)
Definition at line 1851 of file check.c.
Referenced by op_sync().
check_truncate()
void check_truncate (int handle, unsigned name, off_t len)
Definition at line 1670 of file check.c.
References assert, changes_findprevfile(), fc_attach(), fc_create_truncate(), fschange::len, name, and nextfilenum.
Referenced by op_truncate().
check_unlink()
void check_unlink (unsigned name)
Definition at line 1717 of file check.c.
References changes_findprevdir(), changes_findprevfile(), cwd, fc_attach(), fc_create_unlink(), model_findfile(), and name.
Referenced by op_unlink().
check_write()
void check_write (int handle, unsigned name, unsigned code, unsigned seq, off_t pos, off_t len)
Definition at line 1648 of file check.c.
References assert, changes_findprevfile(), fschange::code, fc_attach(), fc_create_write(), fschange::len, model_getfilesize(), name, nextfilenum, pos, and fschange::seq.
Referenced by op_write().
checkfs()
void checkfs (void)
Definition at line 2808 of file check.c.
References advancestateto(), apply_change(), assert, changes, checkallfilecontents(), compare_objects(), FC_NEWFS, firstchange, found, found_files, found_subdirs, inspectfs(), fschange::next, nextdirnum, nextfilenum, NULL, fschange::partial, printdiffs(), printf(), rewindstate(), state, fschange::type, and fschange::version.
Referenced by complete().