os161-doc: /home/os161user/os161/os161-base-2.0.3/common/libc/string/strcat.c File Reference
strcat.c File Reference
#include <string.h>
Functions
char * strcat (char *dest, const char *src)
Function Documentation
strcat()
char* strcat (char * dest, const char * src)
Definition at line 47 of file strcat.c.
References strcpy(), and strlen().
Referenced by dir_test(), do_renamexd(), main(), mkfile(), mkrawname(), and vfs_setbootfs().