os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/common_buf.c File Reference
common_buf.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Data Structures
struct buftest
Macros
#define T(call)
Functions
static int read_setup (void)
static int read_badbuf (void *buf)
static void read_cleanup (void)
static int write_setup (void)
static int write_badbuf (void *ptr)
static void write_cleanup (void)
static int getdirentry_setup (void)
static int getdirentry_badbuf (void *ptr)
static void getdirentry_cleanup (void)
static int readlink_setup (void)
static int readlink_badbuf (void *buf)
static void readlink_cleanup (void)
static int getcwd_setup (void)
static void getcwd_cleanup (void)
static int getcwd_badbuf (void *buf)
static void common_badbuf (struct buftest *info, void *buf, const char *bufdesc)
static void any_badbuf (struct buftest *info)
T (read)
T (write)
T (getdirentry)
T (readlink)
T (getcwd)
Variables
static int buf_fd
Macro Definition Documentation
T
#define T (call)
Value:
  void                  \
  test_##call##_buf(void)       \
  {                 \
    static struct buftest info = {  \
        call##_setup,       \
        call##_badbuf,      \
        call##_cleanup,     \
        #call,          \
    };              \
    any_badbuf(&info);      \
  }
Definition at line 202 of file common_buf.c.
Function Documentation
any_badbuf()
static void any_badbuf (struct buftest * info) static
Definition at line 193 of file common_buf.c.
References common_badbuf(), and NULL.
common_badbuf()
static void common_badbuf (struct buftest * info, void * buf, const char * bufdesc) static
Definition at line 179 of file common_buf.c.
References buf, buftest::cleanup, EFAULT, errno, buftest::name, buftest::op, report_begin(), report_check(), and buftest::setup.
Referenced by any_badbuf().
getcwd_badbuf()
static int getcwd_badbuf (void * buf) static
Definition at line 170 of file common_buf.c.
References __getcwd(), and buf.
getcwd_cleanup()
static void getcwd_cleanup (void) static
Definition at line 166 of file common_buf.c.
getcwd_setup()
static int getcwd_setup (void) static
Definition at line 165 of file common_buf.c.
getdirentry_badbuf()
static int getdirentry_badbuf (void * ptr) static
Definition at line 128 of file common_buf.c.
References buf_fd, and getdirentry().
getdirentry_cleanup()
static void getdirentry_cleanup (void) static
Definition at line 135 of file common_buf.c.
References buf_fd, and close().
getdirentry_setup()
static int getdirentry_setup (void) static
Definition at line 116 of file common_buf.c.
References buf_fd, O_RDONLY, open(), and warn().
read_badbuf()
static int read_badbuf (void * buf) static
Definition at line 71 of file common_buf.c.
References buf, buf_fd, and read().
read_cleanup()
static void read_cleanup (void) static
Definition at line 78 of file common_buf.c.
References buf_fd, close(), remove(), and TESTFILE.
read_setup()
static int read_setup (void) static
Definition at line 60 of file common_buf.c.
References buf_fd, and open_testfile().
readlink_badbuf()
static int readlink_badbuf (void * buf) static
Definition at line 151 of file common_buf.c.
References buf, readlink(), and TESTLINK.
readlink_cleanup()
static void readlink_cleanup (void) static
Definition at line 158 of file common_buf.c.
References remove(), and TESTLINK.
readlink_setup()
static int readlink_setup (void) static
Definition at line 144 of file common_buf.c.
References create_testlink().
T() [1/5]
T (getcwd)
T() [2/5]
T (getdirentry)
T() [3/5]
T (read)
T() [4/5]
T (readlink)
T() [5/5]
T (write)
write_badbuf()
static int write_badbuf (void * ptr) static
Definition at line 99 of file common_buf.c.
References buf_fd, and write().
write_cleanup()
static void write_cleanup (void) static
Definition at line 106 of file common_buf.c.
References buf_fd, close(), remove(), and TESTFILE.
write_setup()
static int write_setup (void) static
Definition at line 88 of file common_buf.c.
References buf_fd, NULL, and open_testfile().
Variable Documentation
buf_fd
int buf_fd static
Definition at line 47 of file common_buf.c.
Referenced by getdirentry_badbuf(), getdirentry_cleanup(), getdirentry_setup(), read_badbuf(), read_cleanup(), read_setup(), write_badbuf(), write_cleanup(), and write_setup().