os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/syscall/loadelf.c File Reference
loadelf.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <uio.h>
#include <proc.h>
#include <current.h>
#include <addrspace.h>
#include <vnode.h>
#include <elf.h>
Functions
static int load_segment (struct addrspace *as, struct vnode *v, off_t offset, vaddr_t vaddr, size_t memsize, size_t filesize, int is_executable)
int load_elf (struct vnode *v, vaddr_t *entrypoint)
Function Documentation
load_elf()
int load_elf (struct vnode * v, vaddr_t * entrypoint)
Definition at line 154 of file loadelf.c.
References as_complete_load(), as_define_region(), as_prepare_load(), Elf32_Ehdr::e_entry, Elf32_Ehdr::e_ident, Elf32_Ehdr::e_machine, Elf32_Ehdr::e_phentsize, Elf32_Ehdr::e_phnum, Elf32_Ehdr::e_phoff, Elf32_Ehdr::e_type, Elf32_Ehdr::e_version, EI_CLASS, EI_DATA, EI_MAG0, EI_MAG1, EI_MAG2, EI_MAG3, EI_VERSION, ELFCLASS32, ELFDATA2MSB, ELFMAG0, ELFMAG1, ELFMAG2, ELFMAG3, EM_MACHINE, ENOEXEC, ET_EXEC, EV_CURRENT, kprintf(), load_segment(), Elf32_Phdr::p_filesz, Elf32_Phdr::p_flags, Elf32_Phdr::p_memsz, Elf32_Phdr::p_offset, Elf32_Phdr::p_type, Elf32_Phdr::p_vaddr, PF_R, PF_W, PF_X, proc_getas(), PT_LOAD, PT_MIPS_REGINFO, PT_NULL, PT_PHDR, uio_kinit(), UIO_READ, uio::uio_resid, and VOP_READ.
Referenced by runprogram().
load_segment()
static int load_segment (struct addrspace * as, struct vnode * v, off_t offset, vaddr_t vaddr, size_t memsize, size_t filesize, int is_executable) static
Definition at line 79 of file loadelf.c.
References DB_EXEC, DEBUG, ENOEXEC, iovec::iov_len, kprintf(), uio::uio_iov, uio::uio_iovcnt, uio::uio_offset, UIO_READ, uio::uio_resid, uio::uio_rw, uio::uio_segflg, uio::uio_space, UIO_USERISPACE, UIO_USERSPACE, uiomovezeros(), and VOP_READ.
Referenced by load_elf().