os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/fs/sfs/sfs_fsops.c File Reference
sfs_fsops.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <array.h>
#include <bitmap.h>
#include <uio.h>
#include <vfs.h>
#include <device.h>
#include <sfs.h>
#include "sfsprivate.h"
Macros
#define SFS_FS_NBLOCKS(sfs) ((sfs)->sfs_sb.sb_nblocks)
#define SFS_FS_FREEMAPBITS(sfs) SFS_FREEMAPBITS(SFS_FS_NBLOCKS(sfs))
#define SFS_FS_FREEMAPBLOCKS(sfs) SFS_FREEMAPBLOCKS(SFS_FS_NBLOCKS(sfs))
Functions
static int sfs_freemapio (struct sfs_fs *sfs, enum uio_rw rw)
static int sfs_sync_vnodes (struct sfs_fs *sfs)
static int sfs_sync_freemap (struct sfs_fs *sfs)
static int sfs_sync_superblock (struct sfs_fs *sfs)
static int sfs_sync (struct fs *fs)
static const char * sfs_getvolname (struct fs *fs)
static void sfs_fs_destroy (struct sfs_fs *sfs)
static int sfs_unmount (struct fs *fs)
static struct sfs_fs * sfs_fs_create (void)
static int sfs_domount (void *options, struct device *dev, struct fs **ret)
int sfs_mount (const char *device)
Variables
static const struct fs_ops sfs_fsops
Macro Definition Documentation
SFS_FS_FREEMAPBITS
#define SFS_FS_FREEMAPBITS (sfs) SFS_FREEMAPBITS(SFS_FS_NBLOCKS(sfs))
Definition at line 50 of file sfs_fsops.c.
SFS_FS_FREEMAPBLOCKS
#define SFS_FS_FREEMAPBLOCKS (sfs) SFS_FREEMAPBLOCKS(SFS_FS_NBLOCKS(sfs))
Definition at line 51 of file sfs_fsops.c.
SFS_FS_NBLOCKS
#define SFS_FS_NBLOCKS (sfs) ((sfs)->sfs_sb.sb_nblocks)
Definition at line 49 of file sfs_fsops.c.
Function Documentation
sfs_domount()
static int sfs_domount (void * options, struct device * dev, struct fs ** ret) static
Definition at line 386 of file sfs_fsops.c.
References bitmap_create(), device::d_blocks, device::d_blocksize, EINVAL, ENOMEM, ENXIO, kprintf(), NULL, sfs_superblock::sb_magic, sfs_superblock::sb_nblocks, sfs_superblock::sb_volname, sfs_fs::sfs_absfs, SFS_BLOCKSIZE, sfs_fs::sfs_device, sfs_fs::sfs_freemap, sfs_freemapio(), sfs_fs_create(), sfs_fs_destroy(), SFS_FS_FREEMAPBITS, SFS_MAGIC, sfs_readblock(), sfs_fs::sfs_sb, SFS_SUPER_BLOCK, UIO_READ, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by sfs_mount().
sfs_freemapio()
static int sfs_freemapio (struct sfs_fs * sfs, enum uio_rw rw) static
Definition at line 72 of file sfs_fsops.c.
References bitmap_getdata(), freemapdata, SFS_BLOCKSIZE, sfs_fs::sfs_freemap, SFS_FREEMAP_START, SFS_FS_FREEMAPBLOCKS, sfs_readblock(), sfs_writeblock(), and UIO_READ.
Referenced by sfs_domount(), and sfs_sync_freemap().
sfs_fs_create()
static struct sfs_fs* sfs_fs_create (void) static
Definition at line 321 of file sfs_fsops.c.
References COMPILE_ASSERT, fail(), fs::fs_data, fs::fs_ops, kfree(), kmalloc(), NULL, sfs_fs::sfs_absfs, SFS_BLOCKSIZE, sfs_fs::sfs_device, sfs_fs::sfs_freemap, sfs_fs::sfs_freemapdirty, sfs_fsops, sfs_fs::sfs_superdirty, and sfs_fs::sfs_vnodes.
Referenced by sfs_domount().
sfs_fs_destroy()
static void sfs_fs_destroy (struct sfs_fs * sfs) static
Definition at line 260 of file sfs_fsops.c.
References bitmap_destroy(), KASSERT, kfree(), NULL, sfs_fs::sfs_device, sfs_fs::sfs_freemap, and sfs_fs::sfs_vnodes.
Referenced by sfs_domount(), and sfs_unmount().
sfs_getvolname()
static const char* sfs_getvolname (struct fs * fs) static
Definition at line 243 of file sfs_fsops.c.
References fs::fs_data, sfs_superblock::sb_volname, sfs_fs::sfs_sb, vfs_biglock_acquire(), and vfs_biglock_release().
sfs_mount()
int sfs_mount (const char * device)
Definition at line 478 of file sfs_fsops.c.
References NULL, sfs_domount(), and vfs_mount().
sfs_sync()
static int sfs_sync (struct fs * fs) static
Definition at line 172 of file sfs_fsops.c.
References fs::fs_data, sfs_sync_freemap(), sfs_sync_superblock(), sfs_sync_vnodes(), vfs_biglock_acquire(), and vfs_biglock_release().
sfs_sync_freemap()
static int sfs_sync_freemap (struct sfs_fs * sfs) static
Definition at line 131 of file sfs_fsops.c.
References sfs_fs::sfs_freemapdirty, sfs_freemapio(), and UIO_WRITE.
Referenced by sfs_sync().
sfs_sync_superblock()
static int sfs_sync_superblock (struct sfs_fs * sfs) static
Definition at line 151 of file sfs_fsops.c.
References sfs_fs::sfs_sb, SFS_SUPER_BLOCK, sfs_fs::sfs_superdirty, and sfs_writeblock().
Referenced by sfs_sync().
sfs_sync_vnodes()
static int sfs_sync_vnodes (struct sfs_fs * sfs) static
Definition at line 113 of file sfs_fsops.c.
References num, sfs_fs::sfs_vnodes, and VOP_FSYNC.
Referenced by sfs_sync().
sfs_unmount()
static int sfs_unmount (struct fs * fs) static
Definition at line 277 of file sfs_fsops.c.
References EBUSY, fs::fs_data, KASSERT, NULL, sfs_fs::sfs_device, sfs_fs::sfs_freemapdirty, sfs_fs_destroy(), sfs_fs::sfs_superdirty, sfs_fs::sfs_vnodes, vfs_biglock_acquire(), and vfs_biglock_release().
Variable Documentation
sfs_fsops
const struct fs_ops sfs_fsops static
Initial value:
= {
    .fsop_sync = sfs_sync,
    .fsop_getvolname = sfs_getvolname,
    .fsop_getroot = sfs_getroot,
    .fsop_unmount = sfs_unmount,
}
Definition at line 307 of file sfs_fsops.c.
Referenced by sfs_fs_create().