os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/forktest/forktest.c File Reference
forktest.c File Reference
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <err.h>
Functions
static int dofork (void)
static void check (void)
static void dowait (int nowait, int pid)
static void test (int nowait)
int main (int argc, char *argv[])
Variables
static volatile int mypid
Function Documentation
check()
static void check (void) static
Definition at line 73 of file forktest.c.
References errx(), getpid(), and mypid.
Referenced by test().
dofork()
static int dofork (void) static
Definition at line 56 of file forktest.c.
References fork(), pid, and warn().
Referenced by test().
dowait()
static void dowait (int nowait, int pid) static
Definition at line 102 of file forktest.c.
References exit(), pid, waitpid(), warn(), warnx(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
Referenced by test().
main()
int main (int argc, char * argv[])
Definition at line 197 of file forktest.c.
References STDERR_FILENO, strcmp(), strlen(), test(), warnx(), and write().
test()
static void test (int nowait) static
Definition at line 133 of file forktest.c.
References check(), dofork(), dowait(), putchar(), and warnx().
Referenced by main().
Variable Documentation
mypid
volatile int mypid static
Definition at line 49 of file forktest.c.
Referenced by check(), wait_parent(), and wait_siblings_child().