os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/spinlock.h File Reference
spinlock.h File Reference
#include <cdefs.h>
#include <hangman.h>
#include <machine/spinlock.h>
Data Structures
struct spinlock
Macros
#define SPINLOCK_INLINE INLINE
#define SPINLOCK_INITIALIZER { SPINLOCK_DATA_INITIALIZER, NULL }
Functions
void spinlock_init (struct spinlock *lk)
void spinlock_cleanup (struct spinlock *lk)
void spinlock_acquire (struct spinlock *lk)
void spinlock_release (struct spinlock *lk)
bool spinlock_do_i_hold (struct spinlock *lk)
Macro Definition Documentation
SPINLOCK_INITIALIZER
#define SPINLOCK_INITIALIZER { SPINLOCK_DATA_INITIALIZER, NULL }
Definition at line 71 of file spinlock.h.
SPINLOCK_INLINE
#define SPINLOCK_INLINE INLINE
Definition at line 43 of file spinlock.h.
Function Documentation
spinlock_acquire()
void spinlock_acquire (struct spinlock * lk)
Definition at line 76 of file spinlock.c.
References cpu::c_self, cpu::c_spinlocks, HANGMAN_ACQUIRE, HANGMAN_WAIT, IPL_HIGH, IPL_NONE, membar_store_any(), NULL, panic(), spinlock_data_get(), spinlock_data_testandset(), spinlock::splk_holder, spinlock::splk_lock, and splraise().
Referenced by allocpagerefpage(), clocksleep(), do_semu1011(), emufs_reclaim(), getppages(), hangman_acquire(), hangman_release(), hangman_wait(), interprocessor_interrupt(), ipi_send(), ipi_tlbshootdown(), kheap_dump(), kheap_dumpall(), kheap_nextgeneration(), kheap_printstats(), kprintf(), lamebus_attach_interrupt(), lamebus_detach_interrupt(), lamebus_interrupt(), lamebus_mark(), lamebus_mask_interrupt(), lamebus_probe(), lamebus_unmark(), lamebus_unmask_interrupt(), lscreen_irq(), lscreen_write(), lser_irq(), lser_write(), lser_writepolled(), makewaiter(), P(), proc_addthread(), proc_create_runprogram(), proc_getas(), proc_remthread(), proc_setas(), semfs_reclaim(), semu1213(), semu16(), semu7(), sfs_reclaim(), sleepalot_thread(), subpage_kfree(), subpage_kmalloc(), thread_consider_migration(), thread_make_runnable(), thread_switch(), timerclock(), V(), vfs_clearcurdir(), vfs_getcurdir(), vfs_setcurdir(), vnode_check(), vnode_decref(), vnode_incref(), waiter(), waker_thread(), and wchan_sleep().
spinlock_cleanup()
void spinlock_cleanup (struct spinlock * lk)
Definition at line 62 of file spinlock.c.
References KASSERT, NULL, spinlock_data_get(), spinlock::splk_holder, and spinlock::splk_lock.
Referenced by proc_destroy(), sem_destroy(), semu16(), semu7(), and vnode_cleanup().
spinlock_do_i_hold()
bool spinlock_do_i_hold (struct spinlock * lk)
Definition at line 148 of file spinlock.c.
References cpu::c_self, and spinlock::splk_holder.
Referenced by lser_poll_until_write(), subpage_stats(), thread_make_runnable(), wchan_isempty(), wchan_sleep(), wchan_wakeall(), and wchan_wakeone().
spinlock_init()
void spinlock_init (struct spinlock * lk)
Definition at line 51 of file spinlock.c.
References HANGMAN_LOCKABLEINIT, NULL, spinlock_data_set(), spinlock::splk_holder, and spinlock::splk_lock.
Referenced by config_lscreen(), config_lser(), cpu_create(), hardclock_bootstrap(), kprintf_bootstrap(), lamebus_init(), proc_create(), sem_create(), semu16(), semu7(), setup(), and vnode_init().
spinlock_release()
void spinlock_release (struct spinlock * lk)
Definition at line 128 of file spinlock.c.
References cpu::c_self, HANGMAN_RELEASE, IPL_HIGH, IPL_NONE, KASSERT, membar_any_store(), NULL, spinlock_data_set(), spinlock::splk_holder, spinlock::splk_lock, and spllower().
Referenced by allocpagerefpage(), clocksleep(), do_semu1011(), emufs_reclaim(), getppages(), hangman_acquire(), hangman_check(), hangman_release(), hangman_wait(), interprocessor_interrupt(), ipi_send(), ipi_tlbshootdown(), kheap_dump(), kheap_dumpall(), kheap_nextgeneration(), kheap_printstats(), kprintf(), lamebus_attach_interrupt(), lamebus_detach_interrupt(), lamebus_interrupt(), lamebus_mark(), lamebus_mask_interrupt(), lamebus_probe(), lamebus_unmark(), lamebus_unmask_interrupt(), lscreen_irq(), lscreen_write(), lser_irq(), lser_write(), lser_writepolled(), makewaiter(), P(), proc_addthread(), proc_create_runprogram(), proc_getas(), proc_remthread(), proc_setas(), semfs_reclaim(), semu1213(), semu16(), semu7(), sfs_reclaim(), sleepalot_thread(), subpage_kfree(), subpage_kmalloc(), thread_consider_migration(), thread_make_runnable(), thread_startup(), thread_switch(), timerclock(), V(), vfs_clearcurdir(), vfs_getcurdir(), vfs_setcurdir(), vnode_check(), vnode_decref(), vnode_incref(), waiter(), and waker_thread().