os161-doc: /home/os161user/os161/os161-base-2.0.3/common/gcc-millicode/longlong.h File Reference
longlong.h File Reference
#include <sys/types.h>
#include <sys/endian.h>
#include <limits.h>
Data Structures
union uu
Macros
#define H 1
#define L 0
#define H 0
#define L 1
#define LONGLONG_BITS (sizeof(long long) * CHAR_BIT)
#define INT_BITS (sizeof(int) * CHAR_BIT)
#define HALF_BITS (sizeof(int) * CHAR_BIT / 2)
#define HHALF(x) ((unsigned int)(x) >> HALF_BITS)
#define LHALF(x) ((unsigned int)(x) & (((int)1 << HALF_BITS) - 1))
#define LHUP(x) ((unsigned int)(x) << HALF_BITS)
Functions
long long __adddi3 (long long, long long)
long long __anddi3 (long long, long long)
long long __ashldi3 (long long, unsigned int)
long long __ashrdi3 (long long, unsigned int)
int __cmpdi2 (long long, long long)
long long __divdi3 (long long, long long)
long long __iordi3 (long long, long long)
long long __lshldi3 (long long, unsigned int)
long long __lshrdi3 (long long, unsigned int)
long long __moddi3 (long long, long long)
long long __muldi3 (long long, long long)
long long __negdi2 (long long)
long long __one_cmpldi2 (long long)
long long __subdi3 (long long, long long)
int __ucmpdi2 (unsigned long long, unsigned long long)
unsigned long long __udivdi3 (unsigned long long, unsigned long long)
unsigned long long __umoddi3 (unsigned long long, unsigned long long)
long long __xordi3 (long long, long long)
long long __fixdfdi (double)
long long __fixsfdi (float)
unsigned long long __fixunsdfdi (double)
unsigned long long __fixunssfdi (float)
double __floatdidf (long long)
float __floatdisf (long long)
double __floatunsdidf (unsigned long long)
unsigned long long __qdivrem (unsigned long long, unsigned long long, unsigned long long *)
Macro Definition Documentation
H [1/2]
#define H 1
Definition at line 86 of file longlong.h.
H [2/2]
#define H 0
Definition at line 86 of file longlong.h.
HALF_BITS
#define HALF_BITS (sizeof(int) * CHAR_BIT / 2)
Definition at line 98 of file longlong.h.
HHALF
#define HHALF (x) ((unsigned int)(x) >> HALF_BITS)
Definition at line 110 of file longlong.h.
INT_BITS
#define INT_BITS (sizeof(int) * CHAR_BIT)
Definition at line 97 of file longlong.h.
L [1/2]
#define L 0
Definition at line 87 of file longlong.h.
L [2/2]
#define L 1
Definition at line 87 of file longlong.h.
LHALF
#define LHALF (x) ((unsigned int)(x) & (((int)1 << HALF_BITS) - 1))
Definition at line 111 of file longlong.h.
LHUP
#define LHUP (x) ((unsigned int)(x) << HALF_BITS)
Definition at line 112 of file longlong.h.
LONGLONG_BITS
#define LONGLONG_BITS (sizeof(long long) * CHAR_BIT)
Definition at line 96 of file longlong.h.
Function Documentation
__adddi3()
long long __adddi3 (long long , long long)
Definition at line 47 of file adddi3.c.
References H, L, uu::ll, sum(), and uu::ui.
__anddi3()
long long __anddi3 (long long , long long)
Definition at line 44 of file anddi3.c.
References uu::ll, and uu::ui.
__ashldi3()
long long __ashldi3 (long long , unsigned int)
Definition at line 45 of file ashldi3.c.
References H, INT_BITS, L, uu::ll, and uu::ui.
__ashrdi3()
long long __ashrdi3 (long long , unsigned int)
Definition at line 44 of file ashrdi3.c.
References H, INT_BITS, L, uu::ll, uu::si, and uu::ui.
__cmpdi2()
int __cmpdi2 (long long , long long)
Definition at line 46 of file cmpdi2.c.
References H, L, uu::ll, uu::si, and uu::ui.
__divdi3()
long long __divdi3 (long long , long long)
Definition at line 45 of file divdi3.c.
References __qdivrem(), and NULL.
__fixdfdi()
long long __fixdfdi (double)
__fixsfdi()
long long __fixsfdi (float)
__fixunsdfdi()
unsigned long long __fixunsdfdi (double)
__fixunssfdi()
unsigned long long __fixunssfdi (float)
__floatdidf()
double __floatdidf (long long)
__floatdisf()
float __floatdisf (long long)
__floatunsdidf()
double __floatunsdidf (unsigned long long)
__iordi3()
long long __iordi3 (long long , long long)
Definition at line 44 of file iordi3.c.
References uu::ll, and uu::ui.
__lshldi3()
long long __lshldi3 (long long , unsigned int)
Definition at line 45 of file lshldi3.c.
References H, INT_BITS, L, uu::ll, and uu::ui.
__lshrdi3()
long long __lshrdi3 (long long , unsigned int)
Definition at line 44 of file lshrdi3.c.
References H, INT_BITS, L, uu::ll, and uu::ui.
__moddi3()
long long __moddi3 (long long , long long)
Definition at line 46 of file moddi3.c.
References __qdivrem().
__muldi3()
long long __muldi3 (long long , long long)
Definition at line 100 of file muldi3.c.
References __lmulq(), H, L, uu::ll, u0, u1, uu::ui, v0, and v1.
__negdi2()
long long __negdi2 (long long)
Definition at line 44 of file negdi2.c.
References H, L, uu::ll, and uu::ui.
__one_cmpldi2()
long long __one_cmpldi2 (long long)
Definition at line 45 of file notdi2.c.
References uu::ll, and uu::ui.
__qdivrem()
unsigned long long __qdivrem (unsigned long long , unsigned long long , unsigned long long *)
Definition at line 68 of file qdivrem.c.
References B, COMBINE, H, HALF_BITS, HHALF, L, LHALF, uu::ll, shl(), uu::ui, uu::ull, and v1.
Referenced by __divdi3(), __moddi3(), __udivdi3(), and __umoddi3().
__subdi3()
long long __subdi3 (long long , long long)
Definition at line 46 of file subdi3.c.
References H, L, uu::ll, and uu::ui.
__ucmpdi2()
int __ucmpdi2 (unsigned long long , unsigned long long)
Definition at line 45 of file ucmpdi2.c.
References H, L, uu::ui, and uu::ull.
__udivdi3()
unsigned long long __udivdi3 (unsigned long long , unsigned long long)
Definition at line 44 of file udivdi3.c.
References __qdivrem(), and NULL.
__umoddi3()
unsigned long long __umoddi3 (unsigned long long , unsigned long long)
Definition at line 44 of file umoddi3.c.
References __qdivrem().
__xordi3()
long long __xordi3 (long long , long long)
Definition at line 44 of file xordi3.c.
References uu::ll, and uu::ui.