os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/vfs/device.c File Reference
device.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <stat.h>
#include <lib.h>
#include <uio.h>
#include <synch.h>
#include <vnode.h>
#include <device.h>
Functions
static int dev_eachopen (struct vnode *v, int flags)
static int dev_reclaim (struct vnode *v)
static int dev_tryseek (struct device *d, off_t pos)
static int dev_read (struct vnode *v, struct uio *uio)
static int dev_write (struct vnode *v, struct uio *uio)
static int dev_ioctl (struct vnode *v, int op, userptr_t data)
static int dev_stat (struct vnode *v, struct stat *statbuf)
static int dev_gettype (struct vnode *v, mode_t *ret)
static bool dev_isseekable (struct vnode *v)
static int null_fsync (struct vnode *v)
static int dev_mmap (struct vnode *v)
static int dev_truncate (struct vnode *v, off_t len)
static int dev_namefile (struct vnode *v, struct uio *uio)
static int dev_lookup (struct vnode *dir, char *pathname, struct vnode **result)
struct vnode * dev_create_vnode (struct device *dev)
void dev_uncreate_vnode (struct vnode *vn)
Variables
static const struct vnode_ops dev_vnode_ops
Function Documentation
dev_create_vnode()
struct vnode* dev_create_vnode (struct device * dev)
Definition at line 357 of file device.c.
References dev_vnode_ops, kmalloc(), NULL, panic(), strerror(), and vnode_init().
Referenced by vfs_doadd().
dev_eachopen()
static int dev_eachopen (struct vnode * v, int flags) static
Definition at line 53 of file device.c.
References DEVOP_EACHOPEN, EINVAL, O_APPEND, O_CREAT, O_EXCL, O_TRUNC, and vnode::vn_data.
dev_gettype()
static int dev_gettype (struct vnode * v, mode_t * ret) static
Definition at line 201 of file device.c.
References device::d_blocks, S_IFBLK, S_IFCHR, and vnode::vn_data.
dev_ioctl()
static int dev_ioctl (struct vnode * v, int op, userptr_t data) static
Definition at line 147 of file device.c.
References DEVOP_IOCTL, and vnode::vn_data.
dev_isseekable()
static bool dev_isseekable (struct vnode * v) static
Definition at line 218 of file device.c.
References device::d_blocks, and vnode::vn_data.
dev_lookup()
static int dev_lookup (struct vnode * dir, char * pathname, struct vnode ** result) static
Definition at line 306 of file device.c.
References ENOENT, strlen(), and VOP_INCREF.
dev_mmap()
static int dev_mmap (struct vnode * v) static
Definition at line 245 of file device.c.
References ENOSYS.
dev_namefile()
static int dev_namefile (struct vnode * v, struct uio * uio) static
Definition at line 278 of file device.c.
dev_read()
static int dev_read (struct vnode * v, struct uio * uio) static
Definition at line 109 of file device.c.
References dev_tryseek(), DEVOP_IO, KASSERT, uio::uio_offset, UIO_READ, uio::uio_rw, and vnode::vn_data.
dev_reclaim()
static int dev_reclaim (struct vnode * v) static
Definition at line 70 of file device.c.
dev_stat()
static int dev_stat (struct vnode * v, struct stat * statbuf) static
Definition at line 160 of file device.c.
References bzero(), device::d_blocks, device::d_blocksize, device::d_devnumber, stat::st_blksize, stat::st_blocks, stat::st_dev, stat::st_mode, stat::st_nlink, stat::st_rdev, stat::st_size, vnode::vn_data, and VOP_GETTYPE.
dev_truncate()
static int dev_truncate (struct vnode * v, off_t len) static
Definition at line 256 of file device.c.
References device::d_blocks, device::d_blocksize, EINVAL, and vnode::vn_data.
dev_tryseek()
static int dev_tryseek (struct device * d, off_t pos) static
Definition at line 86 of file device.c.
References device::d_blocks, device::d_blocksize, EINVAL, and pos.
Referenced by dev_read(), and dev_write().
dev_uncreate_vnode()
void dev_uncreate_vnode (struct vnode * vn)
Definition at line 383 of file device.c.
References dev_vnode_ops, KASSERT, kfree(), vnode::vn_ops, and vnode_cleanup().
Referenced by vfs_doadd().
dev_write()
static int dev_write (struct vnode * v, struct uio * uio) static
Definition at line 128 of file device.c.
References dev_tryseek(), DEVOP_IO, KASSERT, uio::uio_offset, uio::uio_rw, UIO_WRITE, and vnode::vn_data.
null_fsync()
static int null_fsync (struct vnode * v) static
Definition at line 233 of file device.c.
Variable Documentation
dev_vnode_ops
const struct vnode_ops dev_vnode_ops static
Initial value:
= {
    .vop_magic = VOP_MAGIC,
    .vop_eachopen = dev_eachopen,
    .vop_reclaim = dev_reclaim,
    .vop_read = dev_read,
    .vop_readlink = vopfail_uio_inval,
    .vop_getdirentry = vopfail_uio_notdir,
    .vop_write = dev_write,
    .vop_ioctl = dev_ioctl,
    .vop_stat = dev_stat,
    .vop_gettype = dev_gettype,
    .vop_isseekable = dev_isseekable,
    .vop_fsync = null_fsync,
    .vop_mmap = dev_mmap,
    .vop_truncate = dev_truncate,
    .vop_namefile = dev_namefile,
    .vop_creat = vopfail_creat_notdir,
    .vop_symlink = vopfail_symlink_notdir,
    .vop_mkdir = vopfail_mkdir_notdir,
    .vop_link = vopfail_link_notdir,
    .vop_remove = vopfail_string_notdir,
    .vop_rmdir = vopfail_string_notdir,
    .vop_rename = vopfail_rename_notdir,
    .vop_lookup = dev_lookup,
    .vop_lookparent = vopfail_lookparent_notdir,
}
Definition at line 325 of file device.c.
Referenced by dev_create_vnode(), and dev_uncreate_vnode().