os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/compile/DUMBVM/autoconf.h File Reference
autoconf.h File Reference
Functions
void autoconf_lamebus (struct lamebus_softc *dev, int unit)
struct emu_softc * attach_emu_to_lamebus (int devunit, struct lamebus_softc *bus)
struct ltrace_softc * attach_ltrace_to_lamebus (int devunit, struct lamebus_softc *bus)
struct ltimer_softc * attach_ltimer_to_lamebus (int devunit, struct lamebus_softc *bus)
struct lrandom_softc * attach_lrandom_to_lamebus (int devunit, struct lamebus_softc *bus)
struct lhd_softc * attach_lhd_to_lamebus (int devunit, struct lamebus_softc *bus)
struct lser_softc * attach_lser_to_lamebus (int devunit, struct lamebus_softc *bus)
struct beep_softc * attach_beep_to_ltimer (int devunit, struct ltimer_softc *bus)
struct con_softc * attach_con_to_lser (int devunit, struct lser_softc *bus)
struct rtclock_softc * attach_rtclock_to_ltimer (int devunit, struct ltimer_softc *bus)
struct random_softc * attach_random_to_lrandom (int devunit, struct lrandom_softc *bus)
int config_emu (struct emu_softc *dev, int unit)
int config_ltrace (struct ltrace_softc *dev, int unit)
int config_ltimer (struct ltimer_softc *dev, int unit)
int config_lrandom (struct lrandom_softc *dev, int unit)
int config_lhd (struct lhd_softc *dev, int unit)
int config_lser (struct lser_softc *dev, int unit)
int config_beep (struct beep_softc *dev, int unit)
int config_con (struct con_softc *dev, int unit)
int config_rtclock (struct rtclock_softc *dev, int unit)
int config_random (struct random_softc *dev, int unit)
void pseudoconfig (void)
Function Documentation
attach_beep_to_ltimer()
struct beep_softc* attach_beep_to_ltimer (int devunit, struct ltimer_softc * bus)
Definition at line 42 of file beep_ltimer.c.
References beep_softc::bs_beep, beep_softc::bs_devdata, kmalloc(), ltimer_beep(), and NULL.
Referenced by tryattach_beep_to_ltimer().
attach_con_to_lser()
struct con_softc* attach_con_to_lser (int devunit, struct lser_softc * bus)
Definition at line 42 of file con_lser.c.
References con_input(), con_start(), con_softc::cs_devdata, con_softc::cs_send, con_softc::cs_sendpolled, kmalloc(), lser_softc::ls_devdata, lser_softc::ls_input, lser_softc::ls_start, lser_write(), lser_writepolled(), and NULL.
Referenced by tryattach_con_to_lser().
attach_emu_to_lamebus()
struct emu_softc* attach_emu_to_lamebus (int devunit, struct lamebus_softc * bus)
Definition at line 44 of file emu_att.c.
References emu_softc::e_busdata, emu_softc::e_buspos, emu_softc::e_unit, emu_irq(), kmalloc(), lamebus_attach_interrupt(), lamebus_mark(), lamebus_probe(), LB_VENDOR_CS161, LBCS161_EMUFS, LOW_VERSION, and NULL.
Referenced by tryattach_emu_to_lamebus().
attach_lhd_to_lamebus()
struct lhd_softc* attach_lhd_to_lamebus (int devunit, struct lamebus_softc * bus)
Definition at line 43 of file lhd_att.c.
References kmalloc(), lamebus_attach_interrupt(), lamebus_mark(), lamebus_probe(), LB_VENDOR_CS161, LBCS161_DISK, lhd_softc::lh_busdata, lhd_softc::lh_buspos, lhd_softc::lh_unit, lhd_irq(), LOW_VERSION, and NULL.
Referenced by tryattach_lhd_to_lamebus().
attach_lrandom_to_lamebus()
struct lrandom_softc* attach_lrandom_to_lamebus (int devunit, struct lamebus_softc * bus)
Definition at line 40 of file lrandom_att.c.
References kmalloc(), lamebus_mark(), lamebus_probe(), LB_VENDOR_CS161, LBCS161_RANDOM, LOW_VERSION, lrandom_softc::lr_bus, lrandom_softc::lr_buspos, and NULL.
Referenced by tryattach_lrandom_to_lamebus().
attach_lser_to_lamebus()
struct lser_softc* attach_lser_to_lamebus (int devunit, struct lamebus_softc * bus)
Definition at line 40 of file lser_att.c.
References kmalloc(), lamebus_attach_interrupt(), lamebus_mark(), lamebus_probe(), LB_VENDOR_CS161, LBCS161_SERIAL, LOW_VERSION, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_irq(), and NULL.
Referenced by tryattach_lser_to_lamebus().
attach_ltimer_to_lamebus()
struct ltimer_softc* attach_ltimer_to_lamebus (int devunit, struct lamebus_softc * bus)
Definition at line 43 of file ltimer_att.c.
References kmalloc(), lamebus_attach_interrupt(), lamebus_mark(), lamebus_probe(), LB_VENDOR_CS161, LBCS161_TIMER, LOW_VERSION, ltimer_softc::lt_bus, ltimer_softc::lt_buspos, ltimer_irq(), and NULL.
Referenced by tryattach_ltimer_to_lamebus().
attach_ltrace_to_lamebus()
struct ltrace_softc* attach_ltrace_to_lamebus (int devunit, struct lamebus_softc * bus)
Definition at line 44 of file ltrace_att.c.
References kmalloc(), lamebus_mark(), lamebus_probe(), LB_VENDOR_CS161, LBCS161_TRACE, LOW_VERSION, ltrace_softc::lt_busdata, ltrace_softc::lt_buspos, ltrace_softc::lt_canprof, ltrace_softc::lt_canstop, NULL, PROF_VERSION, and STOP_VERSION.
Referenced by tryattach_ltrace_to_lamebus().
attach_random_to_lrandom()
struct random_softc* attach_random_to_lrandom (int devunit, struct lrandom_softc * bus)
Definition at line 42 of file random_lrandom.c.
References kmalloc(), lrandom_randmax(), lrandom_random(), lrandom_read(), NULL, random_softc::rs_devdata, random_softc::rs_randmax, random_softc::rs_random, and random_softc::rs_read.
Referenced by tryattach_random_to_lrandom().
attach_rtclock_to_ltimer()
struct rtclock_softc* attach_rtclock_to_ltimer (int devunit, struct ltimer_softc * bus)
Definition at line 48 of file rtclock_ltimer.c.
References kmalloc(), ltimer_gettime(), NULL, rtclock_softc::rtc_devdata, and rtclock_softc::rtc_gettime.
Referenced by tryattach_rtclock_to_ltimer().
autoconf_lamebus()
void autoconf_lamebus (struct lamebus_softc * dev, int unit)
Definition at line 316 of file autoconf.c.
References nextunit_emu, nextunit_lhd, nextunit_lrandom, nextunit_lser, nextunit_ltimer, nextunit_ltrace, tryattach_emu_to_lamebus(), tryattach_lhd_to_lamebus(), tryattach_lrandom_to_lamebus(), tryattach_lser_to_lamebus(), tryattach_ltimer_to_lamebus(), and tryattach_ltrace_to_lamebus().
Referenced by mainbus_bootstrap().
config_beep()
int config_beep (struct beep_softc * dev, int unit)
Definition at line 50 of file beep.c.
References ENODEV, KASSERT, NULL, and the_beep.
Referenced by tryattach_beep_to_ltimer().
config_con()
int config_con (struct con_softc * dev, int unit)
Definition at line 344 of file console.c.
References attach_console_to_vfs(), con_userlock_read, con_userlock_write, con_softc::cs_gotchars_head, con_softc::cs_gotchars_tail, con_softc::cs_rsem, con_softc::cs_wsem, ENODEV, ENOMEM, flush_delay_buf(), KASSERT, lock_create(), lock_destroy(), NULL, sem_create(), sem_destroy(), and the_console.
Referenced by tryattach_con_to_lser().
config_emu()
int config_emu (struct emu_softc * dev, int unit)
Definition at line 1338 of file emu.c.
References bus_map_area, emu_softc::e_busdata, emu_softc::e_buspos, emu_softc::e_iobuf, emu_softc::e_lock, emu_softc::e_sem, EMU_BUFFER, emufs_addtovfs(), ENOMEM, lock_create(), lock_destroy(), name, NULL, sem_create(), and snprintf().
Referenced by tryattach_emu_to_lamebus().
config_lhd()
int config_lhd (struct lhd_softc * dev, int unit)
Definition at line 277 of file lhd.c.
References bus_map_area, bus_read_register, device::d_blocks, device::d_blocksize, device::d_data, device::d_ops, ENOMEM, lhd_softc::lh_buf, lhd_softc::lh_busdata, lhd_softc::lh_buspos, lhd_softc::lh_clear, lhd_softc::lh_dev, lhd_softc::lh_done, LHD_BUFFER, lhd_devops, LHD_REG_NSECT, LHD_SECTSIZE, name, NULL, sem_create(), sem_destroy(), snprintf(), and vfs_adddev().
Referenced by tryattach_lhd_to_lamebus().
config_lrandom()
int config_lrandom (struct lrandom_softc * dev, int unit)
Definition at line 47 of file lrandom.c.
Referenced by tryattach_lrandom_to_lamebus().
config_lser()
int config_lser (struct lser_softc * dev, int unit)
Definition at line 175 of file lser.c.
References bus_write_register, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_lock, lser_softc::ls_wbusy, LSER_IRQ_ENABLE, LSER_REG_RIRQ, LSER_REG_WIRQ, and spinlock_init().
Referenced by tryattach_lser_to_lamebus().
config_ltimer()
int config_ltimer (struct ltimer_softc * dev, int unit)
Definition at line 58 of file ltimer.c.
References bus_write_register, havetimerclock, ltimer_softc::lt_bus, ltimer_softc::lt_buspos, LT_GRANULARITY, ltimer_softc::lt_hardclock, LT_REG_COUNT, LT_REG_ROE, and ltimer_softc::lt_timerclock.
Referenced by tryattach_ltimer_to_lamebus().
config_ltrace()
int config_ltrace (struct ltrace_softc * dev, int unit)
Definition at line 111 of file ltrace.c.
References the_trace.
Referenced by tryattach_ltrace_to_lamebus().
config_random()
int config_random (struct random_softc * dev, int unit)
Definition at line 111 of file random.c.
References device::d_blocks, device::d_blocksize, device::d_data, device::d_ops, ENODEV, KASSERT, NULL, random_devops, random_softc::rs_dev, the_random, and vfs_adddev().
Referenced by tryattach_random_to_lrandom().
config_rtclock()
int config_rtclock (struct rtclock_softc * dev, int unit)
Definition at line 53 of file rtclock.c.
References ENODEV, KASSERT, NULL, and the_clock.
Referenced by tryattach_rtclock_to_ltimer().
pseudoconfig()
void pseudoconfig (void)
Definition at line 407 of file autoconf.c.
Referenced by boot().