os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/sfsck/freemap.h File Reference
freemap.h File Reference
#include <stdint.h>
Enumerations
enum blockusage_t {
B_SUPERBLOCK, B_FREEMAPBLOCK, B_INODE, B_IBLOCK,
B_DIRDATA, B_DATA, B_PASTEND
}
Functions
void freemap_setup (void)
void freemap_blockinuse (uint32_t block, blockusage_t how, uint32_t howdesc)
void freemap_blockfree (uint32_t block)
void freemap_check (void)
unsigned long freemap_blocksused (void)
Enumeration Type Documentation
blockusage_t
enum blockusage_t
Enumerator
B_SUPERBLOCK
B_FREEMAPBLOCK
B_INODE
B_IBLOCK
B_DIRDATA
B_DATA
B_PASTEND
Definition at line 41 of file freemap.h.
Function Documentation
freemap_blockfree()
void freemap_blockfree (uint32_t block)
Definition at line 162 of file freemap.c.
References freemapdata, and tofreedata.
Referenced by check_indirect_block(), and check_inode_blocks().
freemap_blockinuse()
void freemap_blockinuse (uint32_t block, blockusage_t how, uint32_t howdesc)
Definition at line 127 of file freemap.c.
References B_PASTEND, blocksinuse, blockusagestr(), EXIT_UNRECOV, freemapdata, setbadness(), tofreedata, and warnx().
Referenced by check_indirect_block(), check_inode_blocks(), freemap_setup(), and pass1_inode().
freemap_blocksused()
unsigned long freemap_blocksused (void)
Definition at line 307 of file freemap.c.
References blocksinuse.
Referenced by main().
freemap_check()
void freemap_check (void)
Definition at line 225 of file freemap.c.
References assert, countbits(), EXIT_RECOV, freemapdata, reportfreemap(), sb_freemapblocks(), setbadness(), SFS_BLOCKSIZE, sfs_readfreemapblock(), sfs_writefreemapblock(), tofreedata, and warnx().
Referenced by main().
freemap_setup()
void freemap_setup (void)
Definition at line 56 of file freemap.c.
References B_FREEMAPBLOCK, B_PASTEND, B_SUPERBLOCK, domalloc(), freemap_blockinuse(), freemapdata, sb_freemapblocks(), sb_totalblocks(), SFS_BITSPERBLOCK, SFS_BLOCKSIZE, SFS_FREEMAP_START, SFS_SUPER_BLOCK, and tofreedata.
Referenced by main().