os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/sfsck/inode.h File Reference
inode.h File Reference
Functions
int inode_add (uint32_t ino, int type)
void inode_sorttable (void)
int inode_visitdir (uint32_t ino)
void inode_addlink (uint32_t ino)
void inode_adjust_filelinks (void)
Function Documentation
inode_add()
int inode_add (uint32_t ino, int type)
Definition at line 177 of file inode.c.
References assert, inodeinfo::ino, inode_addtable(), inodes, inodeinfo::linkcount, ninodes, and inodeinfo::type.
Referenced by pass1_inode().
inode_addlink()
void inode_addlink (uint32_t ino)
Definition at line 222 of file inode.c.
References assert, inodeinfo::ino, inode_find(), inodeinfo::linkcount, SFS_TYPE_FILE, inodeinfo::type, and inodeinfo::visited.
Referenced by pass2_dir().
inode_adjust_filelinks()
void inode_adjust_filelinks (void)
Definition at line 237 of file inode.c.
References assert, EXIT_RECOV, inodes, inodeinfo::linkcount, ninodes, setbadness(), sfs_dinode::sfi_linkcount, sfs_dinode::sfi_type, sfs_readinode(), SFS_TYPE_DIR, SFS_TYPE_FILE, sfs_writeinode(), and warnx().
Referenced by main().
inode_sorttable()
void inode_sorttable (void)
Definition at line 120 of file inode.c.
References inode_compare(), inodes, inodes_sorted, ninodes, and qsort().
Referenced by main().
inode_visitdir()
int inode_visitdir (uint32_t ino)
Definition at line 202 of file inode.c.
References assert, inodeinfo::ino, inode_find(), inodeinfo::linkcount, SFS_TYPE_DIR, inodeinfo::type, and inodeinfo::visited.
Referenced by pass2_dir().