os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/ctest/ctest.c File Reference
ctest.c File Reference
#include <stdio.h>
#include <stdlib.h>
Data Structures
struct entry
Macros
#define SIZE (1024*1024/sizeof(struct entry))
#define DEFAULT 477
Functions
int main (int argc, char **argv)
Variables
struct entry array [SIZE]
Macro Definition Documentation
DEFAULT
#define DEFAULT 477
Definition at line 48 of file ctest.c.
SIZE
#define SIZE (1024*1024/sizeof(struct entry))
Definition at line 47 of file ctest.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 57 of file ctest.c.
References atoi(), DEFAULT, entry::e, printf(), putchar(), and SIZE.
Variable Documentation
array
struct entry array[SIZE]
Definition at line 54 of file ctest.c.