os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/clock.h File Reference
clock.h File Reference
#include <kern/time.h>
Macros
#define HZ 100
Functions
void hardclock_bootstrap (void)
void hardclock (void)
void timerclock (void)
void gettime (struct timespec *ret)
void timespec_add (const struct timespec *t1, const struct timespec *t2, struct timespec *ret)
void timespec_sub (const struct timespec *t1, const struct timespec *t2, struct timespec *ret)
void clocksleep (int seconds)
Macro Definition Documentation
HZ
#define HZ 100
Definition at line 46 of file clock.h.
Function Documentation
clocksleep()
void clocksleep (int seconds)
Definition at line 113 of file clock.c.
References lbolt, lbolt_lock, spinlock_acquire(), spinlock_release(), and wchan_sleep().
Referenced by do_semu1011(), makewaiter(), semu1213(), semu17(), and semu19_sub().
gettime()
void gettime (struct timespec * ret)
Definition at line 66 of file rtclock.c.
References KASSERT, NULL, rtclock_softc::rtc_devdata, rtclock_softc::rtc_gettime, and the_clock.
Referenced by cmd_dispatch(), cvtestthread(), and sys___time().
hardclock()
void hardclock (void)
Definition at line 93 of file clock.c.
References MIGRATE_HARDCLOCKS, schedule(), SCHEDULE_HARDCLOCKS, thread_consider_migration(), and thread_yield().
Referenced by ltimer_irq(), and mainbus_interrupt().
hardclock_bootstrap()
void hardclock_bootstrap (void)
Definition at line 66 of file clock.c.
References lbolt, lbolt_lock, NULL, panic(), spinlock_init(), and wchan_create().
Referenced by boot().
timerclock()
void timerclock (void)
Definition at line 80 of file clock.c.
References lbolt, lbolt_lock, spinlock_acquire(), spinlock_release(), and wchan_wakeall().
Referenced by ltimer_irq().
timespec_add()
void timespec_add (const struct timespec * t1, const struct timespec * t2, struct timespec * ret)
Definition at line 37 of file time.c.
References timespec::tv_nsec, and timespec::tv_sec.
timespec_sub()
void timespec_sub (const struct timespec * t1, const struct timespec * t2, struct timespec * ret)
Definition at line 53 of file time.c.
References timespec::tv_nsec, and timespec::tv_sec.
Referenced by cmd_dispatch(), and cvtestthread().