os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/sfsck/pass1.c File Reference
pass1.c File Reference
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <err.h>
#include "compat.h"
#include <kern/sfs.h>
#include "disk.h"
#include "utils.h"
#include "ibmacros.h"
#include "sfs.h"
#include "sb.h"
#include "freemap.h"
#include "inode.h"
#include "passes.h"
#include "main.h"
Data Structures
struct ibstate
Functions
static void check_indirect_block (struct ibstate *ibs, uint32_t *ientry, int *iechangedp, int indirection)
static int check_inode_blocks (uint32_t ino, struct sfs_dinode *sfi, int isdir)
static int pass1_inode (uint32_t ino, struct sfs_dinode *sfi, int alreadychanged)
static int pass1_direntry (const char *path, uint32_t index, struct sfs_direntry *sfd)
static void pass1_dir (uint32_t ino, const char *pathsofar)
static void pass1_rootdir (void)
void pass1 (void)
unsigned long pass1_founddirs (void)
unsigned long pass1_foundfiles (void)
Variables
static unsigned long count_dirs =0
static unsigned long count_files =0
Function Documentation
check_indirect_block()
static void check_indirect_block (struct ibstate * ibs, uint32_t * ientry, int * iechangedp, int indirection) static
Definition at line 81 of file pass1.c.
References assert, B_IBLOCK, ibstate::curfileblock, EXIT_RECOV, ibstate::fileblocks, freemap_blockfree(), freemap_blockinuse(), ibstate::ino, ibstate::pasteofcount, setbadness(), SFS_DBPERIDB, sfs_readindirect(), sfs_writeindirect(), ibstate::usagetype, ibstate::volblocks, and warnx().
Referenced by check_inode_blocks().
check_inode_blocks()
static int check_inode_blocks (uint32_t ino, struct sfs_dinode * sfi, int isdir) static
Definition at line 185 of file pass1.c.
References B_DATA, B_DIRDATA, check_indirect_block(), ibstate::curfileblock, EXIT_RECOV, ibstate::fileblocks, freemap_blockfree(), freemap_blockinuse(), GET_D, ibstate::ino, isdir(), NUM_D, NUM_I, NUM_II, NUM_III, ibstate::pasteofcount, sb_totalblocks(), SET_D, SET_I, SET_II, SET_III, setbadness(), sfs_dinode::sfi_size, SFS_BLOCKSIZE, SFS_ROUNDUP, ibstate::usagetype, ibstate::volblocks, and warnx().
Referenced by pass1_inode().
pass1()
void pass1 (void)
Definition at line 481 of file pass1.c.
References pass1_rootdir().
Referenced by main().
pass1_dir()
static void pass1_dir (uint32_t ino, const char * pathsofar) static
Definition at line 360 of file pass1.c.
References count_dirs, count_files, domalloc(), EXIT_RECOV, free(), pass1_direntry(), pass1_inode(), setbadness(), sfs_direntry::sfd_ino, sfs_direntry::sfd_name, sfs_dinode::sfi_size, sfs_dinode::sfi_type, SFS_NAMELEN, SFS_NOINO, sfs_readdir(), sfs_readinode(), SFS_ROUNDUP, SFS_TYPE_DIR, SFS_TYPE_FILE, sfs_writedir(), snprintf(), strcmp(), strlen(), and warnx().
Referenced by pass1_rootdir().
pass1_direntry()
static int pass1_direntry (const char * path, uint32_t index, struct sfs_direntry * sfd) static
Definition at line 296 of file pass1.c.
References checkbadstring(), checknullstring(), EXIT_RECOV, nblocks, sb_totalblocks(), setbadness(), sfs_direntry::sfd_ino, sfs_direntry::sfd_name, SFS_NOINO, snprintf(), uniqueid(), and warnx().
Referenced by pass1_dir().
pass1_founddirs()
unsigned long pass1_founddirs (void)
Definition at line 487 of file pass1.c.
References count_dirs.
Referenced by main().
pass1_foundfiles()
unsigned long pass1_foundfiles (void)
Definition at line 493 of file pass1.c.
References count_files.
Referenced by main().
pass1_inode()
static int pass1_inode (uint32_t ino, struct sfs_dinode * sfi, int alreadychanged) static
Definition at line 260 of file pass1.c.
References assert, B_INODE, check_inode_blocks(), checkzeroed(), EXIT_RECOV, freemap_blockinuse(), ibstate::ino, inode_add(), isdir(), setbadness(), sfs_dinode::sfi_type, sfs_dinode::sfi_waste, SFS_TYPE_DIR, sfs_writeinode(), and warnx().
Referenced by pass1_dir().
pass1_rootdir()
static void pass1_rootdir (void) static
Definition at line 450 of file pass1.c.
References EXIT_RECOV, pass1_dir(), sb_volname(), setbadness(), sfs_dinode::sfi_type, sfs_readinode(), SFS_ROOTDIR_INO, SFS_TYPE_DIR, SFS_TYPE_FILE, SFS_VOLNAME_SIZE, sfs_writeinode(), snprintf(), and warnx().
Referenced by pass1().
Variable Documentation
count_dirs
unsigned long count_dirs =0 static
Definition at line 50 of file pass1.c.
Referenced by pass1_dir(), and pass1_founddirs().
count_files
unsigned long count_files =0 static
Definition at line 50 of file pass1.c.
Referenced by pass1_dir(), and pass1_foundfiles().