os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/arch/mips/include/vm.h File Reference
vm.h File Reference
Data Structures
struct tlbshootdown
Macros
#define PAGE_SIZE 4096 /* size of VM page */
#define PAGE_FRAME 0xfffff000 /* mask for getting page number from addr */
#define MIPS_KUSEG 0x00000000
#define MIPS_KSEG0 0x80000000
#define MIPS_KSEG1 0xa0000000
#define MIPS_KSEG2 0xc0000000
#define PADDR_TO_KVADDR(paddr) ((paddr)+MIPS_KSEG0)
#define USERSPACETOP MIPS_KSEG0
#define USERSTACK USERSPACETOP
#define TLBSHOOTDOWN_MAX 16
Functions
void ram_bootstrap (void)
paddr_t ram_stealmem (unsigned long npages)
paddr_t ram_getsize (void)
paddr_t ram_getfirstfree (void)
Macro Definition Documentation
MIPS_KSEG0
#define MIPS_KSEG0 0x80000000
Definition at line 52 of file vm.h.
MIPS_KSEG1
#define MIPS_KSEG1 0xa0000000
Definition at line 53 of file vm.h.
MIPS_KSEG2
#define MIPS_KSEG2 0xc0000000
Definition at line 54 of file vm.h.
MIPS_KUSEG
#define MIPS_KUSEG 0x00000000
Definition at line 51 of file vm.h.
PADDR_TO_KVADDR
#define PADDR_TO_KVADDR (paddr) ((paddr)+MIPS_KSEG0)
Definition at line 68 of file vm.h.
PAGE_FRAME
#define PAGE_FRAME 0xfffff000 /* mask for getting page number from addr */
Definition at line 39 of file vm.h.
PAGE_SIZE
#define PAGE_SIZE 4096 /* size of VM page */
Definition at line 38 of file vm.h.
TLBSHOOTDOWN_MAX
#define TLBSHOOTDOWN_MAX 16
Definition at line 126 of file vm.h.
USERSPACETOP
#define USERSPACETOP MIPS_KSEG0
Definition at line 74 of file vm.h.
USERSTACK
#define USERSTACK USERSPACETOP
Definition at line 84 of file vm.h.
Function Documentation
ram_bootstrap()
void ram_bootstrap (void)
Definition at line 46 of file ram.c.
References firstfree, firstpaddr, kprintf(), lastpaddr, mainbus_ramsize(), and MIPS_KSEG0.
Referenced by boot().
ram_getfirstfree()
paddr_t ram_getfirstfree (void)
Definition at line 146 of file ram.c.
References firstpaddr, and lastpaddr.
ram_getsize()
paddr_t ram_getsize (void)
Definition at line 128 of file ram.c.
References lastpaddr.
ram_stealmem()
paddr_t ram_stealmem (unsigned long npages)
Definition at line 95 of file ram.c.
References firstpaddr, lastpaddr, and PAGE_SIZE.
Referenced by getppages().