os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/vfs/vfscwd.c File Reference
vfscwd.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <stat.h>
#include <lib.h>
#include <uio.h>
#include <proc.h>
#include <current.h>
#include <vfs.h>
#include <fs.h>
#include <vnode.h>
Functions
int vfs_getcurdir (struct vnode **ret)
int vfs_setcurdir (struct vnode *dir)
int vfs_clearcurdir (void)
int vfs_chdir (char *path)
int vfs_getcwd (struct uio *uio)
Function Documentation
vfs_chdir()
int vfs_chdir (char * path)
Definition at line 124 of file vfscwd.c.
References vfs_lookup(), vfs_setcurdir(), and VOP_DECREF.
Referenced by cmd_chdir(), and vfs_setbootfs().
vfs_clearcurdir()
int vfs_clearcurdir (void)
Definition at line 103 of file vfscwd.c.
References curproc, NULL, spinlock_acquire(), spinlock_release(), and VOP_DECREF.
Referenced by shutdown().
vfs_getcurdir()
int vfs_getcurdir (struct vnode ** ret)
Definition at line 49 of file vfscwd.c.
References curproc, ENOENT, NULL, spinlock_acquire(), spinlock_release(), and VOP_INCREF.
Referenced by getdevice(), vfs_getcwd(), and vfs_setbootfs().
vfs_getcwd()
int vfs_getcwd (struct uio * uio)
Definition at line 144 of file vfscwd.c.
References cwd, FSOP_GETVOLNAME, KASSERT, name, NULL, strlen(), UIO_READ, uio::uio_rw, uiomove(), vfs_biglock_acquire(), vfs_biglock_release(), vfs_getcurdir(), vfs_getdevname(), VOP_DECREF, and VOP_NAMEFILE.
Referenced by cmd_pwd().
vfs_setcurdir()
int vfs_setcurdir (struct vnode * dir)
Definition at line 71 of file vfscwd.c.
References curproc, ENOTDIR, NULL, S_IFDIR, spinlock_acquire(), spinlock_release(), VOP_DECREF, VOP_GETTYPE, and VOP_INCREF.
Referenced by vfs_chdir().