os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/dev/lamebus/lser.h File Reference
lser.h File Reference
#include <spinlock.h>
Data Structures
struct lser_softc
Functions
void lser_irq (void *sc)
void lser_write (void *sc, int ch)
void lser_writepolled (void *sc, int ch)
Function Documentation
lser_irq()
void lser_irq (void * sc)
Definition at line 48 of file lser.c.
References bus_read_register, bus_write_register, ch, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_devdata, lser_softc::ls_input, lser_softc::ls_lock, lser_softc::ls_start, lser_softc::ls_wbusy, LSER_IRQ_ACTIVE, LSER_IRQ_ENABLE, LSER_REG_CHAR, LSER_REG_RIRQ, LSER_REG_WIRQ, NULL, spinlock_acquire(), and spinlock_release().
Referenced by attach_lser_to_lamebus().
lser_write()
void lser_write (void * sc, int ch)
Definition at line 88 of file lser.c.
References bus_write_register, ch, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_lock, lser_softc::ls_wbusy, LSER_REG_CHAR, panic(), spinlock_acquire(), and spinlock_release().
Referenced by attach_con_to_lser().
lser_writepolled()
void lser_writepolled (void * sc, int ch)
Definition at line 131 of file lser.c.
References bus_write_register, ch, lser_softc::ls_busdata, lser_softc::ls_buspos, lser_softc::ls_lock, lser_softc::ls_wbusy, LSER_IRQ_ENABLE, LSER_IRQ_FORCE, lser_poll_until_write(), LSER_REG_CHAR, LSER_REG_WIRQ, spinlock_acquire(), and spinlock_release().
Referenced by attach_con_to_lser().