os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/common_path.c File Reference
common_path.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Macros
#define T(call)
#define T2(call)
Functions
static int open_badpath (const char *path)
static int remove_badpath (const char *path)
static int rename_badpath1 (const char *path)
static int rename_badpath2 (const char *path)
static int link_badpath1 (const char *path)
static int link_badpath2 (const char *path)
static int mkdir_badpath (const char *path)
static int rmdir_badpath (const char *path)
static int chdir_badpath (const char *path)
static int symlink_badpath1 (const char *path)
static int symlink_badpath2 (const char *path)
static int readlink_badpath (const char *path)
static int lstat_badpath (const char *name)
static int stat_badpath (const char *name)
static void common_badpath (int(*func)(const char *path), int mk, int rm, const char *path, const char *call, const char *pathdesc)
static void any_badpath (int(*func)(const char *path), const char *call, int mk, int rm)
T (open)
T (remove)
T (mkdir)
T (rmdir)
T (chdir)
T (readlink)
T (stat)
T (lstat)
T2 (rename)
T2 (link)
T2 (symlink)
Macro Definition Documentation
T
#define T (call)
Value:
  void                                  \
  test_##call##_path(void)              \
  {                                     \
    any_badpath(call##_badpath, #call, 0, 0); \
  }
Definition at line 186 of file common_path.c.
T2
#define T2 (call)
Value:
  void                                  \
  test_##call##_paths(void)             \
  {                                     \
    any_badpath(call##_badpath1, #call "(arg1)", 0, 1); \
    any_badpath(call##_badpath2, #call "(arg2)", 1, 1); \
  }
Definition at line 203 of file common_path.c.
Function Documentation
any_badpath()
static void any_badpath (int(*)(const char *path) func, const char * call, int mk, int rm) static
Definition at line 176 of file common_path.c.
References common_badpath(), and NULL.
chdir_badpath()
static int chdir_badpath (const char * path) static
Definition at line 105 of file common_path.c.
References chdir().
common_badpath()
static void common_badpath (int(*)(const char *path) func, int mk, int rm, const char * path, const char * call, const char * pathdesc) static
Definition at line 152 of file common_path.c.
References create_testfile(), EFAULT, errno, remove(), report_aborted(), report_begin(), report_check(), and TESTFILE.
Referenced by any_badpath().
link_badpath1()
static int link_badpath1 (const char * path) static
Definition at line 77 of file common_path.c.
References link(), and TESTFILE.
link_badpath2()
static int link_badpath2 (const char * path) static
Definition at line 84 of file common_path.c.
References link(), and TESTFILE.
lstat_badpath()
static int lstat_badpath (const char * name) static
Definition at line 134 of file common_path.c.
References lstat(), name, and sb.
mkdir_badpath()
static int mkdir_badpath (const char * path) static
Definition at line 91 of file common_path.c.
References mkdir().
open_badpath()
static int open_badpath (const char * path) static
Definition at line 49 of file common_path.c.
References O_RDONLY, and open().
readlink_badpath()
static int readlink_badpath (const char * path) static
Definition at line 126 of file common_path.c.
References buf, and readlink().
remove_badpath()
static int remove_badpath (const char * path) static
Definition at line 56 of file common_path.c.
References remove().
rename_badpath1()
static int rename_badpath1 (const char * path) static
Definition at line 63 of file common_path.c.
References rename(), and TESTFILE.
rename_badpath2()
static int rename_badpath2 (const char * path) static
Definition at line 70 of file common_path.c.
References rename(), and TESTFILE.
rmdir_badpath()
static int rmdir_badpath (const char * path) static
Definition at line 98 of file common_path.c.
References rmdir().
stat_badpath()
static int stat_badpath (const char * name) static
Definition at line 142 of file common_path.c.
References name, sb, and stat().
symlink_badpath1()
static int symlink_badpath1 (const char * path) static
Definition at line 112 of file common_path.c.
References symlink(), and TESTFILE.
symlink_badpath2()
static int symlink_badpath2 (const char * path) static
Definition at line 119 of file common_path.c.
References symlink(), and TESTFILE.
T() [1/8]
T (chdir)
T() [2/8]
T (lstat)
T() [3/8]
T (mkdir)
T() [4/8]
T (open)
T() [5/8]
T (readlink)
T() [6/8]
T (remove)
T() [7/8]
T (rmdir)
T() [8/8]
T (stat)
T2() [1/3]
T2 (link)
T2() [2/3]
T2 (rename)
T2() [3/3]
T2 (symlink)