os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/mksfs/mksfs.c File Reference
mksfs.c File Reference
#include <sys/types.h>
#include <stdint.h>
#include <string.h>
#include <assert.h>
#include <limits.h>
#include <err.h>
#include "support.h"
#include "kern/sfs.h"
#include "disk.h"
Macros
#define SWAP64(x) (x)
#define SWAP32(x) (x)
#define SWAP16(x) (x)
#define MAXFREEMAPBLOCKS 32
Functions
static void check (void)
static void allocblock (uint32_t block)
static void initfreemap (uint32_t fsblocks)
static void writesuper (const char *volname, uint32_t nblocks)
static void writefreemap (uint32_t fsblocks)
static void writerootdir (void)
int main (int argc, char **argv)
Variables
static char freemapbuf [MAXFREEMAPBLOCKS *SFS_BLOCKSIZE]
Macro Definition Documentation
MAXFREEMAPBLOCKS
#define MAXFREEMAPBLOCKS 32
Definition at line 61 of file mksfs.c.
SWAP16
#define SWAP16 (x) (x)
Definition at line 54 of file mksfs.c.
SWAP32
#define SWAP32 (x) (x)
Definition at line 53 of file mksfs.c.
SWAP64
#define SWAP64 (x) (x)
Definition at line 52 of file mksfs.c.
Function Documentation
allocblock()
static void allocblock (uint32_t block) static
Definition at line 83 of file mksfs.c.
References assert, CHAR_BIT, and freemapbuf.
Referenced by initfreemap().
check()
static void check (void) static
Definition at line 71 of file mksfs.c.
References assert, and SFS_BLOCKSIZE.
Referenced by main().
initfreemap()
static void initfreemap (uint32_t fsblocks) static
Definition at line 97 of file mksfs.c.
References allocblock(), errx(), MAXFREEMAPBLOCKS, SFS_FREEMAP_START, SFS_FREEMAPBITS, SFS_FREEMAPBLOCKS, SFS_ROOTDIR_INO, and SFS_SUPER_BLOCK.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 190 of file mksfs.c.
References check(), closedisk(), diskblocks(), diskblocksize(), errx(), hostcompat_init(), initfreemap(), NULL, opendisk(), SFS_BLOCKSIZE, strchr(), strlen(), writefreemap(), writerootdir(), and writesuper().
writefreemap()
static void writefreemap (uint32_t fsblocks) static
Definition at line 153 of file mksfs.c.
References diskwrite(), freemapbuf, SFS_BLOCKSIZE, SFS_FREEMAP_START, and SFS_FREEMAPBLOCKS.
Referenced by main().
writerootdir()
static void writerootdir (void) static
Definition at line 172 of file mksfs.c.
References bzero(), diskwrite(), SFS_ROOTDIR_INO, SFS_TYPE_DIR, SWAP16, and SWAP32.
Referenced by main().
writesuper()
static void writesuper (const char * volname, uint32_t nblocks) static
Definition at line 128 of file mksfs.c.
References bzero(), diskwrite(), errx(), nblocks, sb, sfs_superblock::sb_magic, sfs_superblock::sb_nblocks, sfs_superblock::sb_volname, SFS_MAGIC, SFS_SUPER_BLOCK, SFS_VOLNAME_SIZE, strcpy(), strlen(), and SWAP32.
Referenced by main().
Variable Documentation
freemapbuf
char freemapbuf[MAXFREEMAPBLOCKS *SFS_BLOCKSIZE] static
Definition at line 64 of file mksfs.c.
Referenced by allocblock(), and writefreemap().