os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/bigseek/bigseek.c File Reference
bigseek.c File Reference
#include <sys/types.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
#include <errno.h>
Macros
#define TESTFILE "bigseekfile"
Functions
static void write_slogan (int fd, unsigned which, bool failok)
static void check_slogan (int fd, unsigned which)
static void try_reading (int fd)
static void try_writing (int fd)
static void dolseek (int fd, off_t pos, int whence, const char *whencestr, off_t expected)
static void try_seeking (int fd, off_t pos, off_t cursize)
int main (void)
Variables
static const char * slogans []
Macro Definition Documentation
TESTFILE
#define TESTFILE "bigseekfile"
Definition at line 63 of file bigseek.c.
Function Documentation
check_slogan()
static void check_slogan (int fd, unsigned which) static
Definition at line 95 of file bigseek.c.
References buf, err(), errx(), fd, memcmp(), read(), slogans, strlen(), and warnx().
Referenced by main().
dolseek()
static void dolseek (int fd, off_t pos, int whence, const char * whencestr, off_t expected) static
Definition at line 166 of file bigseek.c.
References err(), errx(), fd, lseek(), and pos.
Referenced by try_seeking().
main()
int main (void)
Definition at line 213 of file bigseek.c.
References check_slogan(), close(), err(), fd, O_CREAT, O_RDWR, O_TRUNC, open(), printf(), remove(), slogans, strlen(), TESTFILE, try_reading(), try_seeking(), try_writing(), and write_slogan().
try_reading()
static void try_reading (int fd) static
Definition at line 141 of file bigseek.c.
References buf, err(), errx(), fd, and read().
Referenced by main().
try_seeking()
static void try_seeking (int fd, off_t pos, off_t cursize) static
Definition at line 183 of file bigseek.c.
References dolseek(), fd, pos, printf(), SEEK_CUR, SEEK_END, and SEEK_SET.
Referenced by main().
try_writing()
static void try_writing (int fd) static
Definition at line 159 of file bigseek.c.
References fd, and write_slogan().
Referenced by main().
write_slogan()
static void write_slogan (int fd, unsigned which, bool failok) static
Definition at line 72 of file bigseek.c.
References EFBIG, err(), errno, errx(), fd, slogans, strlen(), and write().
Referenced by main(), and try_writing().
Variable Documentation
slogans
const char* slogans[] static
Initial value:
= {
    "QUO USQUE TANDEM ABUTERE CATILINA PATENTIA NOSTRA",
    "QUEM IN FINEM SESE EFFRENATA IACTABIT AUDACIA"
}
Definition at line 65 of file bigseek.c.
Referenced by check_slogan(), main(), and write_slogan().