os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/dev/generic/console.h File Reference
console.h File Reference
Data Structures
struct con_softc
Macros
#define CONSOLE_INPUT_BUFFER_SIZE 32
Functions
void con_input (void *cs, int ch)
void con_start (void *cs)
Macro Definition Documentation
CONSOLE_INPUT_BUFFER_SIZE
#define CONSOLE_INPUT_BUFFER_SIZE 32
Definition at line 40 of file console.h.
Function Documentation
con_input()
void con_input (void * cs, int ch)
Definition at line 162 of file console.c.
References ch, CONSOLE_INPUT_BUFFER_SIZE, con_softc::cs_gotchars, con_softc::cs_gotchars_head, con_softc::cs_gotchars_tail, con_softc::cs_rsem, and V().
Referenced by attach_con_to_lscreen(), and attach_con_to_lser().
con_start()
void con_start (void * cs)
Definition at line 183 of file console.c.
References con_softc::cs_wsem, and V().
Referenced by attach_con_to_lscreen(), and attach_con_to_lser().