os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/report.c File Reference
report.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include <assert.h>
#include "config.h"
#include "test.h"
Macros
#define RESULT_COLUMN 72
Functions
static void vsay (const char *fmt, va_list ap)
static void say (const char *fmt,...)
static void indent_to (size_t pos)
static void flush (void)
void report_begin (const char *descfmt,...)
void report_hassubs (void)
void report_beginsub (const char *descfmt,...)
void report_warn (const char *fmt,...)
void report_warnx (const char *fmt,...)
void report_result (int rv, int error)
void report_saw_enosys (void)
static void report_end (const char *msg)
void report_passed (void)
void report_failure (void)
void report_skipped (void)
void report_aborted (void)
void report_survival (int rv, int error)
static void report_checkN (int rv, int error, int *right_errors, int right_num)
void report_check (int rv, int error, int right_error)
void report_check2 (int rv, int error, int okerr1, int okerr2)
void report_check3 (int rv, int error, int okerr1, int okerr2, int okerr3)
Variables
static size_t horizpos
static size_t subpos
static char outbuf [256]
static size_t outbufpos
Macro Definition Documentation
RESULT_COLUMN
#define RESULT_COLUMN 72
Definition at line 44 of file report.c.
Function Documentation
flush()
static void flush (void) static
Definition at line 114 of file report.c.
References outbuf, outbufpos, STDOUT_FILENO, and write().
Referenced by report_begin(), report_end(), report_hassubs(), report_warn(), and report_warnx().
indent_to()
static void indent_to (size_t pos) static
Definition at line 99 of file report.c.
References assert, horizpos, outbuf, outbufpos, and pos.
Referenced by report_beginsub(), report_end(), report_saw_enosys(), report_warn(), and report_warnx().
report_aborted()
void report_aborted (void)
Definition at line 272 of file report.c.
References report_end().
Referenced by common_badpath(), create_testdir(), dup2_self(), exec_common_fork(), ftruncate_fd_device(), ftruncate_size_neg(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), readlink_file(), rmdir_file(), wait_badflags(), wait_badstatus(), wait_nullstatus(), wait_parent(), wait_siblings(), and wait_unaligned().
report_begin()
void report_begin (const char * descfmt, ...)
Definition at line 127 of file report.c.
References flush(), say(), va_end, va_start, and vsay().
Referenced by any_badfd(), any_empty(), chdir_empty(), common_badbuf(), common_badpath(), dup2_fd2(), dup2_self(), enforce_sbrk(), exec_badargs(), exec_badprog(), exec_common_fork(), exec_emptyprog(), exec_onearg(), ftruncate_fd_device(), ftruncate_size_neg(), ioctl_badcode(), link_dir(), link_empty1(), link_empty2(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), mkdir_dot(), mkdir_dotdot(), mkdir_empty(), one_ioctl_badbuf(), open_badflags(), open_empty(), pipe_badptr(), pipe_unaligned(), readlink_dir(), readlink_empty(), readlink_file(), reboot_badflags(), remove_dir(), remove_dot(), remove_dotdot(), remove_empty(), rename_dot(), rename_dotdot(), rename_empty1(), rename_empty2(), rmdir_dot(), rmdir_dotdot(), rmdir_empty(), rmdir_file(), sbrk_unalignedneg(), sbrk_unalignedpos(), symlink_empty1(), symlink_empty2(), time_badnsecs(), time_badsecs(), wait_badflags(), wait_badpid(), wait_badstatus(), wait_nullstatus(), wait_parent(), wait_self(), wait_siblings(), and wait_unaligned().
report_beginsub()
void report_beginsub (const char * descfmt, ...)
Definition at line 156 of file report.c.
References assert, horizpos, indent_to(), say(), subpos, va_end, va_start, and vsay().
Referenced by wait_parent(), wait_siblings(), and wait_siblings_child().
report_check()
void report_check (int rv, int error, int right_error)
Definition at line 326 of file report.c.
References report_checkN().
Referenced by any_badfd(), common_badbuf(), common_badpath(), dup2_fd2(), enforce_sbrk(), exec_badargs(), exec_badprog(), exec_onearg(), ftruncate_fd_device(), ftruncate_size_neg(), ioctl_badcode(), link_dir(), link_empty1(), link_empty2(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_whence_inval(), mkdir_dot(), mkdir_dotdot(), mkdir_empty(), one_ioctl_badbuf(), open_badflags(), open_empty(), pipe_badptr(), readlink_dir(), readlink_file(), reboot_badflags(), remove_dir(), rename_dot(), rename_dotdot(), rmdir_dot(), rmdir_empty(), rmdir_file(), symlink_empty2(), time_badnsecs(), time_badsecs(), wait_badflags(), wait_badstatus(), and wait_nullstatus().
report_check2()
void report_check2 (int rv, int error, int okerr1, int okerr2)
Definition at line 332 of file report.c.
References ok(), and report_checkN().
Referenced by any_empty(), chdir_empty(), exec_emptyprog(), readlink_empty(), remove_dot(), remove_dotdot(), remove_empty(), rename_empty1(), rename_empty2(), rmdir_dotdot(), sbrk_unalignedneg(), sbrk_unalignedpos(), symlink_empty1(), and wait_badpid().
report_check3()
void report_check3 (int rv, int error, int okerr1, int okerr2, int okerr3)
Definition at line 342 of file report.c.
References ok(), and report_checkN().
report_checkN()
static void report_checkN (int rv, int error, int * right_errors, int right_num) static
Definition at line 295 of file report.c.
References ENOSYS, report_failure(), report_passed(), report_result(), report_saw_enosys(), report_skipped(), and say().
Referenced by report_check(), report_check2(), and report_check3().
report_end()
static void report_end (const char * msg) static
Definition at line 246 of file report.c.
References flush(), indent_to(), test::msg, RESULT_COLUMN, and say().
Referenced by report_aborted(), report_failure(), report_passed(), and report_skipped().
report_failure()
void report_failure (void)
Definition at line 260 of file report.c.
References report_end().
Referenced by dup2_self(), exec_common_fork(), lseek_loc_pasteof(), and report_checkN().
report_hassubs()
void report_hassubs (void)
Definition at line 143 of file report.c.
References flush(), horizpos, say(), and subpos.
Referenced by wait_parent(), and wait_siblings().
report_passed()
void report_passed (void)
Definition at line 254 of file report.c.
References report_end().
Referenced by dup2_self(), lseek_loc_pasteof(), report_checkN(), report_survival(), and wait_siblings().
report_result()
void report_result (int rv, int error)
Definition at line 211 of file report.c.
References say(), and strerror().
Referenced by dup2_self(), exec_common_fork(), report_checkN(), and report_survival().
report_saw_enosys()
void report_saw_enosys (void)
Definition at line 231 of file report.c.
References horizpos, indent_to(), and pos.
Referenced by create_testdir(), dup2_self(), report_checkN(), and wait_badpid().
report_skipped()
void report_skipped (void)
Definition at line 266 of file report.c.
References report_end().
Referenced by create_testdir(), dup2_self(), lseek_file_stdin(), and report_checkN().
report_survival()
void report_survival (int rv, int error)
Definition at line 286 of file report.c.
References report_passed(), and report_result().
Referenced by pipe_unaligned(), wait_parent(), wait_self(), wait_siblings_child(), and wait_unaligned().
report_warn()
void report_warn (const char * fmt, ...)
Definition at line 174 of file report.c.
References errno, flush(), horizpos, indent_to(), pos, say(), strerror(), va_end, va_start, and vsay().
Referenced by create_testdir(), create_testfile(), create_testlink(), ftruncate_fd_device(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_pasteof(), open_testfile(), reopen_testfile(), wait_badflags(), wait_badstatus(), wait_nullstatus(), wait_parent(), wait_siblings(), wait_siblings_child(), and wait_unaligned().
report_warnx()
void report_warnx (const char * fmt, ...)
Definition at line 192 of file report.c.
References flush(), horizpos, indent_to(), pos, say(), va_end, va_start, and vsay().
Referenced by create_testdir(), dup2_self(), exec_common_fork(), lseek_file_stdin(), lseek_loc_pasteof(), and wait_siblings().
say()
static void say (const char * fmt, ...) static
Definition at line 85 of file report.c.
References va_end, va_start, and vsay().
Referenced by report_begin(), report_beginsub(), report_checkN(), report_end(), report_hassubs(), report_result(), report_warn(), and report_warnx().
vsay()
static void vsay (const char * fmt, va_list ap) static
Definition at line 63 of file report.c.
References assert, horizpos, outbuf, outbufpos, strlen(), and vsnprintf().
Referenced by report_begin(), report_beginsub(), report_warn(), report_warnx(), and say().
Variable Documentation
horizpos
size_t horizpos static
Definition at line 47 of file report.c.
Referenced by indent_to(), report_beginsub(), report_hassubs(), report_saw_enosys(), report_warn(), report_warnx(), and vsay().
outbuf
char outbuf[256] static
Definition at line 53 of file report.c.
Referenced by flush(), indent_to(), and vsay().
outbufpos
size_t outbufpos static
Definition at line 54 of file report.c.
Referenced by flush(), indent_to(), and vsay().
subpos
size_t subpos static
Definition at line 50 of file report.c.
Referenced by report_beginsub(), and report_hassubs().