os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/vfs/vfslist.c File Reference
vfslist.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <array.h>
#include <synch.h>
#include <vfs.h>
#include <fs.h>
#include <vnode.h>
#include <device.h>
Data Structures
struct knowndev
Macros
#define VFSINLINE
#define SWAP_FS ((struct fs *)-1)
Functions
DECLARRAY (knowndev, static __UNUSED inline)
DEFARRAY (knowndev, static __UNUSED inline)
void vfs_bootstrap (void)
void vfs_biglock_acquire (void)
void vfs_biglock_release (void)
bool vfs_biglock_do_i_hold (void)
int vfs_sync (void)
int vfs_getroot (const char *devname, struct vnode **ret)
const char * vfs_getdevname (struct fs *fs)
static char * mkrawname (const char *name)
static int samestring (const char *a, const char *b)
static int samestring3 (const char *a, const char *b, const char *c, const char *d)
static int badnames (const char *n1, const char *n2, const char *n3)
static int vfs_doadd (const char *dname, int mountable, struct device *dev, struct fs *fs)
int vfs_adddev (const char *devname, struct device *dev, int mountable)
int vfs_addfs (const char *devname, struct fs *fs)
static int findmount (const char *devname, struct knowndev **result)
int vfs_mount (const char *devname, void *data, int(*mountfunc)(void *data, struct device *, struct fs **ret))
int vfs_swapon (const char *devname, struct vnode **ret)
int vfs_unmount (const char *devname)
int vfs_swapoff (const char *devname)
int vfs_unmountall (void)
Variables
static struct knowndevarray * knowndevs
static struct lock * vfs_biglock
static unsigned vfs_biglock_depth
Macro Definition Documentation
SWAP_FS
#define SWAP_FS ((struct fs *)-1)
Definition at line 86 of file vfslist.c.
VFSINLINE
#define VFSINLINE
Definition at line 35 of file vfslist.c.
Function Documentation
badnames()
static int badnames (const char * n1, const char * n2, const char * n3) static
Definition at line 355 of file vfslist.c.
References FSOP_GETVOLNAME, KASSERT, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndevs, NULL, num, samestring3(), SWAP_FS, and vfs_biglock_do_i_hold().
Referenced by vfs_doadd().
DECLARRAY()
DECLARRAY (knowndev , static __UNUSED inline)
DEFARRAY()
DEFARRAY (knowndev , static __UNUSED inline)
findmount()
static int findmount (const char * devname, struct knowndev ** result) static
Definition at line 506 of file vfslist.c.
References ENODEV, found, KASSERT, knowndev::kd_name, knowndev::kd_rawname, knowndevs, NULL, num, strcmp(), and vfs_biglock_do_i_hold().
Referenced by vfs_mount(), vfs_swapoff(), vfs_swapon(), and vfs_unmount().
mkrawname()
static char* mkrawname (const char * name) static
Definition at line 309 of file vfslist.c.
References kmalloc(), name, NULL, strcat(), strcpy(), and strlen().
Referenced by vfs_doadd().
samestring()
static int samestring (const char * a, const char * b) inline static
Definition at line 328 of file vfslist.c.
References NULL, and strcmp().
Referenced by samestring3().
samestring3()
static int samestring3 (const char * a, const char * b, const char * c, const char * d) inline static
Definition at line 343 of file vfslist.c.
References samestring().
Referenced by badnames().
vfs_adddev()
int vfs_adddev (const char * devname, struct device * dev, int mountable)
Definition at line 482 of file vfslist.c.
References NULL, and vfs_doadd().
Referenced by attach_console_to_vfs(), config_lhd(), config_random(), and devnull_create().
vfs_addfs()
int vfs_addfs (const char * devname, struct fs * fs)
Definition at line 493 of file vfslist.c.
References NULL, and vfs_doadd().
Referenced by emufs_addtovfs(), and semfs_bootstrap().
vfs_biglock_acquire()
void vfs_biglock_acquire (void)
Definition at line 127 of file vfslist.c.
References lock_acquire(), lock_do_i_hold(), vfs_biglock, and vfs_biglock_depth.
Referenced by emufs_loadvnode(), emufs_reclaim(), sfs_creat(), sfs_domount(), sfs_fsync(), sfs_getroot(), sfs_gettype(), sfs_getvolname(), sfs_itrunc(), sfs_link(), sfs_lookparent(), sfs_lookup(), sfs_read(), sfs_reclaim(), sfs_remove(), sfs_rename(), sfs_sync(), sfs_unmount(), sfs_write(), vfs_clearbootfs(), vfs_doadd(), vfs_getcwd(), vfs_lookparent(), vfs_lookup(), vfs_mount(), vfs_setbootfs(), vfs_swapoff(), vfs_swapon(), vfs_sync(), vfs_unmount(), and vfs_unmountall().
vfs_biglock_do_i_hold()
bool vfs_biglock_do_i_hold (void)
Definition at line 164 of file vfslist.c.
References lock_do_i_hold(), and vfs_biglock.
Referenced by badnames(), findmount(), getdevice(), sfs_bmap(), sfs_metaio(), sfs_partialio(), sfs_rwblock(), vfs_getdevname(), and vfs_getroot().
vfs_biglock_release()
void vfs_biglock_release (void)
Definition at line 153 of file vfslist.c.
References KASSERT, lock_do_i_hold(), lock_release(), vfs_biglock, and vfs_biglock_depth.
Referenced by emufs_loadvnode(), emufs_reclaim(), sfs_creat(), sfs_domount(), sfs_fsync(), sfs_getroot(), sfs_gettype(), sfs_getvolname(), sfs_itrunc(), sfs_link(), sfs_lookparent(), sfs_lookup(), sfs_read(), sfs_reclaim(), sfs_remove(), sfs_rename(), sfs_sync(), sfs_unmount(), sfs_write(), vfs_clearbootfs(), vfs_doadd(), vfs_getcwd(), vfs_lookparent(), vfs_lookup(), vfs_mount(), vfs_setbootfs(), vfs_swapoff(), vfs_swapon(), vfs_sync(), vfs_unmount(), and vfs_unmountall().
vfs_bootstrap()
void vfs_bootstrap (void)
Definition at line 102 of file vfslist.c.
References devnull_create(), knowndevs, lock_create(), NULL, panic(), semfs_bootstrap(), vfs_biglock, and vfs_biglock_depth.
Referenced by boot().
vfs_doadd()
static int vfs_doadd (const char * dname, int mountable, struct device * dev, struct fs * fs) static
Definition at line 392 of file vfslist.c.
References badnames(), device::d_devnumber, dev_create_vnode(), dev_uncreate_vnode(), EEXIST, ENOMEM, fail(), FSOP_GETVOLNAME, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndev::kd_vnode, kfree(), kmalloc(), knowndevs, kstrdup(), mkrawname(), name, NULL, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by vfs_adddev(), and vfs_addfs().
vfs_getdevname()
const char* vfs_getdevname (struct fs * fs)
Definition at line 277 of file vfslist.c.
References KASSERT, knowndev::kd_fs, knowndev::kd_name, knowndevs, NULL, num, and vfs_biglock_do_i_hold().
Referenced by vfs_getcwd().
vfs_getroot()
int vfs_getroot (const char * devname, struct vnode ** ret)
Definition at line 198 of file vfslist.c.
References ENODEV, ENXIO, FSOP_GETROOT, FSOP_GETVOLNAME, KASSERT, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndev::kd_vnode, knowndevs, NULL, num, strcmp(), SWAP_FS, vfs_biglock_do_i_hold(), and VOP_INCREF.
Referenced by getdevice().
vfs_mount()
int vfs_mount (const char * devname, void * data, int(*)(void *data, struct device *, struct fs **ret) mountfunc)
Definition at line 538 of file vfslist.c.
References EBUSY, findmount(), FSOP_GETVOLNAME, KASSERT, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, kprintf(), NULL, SWAP_FS, vfs_biglock_acquire(), and vfs_biglock_release().
vfs_swapoff()
int vfs_swapoff (const char * devname)
Definition at line 688 of file vfslist.c.
References EINVAL, fail(), findmount(), KASSERT, knowndev::kd_fs, knowndev::kd_name, kprintf(), NULL, SWAP_FS, vfs_biglock_acquire(), and vfs_biglock_release().
vfs_swapon()
int vfs_swapon (const char * devname, struct vnode ** ret)
Definition at line 586 of file vfslist.c.
References EBUSY, ENOMEM, findmount(), KASSERT, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndev::kd_vnode, kfree(), kprintf(), kstrdup(), NULL, strlen(), SWAP_FS, vfs_biglock_acquire(), vfs_biglock_release(), and VOP_INCREF.
vfs_sync()
int vfs_sync (void)
Definition at line 173 of file vfslist.c.
References FSOP_SYNC, knowndev::kd_fs, knowndevs, NULL, num, SWAP_FS, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by cmd_quit(), cmd_sync(), and panic().
vfs_unmount()
int vfs_unmount (const char * devname)
Definition at line 638 of file vfslist.c.
References EINVAL, fail(), findmount(), FSOP_SYNC, FSOP_UNMOUNT, KASSERT, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, kprintf(), NULL, SWAP_FS, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by cmd_unmount().
vfs_unmountall()
int vfs_unmountall (void)
Definition at line 721 of file vfslist.c.
References EBUSY, FSOP_SYNC, FSOP_UNMOUNT, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndevs, kprintf(), NULL, num, strerror(), SWAP_FS, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by shutdown().
Variable Documentation
knowndevs
struct knowndevarray* knowndevs static
Definition at line 91 of file vfslist.c.
Referenced by badnames(), findmount(), vfs_bootstrap(), vfs_doadd(), vfs_getdevname(), vfs_getroot(), vfs_sync(), and vfs_unmountall().
vfs_biglock
struct lock* vfs_biglock static
Definition at line 94 of file vfslist.c.
Referenced by vfs_biglock_acquire(), vfs_biglock_do_i_hold(), vfs_biglock_release(), and vfs_bootstrap().
vfs_biglock_depth
unsigned vfs_biglock_depth static
Definition at line 95 of file vfslist.c.
Referenced by vfs_biglock_acquire(), vfs_biglock_release(), and vfs_bootstrap().