os161-doc: /home/os161user/os161/os161-base-2.0.3/common/libc/string/strcmp.c File Reference
strcmp.c File Reference
#include <string.h>
Functions
int strcmp (const char *a, const char *b)
Function Documentation
strcmp()
int strcmp (const char * a, const char * b)
Definition at line 48 of file strcmp.c.
Referenced by cat(), check(), check_order(), checkmany(), cmd_dispatch(), cmd_kheapdump(), cmd_mount(), createstress_thread(), dirsortfunc(), do_semu1011(), do_semu89(), docommand(), dumpargs(), findentry(), findmount(), findworkload(), fstest_read(), inspectdir(), main(), name_find(), opendisk(), pass1_dir(), pass2_dir(), readfile(), readone(), recursedir(), samestring(), semfs_creat(), semfs_lookup(), semfs_remove(), semu1(), semu1213(), semu18(), semu19(), sfs_dir_findname(), strtosize(), test6(), and vfs_getroot().