os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/poisondisk/poisondisk.c File Reference
poisondisk.c File Reference
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
#include "disk.h"
Macros
#define POISON_BYTE 0xa9
#define BLOCKSIZE 512
Functions
static void poison (void)
int main (int argc, char *argv[])
Macro Definition Documentation
BLOCKSIZE
#define BLOCKSIZE 512
Definition at line 47 of file poisondisk.c.
POISON_BYTE
#define POISON_BYTE 0xa9
Definition at line 46 of file poisondisk.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 65 of file poisondisk.c.
References closedisk(), errx(), opendisk(), and poison().
poison()
static void poison (void) static
Definition at line 51 of file poisondisk.c.
References BLOCKSIZE, buf, diskblocks(), diskwrite(), memset(), and POISON_BYTE.
Referenced by checkfilezeros(), and main().