os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/zero/zero.c File Reference
zero.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
Macros
#define SUM_OF_DATA_STUFF 525
#define SBRK_SIZE 8192
Functions
static void check_data (void)
static void check_bss (void)
static void check_sbrk (void)
int main (void)
Variables
static unsigned data_stuff []
static unsigned bss_stuff [3000]
Macro Definition Documentation
SBRK_SIZE
#define SBRK_SIZE 8192
SUM_OF_DATA_STUFF
#define SUM_OF_DATA_STUFF 525
Definition at line 60 of file zero.c.
Function Documentation
check_bss()
static void check_bss (void) static
Definition at line 87 of file zero.c.
References bss_stuff, errx(), num, and warnx().
Referenced by main().
check_data()
static void check_data (void) static
Definition at line 70 of file zero.c.
References data_stuff, errx(), num, SUM_OF_DATA_STUFF, and warnx().
Referenced by main().
check_sbrk()
static void check_sbrk (void) static
Definition at line 104 of file zero.c.
References ENOSYS, err(), errno, errx(), printf(), sbrk(), SBRK_SIZE, and warnx().
Referenced by main().
main()
int main (void)
Definition at line 134 of file zero.c.
References check_bss(), check_data(), check_sbrk(), and printf().
Variable Documentation
bss_stuff
unsigned bss_stuff[3000] static
Definition at line 66 of file zero.c.
Referenced by check_bss().
data_stuff
unsigned data_stuff[] static
Initial value:
= {
    1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5,
    2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0,
    1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5,
    2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0,
    1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5,
    2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0,
    1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5,
    2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0,
    1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5,
    2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0,
}
Definition at line 47 of file zero.c.
Referenced by check_data().