os161-doc: random_softc Struct Reference
random_softc Struct Reference
#include <random.h>
Data Fields
void * rs_devdata
uint32_t(* rs_random)(void *devdata)
uint32_t(* rs_randmax)(void *devdata)
int(* rs_read)(void *devdata, struct uio *uio)
struct device rs_dev
Detailed Description
Definition at line 36 of file random.h.
Field Documentation
rs_dev
struct device rs_dev
Definition at line 43 of file random.h.
Referenced by config_random().
rs_devdata
void* rs_devdata
Definition at line 38 of file random.h.
Referenced by attach_random_to_lrandom(), randio(), randmax(), and random().
rs_randmax
uint32_t(* rs_randmax(void *devdata)
Definition at line 40 of file random.h.
Referenced by attach_random_to_lrandom(), and randmax().
rs_random
uint32_t(* rs_random(void *devdata)
Definition at line 39 of file random.h.
Referenced by attach_random_to_lrandom(), and random().
rs_read
int(* rs_read(void *devdata, struct uio *uio)
Definition at line 41 of file random.h.
Referenced by attach_random_to_lrandom(), and randio().
The documentation for this struct was generated from the following file:
/home/os161user/os161/os161-base-2.0.3/kern/dev/generic/random.h