os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/tail/tail.c File Reference
tail.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <err.h>
Macros
#define BUFSIZE 1000
Functions
static void tail (int file, off_t where, const char *filename)
int main (int argc, char **argv)
Variables
char buffer [BUFSIZE]
Macro Definition Documentation
BUFSIZE
#define BUFSIZE 1000
Definition at line 43 of file tail.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 66 of file tail.c.
References atoi(), close(), err(), errx(), O_RDONLY, open(), and tail().
tail()
static void tail (int file, off_t where, const char * filename) static
Definition at line 52 of file tail.c.
References buffer, err(), lseek(), read(), SEEK_SET, STDOUT_FILENO, and write().
Referenced by main(), qsort(), and strtok_r().
Variable Documentation
buffer
char buffer[BUFSIZE]
Definition at line 48 of file tail.c.
Referenced by sfs_readdir(), sfs_writedir(), and tail().