os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/lib/libc/string/memcmp.c File Reference
memcmp.c File Reference
#include <string.h>
Functions
int memcmp (const void *av, const void *bv, size_t len)
Function Documentation
memcmp()
int memcmp (const void * av, const void * bv, size_t len)
Definition at line 38 of file memcmp.c.
Referenced by check_slogan(), getenv(), and matches_at().