os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_chdir.c File Reference
bad_chdir.c File Reference
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "test.h"
Functions
static void chdir_empty (void)
void test_chdir (void)
Function Documentation
chdir_empty()
static void chdir_empty (void) static
Definition at line 42 of file bad_chdir.c.
References chdir(), EINVAL, errno, report_begin(), and report_check2().
Referenced by test_chdir().
test_chdir()
void test_chdir (void)
Definition at line 56 of file bad_chdir.c.
References chdir_empty(), and test_chdir_path().