os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_mkdir.c File Reference
bad_mkdir.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void mkdir_dot (void)
static void mkdir_dotdot (void)
static void mkdir_empty (void)
void test_mkdir (void)
Function Documentation
mkdir_dot()
static void mkdir_dot (void) static
Definition at line 48 of file bad_mkdir.c.
References EEXIST, errno, mkdir(), report_begin(), and report_check().
Referenced by test_mkdir().
mkdir_dotdot()
static void mkdir_dotdot (void) static
Definition at line 59 of file bad_mkdir.c.
References EEXIST, errno, mkdir(), report_begin(), and report_check().
Referenced by test_mkdir().
mkdir_empty()
static void mkdir_empty (void) static
Definition at line 70 of file bad_mkdir.c.
References EINVAL, errno, mkdir(), report_begin(), and report_check().
Referenced by test_mkdir().
test_mkdir()
void test_mkdir (void)
Definition at line 80 of file bad_mkdir.c.
References mkdir_dot(), mkdir_dotdot(), mkdir_empty(), and test_mkdir_path().