os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/fs/sfs/sfsprivate.h File Reference
sfsprivate.h File Reference
#include <uio.h>
Macros
#define SFSUIO(iov, uio, ptr, block, rw) uio_kinit(iov, uio, ptr, SFS_BLOCKSIZE, ((off_t)(block))*SFS_BLOCKSIZE, rw)
Functions
int sfs_balloc (struct sfs_fs *sfs, daddr_t *diskblock)
void sfs_bfree (struct sfs_fs *sfs, daddr_t diskblock)
int sfs_bused (struct sfs_fs *sfs, daddr_t diskblock)
int sfs_bmap (struct sfs_vnode *sv, uint32_t fileblock, bool doalloc, daddr_t *diskblock)
int sfs_itrunc (struct sfs_vnode *sv, off_t len)
int sfs_dir_findname (struct sfs_vnode *sv, const char *name, uint32_t *ino, int *slot, int *emptyslot)
int sfs_dir_link (struct sfs_vnode *sv, const char *name, uint32_t ino, int *slot)
int sfs_dir_unlink (struct sfs_vnode *sv, int slot)
int sfs_lookonce (struct sfs_vnode *sv, const char *name, struct sfs_vnode **ret, int *slot)
int sfs_sync_inode (struct sfs_vnode *sv)
int sfs_reclaim (struct vnode *v)
int sfs_loadvnode (struct sfs_fs *sfs, uint32_t ino, int forcetype, struct sfs_vnode **ret)
int sfs_makeobj (struct sfs_fs *sfs, int type, struct sfs_vnode **ret)
int sfs_getroot (struct fs *fs, struct vnode **ret)
int sfs_readblock (struct sfs_fs *sfs, daddr_t block, void *data, size_t len)
int sfs_writeblock (struct sfs_fs *sfs, daddr_t block, void *data, size_t len)
int sfs_io (struct sfs_vnode *sv, struct uio *uio)
int sfs_metaio (struct sfs_vnode *sv, off_t pos, void *data, size_t len, enum uio_rw rw)
Variables
const struct vnode_ops sfs_fileops
const struct vnode_ops sfs_dirops
Macro Definition Documentation
SFSUIO
#define SFSUIO (iov, uio, ptr, block, rw) uio_kinit(iov, uio, ptr, SFS_BLOCKSIZE, ((off_t)(block))*SFS_BLOCKSIZE, rw)
Definition at line 41 of file sfsprivate.h.
Function Documentation
sfs_balloc()
int sfs_balloc (struct sfs_fs * sfs, daddr_t * diskblock)
Definition at line 58 of file sfs_balloc.c.
References bitmap_alloc(), bitmap_unmark(), panic(), sfs_superblock::sb_nblocks, sfs_superblock::sb_volname, sfs_clearblock(), sfs_fs::sfs_freemap, sfs_fs::sfs_freemapdirty, and sfs_fs::sfs_sb.
Referenced by sfs_bmap(), and sfs_makeobj().
sfs_bfree()
void sfs_bfree (struct sfs_fs * sfs, daddr_t diskblock)
Definition at line 85 of file sfs_balloc.c.
References bitmap_unmark(), sfs_fs::sfs_freemap, and sfs_fs::sfs_freemapdirty.
Referenced by sfs_itrunc(), sfs_makeobj(), and sfs_reclaim().
sfs_bmap()
int sfs_bmap (struct sfs_vnode * sv, uint32_t fileblock, bool doalloc, daddr_t * diskblock)
Definition at line 49 of file sfs_bmap.c.
References bzero(), EFBIG, fs::fs_data, KASSERT, panic(), sfs_superblock::sb_volname, sfs_dinode::sfi_direct, sfs_dinode::sfi_indirect, sfs_balloc(), SFS_BLOCKSIZE, sfs_bused(), SFS_DBPERIDB, SFS_NDIRECT, SFS_NINDIRECT, sfs_readblock(), sfs_fs::sfs_sb, sfs_writeblock(), sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, vfs_biglock_do_i_hold(), and vnode::vn_fs.
Referenced by sfs_blockio(), sfs_metaio(), and sfs_partialio().
sfs_bused()
int sfs_bused (struct sfs_fs * sfs, daddr_t diskblock)
Definition at line 95 of file sfs_balloc.c.
References bitmap_isset(), panic(), sfs_superblock::sb_nblocks, sfs_superblock::sb_volname, sfs_fs::sfs_freemap, and sfs_fs::sfs_sb.
Referenced by sfs_bmap(), and sfs_loadvnode().
sfs_dir_findname()
int sfs_dir_findname (struct sfs_vnode * sv, const char * name, uint32_t * ino, int * slot, int * emptyslot)
Definition at line 104 of file sfs_dir.c.
References ENOENT, found, KASSERT, name, NULL, sfs_direntry::sfd_ino, sfs_direntry::sfd_name, sfs_dir_nentries(), SFS_NOINO, sfs_readdir(), and strcmp().
Referenced by sfs_creat(), sfs_dir_link(), and sfs_lookonce().
sfs_dir_link()
int sfs_dir_link (struct sfs_vnode * sv, const char * name, uint32_t ino, int * slot)
Definition at line 154 of file sfs_dir.c.
References bzero(), EEXIST, ENAMETOOLONG, ENOENT, name, NULL, sfs_direntry::sfd_ino, sfs_direntry::sfd_name, sfs_dir_findname(), sfs_dir_nentries(), sfs_writedir(), strcpy(), and strlen().
Referenced by sfs_creat(), sfs_link(), and sfs_rename().
sfs_dir_unlink()
int sfs_dir_unlink (struct sfs_vnode * sv, int slot)
Definition at line 196 of file sfs_dir.c.
References bzero(), sfs_direntry::sfd_ino, SFS_NOINO, and sfs_writedir().
Referenced by sfs_remove(), and sfs_rename().
sfs_getroot()
int sfs_getroot (struct fs * fs, struct vnode ** ret)
Definition at line 293 of file sfs_inode.c.
References EINVAL, fs::fs_data, kprintf(), sfs_superblock::sb_volname, sfs_dinode::sfi_type, sfs_loadvnode(), SFS_ROOTDIR_INO, sfs_fs::sfs_sb, SFS_TYPE_DIR, SFS_TYPE_INVAL, sfs_vnode::sv_absvn, sfs_vnode::sv_i, vfs_biglock_acquire(), and vfs_biglock_release().
sfs_io()
int sfs_io (struct sfs_vnode * sv, struct uio * uio)
Definition at line 292 of file sfs_io.c.
References KASSERT, nblocks, sfs_dinode::sfi_size, sfs_blockio(), SFS_BLOCKSIZE, sfs_partialio(), sfs_vnode::sv_dirty, sfs_vnode::sv_i, uio::uio_offset, UIO_READ, uio::uio_resid, uio::uio_rw, and UIO_WRITE.
Referenced by sfs_read(), and sfs_write().
sfs_itrunc()
int sfs_itrunc (struct sfs_vnode * sv, off_t len)
Definition at line 204 of file sfs_bmap.c.
References DIVROUNDUP, fs::fs_data, KASSERT, sfs_dinode::sfi_direct, sfs_dinode::sfi_indirect, sfs_dinode::sfi_size, sfs_bfree(), SFS_BLOCKSIZE, SFS_DBPERIDB, SFS_NDIRECT, sfs_readblock(), sfs_writeblock(), sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, vfs_biglock_acquire(), vfs_biglock_release(), and vnode::vn_fs.
Referenced by sfs_reclaim(), and sfs_truncate().
sfs_loadvnode()
int sfs_loadvnode (struct sfs_fs * sfs, uint32_t ino, int forcetype, struct sfs_vnode ** ret)
Definition at line 150 of file sfs_inode.c.
References ENOMEM, KASSERT, kfree(), kmalloc(), NULL, num, ops, panic(), sfs_superblock::sb_volname, sfs_dinode::sfi_type, sfs_fs::sfs_absfs, sfs_bused(), sfs_dirops, sfs_fileops, sfs_readblock(), sfs_fs::sfs_sb, SFS_TYPE_DIR, SFS_TYPE_FILE, SFS_TYPE_INVAL, sfs_fs::sfs_vnodes, sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, vnode::vn_data, vnode_cleanup(), vnode_init(), and VOP_INCREF.
Referenced by sfs_creat(), sfs_getroot(), sfs_lookonce(), and sfs_makeobj().
sfs_lookonce()
int sfs_lookonce (struct sfs_vnode * sv, const char * name, struct sfs_vnode ** ret, int * slot)
Definition at line 213 of file sfs_dir.c.
References fs::fs_data, name, NULL, panic(), sfs_superblock::sb_volname, sfs_dir_findname(), sfs_loadvnode(), sfs_fs::sfs_sb, SFS_TYPE_INVAL, sfs_vnode::sv_absvn, sfs_vnode::sv_ino, and vnode::vn_fs.
Referenced by sfs_lookup(), sfs_remove(), and sfs_rename().
sfs_makeobj()
int sfs_makeobj (struct sfs_fs * sfs, int type, struct sfs_vnode ** ret)
Definition at line 262 of file sfs_inode.c.
References sfs_balloc(), sfs_bfree(), and sfs_loadvnode().
Referenced by sfs_creat().
sfs_metaio()
int sfs_metaio (struct sfs_vnode * sv, off_t pos, void * data, size_t len, enum uio_rw rw)
Definition at line 406 of file sfs_io.c.
References bzero(), fs::fs_data, KASSERT, memcpy(), sfs_dinode::sfi_size, SFS_BLOCKSIZE, sfs_bmap(), sfs_readblock(), sfs_writeblock(), sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, UIO_READ, UIO_WRITE, vfs_biglock_do_i_hold(), and vnode::vn_fs.
Referenced by sfs_readdir(), and sfs_writedir().
sfs_readblock()
int sfs_readblock (struct sfs_fs * sfs, daddr_t block, void * data, size_t len)
Definition at line 108 of file sfs_io.c.
References KASSERT, SFS_BLOCKSIZE, sfs_rwblock(), SFSUIO, and UIO_READ.
Referenced by sfs_bmap(), sfs_domount(), sfs_freemapio(), sfs_itrunc(), sfs_loadvnode(), sfs_metaio(), and sfs_partialio().
sfs_reclaim()
int sfs_reclaim (struct vnode * v)
Definition at line 69 of file sfs_inode.c.
References EBUSY, fs::fs_data, KASSERT, kfree(), num, panic(), sfs_superblock::sb_volname, sfs_dinode::sfi_linkcount, sfs_bfree(), sfs_itrunc(), sfs_fs::sfs_sb, sfs_sync_inode(), sfs_fs::sfs_vnodes, spinlock_acquire(), spinlock_release(), sfs_vnode::sv_absvn, sfs_vnode::sv_i, sfs_vnode::sv_ino, vfs_biglock_acquire(), vfs_biglock_release(), vnode::vn_countlock, vnode::vn_data, vnode::vn_fs, vnode::vn_refcount, and vnode_cleanup().
sfs_sync_inode()
int sfs_sync_inode (struct sfs_vnode * sv)
Definition at line 47 of file sfs_inode.c.
References fs::fs_data, sfs_writeblock(), sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, sfs_vnode::sv_ino, and vnode::vn_fs.
Referenced by sfs_fsync(), and sfs_reclaim().
sfs_writeblock()
int sfs_writeblock (struct sfs_fs * sfs, daddr_t block, void * data, size_t len)
Definition at line 123 of file sfs_io.c.
References KASSERT, SFS_BLOCKSIZE, sfs_rwblock(), SFSUIO, and UIO_WRITE.
Referenced by sfs_bmap(), sfs_clearblock(), sfs_freemapio(), sfs_itrunc(), sfs_metaio(), sfs_partialio(), sfs_sync_inode(), and sfs_sync_superblock().
Variable Documentation
sfs_dirops
const struct vnode_ops sfs_dirops
Definition at line 621 of file sfs_vnops.c.
Referenced by sfs_loadvnode().
sfs_fileops
const struct vnode_ops sfs_fileops
Definition at line 587 of file sfs_vnops.c.
Referenced by sfs_loadvnode().