os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/sfsck/sfs.h File Reference
sfs.h File Reference
#include <stdint.h>
Functions
void sfs_setup (void)
void sfs_readsb (uint32_t blocknum, struct sfs_superblock *sb)
void sfs_writesb (uint32_t blocknum, struct sfs_superblock *sb)
void sfs_readfreemapblock (uint32_t whichblock, uint8_t *bits)
void sfs_writefreemapblock (uint32_t whichblock, uint8_t *bits)
void sfs_readinode (uint32_t inum, struct sfs_dinode *sfi)
void sfs_writeinode (uint32_t inum, struct sfs_dinode *sfi)
void sfs_readindirect (uint32_t blocknum, uint32_t *entries)
void sfs_writeindirect (uint32_t blocknum, uint32_t *entries)
void sfs_readdir (struct sfs_dinode *sfi, struct sfs_direntry *d, unsigned nd)
void sfs_writedir (const struct sfs_dinode *sfi, struct sfs_direntry *d, unsigned nd)
int sfsdir_tryadd (struct sfs_direntry *d, int nd, const char *name, uint32_t ino)
void sfsdir_sort (struct sfs_direntry *d, unsigned nd, int *vector)
Function Documentation
sfs_readdir()
void sfs_readdir (struct sfs_dinode * sfi, struct sfs_direntry * d, unsigned nd)
Definition at line 298 of file sfs.c.
References assert, bmap(), buffer, nblocks, SFS_BLOCKSIZE, sfs_readdirblock(), and SFS_ROUNDUP.
sfs_readfreemapblock()
void sfs_readfreemapblock (uint32_t whichblock, uint8_t * bits)
Definition at line 215 of file sfs.c.
References diskread(), SFS_FREEMAP_START, and swapbits().
Referenced by freemap_check().
sfs_readindirect()
void sfs_readindirect (uint32_t blocknum, uint32_t * entries)
Definition at line 253 of file sfs.c.
References diskread(), and swapindir().
Referenced by check_indirect_block().
sfs_readinode()
void sfs_readinode (uint32_t inum, struct sfs_dinode * sfi)
Definition at line 234 of file sfs.c.
References diskread(), and swapinode().
Referenced by inode_adjust_filelinks(), pass1_dir(), pass1_rootdir(), and pass2_dir().
sfs_readsb()
void sfs_readsb (uint32_t blocknum, struct sfs_superblock * sb)
Definition at line 195 of file sfs.c.
References diskread(), sb, and swapsb().
Referenced by sb_load().
sfs_setup()
void sfs_setup (void)
Definition at line 49 of file sfs.c.
References assert, and SFS_BLOCKSIZE.
Referenced by main().
sfs_writedir()
void sfs_writedir (const struct sfs_dinode * sfi, struct sfs_direntry * d, unsigned nd)
Definition at line 363 of file sfs.c.
References assert, bmap(), buffer, memset(), nblocks, SFS_BLOCKSIZE, SFS_ROUNDUP, and sfs_writedirblock().
sfs_writefreemapblock()
void sfs_writefreemapblock (uint32_t whichblock, uint8_t * bits)
Definition at line 222 of file sfs.c.
References diskwrite(), SFS_FREEMAP_START, and swapbits().
Referenced by freemap_check().
sfs_writeindirect()
void sfs_writeindirect (uint32_t blocknum, uint32_t * entries)
Definition at line 260 of file sfs.c.
References diskwrite(), and swapindir().
Referenced by check_indirect_block().
sfs_writeinode()
void sfs_writeinode (uint32_t inum, struct sfs_dinode * sfi)
Definition at line 241 of file sfs.c.
References diskwrite(), and swapinode().
Referenced by inode_adjust_filelinks(), pass1_inode(), pass1_rootdir(), and pass2_dir().
sfs_writesb()
void sfs_writesb (uint32_t blocknum, struct sfs_superblock * sb)
Definition at line 202 of file sfs.c.
References diskwrite(), sb, and swapsb().
Referenced by sb_check().
sfsdir_sort()
void sfsdir_sort (struct sfs_direntry * d, unsigned nd, int * vector)
Definition at line 433 of file sfs.c.
References dirsortfunc(), global_sortdirs, and qsort().
Referenced by pass2_dir().
sfsdir_tryadd()
int sfsdir_tryadd (struct sfs_direntry * d, int nd, const char * name, uint32_t ino)
Definition at line 452 of file sfs.c.
References assert, name, sfs_direntry::sfd_ino, sfs_direntry::sfd_name, SFS_NOINO, strcpy(), and strlen().
Referenced by pass2_dir().