os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/dev/generic/console.c File Reference
console.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <uio.h>
#include <cpu.h>
#include <thread.h>
#include <current.h>
#include <synch.h>
#include <generic/console.h>
#include <vfs.h>
#include <device.h>
#include "autoconf.h"
Macros
#define DELAYBUFSIZE 1024
Functions
static void putch_delayed (int ch)
static void flush_delay_buf (void)
static void putch_polled (struct con_softc *cs, int ch)
static void putch_intr (struct con_softc *cs, int ch)
static int getch_intr (struct con_softc *cs)
void con_input (void *vcs, int ch)
void con_start (void *vcs)
void putch (int ch)
int getch (void)
static int con_eachopen (struct device *dev, int openflags)
static int con_io (struct device *dev, struct uio *uio)
static int con_ioctl (struct device *dev, int op, userptr_t data)
static int attach_console_to_vfs (struct con_softc *cs)
int config_con (struct con_softc *cs, int unit)
Variables
static struct con_softc * the_console = NULL
static struct lock * con_userlock_read = NULL
static struct lock * con_userlock_write = NULL
static char delayed_outbuf [DELAYBUFSIZE]
static size_t delayed_outbuf_pos =0
static const struct device_ops console_devops
Macro Definition Documentation
DELAYBUFSIZE
#define DELAYBUFSIZE 1024
Definition at line 82 of file console.c.
Function Documentation
attach_console_to_vfs()
static int attach_console_to_vfs (struct con_softc * cs) static
Definition at line 313 of file console.c.
References console_devops, device::d_blocks, device::d_blocksize, device::d_data, device::d_ops, ENOMEM, kfree(), kmalloc(), NULL, and vfs_adddev().
Referenced by config_con().
con_eachopen()
static int con_eachopen (struct device * dev, int openflags) static
Definition at line 236 of file console.c.
con_input()
void con_input (void * vcs, int ch)
Definition at line 162 of file console.c.
References ch, CONSOLE_INPUT_BUFFER_SIZE, con_softc::cs_gotchars, con_softc::cs_gotchars_head, con_softc::cs_gotchars_tail, con_softc::cs_rsem, and V().
Referenced by attach_con_to_lscreen(), and attach_con_to_lser().
con_io()
static int con_io (struct device * dev, struct uio * uio) static
Definition at line 245 of file console.c.
References ch, con_userlock_read, con_userlock_write, getch(), KASSERT, lock_acquire(), lock_release(), NULL, putch(), UIO_READ, uio::uio_resid, uio::uio_rw, and uiomove().
con_ioctl()
static int con_ioctl (struct device * dev, int op, userptr_t data) static
Definition at line 296 of file console.c.
References EINVAL.
con_start()
void con_start (void * vcs)
Definition at line 183 of file console.c.
References con_softc::cs_wsem, and V().
Referenced by attach_con_to_lscreen(), and attach_con_to_lser().
config_con()
int config_con (struct con_softc * cs, int unit)
Definition at line 344 of file console.c.
References attach_console_to_vfs(), con_userlock_read, con_userlock_write, con_softc::cs_gotchars_head, con_softc::cs_gotchars_tail, con_softc::cs_rsem, con_softc::cs_wsem, ENODEV, ENOMEM, flush_delay_buf(), KASSERT, lock_create(), lock_destroy(), NULL, sem_create(), sem_destroy(), and the_console.
Referenced by tryattach_con_to_lser().
flush_delay_buf()
static void flush_delay_buf (void) static
Definition at line 101 of file console.c.
References delayed_outbuf, delayed_outbuf_pos, and putch().
Referenced by config_con().
getch()
int getch (void)
Definition at line 219 of file console.c.
References getch_intr(), KASSERT, NULL, and the_console.
Referenced by con_io(), and kgets().
getch_intr()
static int getch_intr (struct con_softc * cs) static
Definition at line 141 of file console.c.
References CONSOLE_INPUT_BUFFER_SIZE, con_softc::cs_gotchars, con_softc::cs_gotchars_tail, con_softc::cs_rsem, and P().
Referenced by getch().
putch()
void putch (int ch)
Definition at line 201 of file console.c.
References ch, NULL, putch_delayed(), putch_intr(), putch_polled(), and the_console.
Referenced by backsp(), con_io(), console_send(), flush_delay_buf(), kgets(), loudthread(), and quietthread().
putch_delayed()
static void putch_delayed (int ch) static
Definition at line 88 of file console.c.
References ch, delayed_outbuf, delayed_outbuf_pos, and KASSERT.
Referenced by putch().
putch_intr()
static void putch_intr (struct con_softc * cs, int ch) static
Definition at line 130 of file console.c.
References ch, con_softc::cs_devdata, con_softc::cs_send, con_softc::cs_wsem, and P().
Referenced by putch().
putch_polled()
static void putch_polled (struct con_softc * cs, int ch) static
Definition at line 118 of file console.c.
References ch, con_softc::cs_devdata, and con_softc::cs_sendpolled.
Referenced by putch().
Variable Documentation
con_userlock_read
struct lock* con_userlock_read = NULL static
Definition at line 72 of file console.c.
Referenced by con_io(), and config_con().
con_userlock_write
struct lock* con_userlock_write = NULL static
Definition at line 73 of file console.c.
Referenced by con_io(), and config_con().
console_devops
const struct device_ops console_devops static
Initial value:
= {
    .devop_eachopen = con_eachopen,
    .devop_io = con_io,
    .devop_ioctl = con_ioctl,
}
Definition at line 305 of file console.c.
Referenced by attach_console_to_vfs().
delayed_outbuf
char delayed_outbuf[DELAYBUFSIZE] static
Definition at line 83 of file console.c.
Referenced by flush_delay_buf(), and putch_delayed().
delayed_outbuf_pos
size_t delayed_outbuf_pos =0 static
Definition at line 84 of file console.c.
Referenced by flush_delay_buf(), and putch_delayed().
the_console
struct con_softc* the_console = NULL static
Definition at line 66 of file console.c.
Referenced by config_con(), getch(), and putch().