os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/thread/synch.c File Reference
synch.c File Reference
#include <types.h>
#include <lib.h>
#include <spinlock.h>
#include <wchan.h>
#include <thread.h>
#include <current.h>
#include <synch.h>
Functions
struct semaphore * sem_create (const char *name, unsigned initial_count)
void sem_destroy (struct semaphore *sem)
void P (struct semaphore *sem)
void V (struct semaphore *sem)
struct lock * lock_create (const char *name)
void lock_destroy (struct lock *lock)
void lock_acquire (struct lock *lock)
void lock_release (struct lock *lock)
bool lock_do_i_hold (struct lock *lock)
struct cv * cv_create (const char *name)
void cv_destroy (struct cv *cv)
void cv_wait (struct cv *cv, struct lock *lock)
void cv_signal (struct cv *cv, struct lock *lock)
void cv_broadcast (struct cv *cv, struct lock *lock)
Function Documentation
cv_broadcast()
void cv_broadcast (struct cv * cv, struct lock * lock)
Definition at line 264 of file synch.c.
Referenced by cvtestthread(), and semfs_wakeup().
cv_create()
struct cv* cv_create (const char * name)
Definition at line 216 of file synch.c.
References cv::cv_name, kfree(), kmalloc(), kstrdup(), name, and NULL.
Referenced by cvtest2(), inititems(), and semfs_sem_create().
cv_destroy()
void cv_destroy (struct cv * cv)
Definition at line 237 of file synch.c.
References cv::cv_name, KASSERT, kfree(), and NULL.
Referenced by cvtest2(), and semfs_sem_destroy().
cv_signal()
void cv_signal (struct cv * cv, struct lock * lock)
Definition at line 256 of file synch.c.
Referenced by semfs_wakeup(), and wakethread().
cv_wait()
void cv_wait (struct cv * cv, struct lock * lock)
Definition at line 248 of file synch.c.
Referenced by cvtestthread(), semfs_read(), and sleepthread().
lock_acquire()
void lock_acquire (struct lock * lock)
Definition at line 176 of file synch.c.
Referenced by cmd_deadlock(), cmd_deadlockthread(), con_io(), cvtestthread(), emu_close(), emu_doread(), emu_getsize(), emu_open(), emu_trunc(), emu_write(), emufs_loadvnode(), emufs_reclaim(), kprintf(), locktestthread(), semfs_creat(), semfs_dirstat(), semfs_getdirentry(), semfs_getsembynum(), semfs_getvnode(), semfs_lookup(), semfs_read(), semfs_reclaim(), semfs_remove(), semfs_semstat(), semfs_truncate(), semfs_unmount(), semfs_write(), sleepthread(), vfs_biglock_acquire(), and wakethread().
lock_create()
struct lock* lock_create (const char * name)
Definition at line 142 of file synch.c.
References HANGMAN_LOCKABLEINIT, kfree(), kmalloc(), kstrdup(), lock::lk_name, name, and NULL.
Referenced by cmd_deadlock(), config_con(), config_emu(), cvtest2(), inititems(), kprintf_bootstrap(), semfs_create(), semfs_sem_create(), and vfs_bootstrap().
lock_destroy()
void lock_destroy (struct lock * lock)
Definition at line 165 of file synch.c.
References KASSERT, kfree(), lock::lk_name, and NULL.
Referenced by cmd_deadlock(), config_con(), config_emu(), cvtest2(), semfs_create(), semfs_destroy(), semfs_sem_create(), and semfs_sem_destroy().
lock_do_i_hold()
bool lock_do_i_hold (struct lock * lock)
Definition at line 201 of file synch.c.
Referenced by emu_close(), semfs_sem_insert(), vfs_biglock_acquire(), vfs_biglock_do_i_hold(), and vfs_biglock_release().
lock_release()
void lock_release (struct lock * lock)
Definition at line 190 of file synch.c.
Referenced by cmd_deadlock(), cmd_deadlockthread(), con_io(), cvtestthread(), emu_close(), emu_doread(), emu_getsize(), emu_open(), emu_trunc(), emu_write(), emufs_loadvnode(), emufs_reclaim(), fail(), kprintf(), locktestthread(), semfs_creat(), semfs_dirstat(), semfs_getdirentry(), semfs_getsembynum(), semfs_getvnode(), semfs_lookup(), semfs_read(), semfs_reclaim(), semfs_remove(), semfs_semstat(), semfs_truncate(), semfs_unmount(), semfs_write(), sleepthread(), vfs_biglock_release(), and wakethread().
P()
void P (struct semaphore * sem)
Definition at line 89 of file synch.c.
References KASSERT, NULL, semaphore::sem_count, semaphore::sem_lock, semaphore::sem_wchan, spinlock_acquire(), spinlock_release(), and wchan_sleep().
Referenced by cvtest(), cvtest2(), docreatestress(), dolongstress(), doreadstress(), dowritestress(), dowritestress2(), emu_waitdone(), finish(), getch_intr(), kmallocstress(), kmalloctest4(), lhd_io(), locktest(), pong_cyclic(), pong_reciprocating(), putch_intr(), runthreads(), semtest(), semtestthread(), semu16(), semu17_sub(), semu18(), semu19(), semu20(), semu21(), semu22(), thread_start_cpus(), waiter(), waitstart(), waker_thread(), and wakethread().
sem_create()
struct semaphore* sem_create (const char * name, unsigned initial_count)
Definition at line 48 of file synch.c.
References kfree(), kmalloc(), kstrdup(), name, NULL, semaphore::sem_count, semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, spinlock_init(), and wchan_create().
Referenced by config_con(), config_emu(), config_lhd(), cvtest2(), init_sem(), init_threadsem(), inititems(), kmallocstress(), kmalloctest4(), makesem(), semu1(), semu2(), semu5(), setup(), and thread_start_cpus().
sem_destroy()
void sem_destroy (struct semaphore * sem)
Definition at line 77 of file synch.c.
References KASSERT, kfree(), NULL, semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, spinlock_cleanup(), and wchan_destroy().
Referenced by config_con(), config_lhd(), cvtest2(), do_semu1011(), do_semu89(), kmallocstress(), kmalloctest4(), semu1(), semu1213(), semu16(), semu17(), semu3(), semu4(), semu5(), semu6(), semu7(), and thread_start_cpus().
V()
void V (struct semaphore * sem)
Definition at line 124 of file synch.c.
References KASSERT, NULL, semaphore::sem_count, semaphore::sem_lock, semaphore::sem_wchan, spinlock_acquire(), spinlock_release(), and wchan_wakeone().
Referenced by compute_thread(), con_input(), con_start(), cpu_hatch(), createstress_thread(), cvtestthread(), do_semu1011(), do_semu89(), emu_irq(), fail(), finish(), kmalloctest4thread(), kmallocthread(), lhd_io(), lhd_iodone(), locktestthread(), longstress_thread(), loudthread(), pong_cyclic(), pong_reciprocating(), quietthread(), readstress_thread(), semtest(), semtestthread(), semu1213(), semu14(), semu15(), semu17(), semu19_sub(), semu7(), sleepalot_thread(), sleepthread(), waker_thread(), wakethread(), writestress2_thread(), and writestress_thread().