os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/dev/generic/random.c File Reference
random.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <lib.h>
#include <uio.h>
#include <vfs.h>
#include <generic/random.h>
#include "autoconf.h"
Functions
static int randeachopen (struct device *dev, int openflags)
static int randio (struct device *dev, struct uio *uio)
static int randioctl (struct device *dev, int op, userptr_t data)
int config_random (struct random_softc *rs, int unit)
uint32_t random (void)
uint32_t randmax (void)
Variables
static struct random_softc * the_random = NULL
static const struct device_ops random_devops
Function Documentation
config_random()
int config_random (struct random_softc * rs, int unit)
Definition at line 111 of file random.c.
References device::d_blocks, device::d_blocksize, device::d_data, device::d_ops, ENODEV, KASSERT, NULL, random_devops, random_softc::rs_dev, the_random, and vfs_adddev().
Referenced by tryattach_random_to_lrandom().
randeachopen()
static int randeachopen (struct device * dev, int openflags) static
Definition at line 58 of file random.c.
References EIO, and O_RDONLY.
randio()
static int randio (struct device * dev, struct uio * uio) static
Definition at line 74 of file random.c.
References device::d_data, EIO, random_softc::rs_devdata, random_softc::rs_read, UIO_READ, and uio::uio_rw.
randioctl()
static int randioctl (struct device * dev, int op, userptr_t data) static
Definition at line 90 of file random.c.
References EIOCTL.
randmax()
uint32_t randmax (void)
Definition at line 152 of file random.c.
References NULL, panic(), random_softc::rs_devdata, random_softc::rs_randmax, and the_random.
random()
uint32_t random (void)
Definition at line 143 of file random.c.
Variable Documentation
random_devops
const struct device_ops random_devops static
Initial value:
= {
    .devop_eachopen = randeachopen,
    .devop_io = randio,
    .devop_ioctl = randioctl,
}
Definition at line 101 of file random.c.
Referenced by config_random().
the_random
struct random_softc* the_random = NULL static
Definition at line 50 of file random.c.
Referenced by config_random(), randmax(), and random().