os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/sfsck/main.c File Reference
main.c File Reference
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <err.h>
#include "compat.h"
#include "disk.h"
#include "sfs.h"
#include "sb.h"
#include "freemap.h"
#include "inode.h"
#include "passes.h"
#include "main.h"
Functions
void setbadness (int code)
int main (int argc, char **argv)
Variables
static int badness =0
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 65 of file main.c.
References assert, badness, closedisk(), errx(), EXIT_CLEAN, EXIT_FATAL, EXIT_RECOV, EXIT_UNRECOV, EXIT_USAGE, freemap_blocksused(), freemap_check(), freemap_setup(), hostcompat_init(), inode_adjust_filelinks(), inode_sorttable(), opendisk(), pass1(), pass1_founddirs(), pass1_foundfiles(), pass2(), printf(), sb_check(), sb_load(), sb_totalblocks(), sfs_setup(), and warnx().
setbadness()
void setbadness (int code)
Definition at line 54 of file main.c.
References badness.
Referenced by check_indirect_block(), check_inode_blocks(), freemap_blockinuse(), freemap_check(), inode_adjust_filelinks(), pass1_dir(), pass1_direntry(), pass1_inode(), pass1_rootdir(), pass2_dir(), sb_check(), and sfs_writedirblock().
Variable Documentation
badness
int badness =0 static
Definition at line 45 of file main.c.
Referenced by main(), and setbadness().