os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_readlink.c File Reference
bad_readlink.c File Reference
#include <unistd.h>
#include <errno.h>
#include "test.h"
Functions
static void readlink_file (void)
static void readlink_dir (void)
static void readlink_empty (void)
void test_readlink (void)
Function Documentation
readlink_dir()
static void readlink_dir (void) static
Definition at line 60 of file bad_readlink.c.
References buf, EISDIR, errno, readlink(), report_begin(), and report_check().
Referenced by test_readlink().
readlink_empty()
static void readlink_empty (void) static
Definition at line 72 of file bad_readlink.c.
References buf, EINVAL, EISDIR, errno, readlink(), report_begin(), and report_check2().
Referenced by test_readlink().
readlink_file()
static void readlink_file (void) static
Definition at line 41 of file bad_readlink.c.
References buf, close(), EINVAL, errno, fd, open_testfile(), readlink(), remove(), report_aborted(), report_begin(), report_check(), and TESTFILE.
Referenced by test_readlink().
test_readlink()
void test_readlink (void)
Definition at line 83 of file bad_readlink.c.
References readlink_dir(), readlink_empty(), readlink_file(), test_readlink_buf(), and test_readlink_path().