os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/frack/workloads.c File Reference
workloads.c File Reference
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <assert.h>
#include <errno.h>
#include <err.h>
#include "ops.h"
#include "workloads.h"
#include <stdio.h>
Macros
#define false 0
#define true 1
#define BLOCKSIZE /*SFS_BLOCKSIZE*/ 512
#define ISNT 0
#define IS_FILE 1
#define IS_DIR 2
Typedefs
typedef unsigned bool
Enumerations
enum sizes {
SIZE_ONE, SIZE_SMALL, SIZE_MEDIUM, SIZE_LARGE,
SIZE_LARGEPLUS
}
Functions
static unsigned long getnum (const char *str)
static enum sizes strtosize (const char *word)
static enum sizes randsize (void)
static enum sizes nextsmallersize (enum sizes sz)
static enum sizes nextlargersize (enum sizes sz)
static unsigned sizeblocks (enum sizes sz)
static unsigned sizebytes (enum sizes sz)
static void file_randomwrite (struct file *f, enum sizes sz, unsigned startskip, unsigned endskip)
static void writeemptyfile (unsigned filenum)
static void writeoutfile (unsigned testcode, unsigned filenum, unsigned openflags, enum sizes sz)
static void writenewfile (unsigned testcode, unsigned filenum, enum sizes sz)
static void writeholeyfile (unsigned testcode, unsigned filenum, enum sizes sz)
static void makesubtree (unsigned testcode, unsigned filenum)
void wl_createwrite (const char *size)
void wl_rewrite (const char *size)
void wl_randupdate (const char *size)
void wl_truncwrite (const char *size)
void wl_makehole (const char *size)
void wl_fillhole (const char *size)
void wl_truncfill (const char *size)
void wl_append (const char *size)
void wl_trunczero (const char *size)
void wl_trunconeblock (const char *size)
void wl_truncsmallersize (const char *size)
void wl_trunclargersize (const char *size)
void wl_appendandtrunczero (const char *size)
void wl_appendandtruncpartly (const char *size)
void wl_mkfile (void)
void wl_mkdir (void)
void wl_mkmanyfile (void)
void wl_mkmanydir (void)
static void wl_mktree_sub (unsigned testcode, unsigned depth)
static void wl_rmtree_sub (unsigned depth)
void wl_mktree (void)
static void mkrandtree_sub (unsigned testcode, unsigned depth, unsigned *ct, unsigned numthings)
static void rmrandtree_sub (unsigned depth, unsigned *ct, unsigned numthings)
void wl_mkrandtree (const char *seed)
void wl_rmfile (void)
void wl_rmdir (void)
void wl_rmfiledelayed (void)
void wl_rmfiledelayedappend (void)
void wl_rmdirdelayed (void)
void wl_rmmanyfile (void)
void wl_rmmanyfiledelayed (void)
void wl_rmmanyfiledelayedandappend (void)
void wl_rmmanydir (void)
void wl_rmmanydirdelayed (void)
void wl_rmtree (void)
void wl_rmrandtree (const char *seed)
void wl_linkfile (void)
void wl_linkmanyfile (void)
void wl_unlinkfile (void)
void wl_unlinkmanyfile (void)
void wl_linkunlinkfile (void)
void wl_renamefile (void)
void wl_renamedir (void)
void wl_renamesubtree (void)
void wl_renamexdfile (void)
void wl_renamexddir (void)
void wl_renamexdsubtree (void)
void wl_renamemanyfile (void)
void wl_renamemanydir (void)
void wl_renamemanysubtree (void)
void wl_copyandrename (void)
void wl_untar (void)
void wl_compile (void)
void wl_cvsupdate (void)
static void createfiles (unsigned testcode, unsigned num, enum sizes sz)
static void openfiles (unsigned testcode, struct file **files, unsigned opennum, unsigned totnum)
static void randwrite (struct file *file)
static void randtruncate (struct file *file)
void wl_writefileseq (const char *seed)
void wl_writetruncseq (const char *seed)
void wl_mkrmseq (const char *seed)
void wl_linkunlinkseq (const char *seed)
void wl_renameseq (const char *seed)
static bool randop (unsigned testcode, unsigned *exists, unsigned numfiles, bool dofileops, struct file **files)
static void prep (unsigned testcode, unsigned *exists, unsigned numfiles, bool dofileops, struct file **files)
void wl_diropseq (const char *seed)
void wl_genseq (const char *seed)
Macro Definition Documentation
BLOCKSIZE
#define BLOCKSIZE /*SFS_BLOCKSIZE*/ 512
false
#define false 0
Definition at line 42 of file workloads.c.
IS_DIR
#define IS_DIR 2
Definition at line 1592 of file workloads.c.
IS_FILE
#define IS_FILE 1
Definition at line 1591 of file workloads.c.
ISNT
#define ISNT 0
Definition at line 1590 of file workloads.c.
true
#define true 1
Definition at line 43 of file workloads.c.
Typedef Documentation
bool
typedef unsigned bool
Definition at line 41 of file workloads.c.
Enumeration Type Documentation
sizes
enum sizes
Enumerator
SIZE_ONE
SIZE_SMALL
SIZE_MEDIUM
SIZE_LARGE
SIZE_LARGEPLUS
Definition at line 77 of file workloads.c.
Function Documentation
createfiles()
static void createfiles (unsigned testcode, unsigned num, enum sizes sz) static
Definition at line 1355 of file workloads.c.
References num, and writenewfile().
Referenced by wl_writefileseq(), and wl_writetruncseq().
file_randomwrite()
static void file_randomwrite (struct file * f, enum sizes sz, unsigned startskip, unsigned endskip) static
Definition at line 215 of file workloads.c.
References assert, BLOCKSIZE, f, nblocks, op_write(), pos, random(), and sizeblocks().
Referenced by wl_fillhole(), wl_randupdate(), and wl_truncfill().
getnum()
static unsigned long getnum (const char * str) static
Definition at line 54 of file workloads.c.
References atoi(), err(), errno, errx(), and strlen().
Referenced by wl_diropseq(), wl_genseq(), wl_linkunlinkseq(), wl_mkrandtree(), wl_mkrmseq(), wl_renameseq(), wl_rmrandtree(), wl_writefileseq(), and wl_writetruncseq().
makesubtree()
static void makesubtree (unsigned testcode, unsigned filenum) static
Definition at line 286 of file workloads.c.
References op_chdir(), op_chdirup(), op_mkdir(), SIZE_ONE, file::testcode, and writenewfile().
Referenced by wl_renamemanysubtree(), wl_renamesubtree(), wl_renamexdsubtree(), and wl_untar().
mkrandtree_sub()
static void mkrandtree_sub (unsigned testcode, unsigned depth, unsigned * ct, unsigned numthings) static
Definition at line 705 of file workloads.c.
References op_chdir(), op_chdirup(), op_mkdir(), random(), SIZE_ONE, file::testcode, and writenewfile().
Referenced by wl_mkrandtree(), and wl_rmrandtree().
nextlargersize()
static enum sizes nextlargersize (enum sizes sz) static
Definition at line 153 of file workloads.c.
References assert, SIZE_LARGE, SIZE_LARGEPLUS, SIZE_MEDIUM, SIZE_ONE, and SIZE_SMALL.
Referenced by wl_trunclargersize().
nextsmallersize()
static enum sizes nextsmallersize (enum sizes sz) static
Definition at line 133 of file workloads.c.
References assert, SIZE_LARGE, SIZE_LARGEPLUS, SIZE_MEDIUM, SIZE_ONE, and SIZE_SMALL.
Referenced by wl_truncsmallersize().
openfiles()
static void openfiles (unsigned testcode, struct file ** files, unsigned opennum, unsigned totnum) static
Definition at line 1366 of file workloads.c.
References NULL, and op_open().
Referenced by wl_writefileseq(), and wl_writetruncseq().
prep()
static void prep (unsigned testcode, unsigned * exists, unsigned numfiles, bool dofileops, struct file ** files) static
Definition at line 1719 of file workloads.c.
References IS_DIR, IS_FILE, ISNT, NULL, op_mkdir(), SIZE_ONE, file::testcode, and writenewfile().
Referenced by forkem(), runtaskgroup(), wl_diropseq(), and wl_genseq().
randop()
static bool randop (unsigned testcode, unsigned * exists, unsigned numfiles, bool dofileops, struct file ** files) static
Definition at line 1596 of file workloads.c.
References assert, IS_DIR, IS_FILE, ISNT, NULL, op_close(), op_link(), op_mkdir(), op_open(), op_rename(), op_rmdir(), op_unlink(), random(), randsize(), randtruncate(), randwrite(), SIZE_ONE, file::testcode, and writenewfile().
Referenced by wl_diropseq(), and wl_genseq().
randsize()
static enum sizes randsize (void) static
Definition at line 109 of file workloads.c.
References random(), SIZE_LARGE, SIZE_MEDIUM, SIZE_ONE, and SIZE_SMALL.
Referenced by randop(), try___getcwd(), try_getdirentry(), try_read(), try_readlink(), and try_write().
randtruncate()
static void randtruncate (struct file * file) static
Definition at line 1394 of file workloads.c.
References op_truncate(), random(), SIZE_MEDIUM, and sizebytes().
Referenced by randop(), and wl_writetruncseq().
randwrite()
static void randwrite (struct file * file) static
Definition at line 1381 of file workloads.c.
References op_write(), pos, random(), SIZE_MEDIUM, and sizebytes().
Referenced by randop(), wl_writefileseq(), and wl_writetruncseq().
rmrandtree_sub()
static void rmrandtree_sub (unsigned depth, unsigned * ct, unsigned numthings) static
Definition at line 738 of file workloads.c.
References op_chdir(), op_chdirup(), op_rmdir(), op_unlink(), and random().
Referenced by wl_rmrandtree().
sizeblocks()
static unsigned sizeblocks (enum sizes sz) static
Definition at line 173 of file workloads.c.
References assert, SIZE_LARGE, SIZE_LARGEPLUS, SIZE_MEDIUM, SIZE_ONE, and SIZE_SMALL.
Referenced by file_randomwrite(), and sizebytes().
sizebytes()
static unsigned sizebytes (enum sizes sz) static
Definition at line 205 of file workloads.c.
References BLOCKSIZE, and sizeblocks().
Referenced by randtruncate(), randwrite(), wl_append(), wl_appendandtruncpartly(), wl_appendandtrunczero(), wl_rmfiledelayedappend(), wl_rmmanyfiledelayedandappend(), wl_truncfill(), wl_trunclargersize(), wl_trunconeblock(), wl_truncsmallersize(), writeholeyfile(), and writeoutfile().
strtosize()
static enum sizes strtosize (const char * word) static
Definition at line 91 of file workloads.c.
References errx(), SIZE_LARGE, SIZE_MEDIUM, SIZE_SMALL, and strcmp().
Referenced by wl_append(), wl_appendandtruncpartly(), wl_appendandtrunczero(), wl_createwrite(), wl_fillhole(), wl_makehole(), wl_randupdate(), wl_rewrite(), wl_truncfill(), wl_trunclargersize(), wl_trunconeblock(), wl_truncsmallersize(), wl_truncwrite(), and wl_trunczero().
wl_append()
void wl_append (const char * size)
Definition at line 458 of file workloads.c.
References BLOCKSIZE, f, op_close(), op_open(), op_sync(), op_write(), sizebytes(), strtosize(), file::testcode, and writenewfile().
wl_appendandtruncpartly()
void wl_appendandtruncpartly (const char * size)
Definition at line 576 of file workloads.c.
References BLOCKSIZE, f, op_close(), op_open(), op_sync(), op_truncate(), op_write(), sizebytes(), strtosize(), file::testcode, and writenewfile().
wl_appendandtrunczero()
void wl_appendandtrunczero (const char * size)
Definition at line 555 of file workloads.c.
References BLOCKSIZE, f, op_close(), op_open(), op_sync(), op_truncate(), op_write(), sizebytes(), strtosize(), file::testcode, and writenewfile().
wl_compile()
void wl_compile (void)
Definition at line 1319 of file workloads.c.
References errx(), op_sync(), SIZE_MEDIUM, SIZE_SMALL, and writenewfile().
wl_copyandrename()
void wl_copyandrename (void)
Definition at line 1291 of file workloads.c.
References op_rename(), op_sync(), SIZE_MEDIUM, writeemptyfile(), and writenewfile().
wl_createwrite()
void wl_createwrite (const char * size)
Definition at line 330 of file workloads.c.
References strtosize(), file::testcode, and writenewfile().
wl_cvsupdate()
void wl_cvsupdate (void)
Definition at line 1343 of file workloads.c.
References errx().
wl_diropseq()
void wl_diropseq (const char * seed)
Definition at line 1745 of file workloads.c.
References getnum(), NULL, op_sync(), prep(), random(), randop(), srandom(), and file::testcode.
wl_fillhole()
void wl_fillhole (const char * size)
Definition at line 415 of file workloads.c.
References f, file_randomwrite(), op_close(), op_open(), op_sync(), srandom(), strtosize(), file::testcode, and writeholeyfile().
wl_genseq()
void wl_genseq (const char * seed)
Definition at line 1772 of file workloads.c.
References getnum(), op_sync(), prep(), random(), randop(), srandom(), and file::testcode.
wl_linkfile()
void wl_linkfile (void)
Definition at line 1052 of file workloads.c.
References op_link(), op_sync(), SIZE_ONE, and writenewfile().
wl_linkmanyfile()
void wl_linkmanyfile (void)
Definition at line 1065 of file workloads.c.
References op_link(), op_sync(), SIZE_ONE, and writenewfile().
wl_linkunlinkfile()
void wl_linkunlinkfile (void)
Definition at line 1126 of file workloads.c.
References op_link(), op_sync(), op_unlink(), SIZE_ONE, and writenewfile().
wl_linkunlinkseq()
void wl_linkunlinkseq (const char * seed)
Definition at line 1511 of file workloads.c.
References getnum(), op_link(), op_sync(), op_unlink(), random(), SIZE_ONE, srandom(), file::testcode, and writenewfile().
wl_makehole()
void wl_makehole (const char * size)
Definition at line 400 of file workloads.c.
References strtosize(), file::testcode, and writeholeyfile().
wl_mkdir()
void wl_mkdir (void)
Definition at line 611 of file workloads.c.
References op_mkdir().
wl_mkfile()
void wl_mkfile (void)
Definition at line 600 of file workloads.c.
References SIZE_ONE, file::testcode, and writenewfile().
wl_mkmanydir()
void wl_mkmanydir (void)
Definition at line 635 of file workloads.c.
References op_mkdir().
wl_mkmanyfile()
void wl_mkmanyfile (void)
Definition at line 620 of file workloads.c.
References SIZE_ONE, file::testcode, and writenewfile().
wl_mkrandtree()
void wl_mkrandtree (const char * seed)
Definition at line 769 of file workloads.c.
References count, getnum(), mkrandtree_sub(), random(), srandom(), and file::testcode.
wl_mkrmseq()
void wl_mkrmseq (const char * seed)
Definition at line 1477 of file workloads.c.
References getnum(), op_unlink(), random(), SIZE_ONE, srandom(), file::testcode, and writenewfile().
wl_mktree()
void wl_mktree (void)
Definition at line 692 of file workloads.c.
References file::testcode, and wl_mktree_sub().
wl_mktree_sub()
static void wl_mktree_sub (unsigned testcode, unsigned depth) static
Definition at line 651 of file workloads.c.
References op_chdir(), op_chdirup(), op_mkdir(), SIZE_ONE, file::testcode, and writenewfile().
Referenced by wl_mktree(), and wl_rmtree().
wl_randupdate()
void wl_randupdate (const char * size)
Definition at line 362 of file workloads.c.
References f, file_randomwrite(), op_close(), op_open(), op_sync(), srandom(), strtosize(), file::testcode, and writenewfile().
wl_renamedir()
void wl_renamedir (void)
Definition at line 1157 of file workloads.c.
References op_mkdir(), op_rename(), op_sync(), and writeemptyfile().
wl_renamefile()
void wl_renamefile (void)
Definition at line 1143 of file workloads.c.
References op_rename(), op_sync(), SIZE_ONE, writeemptyfile(), and writenewfile().
wl_renamemanydir()
void wl_renamemanydir (void)
Definition at line 1251 of file workloads.c.
References op_mkdir(), op_rename(), op_sync(), and writeemptyfile().
wl_renamemanyfile()
void wl_renamemanyfile (void)
Definition at line 1232 of file workloads.c.
References op_rename(), op_sync(), SIZE_ONE, writeemptyfile(), and writenewfile().
wl_renamemanysubtree()
void wl_renamemanysubtree (void)
Definition at line 1269 of file workloads.c.
References makesubtree(), op_rename(), op_sync(), and writeemptyfile().
wl_renameseq()
void wl_renameseq (const char * seed)
Definition at line 1550 of file workloads.c.
References getnum(), op_rename(), op_sync(), random(), SIZE_ONE, srandom(), file::testcode, and writenewfile().
wl_renamesubtree()
void wl_renamesubtree (void)
Definition at line 1169 of file workloads.c.
References makesubtree(), op_rename(), op_sync(), and writeemptyfile().
wl_renamexddir()
void wl_renamexddir (void)
Definition at line 1200 of file workloads.c.
References op_chdir(), op_chdirup(), op_mkdir(), op_renamexd(), and op_sync().
wl_renamexdfile()
void wl_renamexdfile (void)
Definition at line 1183 of file workloads.c.
References op_chdir(), op_chdirup(), op_mkdir(), op_renamexd(), op_sync(), SIZE_ONE, and writenewfile().
wl_renamexdsubtree()
void wl_renamexdsubtree (void)
Definition at line 1215 of file workloads.c.
References makesubtree(), op_chdir(), op_chdirup(), op_mkdir(), op_renamexd(), and op_sync().
wl_rewrite()
void wl_rewrite (const char * size)
Definition at line 345 of file workloads.c.
References op_sync(), strtosize(), file::testcode, writenewfile(), and writeoutfile().
wl_rmdir()
void wl_rmdir (void)
Definition at line 803 of file workloads.c.
References op_mkdir(), op_rmdir(), op_sync(), and writeemptyfile().
wl_rmdirdelayed()
void wl_rmdirdelayed (void)
Definition at line 855 of file workloads.c.
References op_closedir(), op_mkdir(), op_opendir(), op_rmdir(), op_sync(), and writeemptyfile().
wl_rmfile()
void wl_rmfile (void)
Definition at line 789 of file workloads.c.
References op_sync(), op_unlink(), SIZE_ONE, file::testcode, writeemptyfile(), and writenewfile().
wl_rmfiledelayed()
void wl_rmfiledelayed (void)
Definition at line 818 of file workloads.c.
References f, op_close(), op_open(), op_sync(), op_unlink(), SIZE_ONE, file::testcode, writeemptyfile(), and writenewfile().
wl_rmfiledelayedappend()
void wl_rmfiledelayedappend (void)
Definition at line 836 of file workloads.c.
References BLOCKSIZE, f, op_close(), op_open(), op_sync(), op_unlink(), op_write(), SIZE_SMALL, sizebytes(), file::testcode, writeemptyfile(), and writenewfile().
wl_rmmanydir()
void wl_rmmanydir (void)
Definition at line 966 of file workloads.c.
References op_mkdir(), op_rmdir(), op_sync(), and writeemptyfile().
wl_rmmanydirdelayed()
void wl_rmmanydirdelayed (void)
Definition at line 985 of file workloads.c.
References op_closedir(), op_mkdir(), op_opendir(), op_rmdir(), op_sync(), and writeemptyfile().
wl_rmmanyfile()
void wl_rmmanyfile (void)
Definition at line 871 of file workloads.c.
References op_sync(), op_unlink(), SIZE_ONE, writeemptyfile(), and writenewfile().
wl_rmmanyfiledelayed()
void wl_rmmanyfiledelayed (void)
Definition at line 891 of file workloads.c.
References op_close(), op_open(), op_sync(), op_unlink(), SIZE_ONE, file::testcode, writeemptyfile(), and writenewfile().
wl_rmmanyfiledelayedandappend()
void wl_rmmanyfiledelayedandappend (void)
Definition at line 921 of file workloads.c.
References assert, BLOCKSIZE, op_close(), op_open(), op_sync(), op_unlink(), op_write(), SIZE_SMALL, sizebytes(), file::testcode, writeemptyfile(), and writenewfile().
wl_rmrandtree()
void wl_rmrandtree (const char * seed)
Definition at line 1024 of file workloads.c.
References assert, count, getnum(), mkrandtree_sub(), op_sync(), random(), rmrandtree_sub(), and srandom().
wl_rmtree()
void wl_rmtree (void)
Definition at line 1011 of file workloads.c.
References op_sync(), wl_mktree_sub(), and wl_rmtree_sub().
wl_rmtree_sub()
static void wl_rmtree_sub (unsigned depth) static
Definition at line 672 of file workloads.c.
References op_chdir(), op_chdirup(), op_rmdir(), and op_unlink().
Referenced by wl_rmtree().
wl_truncfill()
void wl_truncfill (const char * size)
Definition at line 435 of file workloads.c.
References f, file_randomwrite(), O_CREAT, O_EXCL, op_close(), op_open(), op_sync(), op_truncate(), sizebytes(), srandom(), strtosize(), and file::testcode.
wl_trunclargersize()
void wl_trunclargersize (const char * size)
Definition at line 536 of file workloads.c.
References f, nextlargersize(), op_close(), op_open(), op_sync(), op_truncate(), sizebytes(), strtosize(), file::testcode, and writenewfile().
wl_trunconeblock()
void wl_trunconeblock (const char * size)
Definition at line 499 of file workloads.c.
References BLOCKSIZE, f, op_close(), op_open(), op_sync(), op_truncate(), sizebytes(), strtosize(), file::testcode, and writenewfile().
wl_truncsmallersize()
void wl_truncsmallersize (const char * size)
Definition at line 518 of file workloads.c.
References f, nextsmallersize(), op_close(), op_open(), op_sync(), op_truncate(), sizebytes(), strtosize(), file::testcode, and writenewfile().
wl_truncwrite()
void wl_truncwrite (const char * size)
Definition at line 383 of file workloads.c.
References O_TRUNC, op_sync(), strtosize(), file::testcode, writenewfile(), and writeoutfile().
wl_trunczero()
void wl_trunczero (const char * size)
Definition at line 480 of file workloads.c.
References f, op_close(), op_open(), op_sync(), op_truncate(), strtosize(), file::testcode, and writenewfile().
wl_unlinkfile()
void wl_unlinkfile (void)
Definition at line 1083 of file workloads.c.
References op_link(), op_sync(), op_unlink(), SIZE_ONE, writeemptyfile(), and writenewfile().
wl_unlinkmanyfile()
void wl_unlinkmanyfile (void)
Definition at line 1098 of file workloads.c.
References op_link(), op_sync(), op_unlink(), SIZE_ONE, writeemptyfile(), and writenewfile().
wl_untar()
void wl_untar (void)
Definition at line 1307 of file workloads.c.
References makesubtree().
wl_writefileseq()
void wl_writefileseq (const char * seed)
Definition at line 1403 of file workloads.c.
References createfiles(), getnum(), NULL, O_CREAT, O_EXCL, op_open(), op_sync(), openfiles(), random(), randwrite(), SIZE_MEDIUM, srandom(), and file::testcode.
wl_writetruncseq()
void wl_writetruncseq (const char * seed)
Definition at line 1438 of file workloads.c.
References createfiles(), getnum(), NULL, O_CREAT, O_EXCL, op_open(), op_sync(), openfiles(), random(), randtruncate(), randwrite(), SIZE_MEDIUM, srandom(), and file::testcode.
writeemptyfile()
static void writeemptyfile (unsigned filenum) static
Definition at line 240 of file workloads.c.
References f, O_CREAT, O_EXCL, op_close(), and op_open().
Referenced by wl_copyandrename(), wl_renamedir(), wl_renamefile(), wl_renamemanydir(), wl_renamemanyfile(), wl_renamemanysubtree(), wl_renamesubtree(), wl_rmdir(), wl_rmdirdelayed(), wl_rmfile(), wl_rmfiledelayed(), wl_rmfiledelayedappend(), wl_rmmanydir(), wl_rmmanydirdelayed(), wl_rmmanyfile(), wl_rmmanyfiledelayed(), wl_rmmanyfiledelayedandappend(), wl_unlinkfile(), and wl_unlinkmanyfile().
writeholeyfile()
static void writeholeyfile (unsigned testcode, unsigned filenum, enum sizes sz) static
Definition at line 270 of file workloads.c.
References BLOCKSIZE, f, O_CREAT, O_EXCL, op_close(), op_open(), op_write(), sizebytes(), and file::testcode.
Referenced by wl_fillhole(), and wl_makehole().
writenewfile()
static void writenewfile (unsigned testcode, unsigned filenum, enum sizes sz) static
Definition at line 263 of file workloads.c.
References O_CREAT, O_EXCL, file::testcode, and writeoutfile().
Referenced by createfiles(), makesubtree(), mkrandtree_sub(), prep(), randop(), wl_append(), wl_appendandtruncpartly(), wl_appendandtrunczero(), wl_compile(), wl_copyandrename(), wl_createwrite(), wl_linkfile(), wl_linkmanyfile(), wl_linkunlinkfile(), wl_linkunlinkseq(), wl_mkfile(), wl_mkmanyfile(), wl_mkrmseq(), wl_mktree_sub(), wl_randupdate(), wl_renamefile(), wl_renamemanyfile(), wl_renameseq(), wl_renamexdfile(), wl_rewrite(), wl_rmfile(), wl_rmfiledelayed(), wl_rmfiledelayedappend(), wl_rmmanyfile(), wl_rmmanyfiledelayed(), wl_rmmanyfiledelayedandappend(), wl_trunclargersize(), wl_trunconeblock(), wl_truncsmallersize(), wl_truncwrite(), wl_trunczero(), wl_unlinkfile(), and wl_unlinkmanyfile().
writeoutfile()
static void writeoutfile (unsigned testcode, unsigned filenum, unsigned openflags, enum sizes sz) static
Definition at line 251 of file workloads.c.
References f, op_close(), op_open(), op_write(), sizebytes(), and file::testcode.
Referenced by wl_rewrite(), wl_truncwrite(), and writenewfile().