os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/fs/semfs/semfs_obj.c File Reference
semfs_obj.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <synch.h>
#include "semfs.h"
Macros
#define SEMFS_INLINE
Functions
struct semfs_sem * semfs_sem_create (const char *name)
void semfs_sem_destroy (struct semfs_sem *sem)
int semfs_sem_insert (struct semfs *semfs, struct semfs_sem *sem, unsigned *ret)
struct semfs_direntry * semfs_direntry_create (const char *name, unsigned semnum)
void semfs_direntry_destroy (struct semfs_direntry *dent)
Macro Definition Documentation
SEMFS_INLINE
#define SEMFS_INLINE
Definition at line 34 of file semfs_obj.c.
Function Documentation
semfs_direntry_create()
struct semfs_direntry* semfs_direntry_create (const char * name, unsigned semnum)
Definition at line 120 of file semfs_obj.c.
References kfree(), kmalloc(), kstrdup(), name, NULL, semfs_direntry::semd_name, and semfs_direntry::semd_semnum.
Referenced by semfs_creat().
semfs_direntry_destroy()
void semfs_direntry_destroy (struct semfs_direntry * dent)
Definition at line 141 of file semfs_obj.c.
References kfree(), and semfs_direntry::semd_name.
Referenced by semfs_creat(), semfs_destroy(), and semfs_remove().
semfs_sem_create()
struct semfs_sem* semfs_sem_create (const char * name)
Definition at line 44 of file semfs_obj.c.
References cv_create(), kfree(), kmalloc(), lock_create(), lock_destroy(), name, NULL, semfs_sem::sems_count, semfs_sem::sems_cv, semfs_sem::sems_hasvnode, semfs_sem::sems_linked, semfs_sem::sems_lock, and snprintf().
Referenced by semfs_creat().
semfs_sem_destroy()
void semfs_sem_destroy (struct semfs_sem * sem)
Definition at line 82 of file semfs_obj.c.
References cv_destroy(), kfree(), lock_destroy(), semfs_sem::sems_cv, and semfs_sem::sems_lock.
Referenced by semfs_creat(), semfs_destroy(), semfs_reclaim(), and semfs_remove().
semfs_sem_insert()
int semfs_sem_insert (struct semfs * semfs, struct semfs_sem * sem, unsigned * ret)
Definition at line 93 of file semfs_obj.c.
References ENOSPC, KASSERT, lock_do_i_hold(), NULL, num, SEMFS_ROOTDIR, semfs::semfs_sems, and semfs::semfs_tablelock.
Referenced by semfs_creat().