os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/bigfork/bigfork.c File Reference
bigfork.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
Macros
#define BRANCHES 6
#define DIM 64
Functions
static void init (void)
static void add (int *x, const int *a, const int *b)
static void mul (int *x, const int *a, const int *b)
static void scale (int *x, const int *a, int b)
static void grind (void)
static int trace (void)
static pid_t dofork (void)
static void dowait (pid_t pid)
static void dotest (void)
int main (void)
Variables
static int m1 [DIM *DIM]
static int m2 [DIM *DIM]
static int m3 [DIM *DIM]
static int m4 [DIM *DIM]
static const int right [BRANCHES]
static unsigned failures
Macro Definition Documentation
BRANCHES
#define BRANCHES 6
Definition at line 48 of file bigfork.c.
DIM
#define DIM 64
Definition at line 55 of file bigfork.c.
Function Documentation
add()
static void add (int * x, const int * a, const int * b) static
Definition at line 84 of file bigfork.c.
References DIM.
Referenced by grind().
dofork()
static pid_t dofork (void) static
Definition at line 155 of file bigfork.c.
References fork(), pid, and warn().
Referenced by dotest(), main(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), and trycalls().
dotest()
static void dotest (void) static
Definition at line 194 of file bigfork.c.
References BRANCHES, dofork(), dowait(), failures, grind(), me, test::msg, pids, printf(), right, snprintf(), STDOUT_FILENO, strlen(), trace(), and write().
Referenced by main().
dowait()
static void dowait (pid_t pid) static
Definition at line 168 of file bigfork.c.
References exit(), failures, pid, waitpid(), warn(), warnx(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
Referenced by dotest().
grind()
static void grind (void) static
Definition at line 126 of file bigfork.c.
References add(), m1, m2, m3, m4, mul(), and scale().
Referenced by dotest(), and runit().
init()
static void init (void) static
Definition at line 70 of file bigfork.c.
References DIM, m1, random(), and srandom().
Referenced by main().
main()
int main (void)
Definition at line 234 of file bigfork.c.
References dotest(), and init().
mul()
static void mul (int * x, const int * a, const int * b) static
Definition at line 97 of file bigfork.c.
References DIM.
Referenced by grind().
scale()
static void scale (int * x, const int * a, int b) static
Definition at line 113 of file bigfork.c.
References DIM.
Referenced by grind().
trace()
static int trace (void) static
Definition at line 139 of file bigfork.c.
References DIM, and m1.
Referenced by dotest().
Variable Documentation
failures
unsigned failures static
Definition at line 66 of file bigfork.c.
Referenced by dotest(), dowait(), runtaskgroup(), triple(), and waitall().
m1
int m1[DIM *DIM] static
Definition at line 57 of file bigfork.c.
Referenced by addeq(), compute_thread(), grind(), init(), multiply(), and trace().
m2
int m2[DIM *DIM] static
Definition at line 57 of file bigfork.c.
Referenced by addeq(), compute_thread(), grind(), and multiply().
m3
int m3[DIM *DIM] static
Definition at line 57 of file bigfork.c.
Referenced by compute_thread(), and grind().
m4
int m4[DIM *DIM] static
Definition at line 57 of file bigfork.c.
Referenced by grind().
right
const int right[BRANCHES] static
Initial value:
= {
    536763422,
    478946723,
    375722852,
    369910585,
    328220902,
    62977821,
}
Definition at line 58 of file bigfork.c.
Referenced by dotest().