os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/vnode.h File Reference
vnode.h File Reference
#include <spinlock.h>
Data Structures
struct vnode
struct vnode_ops
Macros
#define VOP_MAGIC 0xa2b3c4d5
#define __VOP(vn, sym) (vnode_check(vn, #sym), (vn)->vn_ops->vop_##sym)
#define VOP_EACHOPEN(vn, flags) (__VOP(vn, eachopen)(vn, flags))
#define VOP_RECLAIM(vn) (__VOP(vn, reclaim)(vn))
#define VOP_READ(vn, uio) (__VOP(vn, read)(vn, uio))
#define VOP_READLINK(vn, uio) (__VOP(vn, readlink)(vn, uio))
#define VOP_GETDIRENTRY(vn, uio) (__VOP(vn,getdirentry)(vn, uio))
#define VOP_WRITE(vn, uio) (__VOP(vn, write)(vn, uio))
#define VOP_IOCTL(vn, code, buf) (__VOP(vn, ioctl)(vn,code,buf))
#define VOP_STAT(vn, ptr) (__VOP(vn, stat)(vn, ptr))
#define VOP_GETTYPE(vn, result) (__VOP(vn, gettype)(vn, result))
#define VOP_ISSEEKABLE(vn) (__VOP(vn, isseekable)(vn))
#define VOP_FSYNC(vn) (__VOP(vn, fsync)(vn))
#define VOP_MMAP(vn) (__VOP(vn, mmap)(vn /*add stuff */))
#define VOP_TRUNCATE(vn, pos) (__VOP(vn, truncate)(vn, pos))
#define VOP_NAMEFILE(vn, uio) (__VOP(vn, namefile)(vn, uio))
#define VOP_CREAT(vn, nm, excl, mode, res) (__VOP(vn, creat)(vn,nm,excl,mode,res))
#define VOP_SYMLINK(vn, name, content) (__VOP(vn, symlink)(vn, name, content))
#define VOP_MKDIR(vn, name, mode) (__VOP(vn, mkdir)(vn, name, mode))
#define VOP_LINK(vn, name, vn2) (__VOP(vn, link)(vn, name, vn2))
#define VOP_REMOVE(vn, name) (__VOP(vn, remove)(vn, name))
#define VOP_RMDIR(vn, name) (__VOP(vn, rmdir)(vn, name))
#define VOP_RENAME(vn1, name1, vn2, name2) (__VOP(vn1,rename)(vn1,name1,vn2,name2))
#define VOP_LOOKUP(vn, name, res) (__VOP(vn, lookup)(vn, name, res))
#define VOP_LOOKPARENT(vn, nm, res, bf, ln) (__VOP(vn,lookparent)(vn,nm,res,bf,ln))
#define VOP_INCREF(vn) vnode_incref(vn)
#define VOP_DECREF(vn) vnode_decref(vn)
Functions
void vnode_check (struct vnode *, const char *op)
void vnode_incref (struct vnode *)
void vnode_decref (struct vnode *)
int vnode_init (struct vnode *, const struct vnode_ops *ops, struct fs *fs, void *fsdata)
void vnode_cleanup (struct vnode *)
int vopfail_uio_notdir (struct vnode *vn, struct uio *uio)
int vopfail_uio_isdir (struct vnode *vn, struct uio *uio)
int vopfail_uio_inval (struct vnode *vn, struct uio *uio)
int vopfail_uio_nosys (struct vnode *vn, struct uio *uio)
int vopfail_mmap_isdir (struct vnode *vn)
int vopfail_mmap_perm (struct vnode *vn)
int vopfail_mmap_nosys (struct vnode *vn)
int vopfail_truncate_isdir (struct vnode *vn, off_t pos)
int vopfail_creat_notdir (struct vnode *vn, const char *name, bool excl, mode_t mode, struct vnode **result)
int vopfail_symlink_notdir (struct vnode *vn, const char *contents, const char *name)
int vopfail_symlink_nosys (struct vnode *vn, const char *contents, const char *name)
int vopfail_mkdir_notdir (struct vnode *vn, const char *name, mode_t mode)
int vopfail_mkdir_nosys (struct vnode *vn, const char *name, mode_t mode)
int vopfail_link_notdir (struct vnode *dir, const char *name, struct vnode *file)
int vopfail_link_nosys (struct vnode *dir, const char *name, struct vnode *file)
int vopfail_string_notdir (struct vnode *vn, const char *name)
int vopfail_string_nosys (struct vnode *vn, const char *name)
int vopfail_rename_notdir (struct vnode *fromdir, const char *fromname, struct vnode *todir, const char *toname)
int vopfail_rename_nosys (struct vnode *fromdir, const char *fromname, struct vnode *todir, const char *toname)
int vopfail_lookup_notdir (struct vnode *vn, char *path, struct vnode **result)
int vopfail_lookparent_notdir (struct vnode *vn, char *path, struct vnode **result, char *buf, size_t len)
Macro Definition Documentation
__VOP
#define __VOP (vn, sym) (vnode_check(vn, #sym), (vn)->vn_ops->vop_##sym)
Definition at line 226 of file vnode.h.
VOP_CREAT
#define VOP_CREAT (vn, nm, excl, mode, res) (__VOP(vn, creat)(vn,nm,excl,mode,res))
Definition at line 244 of file vnode.h.
VOP_DECREF
#define VOP_DECREF (vn) vnode_decref(vn)
Definition at line 267 of file vnode.h.
VOP_EACHOPEN
#define VOP_EACHOPEN (vn, flags) (__VOP(vn, eachopen)(vn, flags))
Definition at line 228 of file vnode.h.
VOP_FSYNC
#define VOP_FSYNC (vn) (__VOP(vn, fsync)(vn))
Definition at line 239 of file vnode.h.
VOP_GETDIRENTRY
#define VOP_GETDIRENTRY (vn, uio) (__VOP(vn,getdirentry)(vn, uio))
Definition at line 233 of file vnode.h.
VOP_GETTYPE
#define VOP_GETTYPE (vn, result) (__VOP(vn, gettype)(vn, result))
Definition at line 237 of file vnode.h.
VOP_INCREF
#define VOP_INCREF (vn) vnode_incref(vn)
Definition at line 266 of file vnode.h.
VOP_IOCTL
#define VOP_IOCTL (vn, code, buf) (__VOP(vn, ioctl)(vn,code,buf))
Definition at line 235 of file vnode.h.
VOP_ISSEEKABLE
#define VOP_ISSEEKABLE (vn) (__VOP(vn, isseekable)(vn))
Definition at line 238 of file vnode.h.
VOP_LINK
#define VOP_LINK (vn, name, vn2) (__VOP(vn, link)(vn, name, vn2))
Definition at line 247 of file vnode.h.
VOP_LOOKPARENT
#define VOP_LOOKPARENT (vn, nm, res, bf, ln) (__VOP(vn,lookparent)(vn,nm,res,bf,ln))
Definition at line 253 of file vnode.h.
VOP_LOOKUP
#define VOP_LOOKUP (vn, name, res) (__VOP(vn, lookup)(vn, name, res))
Definition at line 252 of file vnode.h.
VOP_MAGIC
#define VOP_MAGIC 0xa2b3c4d5
Definition at line 178 of file vnode.h.
VOP_MKDIR
#define VOP_MKDIR (vn, name, mode) (__VOP(vn, mkdir)(vn, name, mode))
Definition at line 246 of file vnode.h.
VOP_MMAP
#define VOP_MMAP (vn) (__VOP(vn, mmap)(vn /*add stuff */))
Definition at line 240 of file vnode.h.
VOP_NAMEFILE
#define VOP_NAMEFILE (vn, uio) (__VOP(vn, namefile)(vn, uio))
Definition at line 242 of file vnode.h.
VOP_READ
#define VOP_READ (vn, uio) (__VOP(vn, read)(vn, uio))
Definition at line 231 of file vnode.h.
VOP_READLINK
#define VOP_READLINK (vn, uio) (__VOP(vn, readlink)(vn, uio))
Definition at line 232 of file vnode.h.
VOP_RECLAIM
#define VOP_RECLAIM (vn) (__VOP(vn, reclaim)(vn))
Definition at line 229 of file vnode.h.
VOP_REMOVE
#define VOP_REMOVE (vn, name) (__VOP(vn, remove)(vn, name))
Definition at line 248 of file vnode.h.
VOP_RENAME
#define VOP_RENAME (vn1, name1, vn2, name2) (__VOP(vn1,rename)(vn1,name1,vn2,name2))
Definition at line 250 of file vnode.h.
VOP_RMDIR
#define VOP_RMDIR (vn, name) (__VOP(vn, rmdir)(vn, name))
Definition at line 249 of file vnode.h.
VOP_STAT
#define VOP_STAT (vn, ptr) (__VOP(vn, stat)(vn, ptr))
Definition at line 236 of file vnode.h.
VOP_SYMLINK
#define VOP_SYMLINK (vn, name, content) (__VOP(vn, symlink)(vn, name, content))
Definition at line 245 of file vnode.h.
VOP_TRUNCATE
#define VOP_TRUNCATE (vn, pos) (__VOP(vn, truncate)(vn, pos))
Definition at line 241 of file vnode.h.
VOP_WRITE
#define VOP_WRITE (vn, uio) (__VOP(vn, write)(vn, uio))
Definition at line 234 of file vnode.h.
Function Documentation
vnode_check()
void vnode_check (struct vnode * , const char * op)
Definition at line 130 of file vnode.c.
References kprintf(), NULL, panic(), spinlock_acquire(), spinlock_release(), vnode::vn_countlock, vnode::vn_fs, vnode::vn_ops, vnode::vn_refcount, VOP_MAGIC, and vnode_ops::vop_magic.
vnode_cleanup()
void vnode_cleanup (struct vnode *)
Definition at line 62 of file vnode.c.
References KASSERT, NULL, spinlock_cleanup(), vnode::vn_countlock, vnode::vn_data, vnode::vn_fs, vnode::vn_ops, and vnode::vn_refcount.
Referenced by dev_uncreate_vnode(), emufs_loadvnode(), emufs_reclaim(), semfs_vnode_destroy(), sfs_loadvnode(), and sfs_reclaim().
vnode_decref()
void vnode_decref (struct vnode *)
Definition at line 95 of file vnode.c.
References EBUSY, KASSERT, kprintf(), NULL, spinlock_acquire(), spinlock_release(), strerror(), vnode::vn_countlock, vnode::vn_refcount, and VOP_RECLAIM.
vnode_incref()
void vnode_incref (struct vnode *)
Definition at line 80 of file vnode.c.
References KASSERT, NULL, spinlock_acquire(), spinlock_release(), vnode::vn_countlock, and vnode::vn_refcount.
vnode_init()
int vnode_init (struct vnode * , const struct vnode_ops * ops, struct fs * fs, void * fsdata)
Definition at line 44 of file vnode.c.
References KASSERT, NULL, ops, spinlock_init(), vnode::vn_countlock, vnode::vn_data, vnode::vn_fs, vnode::vn_ops, and vnode::vn_refcount.
Referenced by dev_create_vnode(), emufs_loadvnode(), semfs_vnode_create(), and sfs_loadvnode().
vopfail_creat_notdir()
int vopfail_creat_notdir (struct vnode * vn, const char * name, bool excl, mode_t mode, struct vnode ** result)
Definition at line 121 of file vfsfail.c.
References ENOTDIR, and name.
vopfail_link_nosys()
int vopfail_link_nosys (struct vnode * dir, const char * name, struct vnode * file)
Definition at line 189 of file vfsfail.c.
References ENOSYS, and name.
vopfail_link_notdir()
int vopfail_link_notdir (struct vnode * dir, const char * name, struct vnode * file)
Definition at line 180 of file vfsfail.c.
References ENOTDIR, and name.
vopfail_lookparent_notdir()
int vopfail_lookparent_notdir (struct vnode * vn, char * path, struct vnode ** result, char * buf, size_t len)
Definition at line 254 of file vfsfail.c.
References buf, and ENOTDIR.
vopfail_lookup_notdir()
int vopfail_lookup_notdir (struct vnode * vn, char * path, struct vnode ** result)
Definition at line 245 of file vfsfail.c.
References ENOTDIR.
vopfail_mkdir_nosys()
int vopfail_mkdir_nosys (struct vnode * vn, const char * name, mode_t mode)
Definition at line 168 of file vfsfail.c.
References ENOSYS, and name.
vopfail_mkdir_notdir()
int vopfail_mkdir_notdir (struct vnode * vn, const char * name, mode_t mode)
Definition at line 159 of file vfsfail.c.
References ENOTDIR, and name.
vopfail_mmap_isdir()
int vopfail_mmap_isdir (struct vnode * vn)
Definition at line 86 of file vfsfail.c.
References EISDIR.
vopfail_mmap_nosys()
int vopfail_mmap_nosys (struct vnode * vn)
Definition at line 100 of file vfsfail.c.
References ENOSYS.
vopfail_mmap_perm()
int vopfail_mmap_perm (struct vnode * vn)
Definition at line 93 of file vfsfail.c.
References EPERM.
vopfail_rename_nosys()
int vopfail_rename_nosys (struct vnode * fromdir, const char * fromname, struct vnode * todir, const char * toname)
Definition at line 231 of file vfsfail.c.
References ENOSYS.
vopfail_rename_notdir()
int vopfail_rename_notdir (struct vnode * fromdir, const char * fromname, struct vnode * todir, const char * toname)
Definition at line 220 of file vfsfail.c.
References ENOTDIR.
vopfail_string_nosys()
int vopfail_string_nosys (struct vnode * vn, const char * name)
Definition at line 209 of file vfsfail.c.
References ENOSYS, and name.
vopfail_string_notdir()
int vopfail_string_notdir (struct vnode * vn, const char * name)
Definition at line 201 of file vfsfail.c.
References ENOTDIR, and name.
vopfail_symlink_nosys()
int vopfail_symlink_nosys (struct vnode * vn, const char * contents, const char * name)
Definition at line 146 of file vfsfail.c.
References ENOSYS, and name.
vopfail_symlink_notdir()
int vopfail_symlink_notdir (struct vnode * vn, const char * contents, const char * name)
Definition at line 136 of file vfsfail.c.
References ENOTDIR, and name.
vopfail_truncate_isdir()
int vopfail_truncate_isdir (struct vnode * vn, off_t pos)
Definition at line 110 of file vfsfail.c.
References EISDIR, and pos.
vopfail_uio_inval()
int vopfail_uio_inval (struct vnode * vn, struct uio * uio)
Definition at line 67 of file vfsfail.c.
References EINVAL.
vopfail_uio_isdir()
int vopfail_uio_isdir (struct vnode * vn, struct uio * uio)
Definition at line 59 of file vfsfail.c.
References EISDIR.
vopfail_uio_nosys()
int vopfail_uio_nosys (struct vnode * vn, struct uio * uio)
Definition at line 75 of file vfsfail.c.
References ENOSYS.
vopfail_uio_notdir()
int vopfail_uio_notdir (struct vnode * vn, struct uio * uio)
Definition at line 51 of file vfsfail.c.
References ENOTDIR.