os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/lib/libc/stdlib/qsort.c File Reference
qsort.c File Reference
#include <stdlib.h>
#include <string.h>
#include <assert.h>
Macros
#define COMPARE(aa, bb) ((aa) == (bb) ? 0 : f(data + (aa) * size, data + (bb) * size))
#define EXCHANGE(aa, bb)
Functions
void qsort (void *vdata, unsigned num, size_t size, int(*f)(const void *, const void *))
Macro Definition Documentation
COMPARE
#define COMPARE (aa, bb) ((aa) == (bb) ? 0 : f(data + (aa) * size, data + (bb) * size))
EXCHANGE
#define EXCHANGE (aa, bb)
Value:
        memcpy(tmp, data + (aa) * size, size);          \
        memcpy(data + (aa) * size, data + (bb) * size, size);   \
        memcpy(data + (bb) * size, tmp, size)
Function Documentation
qsort()
void qsort (void * vdata, unsigned num, size_t size, int(*)(const void *, const void *) f)
Definition at line 38 of file qsort.c.
References assert, COMPARE, EXCHANGE, f, num, and tail().
Referenced by grind(), inode_sorttable(), and sfsdir_sort().