os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/factorial/factorial.c File Reference
factorial.c File Reference
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <assert.h>
#include <err.h>
Data Structures
struct number
Macros
#define _PATH_SELF "/testbin/factorial"
#define NUMSIZE 8191
Functions
static void number_init (struct number *n, const char *txt)
static char * number_get (struct number *n)
static void finishcarry (struct number *r, const struct number *b, size_t pos, unsigned carry)
static void pluseq (struct number *r, const struct number *b)
static void dec (struct number *r)
static void multc (struct number *r, const struct number *a, unsigned bn, size_t offset)
static void mult (struct number *r, const struct number *a, const struct number *b)
static void self (const char *arg1, const char *arg2)
int main (int argc, char *argv[])
Variables
static struct number scratch
static struct number n1 n2 multbuf
Macro Definition Documentation
_PATH_SELF
#define _PATH_SELF "/testbin/factorial"
Definition at line 36 of file factorial.c.
NUMSIZE
#define NUMSIZE 8191
Definition at line 58 of file factorial.c.
Function Documentation
dec()
static void dec (struct number * r) static
Definition at line 152 of file factorial.c.
References number::buf, errx(), number::first, NUMSIZE, and pos.
Referenced by main().
finishcarry()
static void finishcarry (struct number * r, const struct number * b, size_t pos, unsigned carry) static
Definition at line 115 of file factorial.c.
References number::buf, errx(), number::first, and pos.
Referenced by multc(), and pluseq().
main()
int main (int argc, char * argv[])
Definition at line 237 of file factorial.c.
References dec(), mult(), multbuf, number_get(), number_init(), printf(), strcmp(), and warnx().
mult()
static void mult (struct number * r, const struct number * a, const struct number * b) static
Definition at line 197 of file factorial.c.
References number::buf, number::first, multc(), number_init(), NUMSIZE, pluseq(), and scratch.
Referenced by main().
multc()
static void multc (struct number * r, const struct number * a, unsigned bn, size_t offset) static
Definition at line 171 of file factorial.c.
References number::buf, errx(), finishcarry(), number::first, NUMSIZE, and pos.
Referenced by mult().
number_get()
static char* number_get (struct number * n) static
Definition at line 98 of file factorial.c.
References number::buf, buf, number::first, NUMSIZE, and pos.
Referenced by main().
number_init()
static void number_init (struct number * n, const char * txt) static
Definition at line 68 of file factorial.c.
References assert, number::buf, errx(), number::first, NUMSIZE, strcpy(), strlen(), and warnx().
Referenced by main(), and mult().
pluseq()
static void pluseq (struct number * r, const struct number * b) static
Definition at line 134 of file factorial.c.
References number::buf, finishcarry(), number::first, NUMSIZE, and pos.
Referenced by mult().
self()
static void self (const char * arg1, const char * arg2) static
Definition at line 222 of file factorial.c.
References _PATH_SELF, err(), execv(), and NULL.
Variable Documentation
multbuf
struct number n1 n2 multbuf static
Definition at line 234 of file factorial.c.
Referenced by main().
scratch
struct number scratch static
Definition at line 64 of file factorial.c.
Referenced by mult().