os161-doc: /home/os161user/os161/os161-base-2.0.3/common/libc/printf/__printf.c File Reference
__printf.c File Reference
#include <sys/types.h>
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
Data Structures
struct PF
Macros
#define USE_LONGLONG
#define INTTYPE long long
#define NUMBER_BUF_SIZE ((sizeof(INTTYPE) * CHAR_BIT) / 3 + 2)
Functions
static void __pf_print (PF *pf, const char *txt, size_t len)
static void __pf_endfield (PF *pf)
static void __pf_modifier (PF *pf, int ch)
static void __pf_getnum (PF *pf, int ch)
static void __pf_setbase (PF *pf, int ch)
static void __pf_fill (PF *pf, int spc)
static void __pf_printstuff (PF *pf, const char *prefix, const char *prefix2, const char *stuff)
static void __pf_printnum (PF *pf)
static void __pf_send (PF *pf, int ch)
int __vprintf (void(*func)(void *clientdata, const char *str, size_t len), void *clientdata, const char *format, va_list ap)
Macro Definition Documentation
INTTYPE
#define INTTYPE long long
Definition at line 70 of file __printf.c.
NUMBER_BUF_SIZE
#define NUMBER_BUF_SIZE ((sizeof(INTTYPE) * CHAR_BIT) / 3 + 2)
Definition at line 84 of file __printf.c.
USE_LONGLONG
#define USE_LONGLONG
Definition at line 64 of file __printf.c.
Function Documentation
__pf_endfield()
static void __pf_endfield (PF * pf) static
Definition at line 157 of file __printf.c.
References PF::altformat, PF::base, PF::baseprefix, PF::fillchar, PF::in_pct, PF::num, PF::rightspc, PF::sign, PF::size, and PF::spacing.
Referenced by __pf_send(), and __vprintf().
__pf_fill()
static void __pf_fill (PF * pf, int spc) static
Definition at line 350 of file __printf.c.
References __pf_print(), f, and PF::fillchar.
Referenced by __pf_printstuff().
__pf_getnum()
static void __pf_getnum (PF * pf, int ch) static
Definition at line 242 of file __printf.c.
References PF::ap, ch, INTTYPE, PF::num, PF::sign, PF::size, and va_arg.
Referenced by __pf_send().
__pf_modifier()
static void __pf_modifier (PF * pf, int ch) static
Definition at line 182 of file __printf.c.
References PF::altformat, assert, ch, PF::fillchar, PF::rightspc, PF::size, and PF::spacing.
Referenced by __pf_send().
__pf_print()
static void __pf_print (PF * pf, const char * txt, size_t len) static
Definition at line 146 of file __printf.c.
References PF::charcount, PF::clientdata, and PF::sendfunc.
Referenced by __pf_fill(), __pf_printstuff(), and __pf_send().
__pf_printnum()
static void __pf_printnum (PF * pf) static
Definition at line 415 of file __printf.c.
References __pf_printstuff(), PF::base, PF::baseprefix, buf, INTTYPE, PF::num, NUMBER_BUF_SIZE, and PF::sign.
Referenced by __pf_send().
__pf_printstuff()
static void __pf_printstuff (PF * pf, const char * prefix, const char * prefix2, const char * stuff) static
Definition at line 367 of file __printf.c.
References __pf_fill(), __pf_print(), PF::fillchar, PF::rightspc, PF::spacing, and strlen().
Referenced by __pf_printnum(), and __pf_send().
__pf_send()
static void __pf_send (PF * pf, int ch) static
Definition at line 498 of file __printf.c.
References __pf_endfield(), __pf_getnum(), __pf_modifier(), __pf_print(), __pf_printnum(), __pf_printstuff(), __pf_setbase(), PF::ap, assert, ch, PF::in_pct, NULL, strchr(), and va_arg.
Referenced by __vprintf().
__pf_setbase()
static void __pf_setbase (PF * pf, int ch) static
Definition at line 325 of file __printf.c.
References PF::altformat, PF::base, PF::baseprefix, and ch.
Referenced by __pf_send().
__vprintf()
int __vprintf (void(*)(void *clientdata, const char *str, size_t len) func, void * clientdata, const char * format, va_list ap)
Definition at line 571 of file __printf.c.
References __pf_endfield(), __pf_send(), PF::ap, PF::charcount, PF::clientdata, PF::sendfunc, and va_copy.