os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/sfsck/sb.h File Reference
sb.h File Reference
#include <stdint.h>
Functions
void sb_load (void)
uint32_t sb_totalblocks (void)
uint32_t sb_freemapblocks (void)
const char * sb_volname (void)
void sb_check (void)
Function Documentation
sb_check()
void sb_check (void)
Definition at line 66 of file sb.c.
References checkbadstring(), checknullstring(), checkzeroed(), EXIT_RECOV, sfs_superblock::reserved, sb, sfs_superblock::sb_volname, setbadness(), SFS_SUPER_BLOCK, sfs_writesb(), and warnx().
Referenced by main().
sb_freemapblocks()
uint32_t sb_freemapblocks (void)
Definition at line 112 of file sb.c.
References sb, sfs_superblock::sb_nblocks, and SFS_FREEMAPBLOCKS.
Referenced by freemap_check(), and freemap_setup().
sb_load()
void sb_load (void)
Definition at line 51 of file sb.c.
References assert, errx(), EXIT_FATAL, sb, sfs_superblock::sb_magic, sfs_superblock::sb_nblocks, SFS_FREEMAPBLOCKS, SFS_MAGIC, sfs_readsb(), and SFS_SUPER_BLOCK.
Referenced by main().
sb_totalblocks()
uint32_t sb_totalblocks (void)
Definition at line 102 of file sb.c.
References sb, and sfs_superblock::sb_nblocks.
Referenced by check_inode_blocks(), freemap_setup(), main(), and pass1_direntry().
sb_volname()
const char* sb_volname (void)
Definition at line 121 of file sb.c.
References sb, and sfs_superblock::sb_volname.
Referenced by pass1_rootdir(), and pass2().