os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/array.h File Reference
array.h File Reference
#include <cdefs.h>
#include <lib.h>
Data Structures
struct array
Macros
#define ARRAYS_CHECKED
#define ARRAYASSERT KASSERT
#define ARRAYINLINE INLINE
#define DECLARRAY_BYTYPE(ARRAY, T, INLINE)
#define DEFARRAY_BYTYPE(ARRAY, T, INLINE)
#define DECLARRAY(T, INLINE) DECLARRAY_BYTYPE(T##array, struct T, INLINE)
#define DEFARRAY(T, INLINE) DEFARRAY_BYTYPE(T##array, struct T, INLINE)
Functions
struct array * array_create (void)
void array_destroy (struct array *)
void array_init (struct array *)
void array_cleanup (struct array *)
ARRAYINLINE unsigned array_num (const struct array *)
ARRAYINLINE void * array_get (const struct array *, unsigned index)
ARRAYINLINE void array_set (const struct array *, unsigned index, void *val)
int array_preallocate (struct array *, unsigned num)
int array_setsize (struct array *, unsigned num)
ARRAYINLINE int array_add (struct array *, void *val, unsigned *index_ret)
void array_remove (struct array *, unsigned index)
DECLARRAY_BYTYPE (stringarray, char, ARRAYINLINE)
DEFARRAY_BYTYPE (stringarray, char, ARRAYINLINE)
Macro Definition Documentation
ARRAYASSERT
#define ARRAYASSERT KASSERT
Definition at line 39 of file array.h.
ARRAYINLINE
#define ARRAYINLINE INLINE
Definition at line 45 of file array.h.
ARRAYS_CHECKED
#define ARRAYS_CHECKED
Definition at line 36 of file array.h.
DECLARRAY
#define DECLARRAY (T, INLINE) DECLARRAY_BYTYPE(T##array, struct T, INLINE)
Definition at line 258 of file array.h.
DECLARRAY_BYTYPE
#define DECLARRAY_BYTYPE (ARRAY, T, INLINE)
Value:
    struct ARRAY {                      \
        struct array arr;               \
    };                          \
                                \
    INLINE struct ARRAY *ARRAY##_create(void);      \
    INLINE void ARRAY##_destroy(struct ARRAY *a);       \
    INLINE void ARRAY##_init(struct ARRAY *a);      \
    INLINE void ARRAY##_cleanup(struct ARRAY *a);       \
    INLINE unsigned ARRAY##_num(const struct ARRAY *a); \
    INLINE T *ARRAY##_get(const struct ARRAY *a, unsigned index); \
    INLINE void ARRAY##_set(struct ARRAY *a, unsigned index, T *val); \
    INLINE int ARRAY##_preallocate(struct ARRAY *a, unsigned num);  \
    INLINE int ARRAY##_setsize(struct ARRAY *a, unsigned num);  \
    INLINE int ARRAY##_add(struct ARRAY *a, T *val, unsigned *index_ret); \
    INLINE void ARRAY##_remove(struct ARRAY *a, unsigned index)
Definition at line 168 of file array.h.
DEFARRAY
#define DEFARRAY (T, INLINE) DEFARRAY_BYTYPE(T##array, struct T, INLINE)
Definition at line 259 of file array.h.
DEFARRAY_BYTYPE
#define DEFARRAY_BYTYPE (ARRAY, T, INLINE)
Definition at line 185 of file array.h.
Function Documentation
array_add()
ARRAYINLINE int array_add (struct array * a, void * val, unsigned * index_ret)
Definition at line 112 of file array.h.
References array_setsize(), NULL, array::num, and array::v.
Referenced by arraytest2(), and testa().
array_cleanup()
void array_cleanup (struct array *)
Definition at line 64 of file array.c.
References ARRAYASSERT, kfree(), NULL, array::num, and array::v.
Referenced by array_destroy().
array_create()
struct array* array_create (void)
Definition at line 38 of file array.c.
References array_init(), kmalloc(), and NULL.
Referenced by arraytest(), and arraytest2().
array_destroy()
void array_destroy (struct array *)
Definition at line 50 of file array.c.
References array_cleanup(), and kfree().
Referenced by arraytest(), and arraytest2().
array_get()
ARRAYINLINE void * array_get (const struct array * a, unsigned index)
Definition at line 98 of file array.h.
References ARRAYASSERT, num, and array::v.
Referenced by arraytest2(), and testa().
array_init()
void array_init (struct array *)
Definition at line 57 of file array.c.
References array::max, NULL, array::num, and array::v.
Referenced by array_create().
array_num()
ARRAYINLINE unsigned array_num (const struct array * a)
Definition at line 92 of file array.h.
References array::num.
Referenced by arraytest2(), and testa().
array_preallocate()
int array_preallocate (struct array * , unsigned num)
Definition at line 79 of file array.c.
References ENOMEM, kfree(), kmalloc(), array::max, memcpy(), NULL, array::num, num, and array::v.
Referenced by array_setsize().
array_remove()
void array_remove (struct array * , unsigned index)
Definition at line 125 of file array.c.
References ARRAYASSERT, array::max, memmove(), array::num, num, and array::v.
Referenced by arraytest2(), and testa().
array_set()
ARRAYINLINE void array_set (const struct array * a, unsigned index, void * val)
Definition at line 105 of file array.h.
References ARRAYASSERT, num, and array::v.
Referenced by arraytest2(), and testa().
array_setsize()
int array_setsize (struct array * , unsigned num)
Definition at line 111 of file array.c.
References array_preallocate(), array::num, and num.
Referenced by array_add(), arraytest(), arraytest2(), and testa().
DECLARRAY_BYTYPE()
DECLARRAY_BYTYPE (stringarray , char , ARRAYINLINE)
DEFARRAY_BYTYPE()
DEFARRAY_BYTYPE (stringarray , char , ARRAYINLINE)