os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/dev/lamebus/ltimer.h File Reference
ltimer.h File Reference
Data Structures
struct ltimer_softc
Functions
void ltimer_irq (void *lt)
void ltimer_beep (void *devdata)
void ltimer_gettime (void *devdata, struct timespec *ts)
Function Documentation
ltimer_beep()
void ltimer_beep (void * devdata)
Definition at line 136 of file ltimer.c.
References bus_write_register, ltimer_softc::lt_bus, ltimer_softc::lt_buspos, and LT_REG_SPKR.
Referenced by attach_beep_to_ltimer().
ltimer_gettime()
void ltimer_gettime (void * devdata, struct timespec * ts)
Definition at line 149 of file ltimer.c.
References bus_read_register, ltimer_softc::lt_bus, ltimer_softc::lt_buspos, LT_REG_NSEC, LT_REG_SEC, splhigh(), splx(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by attach_rtclock_to_ltimer().
ltimer_irq()
void ltimer_irq (void * lt)
Definition at line 107 of file ltimer.c.
References bus_read_register, hardclock(), ltimer_softc::lt_bus, ltimer_softc::lt_buspos, ltimer_softc::lt_hardclock, LT_REG_IRQ, ltimer_softc::lt_timerclock, and timerclock().
Referenced by attach_ltimer_to_lamebus().