os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/frack/data.c File Reference
data.c File Reference
#include <sys/types.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "data.h"
Macros
#define BLOCKSIZE /*SFS_BLOCKSIZE*/ 512
Functions
static void prepdata (unsigned code, unsigned seq, char *buf, off_t len)
static int matches_at (size_t start, size_t len)
static int byte_at (size_t start, size_t len, unsigned char val)
static int zero_at (size_t start, size_t len)
static int poison_at (size_t start, size_t len)
int data_matches (const char *namestr, off_t regionoffset, unsigned code, unsigned seq, off_t zerostart, off_t len, off_t checkstart, off_t checklen)
void data_check (const char *namestr, off_t regionoffset, unsigned code, unsigned seq, off_t zerostart, off_t len, off_t checkstart, off_t checklen)
void * data_map (unsigned code, unsigned seq, off_t len)
void * data_mapreadbuf (off_t len)
Variables
static char databuf [DATA_MAXSIZE]
static char readbuf [DATA_MAXSIZE]
Macro Definition Documentation
BLOCKSIZE
#define BLOCKSIZE /*SFS_BLOCKSIZE*/ 512
Definition at line 41 of file data.c.
Function Documentation
byte_at()
static int byte_at (size_t start, size_t len, unsigned char val) static
Definition at line 84 of file data.c.
References fschange::len, and readbuf.
Referenced by poison_at(), and zero_at().
data_check()
void data_check (const char * namestr, off_t regionoffset, unsigned code, unsigned seq, off_t zerostart, off_t len, off_t checkstart, off_t checklen)
Definition at line 199 of file data.c.
References assert, fschange::code, data_matches(), fschange::len, printf(), and fschange::seq.
Referenced by checkfiledata().
data_map()
void* data_map (unsigned code, unsigned seq, off_t len)
Definition at line 215 of file data.c.
References assert, fschange::code, DATA_MAXSIZE, databuf, fschange::len, prepdata(), and fschange::seq.
Referenced by do_write().
data_mapreadbuf()
void* data_mapreadbuf (off_t len)
Definition at line 223 of file data.c.
References assert, DATA_MAXSIZE, fschange::len, and readbuf.
Referenced by readfiledata().
data_matches()
int data_matches (const char * namestr, off_t regionoffset, unsigned code, unsigned seq, off_t zerostart, off_t len, off_t checkstart, off_t checklen)
Definition at line 123 of file data.c.
References assert, BLOCKSIZE, fschange::code, DATA_MAXSIZE, databuf, fschange::len, matches_at(), poison_at(), prepdata(), printf(), fschange::seq, and zero_at().
Referenced by change_is_present(), and data_check().
matches_at()
static int matches_at (size_t start, size_t len) static
Definition at line 74 of file data.c.
References databuf, fschange::len, memcmp(), and readbuf.
Referenced by data_matches().
poison_at()
static int poison_at (size_t start, size_t len) static
Definition at line 105 of file data.c.
References byte_at(), fschange::len, and POISON_VAL.
Referenced by data_matches().
prepdata()
static void prepdata (unsigned code, unsigned seq, char * buf, off_t len) static
Definition at line 48 of file data.c.
References buf, fschange::code, fschange::len, memcpy(), memset(), fschange::seq, snprintf(), and strlen().
Referenced by data_map(), and data_matches().
zero_at()
static int zero_at (size_t start, size_t len) static
Definition at line 98 of file data.c.
References byte_at(), and fschange::len.
Referenced by data_matches().
Variable Documentation
databuf
char databuf[DATA_MAXSIZE] static
Definition at line 43 of file data.c.
Referenced by data_map(), data_matches(), and matches_at().
readbuf
char readbuf[DATA_MAXSIZE] static
Definition at line 44 of file data.c.
Referenced by byte_at(), data_mapreadbuf(), main(), matches_at(), and readfiledata().