os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_link.c File Reference
bad_link.c File Reference
#include <unistd.h>
#include <errno.h>
#include "test.h"
Functions
static void link_dir (void)
static void link_empty1 (void)
static void link_empty2 (void)
void test_link (void)
Function Documentation
link_dir()
static void link_dir (void) static
Definition at line 41 of file bad_link.c.
References EINVAL, errno, link(), remove(), report_begin(), report_check(), and TESTDIR.
Referenced by test_link().
link_empty1()
static void link_empty1 (void) static
Definition at line 56 of file bad_link.c.
References EINVAL, errno, link(), report_begin(), report_check(), and TESTDIR.
Referenced by test_link().
link_empty2()
static void link_empty2 (void) static
Definition at line 67 of file bad_link.c.
References create_testdir(), EINVAL, errno, link(), report_begin(), report_check(), rmdir(), and TESTDIR.
Referenced by test_link().
test_link()
void test_link (void)
Definition at line 82 of file bad_link.c.
References link_dir(), link_empty1(), link_empty2(), and test_link_paths().