os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/test/bitmaptest.c File Reference
bitmaptest.c File Reference
#include <types.h>
#include <lib.h>
#include <bitmap.h>
#include <test.h>
Macros
#define TESTSIZE 533
Functions
int bitmaptest (int nargs, char **args)
Macro Definition Documentation
TESTSIZE
#define TESTSIZE 533
Definition at line 35 of file bitmaptest.c.
Function Documentation
bitmaptest()
int bitmaptest (int nargs, char ** args)
Definition at line 38 of file bitmaptest.c.
References bitmap_alloc(), bitmap_create(), bitmap_isset(), bitmap_mark(), bitmap_unmark(), KASSERT, kprintf(), NULL, random(), and TESTSIZE.