os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/schedpong/pong.c File Reference
pong.c File Reference
#include <stdio.h>
#include <err.h>
#include <assert.h>
#include "usem.h"
#include "tasks.h"
Macros
#define MAXCOUNT 64
#define PONGLOOPS 1000
Functions
void pong_prep (unsigned groupid, unsigned count)
void pong_cleanup (unsigned groupid, unsigned count)
static void pong_cyclic (unsigned id)
static void pong_reciprocating (unsigned id)
void pong (unsigned groupid, unsigned id)
Variables
static struct usem sems [MAXCOUNT]
static unsigned nsems
Macro Definition Documentation
MAXCOUNT
#define MAXCOUNT 64
Definition at line 42 of file pong.c.
PONGLOOPS
#define PONGLOOPS 1000
Definition at line 43 of file pong.c.
Function Documentation
pong()
void pong (unsigned groupid, unsigned id)
Definition at line 185 of file pong.c.
References nsems, pong_cyclic(), pong_reciprocating(), printf(), sems, usem_close(), usem_open(), and waitstart().
Referenced by runit().
pong_cleanup()
void pong_cleanup (unsigned groupid, unsigned count)
Definition at line 73 of file pong.c.
References assert, count, nsems, sems, and usem_cleanup().
Referenced by runit().
pong_cyclic()
static void pong_cyclic (unsigned id) static
Definition at line 92 of file pong.c.
References nsems, P(), PONGLOOPS, printf(), putchar(), sems, and V().
Referenced by pong().
pong_prep()
void pong_prep (unsigned groupid, unsigned count)
Definition at line 59 of file pong.c.
References count, err(), MAXCOUNT, nsems, sems, and usem_init().
Referenced by runit().
pong_reciprocating()
static void pong_reciprocating (unsigned id) static
Definition at line 129 of file pong.c.
References nsems, P(), PONGLOOPS, printf(), putchar(), sems, and V().
Referenced by pong().
Variable Documentation
nsems
unsigned nsems static
Definition at line 47 of file pong.c.
Referenced by pong(), pong_cleanup(), pong_cyclic(), pong_prep(), and pong_reciprocating().
sems
struct usem sems[MAXCOUNT] static
Definition at line 46 of file pong.c.
Referenced by pong(), pong_cleanup(), pong_cyclic(), pong_prep(), and pong_reciprocating().