os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/vm/kmalloc.c File Reference
kmalloc.c File Reference
#include <types.h>
#include <lib.h>
#include <spinlock.h>
#include <vm.h>
Data Structures
struct freelist
struct pageref
struct pagerefpage
struct kheap_root
Macros
#define INVALID_OFFSET (0xffff)
#define PR_PAGEADDR(pr) ((pr)->pageaddr_and_blocktype & PAGE_FRAME)
#define PR_BLOCKTYPE(pr) ((pr)->pageaddr_and_blocktype & ~PAGE_FRAME)
#define MKPAB(pa, blk) (((pa)&PAGE_FRAME) | ((blk) & ~PAGE_FRAME))
#define NPAGEREFS_PER_PAGE (PAGE_SIZE / sizeof(struct pageref))
#define INUSE_WORDS (NPAGEREFS_PER_PAGE / 32)
#define NUM_PAGEREFPAGES 16
#define TOTAL_PAGEREFS (NUM_PAGEREFPAGES * NPAGEREFS_PER_PAGE)
#define GUARD_OVERHEAD 0
#define checksubpage(pr) ((void)(pr))
#define checksubpages()
#define LABEL_OVERHEAD 0
Functions
static void fill_deadbeef (void *vptr, size_t len)
static void allocpagerefpage (struct kheap_root *root)
static struct pageref * allocpageref (void)
static void freepageref (struct pageref *p)
void kheap_nextgeneration (void)
void kheap_dump (void)
void kheap_dumpall (void)
static void subpage_stats (struct pageref *pr)
void kheap_printstats (void)
static void remove_lists (struct pageref *pr, int blktype)
static int blocktype (size_t clientsz)
static void * subpage_kmalloc (size_t sz)
static int subpage_kfree (void *ptr)
void * kmalloc (size_t sz)
void kfree (void *ptr)
Variables
static struct spinlock kmalloc_spinlock = SPINLOCK_INITIALIZER
static struct kheap_root kheaproots [NUM_PAGEREFPAGES]
static struct pageref * sizebases [NSIZES]
static struct pageref * allbase
Macro Definition Documentation
checksubpage
#define checksubpage (pr) ((void)(pr))
Definition at line 570 of file kmalloc.c.
checksubpages
#define checksubpages ()
Definition at line 605 of file kmalloc.c.
GUARD_OVERHEAD
#define GUARD_OVERHEAD 0
Definition at line 440 of file kmalloc.c.
INUSE_WORDS
#define INUSE_WORDS (NPAGEREFS_PER_PAGE / 32)
Definition at line 192 of file kmalloc.c.
INVALID_OFFSET
#define INVALID_OFFSET (0xffff)
Definition at line 154 of file kmalloc.c.
LABEL_OVERHEAD
#define LABEL_OVERHEAD 0
Definition at line 696 of file kmalloc.c.
MKPAB
#define MKPAB (pa, blk) (((pa)&PAGE_FRAME) | ((blk) & ~PAGE_FRAME))
Definition at line 158 of file kmalloc.c.
NPAGEREFS_PER_PAGE
#define NPAGEREFS_PER_PAGE (PAGE_SIZE / sizeof(struct pageref))
Definition at line 181 of file kmalloc.c.
NUM_PAGEREFPAGES
#define NUM_PAGEREFPAGES 16
Definition at line 210 of file kmalloc.c.
PR_BLOCKTYPE
#define PR_BLOCKTYPE (pr) ((pr)->pageaddr_and_blocktype & ~PAGE_FRAME)
Definition at line 157 of file kmalloc.c.
PR_PAGEADDR
#define PR_PAGEADDR (pr) ((pr)->pageaddr_and_blocktype & PAGE_FRAME)
Definition at line 156 of file kmalloc.c.
TOTAL_PAGEREFS
#define TOTAL_PAGEREFS (NUM_PAGEREFPAGES * NPAGEREFS_PER_PAGE)
Definition at line 211 of file kmalloc.c.
Function Documentation
allocpageref()
static struct pageref* allocpageref (void) static
Definition at line 258 of file kmalloc.c.
References allocpagerefpage(), INUSE_WORDS, KASSERT, kheaproots, NPAGEREFS_PER_PAGE, NULL, NUM_PAGEREFPAGES, kheap_root::numinuse, kheap_root::page, kheap_root::pagerefs_inuse, and pagerefpage::refs.
Referenced by subpage_kmalloc().
allocpagerefpage()
static void allocpagerefpage (struct kheap_root * root) static
Definition at line 220 of file kmalloc.c.
References alloc_kpages(), free_kpages(), KASSERT, kmalloc_spinlock, kprintf(), NULL, kheap_root::page, PAGE_SIZE, spinlock_acquire(), and spinlock_release().
Referenced by allocpageref().
blocktype()
static int blocktype (size_t clientsz) inline static
Definition at line 853 of file kmalloc.c.
References panic().
Referenced by subpage_kmalloc().
fill_deadbeef()
static void fill_deadbeef (void * vptr, size_t len) static
Definition at line 45 of file kmalloc.c.
Referenced by subpage_kfree(), and subpage_kmalloc().
freepageref()
static void freepageref (struct pageref * p) static
Definition at line 305 of file kmalloc.c.
References KASSERT, kheaproots, NPAGEREFS_PER_PAGE, NULL, NUM_PAGEREFPAGES, kheap_root::numinuse, kheap_root::page, kheap_root::pagerefs_inuse, and pagerefpage::refs.
Referenced by subpage_kfree().
kfree()
void kfree (void * ptr)
Definition at line 1212 of file kmalloc.c.
References free_kpages(), KASSERT, NULL, PAGE_SIZE, and subpage_kfree().
Referenced by array_cleanup(), array_destroy(), array_preallocate(), as_destroy(), attach_console_to_vfs(), bitmap_create(), bitmap_destroy(), compute_thread(), cv_create(), cv_destroy(), dev_uncreate_vnode(), emufs_addtovfs(), emufs_loadvnode(), emufs_reclaim(), fakethread_destroy(), kmalloctest3(), kmalloctest4thread(), kmallocthread(), lock_create(), lock_destroy(), proc_create(), proc_destroy(), sem_create(), sem_destroy(), semfs_create(), semfs_destroy(), semfs_direntry_create(), semfs_direntry_destroy(), semfs_sem_create(), semfs_sem_destroy(), semfs_vnode_destroy(), sfs_fs_create(), sfs_fs_destroy(), sfs_loadvnode(), sfs_reclaim(), thread_create(), thread_destroy(), vfs_doadd(), vfs_swapon(), and wchan_destroy().
kheap_dump()
void kheap_dump (void)
Definition at line 711 of file kmalloc.c.
References kmalloc_spinlock, kprintf(), spinlock_acquire(), and spinlock_release().
Referenced by cmd_kheapdump().
kheap_dumpall()
void kheap_dumpall (void)
Definition at line 724 of file kmalloc.c.
References kmalloc_spinlock, kprintf(), spinlock_acquire(), and spinlock_release().
Referenced by cmd_kheapdump().
kheap_nextgeneration()
void kheap_nextgeneration (void)
Definition at line 701 of file kmalloc.c.
References kmalloc_spinlock, spinlock_acquire(), and spinlock_release().
Referenced by boot(), and cmd_kheapgeneration().
kheap_printstats()
void kheap_printstats (void)
Definition at line 801 of file kmalloc.c.
References allbase, kmalloc_spinlock, kprintf(), pageref::next_all, NULL, spinlock_acquire(), spinlock_release(), and subpage_stats().
Referenced by cmd_kheapstats().
kmalloc()
void* kmalloc (size_t sz)
Definition at line 1170 of file kmalloc.c.
References alloc_kpages(), GUARD_OVERHEAD, KASSERT, LABEL_OVERHEAD, NULL, PAGE_SIZE, and subpage_kmalloc().
Referenced by array_create(), array_preallocate(), as_create(), attach_beep_to_ltimer(), attach_con_to_lscreen(), attach_con_to_lser(), attach_console_to_vfs(), attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), attach_ltrace_to_lamebus(), attach_random_to_lrandom(), attach_rtclock_to_ltimer(), bitmap_create(), compute_thread(), cpu_create(), cv_create(), dev_create_vnode(), devnull_create(), emufs_addtovfs(), emufs_loadvnode(), fakethread_create(), kmalloctest3(), kmalloctest4thread(), kmallocthread(), kstrdup(), lamebus_init(), lock_create(), mkrawname(), proc_create(), sem_create(), semfs_create(), semfs_direntry_create(), semfs_sem_create(), semfs_vnode_create(), sfs_fs_create(), sfs_loadvnode(), thread_create(), thread_fork(), vfs_doadd(), and wchan_create().
remove_lists()
static void remove_lists (struct pageref * pr, int blktype) static
Definition at line 824 of file kmalloc.c.
References allbase, checksubpage, KASSERT, pageref::next_all, pageref::next_samesize, and sizebases.
Referenced by subpage_kfree().
subpage_kfree()
static int subpage_kfree (void * ptr) static
Definition at line 1026 of file kmalloc.c.
References allbase, checksubpage, checksubpages, fill_deadbeef(), free_kpages(), pageref::freelist_offset, freepageref(), INVALID_OFFSET, KASSERT, kmalloc_spinlock, freelist::next, pageref::next_all, pageref::nfree, NULL, PAGE_SIZE, panic(), PR_BLOCKTYPE, PR_PAGEADDR, remove_lists(), spinlock_acquire(), and spinlock_release().
Referenced by kfree().
subpage_kmalloc()
static void* subpage_kmalloc (size_t sz) static
Definition at line 875 of file kmalloc.c.
References allbase, alloc_kpages(), allocpageref(), blocktype(), checksubpage, checksubpages, fill_deadbeef(), free_kpages(), pageref::freelist_offset, GUARD_OVERHEAD, INVALID_OFFSET, KASSERT, kmalloc_spinlock, kprintf(), MKPAB, freelist::next, pageref::next_all, pageref::next_samesize, pageref::nfree, NULL, PAGE_SIZE, pageref::pageaddr_and_blocktype, PR_BLOCKTYPE, PR_PAGEADDR, sizebases, spinlock_acquire(), and spinlock_release().
Referenced by kmalloc().
subpage_stats()
static void subpage_stats (struct pageref * pr) static
Definition at line 747 of file kmalloc.c.
References ARRAYCOUNT, checksubpage, pageref::freelist_offset, INVALID_OFFSET, KASSERT, kmalloc_spinlock, kprintf(), freelist::next, pageref::nfree, NULL, PAGE_SIZE, PR_BLOCKTYPE, PR_PAGEADDR, and spinlock_do_i_hold().
Referenced by kheap_printstats().
Variable Documentation
allbase
struct pageref* allbase static
Definition at line 346 of file kmalloc.c.
Referenced by kheap_printstats(), remove_lists(), subpage_kfree(), and subpage_kmalloc().
kheaproots
struct kheap_root kheaproots[NUM_PAGEREFPAGES] static
Definition at line 213 of file kmalloc.c.
Referenced by allocpageref(), and freepageref().
kmalloc_spinlock
struct spinlock kmalloc_spinlock = SPINLOCK_INITIALIZER static
Definition at line 169 of file kmalloc.c.
Referenced by allocpagerefpage(), kheap_dump(), kheap_dumpall(), kheap_nextgeneration(), kheap_printstats(), subpage_kfree(), subpage_kmalloc(), and subpage_stats().
sizebases
struct pageref* sizebases[NSIZES] static
Definition at line 345 of file kmalloc.c.
Referenced by remove_lists(), and subpage_kmalloc().