os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/vfs/vnode.c File Reference
vnode.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <synch.h>
#include <vfs.h>
#include <vnode.h>
Functions
int vnode_init (struct vnode *vn, const struct vnode_ops *ops, struct fs *fs, void *fsdata)
void vnode_cleanup (struct vnode *vn)
void vnode_incref (struct vnode *vn)
void vnode_decref (struct vnode *vn)
void vnode_check (struct vnode *v, const char *opstr)
Function Documentation
vnode_check()
void vnode_check (struct vnode * v, const char * opstr)
Definition at line 130 of file vnode.c.
References kprintf(), NULL, panic(), spinlock_acquire(), spinlock_release(), vnode::vn_countlock, vnode::vn_fs, vnode::vn_ops, vnode::vn_refcount, VOP_MAGIC, and vnode_ops::vop_magic.
vnode_cleanup()
void vnode_cleanup (struct vnode * vn)
Definition at line 62 of file vnode.c.
References KASSERT, NULL, spinlock_cleanup(), vnode::vn_countlock, vnode::vn_data, vnode::vn_fs, vnode::vn_ops, and vnode::vn_refcount.
Referenced by dev_uncreate_vnode(), emufs_loadvnode(), emufs_reclaim(), semfs_vnode_destroy(), sfs_loadvnode(), and sfs_reclaim().
vnode_decref()
void vnode_decref (struct vnode * vn)
Definition at line 95 of file vnode.c.
References EBUSY, KASSERT, kprintf(), NULL, spinlock_acquire(), spinlock_release(), strerror(), vnode::vn_countlock, vnode::vn_refcount, and VOP_RECLAIM.
vnode_incref()
void vnode_incref (struct vnode * vn)
Definition at line 80 of file vnode.c.
References KASSERT, NULL, spinlock_acquire(), spinlock_release(), vnode::vn_countlock, and vnode::vn_refcount.
vnode_init()
int vnode_init (struct vnode * vn, const struct vnode_ops * ops, struct fs * fs, void * fsdata)
Definition at line 44 of file vnode.c.
References KASSERT, NULL, ops, spinlock_init(), vnode::vn_countlock, vnode::vn_data, vnode::vn_fs, vnode::vn_ops, and vnode::vn_refcount.
Referenced by dev_create_vnode(), emufs_loadvnode(), semfs_vnode_create(), and sfs_loadvnode().