os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/sfsck/passes.h File Reference
passes.h File Reference
Functions
void pass1 (void)
void pass2 (void)
unsigned long pass1_founddirs (void)
unsigned long pass1_foundfiles (void)
Function Documentation
pass1()
void pass1 (void)
Definition at line 481 of file pass1.c.
References pass1_rootdir().
Referenced by main().
pass1_founddirs()
unsigned long pass1_founddirs (void)
Definition at line 487 of file pass1.c.
References count_dirs.
Referenced by main().
pass1_foundfiles()
unsigned long pass1_foundfiles (void)
Definition at line 493 of file pass1.c.
References count_files.
Referenced by main().
pass2()
void pass2 (void)
Definition at line 319 of file pass2.c.
References pass2_dir(), sb_volname(), SFS_ROOTDIR_INO, SFS_VOLNAME_SIZE, and snprintf().
Referenced by main().