os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/lib/array.c File Reference
array.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <array.h>
Macros
#define ARRAYINLINE
Functions
struct array * array_create (void)
void array_destroy (struct array *a)
void array_init (struct array *a)
void array_cleanup (struct array *a)
int array_preallocate (struct array *a, unsigned num)
int array_setsize (struct array *a, unsigned num)
void array_remove (struct array *a, unsigned index)
Macro Definition Documentation
ARRAYINLINE
#define ARRAYINLINE
Definition at line 30 of file array.c.
Function Documentation
array_cleanup()
void array_cleanup (struct array * a)
Definition at line 64 of file array.c.
References ARRAYASSERT, kfree(), NULL, array::num, and array::v.
Referenced by array_destroy().
array_create()
struct array* array_create (void)
Definition at line 38 of file array.c.
References array_init(), kmalloc(), and NULL.
Referenced by arraytest(), and arraytest2().
array_destroy()
void array_destroy (struct array * a)
Definition at line 50 of file array.c.
References array_cleanup(), and kfree().
Referenced by arraytest(), and arraytest2().
array_init()
void array_init (struct array * a)
Definition at line 57 of file array.c.
References array::max, NULL, array::num, and array::v.
Referenced by array_create().
array_preallocate()
int array_preallocate (struct array * a, unsigned num)
Definition at line 79 of file array.c.
References ENOMEM, kfree(), kmalloc(), array::max, memcpy(), NULL, array::num, num, and array::v.
Referenced by array_setsize().
array_remove()
void array_remove (struct array * a, unsigned index)
Definition at line 125 of file array.c.
References ARRAYASSERT, array::max, memmove(), array::num, num, and array::v.
Referenced by arraytest2(), and testa().
array_setsize()
int array_setsize (struct array * a, unsigned num)
Definition at line 111 of file array.c.
References array_preallocate(), array::num, and num.
Referenced by array_add(), arraytest(), arraytest2(), and testa().