os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/bloat/bloat.c File Reference
bloat.c File Reference
#include <stdbool.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <assert.h>
#include <err.h>
Macros
#define PAGE_SIZE 4096
Functions
static void moremem (void)
static void touchpage (unsigned pagenum)
static unsigned pickpage (unsigned numpages)
static void touchmem (void)
static void run (void)
static void printsettings (void)
static void usage (void)
int main (int argc, char *argv[])
Variables
static void * firstpage
static void * lastpage
static unsigned allocs
static unsigned touchpages
static unsigned bias
Macro Definition Documentation
PAGE_SIZE
#define PAGE_SIZE 4096
Definition at line 20 of file bloat.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 153 of file bloat.c.
References allocs, atoi(), bias, errx(), printsettings(), run(), srandom(), strcmp(), touchpages, and usage().
moremem()
static void moremem (void) static
Definition at line 38 of file bloat.c.
References allocs, err(), firstpage, lastpage, NULL, PAGE_SIZE, and sbrk().
Referenced by run().
pickpage()
static unsigned pickpage (unsigned numpages) static
Definition at line 70 of file bloat.c.
References assert, bias, random(), and touchpages.
Referenced by touchmem().
printsettings()
static void printsettings (void) static
Definition at line 132 of file bloat.c.
References allocs, bias, PAGE_SIZE, printf(), and touchpages.
Referenced by main().
run()
static void run (void) static
Definition at line 122 of file bloat.c.
References moremem(), and touchmem().
Referenced by main().
touchmem()
static void touchmem (void) static
Definition at line 105 of file bloat.c.
References firstpage, lastpage, num, PAGE_SIZE, pickpage(), touchpage(), touchpages, and warnx().
Referenced by run().
touchpage()
static void touchpage (unsigned pagenum) static
Definition at line 60 of file bloat.c.
References firstpage, and PAGE_SIZE.
Referenced by touchmem().
usage()
static void usage (void) static
Definition at line 143 of file bloat.c.
References exit(), and warnx().
Referenced by main().
Variable Documentation
allocs
unsigned allocs static
Definition at line 27 of file bloat.c.
Referenced by main(), moremem(), and printsettings().
bias
unsigned bias static
Definition at line 33 of file bloat.c.
Referenced by checkblock(), main(), markblock(), pickpage(), and printsettings().
firstpage
void* firstpage static
Definition at line 23 of file bloat.c.
Referenced by moremem(), touchmem(), and touchpage().
lastpage
void* lastpage static
Definition at line 24 of file bloat.c.
Referenced by moremem(), and touchmem().
touchpages
unsigned touchpages static
Definition at line 30 of file bloat.c.
Referenced by main(), pickpage(), printsettings(), and touchmem().