os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/test.h File Reference
test.h File Reference
Functions
int arraytest (int, char **)
int arraytest2 (int, char **)
int bitmaptest (int, char **)
int threadlisttest (int, char **)
int threadtest (int, char **)
int threadtest2 (int, char **)
int threadtest3 (int, char **)
int semtest (int, char **)
int locktest (int, char **)
int cvtest (int, char **)
int cvtest2 (int, char **)
int semu1 (int, char **)
int semu2 (int, char **)
int semu3 (int, char **)
int semu4 (int, char **)
int semu5 (int, char **)
int semu6 (int, char **)
int semu7 (int, char **)
int semu8 (int, char **)
int semu9 (int, char **)
int semu10 (int, char **)
int semu11 (int, char **)
int semu12 (int, char **)
int semu13 (int, char **)
int semu14 (int, char **)
int semu15 (int, char **)
int semu16 (int, char **)
int semu17 (int, char **)
int semu18 (int, char **)
int semu19 (int, char **)
int semu20 (int, char **)
int semu21 (int, char **)
int semu22 (int, char **)
int fstest (int, char **)
int readstress (int, char **)
int writestress (int, char **)
int writestress2 (int, char **)
int longstress (int, char **)
int createstress (int, char **)
int printfile (int, char **)
int kmalloctest (int, char **)
int kmallocstress (int, char **)
int kmalloctest3 (int, char **)
int kmalloctest4 (int, char **)
int nettest (int, char **)
int runprogram (char *progname)
void menu (char *argstr)
void kmain (char *bootstring)
Function Documentation
arraytest()
int arraytest (int , char **)
Definition at line 124 of file arraytest.c.
References array_create(), array_destroy(), array_setsize(), KASSERT, kprintf(), NULL, and testa().
arraytest2()
int arraytest2 (int , char **)
Definition at line 149 of file arraytest.c.
References array_add(), array_create(), array_destroy(), array_get(), array_num(), array_remove(), array_set(), array_setsize(), BIGTESTSIZE, KASSERT, kprintf(), NTH, and NULL.
bitmaptest()
int bitmaptest (int , char **)
Definition at line 38 of file bitmaptest.c.
References bitmap_alloc(), bitmap_create(), bitmap_isset(), bitmap_mark(), bitmap_unmark(), KASSERT, kprintf(), NULL, random(), and TESTSIZE.
createstress()
int createstress (int , char **)
cvtest()
int cvtest (int , char **)
Definition at line 270 of file synchtest.c.
References cvtestthread(), donesem, inititems(), kprintf(), NTHREADS, NULL, P(), panic(), strerror(), testval1, and thread_fork().
cvtest2()
int cvtest2 (int , char **)
Definition at line 360 of file synchtest.c.
References cv_create(), cv_destroy(), exitsem, gatesem, kprintf(), lock_create(), lock_destroy(), NCVS, NULL, P(), panic(), sem_create(), sem_destroy(), sleepthread(), testcvs, testlocks, thread_fork(), and wakethread().
fstest()
int fstest (int , char **)
kmain()
void kmain (char * bootstring)
Definition at line 209 of file main.c.
References boot(), and menu().
kmallocstress()
int kmallocstress (int , char **)
Definition at line 114 of file kmalloctest.c.
References kmallocthread(), kprintf(), NTHREADS, NULL, P(), panic(), sem_create(), sem_destroy(), strerror(), and thread_fork().
kmalloctest()
int kmalloctest (int , char **)
Definition at line 101 of file kmalloctest.c.
References kmallocthread(), kprintf(), and NULL.
kmalloctest3()
int kmalloctest3 (int , char **)
Definition at line 173 of file kmalloctest.c.
References atoi(), DIVROUNDUP, EINVAL, KASSERT, kfree(), kmalloc(), kprintf(), NULL, NUM_KM3_SIZES, PAGE_SIZE, and panic().
kmalloctest4()
int kmalloctest4 (int , char **)
Definition at line 341 of file kmalloctest.c.
References kmalloctest4thread(), kprintf(), NTHREADS, NULL, P(), panic(), sem_create(), sem_destroy(), strerror(), and thread_fork().
locktest()
int locktest (int , char **)
Definition at line 196 of file synchtest.c.
References donesem, inititems(), kprintf(), locktestthread(), NTHREADS, NULL, P(), panic(), strerror(), and thread_fork().
longstress()
int longstress (int , char **)
menu()
void menu (char * argstr)
Definition at line 816 of file menu.c.
References buf, kgets(), kprintf(), and menu_execute().
Referenced by kmain(), and main().
nettest()
int nettest (int , char **)
Definition at line 38 of file nettest.c.
References kprintf().
printfile()
int printfile (int , char **)
Definition at line 721 of file fstest.c.
References buf, EINVAL, kprintf(), O_RDONLY, O_WRONLY, strcpy(), strerror(), uio_kinit(), uio::uio_offset, UIO_READ, uio::uio_resid, UIO_WRITE, vfs_close(), vfs_open(), VOP_READ, and VOP_WRITE.
readstress()
int readstress (int , char **)
runprogram()
int runprogram (char * progname)
Definition at line 55 of file runprogram.c.
References as_activate(), as_create(), as_define_stack(), EINVAL, ENOMEM, enter_new_process(), KASSERT, load_elf(), NULL, O_RDONLY, panic(), proc_getas(), proc_setas(), progname, vfs_close(), and vfs_open().
Referenced by cmd_progthread().
semtest()
int semtest (int , char **)
Definition at line 104 of file synchtest.c.
References donesem, inititems(), kprintf(), NTHREADS, NULL, P(), panic(), semtestthread(), strerror(), testsem, thread_fork(), and V().
semu1()
int semu1 (int , char **)
Definition at line 155 of file semunit.c.
References KASSERT, name, NAMESTRING, NULL, ok(), panic(), semaphore::sem_count, sem_create(), sem_destroy(), semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, spinlock_not_held(), and strcmp().
semu10()
int semu10 (int , char **)
Definition at line 449 of file semunit.c.
References do_semu1011().
semu11()
int semu11 (int , char **)
Definition at line 458 of file semunit.c.
References do_semu1011().
semu12()
int semu12 (int , char **)
Definition at line 536 of file semunit.c.
References semu1213().
semu13()
int semu13 (int , char **)
Definition at line 545 of file semunit.c.
References semu1213().
semu14()
int semu14 (int , char **)
Definition at line 558 of file semunit.c.
References KASSERT, kprintf(), makesem(), panic(), semaphore::sem_count, and V().
semu15()
int semu15 (int , char **)
Definition at line 582 of file semunit.c.
References kprintf(), NULL, panic(), and V().
semu16()
int semu16 (int , char **)
Definition at line 596 of file semunit.c.
References makesem(), ok(), P(), sem_destroy(), spinlock_acquire(), spinlock_cleanup(), spinlock_init(), and spinlock_release().
semu17()
int semu17 (int , char **)
Definition at line 641 of file semunit.c.
References clocksleep(), KASSERT, kprintf(), makesem(), NULL, ok(), panic(), S_SLEEP, sem_destroy(), semu17_sub(), semu17_thread, thread::t_state, thread_fork(), and V().
semu18()
int semu18 (int , char **)
Definition at line 679 of file semunit.c.
References KASSERT, makesem(), name, NAMESTRING, P(), semaphore::sem_count, semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, spinlock_not_held(), and strcmp().
semu19()
int semu19 (int , char **)
Definition at line 736 of file semunit.c.
References KASSERT, makesem(), name, NAMESTRING, NULL, P(), panic(), semaphore::sem_count, semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, semu19_sub(), spinlock_not_held(), strcmp(), and thread_fork().
semu2()
int semu2 (int , char **)
Definition at line 182 of file semunit.c.
References kprintf(), NULL, panic(), and sem_create().
semu20()
int semu20 (int , char **)
Definition at line 775 of file semunit.c.
References kprintf(), makesem(), P(), and panic().
semu21()
int semu21 (int , char **)
Definition at line 792 of file semunit.c.
References kprintf(), makesem(), P(), and panic().
semu22()
int semu22 (int , char **)
Definition at line 812 of file semunit.c.
References kprintf(), NULL, P(), and panic().
semu3()
int semu3 (int , char **)
Definition at line 199 of file semunit.c.
References kprintf(), NULL, panic(), and sem_destroy().
semu4()
int semu4 (int , char **)
Definition at line 213 of file semunit.c.
References KASSERT, makesem(), ok(), semaphore::sem_count, and sem_destroy().
semu5()
int semu5 (int , char **)
Definition at line 237 of file semunit.c.
References KASSERT, NAMESTRING, NULL, ok(), panic(), semaphore::sem_count, sem_create(), and sem_destroy().
semu6()
int semu6 (int , char **)
Definition at line 261 of file semunit.c.
References kprintf(), makesem(), makewaiter(), panic(), and sem_destroy().
semu7()
int semu7 (int , char **)
Definition at line 280 of file semunit.c.
References makesem(), ok(), sem_destroy(), spinlock_acquire(), spinlock_cleanup(), spinlock_init(), spinlock_release(), and V().
semu8()
int semu8 (int , char **)
Definition at line 367 of file semunit.c.
References do_semu89().
semu9()
int semu9 (int , char **)
Definition at line 376 of file semunit.c.
References do_semu89().
threadlisttest()
int threadlisttest (int , char **)
Definition at line 316 of file threadlisttest.c.
References fakethread_create(), fakethread_destroy(), fakethreads, kprintf(), names, NULL, NUMNAMES, threadlisttest_a(), threadlisttest_b(), threadlisttest_c(), threadlisttest_d(), threadlisttest_e(), and threadlisttest_f().
threadtest()
int threadtest (int , char **)
Definition at line 121 of file threadtest.c.
References init_sem(), kprintf(), and runthreads().
threadtest2()
int threadtest2 (int , char **)
Definition at line 135 of file threadtest.c.
References init_sem(), kprintf(), and runthreads().
threadtest3()
int threadtest3 (int , char **)
Definition at line 263 of file tt3.c.
References atoi(), kprintf(), and runtest3().
writestress()
int writestress (int , char **)
writestress2()
int writestress2 (int , char **)