os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/mainbus.h File Reference
mainbus.h File Reference
Functions
void mainbus_bootstrap (void)
void mainbus_start_cpus (void)
void mainbus_interrupt (struct trapframe *)
size_t mainbus_ramsize (void)
void mainbus_send_ipi (struct cpu *target)
void mainbus_debugger (void)
void mainbus_halt (void)
void mainbus_poweroff (void)
void mainbus_reboot (void)
void mainbus_panic (void)
Function Documentation
mainbus_bootstrap()
void mainbus_bootstrap (void)
Definition at line 87 of file lamebus_machdep.c.
References autoconf_lamebus(), CPU_FREQUENCY, HZ, KASSERT, kprintf(), lamebus, lamebus_find_cpus(), lamebus_init(), mips_timer_set(), and spl0().
Referenced by boot().
mainbus_debugger()
void mainbus_debugger (void)
Definition at line 283 of file lamebus_machdep.c.
References ltrace_stop().
Referenced by cmd_debug().
mainbus_halt()
void mainbus_halt (void)
Definition at line 226 of file lamebus_machdep.c.
References cpu_halt().
Referenced by sys_reboot().
mainbus_interrupt()
void mainbus_interrupt (struct trapframe *)
Definition at line 298 of file lamebus_machdep.c.
References CCA_IRQS, CPU_FREQUENCY, hardclock(), HZ, interprocessor_interrupt(), KASSERT, lamebus, lamebus_clear_ipi(), lamebus_interrupt(), LAMEBUS_IPI_BIT, LAMEBUS_IRQ_BIT, MIPS_TIMER_BIT, mips_timer_set(), panic(), and trapframe::tf_cause.
Referenced by mips_trap().
mainbus_panic()
void mainbus_panic (void)
Definition at line 239 of file lamebus_machdep.c.
References mainbus_poweroff().
Referenced by panic().
mainbus_poweroff()
void mainbus_poweroff (void)
Definition at line 192 of file lamebus_machdep.c.
References lamebus, and lamebus_poweroff().
Referenced by mainbus_panic(), mainbus_reboot(), and sys_reboot().
mainbus_ramsize()
size_t mainbus_ramsize (void)
Definition at line 249 of file lamebus_machdep.c.
References lamebus_ramsize().
Referenced by ram_bootstrap().
mainbus_reboot()
void mainbus_reboot (void)
Definition at line 207 of file lamebus_machdep.c.
References kprintf(), and mainbus_poweroff().
Referenced by sys_reboot().
mainbus_send_ipi()
void mainbus_send_ipi (struct cpu * target)
Definition at line 274 of file lamebus_machdep.c.
References lamebus, and lamebus_assert_ipi().
Referenced by ipi_send(), and ipi_tlbshootdown().
mainbus_start_cpus()
void mainbus_start_cpus (void)
Definition at line 126 of file lamebus_machdep.c.
References lamebus, and lamebus_start_cpus().
Referenced by thread_start_cpus().