os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/thread/hangman.c File Reference
hangman.c File Reference
#include <types.h>
#include <lib.h>
#include <spl.h>
#include <spinlock.h>
#include <hangman.h>
Functions
static void hangman_check (const struct hangman_lockable *start, const struct hangman_actor *target)
void hangman_wait (struct hangman_actor *a, struct hangman_lockable *l)
void hangman_acquire (struct hangman_actor *a, struct hangman_lockable *l)
void hangman_release (struct hangman_actor *a, struct hangman_lockable *l)
Variables
static struct spinlock hangman_lock = SPINLOCK_INITIALIZER
Function Documentation
hangman_acquire()
void hangman_acquire (struct hangman_actor * a, struct hangman_lockable * l)
Definition at line 132 of file hangman.c.
References hangman_lock, NULL, panic(), spinlock_acquire(), and spinlock_release().
hangman_check()
static void hangman_check (const struct hangman_lockable * start, const struct hangman_actor * target) static
Definition at line 52 of file hangman.c.
References found, hangman_lock, kprintf(), NULL, panic(), spinlock_release(), and splhigh().
Referenced by hangman_wait().
hangman_release()
void hangman_release (struct hangman_actor * a, struct hangman_lockable * l)
Definition at line 160 of file hangman.c.
References hangman_lock, NULL, panic(), spinlock_acquire(), and spinlock_release().
hangman_wait()
void hangman_wait (struct hangman_actor * a, struct hangman_lockable * l)
Definition at line 110 of file hangman.c.
References hangman_check(), hangman_lock, NULL, panic(), spinlock_acquire(), and spinlock_release().
Variable Documentation
hangman_lock
struct spinlock hangman_lock = SPINLOCK_INITIALIZER static
Definition at line 40 of file hangman.c.
Referenced by hangman_acquire(), hangman_check(), hangman_release(), and hangman_wait().