os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/lib/hostcompat/hostcompat.c File Reference
hostcompat.c File Reference
#include <unistd.h>
#include <termios.h>
#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include "hostcompat.h"
Functions
static void hostcompat_ttyreset (void)
static void hostcompat_ttyresume (void)
static int hostcompat_ttysetup (void)
static void hostcompat_die (int sig)
static void hostcompat_stop (int sig)
static void hostcompat_cont (int sig)
void hostcompat_init (int argc, char *argv[])
Variables
const char * hostcompat_progname = NULL
static struct termios hostcompat_runtios
static struct termios hostcompat_savetios
Function Documentation
hostcompat_cont()
static void hostcompat_cont (int sig) static
Definition at line 167 of file hostcompat.c.
References hostcompat_stop(), hostcompat_ttyresume(), sig, SIGCONT, SIGTSTP, SIGTTIN, and SIGTTOU.
Referenced by hostcompat_init().
hostcompat_die()
static void hostcompat_die (int sig) static
Definition at line 130 of file hostcompat.c.
References _exit(), getpid(), hostcompat_ttyreset(), sig, and SIG_DFL.
Referenced by hostcompat_init().
hostcompat_init()
void hostcompat_init (int argc, char * argv[])
Definition at line 188 of file hostcompat.c.
References hostcompat_cont(), hostcompat_die(), hostcompat_progname, hostcompat_stop(), hostcompat_ttyreset(), hostcompat_ttysetup(), NULL, SIGABRT, SIGALRM, SIGBUS, SIGCONT, SIGEMT, SIGFPE, SIGHUP, SIGILL, SIGINT, SIGPIPE, SIGPROF, SIGQUIT, SIGSEGV, SIGSYS, SIGTERM, SIGTRAP, SIGTSTP, SIGTTIN, SIGTTOU, SIGUSR1, SIGUSR2, SIGVTALRM, SIGXCPU, and SIGXFSZ.
hostcompat_stop()
static void hostcompat_stop (int sig) static
Definition at line 150 of file hostcompat.c.
References getpid(), hostcompat_ttyreset(), sig, and SIG_DFL.
Referenced by hostcompat_cont(), and hostcompat_init().
hostcompat_ttyreset()
static void hostcompat_ttyreset (void) static
Definition at line 56 of file hostcompat.c.
References hostcompat_savetios, and STDIN_FILENO.
Referenced by hostcompat_die(), hostcompat_init(), and hostcompat_stop().
hostcompat_ttyresume()
static void hostcompat_ttyresume (void) static
Definition at line 66 of file hostcompat.c.
References hostcompat_runtios, and STDIN_FILENO.
Referenced by hostcompat_cont().
hostcompat_ttysetup()
static int hostcompat_ttysetup (void) static
Definition at line 76 of file hostcompat.c.
References hostcompat_runtios, hostcompat_savetios, and STDIN_FILENO.
Referenced by hostcompat_init().
Variable Documentation
hostcompat_progname
const char* hostcompat_progname = NULL
Definition at line 42 of file hostcompat.c.
Referenced by hostcompat_init(), and main().
hostcompat_runtios
struct termios hostcompat_runtios static
Definition at line 48 of file hostcompat.c.
Referenced by hostcompat_ttyresume(), and hostcompat_ttysetup().
hostcompat_savetios
struct termios hostcompat_savetios static
Definition at line 49 of file hostcompat.c.
Referenced by hostcompat_ttyreset(), and hostcompat_ttysetup().