os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/sfsck/main.h File Reference
main.h File Reference
Macros
#define EXIT_USAGE 4
#define EXIT_FATAL 3
#define EXIT_UNRECOV 2
#define EXIT_RECOV 1
#define EXIT_CLEAN 0
Functions
void setbadness (int code)
Macro Definition Documentation
EXIT_CLEAN
#define EXIT_CLEAN 0
Definition at line 44 of file main.h.
EXIT_FATAL
#define EXIT_FATAL 3
Definition at line 41 of file main.h.
EXIT_RECOV
#define EXIT_RECOV 1
Definition at line 43 of file main.h.
EXIT_UNRECOV
#define EXIT_UNRECOV 2
Definition at line 42 of file main.h.
EXIT_USAGE
#define EXIT_USAGE 4
Definition at line 40 of file main.h.
Function Documentation
setbadness()
void setbadness (int code)
Definition at line 54 of file main.c.
References badness.
Referenced by check_indirect_block(), check_inode_blocks(), freemap_blockinuse(), freemap_check(), inode_adjust_filelinks(), pass1_dir(), pass1_direntry(), pass1_inode(), pass1_rootdir(), pass2_dir(), sb_check(), and sfs_writedirblock().