os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/uio.h File Reference
uio.h File Reference
#include <kern/iovec.h>
Data Structures
struct uio
Enumerations
enum uio_rw { UIO_READ, UIO_WRITE }
enum uio_seg { UIO_USERISPACE, UIO_USERSPACE, UIO_SYSSPACE }
Functions
int uiomove (void *kbuffer, size_t len, struct uio *uio)
int uiomovezeros (size_t len, struct uio *uio)
void uio_kinit (struct iovec *, struct uio *, void *kbuf, size_t len, off_t pos, enum uio_rw rw)
Enumeration Type Documentation
uio_rw
enum uio_rw
Enumerator
UIO_READ
UIO_WRITE
Definition at line 61 of file uio.h.
uio_seg
enum uio_seg
Enumerator
UIO_USERISPACE
UIO_USERSPACE
UIO_SYSSPACE
Definition at line 67 of file uio.h.
Function Documentation
uio_kinit()
void uio_kinit (struct iovec * , struct uio * , void * kbuf, size_t len, off_t pos, enum uio_rw rw)
Definition at line 152 of file uio.c.
References iovec::iov_len, NULL, pos, uio::uio_iov, uio::uio_iovcnt, uio::uio_offset, uio::uio_resid, uio::uio_rw, uio::uio_segflg, uio::uio_space, and UIO_SYSSPACE.
Referenced by cmd_pwd(), createstress_thread(), fstest_read(), fstest_write(), load_elf(), and printfile().
uiomove()
int uiomove (void * kbuffer, size_t len, struct uio * uio)
Definition at line 42 of file uio.c.
References copyin(), copyout(), iovec::iov_len, KASSERT, memmove(), NULL, panic(), proc_getas(), uio::uio_iov, uio::uio_iovcnt, uio::uio_offset, UIO_READ, uio::uio_resid, uio::uio_rw, uio::uio_segflg, uio::uio_space, UIO_SYSSPACE, UIO_USERISPACE, UIO_USERSPACE, and UIO_WRITE.
Referenced by con_io(), emu_doread(), emu_write(), lhd_io(), lrandom_read(), semfs_getdirentry(), sfs_partialio(), uiomovezeros(), and vfs_getcwd().
uiomovezeros()
int uiomovezeros (size_t len, struct uio * uio)
Definition at line 122 of file uio.c.
References KASSERT, UIO_READ, uio::uio_rw, and uiomove().
Referenced by load_segment(), and sfs_blockio().