os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/lib/kprintf.c File Reference
kprintf.c File Reference
#include <types.h>
#include <kern/unistd.h>
#include <stdarg.h>
#include <lib.h>
#include <spl.h>
#include <cpu.h>
#include <thread.h>
#include <current.h>
#include <synch.h>
#include <mainbus.h>
#include <vfs.h>
#include <lamebus/ltrace.h>
Functions
void kprintf_bootstrap (void)
static void console_send (void *junk, const char *data, size_t len)
int kprintf (const char *fmt,...)
void panic (const char *fmt,...)
void badassert (const char *expr, const char *file, int line, const char *func)
Variables
uint32_t dbflags = 0
static struct lock * kprintf_lock
static struct spinlock kprintf_spinlock
Function Documentation
badassert()
void badassert (const char * expr, const char * file, int line, const char * func)
Definition at line 212 of file kprintf.c.
References panic().
console_send()
static void console_send (void * junk, const char * data, size_t len) static
Definition at line 81 of file kprintf.c.
References putch().
Referenced by kprintf(), and panic().
kprintf()
int kprintf (const char * fmt, ...)
Definition at line 96 of file kprintf.c.
References __vprintf(), console_send(), kprintf_lock, kprintf_spinlock, lock_acquire(), lock_release(), NULL, spinlock_acquire(), spinlock_release(), va_end, and va_start.
Referenced by panic().
kprintf_bootstrap()
void kprintf_bootstrap (void)
Definition at line 65 of file kprintf.c.
References KASSERT, kprintf_lock, kprintf_spinlock, lock_create(), NULL, panic(), and spinlock_init().
Referenced by boot().
panic()
void panic (const char * fmt, ...)
Definition at line 134 of file kprintf.c.
References __vprintf(), console_send(), kprintf(), ltrace_stop(), mainbus_panic(), NULL, splhigh(), thread_panic(), va_end, va_start, and vfs_sync().
Referenced by badassert(), and kprintf_bootstrap().
Variable Documentation
dbflags
uint32_t dbflags = 0
Definition at line 45 of file kprintf.c.
kprintf_lock
struct lock* kprintf_lock static
Definition at line 48 of file kprintf.c.
Referenced by kprintf(), and kprintf_bootstrap().
kprintf_spinlock
struct spinlock kprintf_spinlock static
Definition at line 51 of file kprintf.c.
Referenced by kprintf(), and kprintf_bootstrap().