os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/thread/clock.c File Reference
clock.c File Reference
#include <types.h>
#include <lib.h>
#include <cpu.h>
#include <wchan.h>
#include <clock.h>
#include <thread.h>
#include <current.h>
Macros
#define SCHEDULE_HARDCLOCKS 4 /* Reschedule every 4 hardclocks. */
#define MIGRATE_HARDCLOCKS 16 /* Migrate every 16 hardclocks. */
Functions
void hardclock_bootstrap (void)
void timerclock (void)
void hardclock (void)
void clocksleep (int num_secs)
Variables
static struct wchan * lbolt
static struct spinlock lbolt_lock
Macro Definition Documentation
MIGRATE_HARDCLOCKS
#define MIGRATE_HARDCLOCKS 16 /* Migrate every 16 hardclocks. */
Definition at line 54 of file clock.c.
SCHEDULE_HARDCLOCKS
#define SCHEDULE_HARDCLOCKS 4 /* Reschedule every 4 hardclocks. */
Definition at line 53 of file clock.c.
Function Documentation
clocksleep()
void clocksleep (int num_secs)
Definition at line 113 of file clock.c.
References lbolt, lbolt_lock, spinlock_acquire(), spinlock_release(), and wchan_sleep().
Referenced by do_semu1011(), makewaiter(), semu1213(), semu17(), and semu19_sub().
hardclock()
void hardclock (void)
Definition at line 93 of file clock.c.
References MIGRATE_HARDCLOCKS, schedule(), SCHEDULE_HARDCLOCKS, thread_consider_migration(), and thread_yield().
Referenced by ltimer_irq(), and mainbus_interrupt().
hardclock_bootstrap()
void hardclock_bootstrap (void)
Definition at line 66 of file clock.c.
References lbolt, lbolt_lock, NULL, panic(), spinlock_init(), and wchan_create().
Referenced by boot().
timerclock()
void timerclock (void)
Definition at line 80 of file clock.c.
References lbolt, lbolt_lock, spinlock_acquire(), spinlock_release(), and wchan_wakeall().
Referenced by ltimer_irq().
Variable Documentation
lbolt
struct wchan* lbolt static
Definition at line 59 of file clock.c.
Referenced by clocksleep(), hardclock_bootstrap(), and timerclock().
lbolt_lock
struct spinlock lbolt_lock static
Definition at line 60 of file clock.c.
Referenced by clocksleep(), hardclock_bootstrap(), and timerclock().