os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/rmtest/rmtest.c File Reference
rmtest.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
Macros
#define TEST "rmdata"
#define TESTDATA "I wish I was a headlight. -- Jerry Garcia"
#define TESTLEN (sizeof(TESTDATA)-1)
Functions
static void dorm (int fd)
static int same (const char *a, const char *b, int len)
int main (void)
Macro Definition Documentation
TEST
#define TEST "rmdata"
Definition at line 46 of file rmtest.c.
TESTDATA
#define TESTDATA "I wish I was a headlight. -- Jerry Garcia"
Definition at line 47 of file rmtest.c.
TESTLEN
#define TESTLEN (sizeof(TESTDATA)-1)
Definition at line 48 of file rmtest.c.
Function Documentation
dorm()
static void dorm (int fd) static
Definition at line 52 of file rmtest.c.
References _exit(), close(), err(), fd, fork(), pid, remove(), TEST, waitpid(), warn(), warnx(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
Referenced by main().
main()
int main (void)
Definition at line 101 of file rmtest.c.
References buf, close(), dorm(), ENOENT, err(), errno, errx(), lseek(), memset(), O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, open(), printf(), read(), same(), SEEK_SET, TEST, TESTDATA, TESTLEN, warn(), warnx(), and write().
same()
static int same (const char * a, const char * b, int len) static
Definition at line 92 of file rmtest.c.
Referenced by main().