os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/psort/psort.c File Reference
psort.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
Macros
#define RANDOM_MAX RAND_MAX
#define PATH_KEYS "sortkeys"
#define PATH_SORTED "output"
#define PATH_TESTDIR "psortdir"
#define PATH_RANDOM "rand:"
#define WORKNUM (96*1024)
#define NOBODY (-1)
Functions
static void sortints (int *v, int num)
static void initprogname (const char *av0)
static void vscomplain (char *buf, size_t len, const char *fmt, va_list ap, int err)
static void complainx (const char *fmt,...)
static void complain (const char *fmt,...)
static int doopen (const char *path, int flags, int mode)
static void doclose (const char *path, int fd)
static void docreate (const char *path)
static void doremove (const char *path)
static off_t getsize (const char *path)
static size_t doread (const char *path, int fd, void *buf, size_t len)
static void doexactread (const char *path, int fd, void *buf, size_t len)
static void dowrite (const char *path, int fd, const void *buf, size_t len)
static void dolseek (const char *name, int fd, off_t offset, int whence)
static pid_t dofork (void)
static int dowait (int guy, pid_t pid)
static void doforkall (const char *phasename, void(*func)(void))
static void seekmyplace (const char *name, int fd)
static int getmykeys (void)
static unsigned long checksum_file (const char *path)
static void genkeys_sub (void)
static void genkeys (void)
static const char * binname (int a, int b)
static const char * mergedname (int a)
static void bin (void)
static void sortbins (void)
static void mergebins (void)
static void assemble (void)
static void checksize_bins (void)
static void checksize_merge (void)
static void sort (void)
static const char * validname (int a)
static void checksize_valid (void)
static void dovalidate (void)
static void validate (void)
static void setdir (void)
static void unsetdir (void)
static void randomize (void)
static void usage (void)
static void doargs (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
static int numprocs = 4
static int numkeys = 128*1024
static int workspace [WORKNUM]
static long randomseed = 15432753
static off_t correctsize
static unsigned long checksum
static int me = NOBODY
static const char * progname
static long * seeds
Macro Definition Documentation
NOBODY
#define NOBODY (-1)
Definition at line 123 of file psort.c.
PATH_KEYS
#define PATH_KEYS "sortkeys"
Definition at line 56 of file psort.c.
PATH_RANDOM
#define PATH_RANDOM "rand:"
Definition at line 59 of file psort.c.
PATH_SORTED
#define PATH_SORTED "output"
Definition at line 57 of file psort.c.
PATH_TESTDIR
#define PATH_TESTDIR "psortdir"
Definition at line 58 of file psort.c.
RANDOM_MAX
#define RANDOM_MAX RAND_MAX
Definition at line 53 of file psort.c.
WORKNUM
#define WORKNUM (96*1024)
Definition at line 109 of file psort.c.
Function Documentation
assemble()
static void assemble (void) static
Definition at line 839 of file psort.c.
References complain(), doclose(), dolseek(), doopen(), dup2(), execv(), exit(), fd, getsize(), me, mergedname(), NULL, O_WRONLY, PATH_SORTED, SEEK_SET, and STDOUT_FILENO.
Referenced by sort().
bin()
static void bin (void) static
Definition at line 672 of file psort.c.
References assert, binname(), complainx(), doclose(), doexactread(), doopen(), dowrite(), getmykeys(), me, name, numprocs, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, PATH_KEYS, RANDOM_MAX, seekmyplace(), WORKNUM, and workspace.
Referenced by sort().
binname()
static const char* binname (int a, int b) static
Definition at line 654 of file psort.c.
References snprintf().
Referenced by bin(), checksize_bins(), mergebins(), sort(), and sortbins().
checksize_bins()
static void checksize_bins (void) static
Definition at line 870 of file psort.c.
References binname(), complain(), correctsize, exit(), getsize(), and numprocs.
Referenced by sort().
checksize_merge()
static void checksize_merge (void) static
Definition at line 890 of file psort.c.
References complain(), correctsize, exit(), getsize(), mergedname(), and numprocs.
Referenced by sort().
checksize_valid()
static void checksize_valid (void) static
Definition at line 979 of file psort.c.
References complainx(), exit(), getsize(), numprocs, and validname().
Referenced by validate().
checksum_file()
static unsigned long checksum_file (const char * path) static
Definition at line 551 of file psort.c.
References buf, count, doclose(), doopen(), doread(), fd, O_RDONLY, and sum().
Referenced by genkeys(), and sort().
complain()
static void complain (const char * fmt, ...) static
Definition at line 249 of file psort.c.
References buf, err(), errno, STDERR_FILENO, strlen(), va_end, va_start, vscomplain(), and write().
Referenced by assemble(), checksize_bins(), checksize_merge(), doargs(), doclose(), dofork(), dolseek(), doopen(), doread(), doremove(), dovalidate(), dowait(), dowrite(), getsize(), unsetdir(), usage(), and validate().
complainx()
static void complainx (const char * fmt, ...) static
Definition at line 227 of file psort.c.
References buf, STDERR_FILENO, strlen(), va_end, va_start, vscomplain(), and write().
Referenced by bin(), checksize_valid(), doexactread(), doforkall(), dowait(), dowrite(), genkeys(), main(), mergebins(), sort(), sortbins(), and validate().
doargs()
static void doargs (int argc, char * argv[]) static
Definition at line 1161 of file psort.c.
References assert, atoi(), ch, complain(), exit(), numkeys, numprocs, randomize(), randomseed, and usage().
Referenced by main().
doclose()
static void doclose (const char * path, int fd) static
Definition at line 288 of file psort.c.
References close(), complain(), exit(), and fd.
Referenced by assemble(), bin(), checksum_file(), docreate(), dovalidate(), genkeys_sub(), mergebins(), randomize(), and sortbins().
docreate()
static void docreate (const char * path) static
Definition at line 298 of file psort.c.
References doclose(), doopen(), fd, O_CREAT, O_TRUNC, and O_WRONLY.
Referenced by genkeys(), and sort().
doexactread()
static void doexactread (const char * path, int fd, void * buf, size_t len) static
Definition at line 387 of file psort.c.
References buf, complainx(), doread(), exit(), and fd.
Referenced by bin(), dovalidate(), randomize(), sortbins(), and validate().
dofork()
static pid_t dofork (void) static
Definition at line 449 of file psort.c.
References complain(), fork(), and pid.
Referenced by doforkall().
doforkall()
static void doforkall (const char * phasename, void(*)(void) func) static
Definition at line 490 of file psort.c.
References complainx(), dofork(), dowait(), exit(), me, numprocs, and pids.
Referenced by genkeys(), sort(), and validate().
dolseek()
static void dolseek (const char * name, int fd, off_t offset, int whence) static
Definition at line 417 of file psort.c.
References complain(), exit(), fd, lseek(), and name.
Referenced by assemble(), seekmyplace(), and sortbins().
doopen()
static int doopen (const char * path, int flags, int mode) static
Definition at line 274 of file psort.c.
References complain(), exit(), fd, and open().
Referenced by assemble(), bin(), checksum_file(), docreate(), dovalidate(), genkeys_sub(), getsize(), mergebins(), randomize(), sortbins(), and validate().
doread()
static size_t doread (const char * path, int fd, void * buf, size_t len) static
Definition at line 373 of file psort.c.
References buf, complain(), exit(), fd, and read().
Referenced by checksum_file(), doexactread(), and mergebins().
doremove()
static void doremove (const char * path) static
Definition at line 308 of file psort.c.
References complain(), ENOSYS, errno, and remove().
Referenced by sort(), unsetdir(), and validate().
dovalidate()
static void dovalidate (void) static
Definition at line 1000 of file psort.c.
References complain(), doclose(), doexactread(), doopen(), dowrite(), exit(), fd, getmykeys(), me, name, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, PATH_SORTED, RANDOM_MAX, seekmyplace(), validname(), WORKNUM, and workspace.
Referenced by validate().
dowait()
static int dowait (int guy, pid_t pid) static
Definition at line 466 of file psort.c.
References assert, complain(), complainx(), pid, waitpid(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
Referenced by doforkall().
dowrite()
static void dowrite (const char * path, int fd, const void * buf, size_t len) static
Definition at line 400 of file psort.c.
References buf, complain(), complainx(), exit(), fd, and write().
Referenced by bin(), dovalidate(), genkeys_sub(), mergebins(), and sortbins().
genkeys()
static void genkeys (void) static
Definition at line 618 of file psort.c.
References checksum, checksum_file(), complainx(), correctsize, docreate(), doforkall(), exit(), genkeys_sub(), getsize(), NULL, numkeys, numprocs, PATH_KEYS, random(), randomseed, seeds, and srandom().
Referenced by main().
genkeys_sub()
static void genkeys_sub (void) static
Definition at line 577 of file psort.c.
References assert, doclose(), doopen(), dowrite(), fd, getmykeys(), me, O_WRONLY, PATH_KEYS, random(), RANDOM_MAX, seeds, seekmyplace(), srandom(), WORKNUM, and workspace.
Referenced by genkeys().
getmykeys()
static int getmykeys (void) static
Definition at line 536 of file psort.c.
References me, numkeys, and numprocs.
Referenced by bin(), dovalidate(), and genkeys_sub().
getsize()
static off_t getsize (const char * path) static
Definition at line 327 of file psort.c.
References buf, close(), complain(), doopen(), ENOSYS, errno, exit(), fd, fstat(), lseek(), O_RDONLY, SEEK_CUR, SEEK_END, and stat().
Referenced by assemble(), checksize_bins(), checksize_merge(), checksize_valid(), genkeys(), sort(), and sortbins().
initprogname()
static void initprogname (const char * av0) static
Definition at line 184 of file psort.c.
References progname, and strrchr().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 1208 of file psort.c.
References complainx(), correctsize, doargs(), genkeys(), initprogname(), NULL, numkeys, setdir(), sort(), unsetdir(), and validate().
mergebins()
static void mergebins (void) static
Definition at line 757 of file psort.c.
References assert, binname(), complainx(), doclose(), doopen(), doread(), dowrite(), exit(), me, mergedname(), name, numprocs, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, WORKNUM, and workspace.
Referenced by sort().
mergedname()
static const char* mergedname (int a) static
Definition at line 663 of file psort.c.
References snprintf().
Referenced by assemble(), checksize_merge(), mergebins(), and sort().
randomize()
static void randomize (void) static
Definition at line 1142 of file psort.c.
References doclose(), doexactread(), doopen(), fd, O_RDONLY, PATH_RANDOM, and randomseed.
Referenced by doargs().
seekmyplace()
static void seekmyplace (const char * name, int fd) static
Definition at line 522 of file psort.c.
References dolseek(), fd, me, name, numkeys, numprocs, and SEEK_SET.
Referenced by bin(), dovalidate(), and genkeys_sub().
setdir()
static void setdir (void) static
Definition at line 1114 of file psort.c.
References domkdir(), and PATH_TESTDIR.
Referenced by main().
sort()
static void sort (void) static
Definition at line 908 of file psort.c.
References assemble(), bin(), binname(), checksize_bins(), checksize_merge(), checksum, checksum_file(), complainx(), correctsize, docreate(), doforkall(), doremove(), exit(), getsize(), mergebins(), mergedname(), numprocs, PATH_SORTED, and sortbins().
Referenced by main().
sortbins()
static void sortbins (void) static
Definition at line 725 of file psort.c.
References binname(), complainx(), doclose(), doexactread(), dolseek(), doopen(), dowrite(), exit(), fd, getsize(), me, name, numprocs, O_RDWR, SEEK_SET, sortints(), and workspace.
Referenced by sort().
sortints()
static void sortints (int * v, int num) static
Definition at line 132 of file psort.c.
References assert, and num.
Referenced by sortbins().
unsetdir()
static void unsetdir (void) static
Definition at line 1124 of file psort.c.
References complain(), doremove(), PATH_KEYS, PATH_SORTED, PATH_TESTDIR, and rmdir().
Referenced by main().
usage()
static void usage (void) static
Definition at line 1153 of file psort.c.
References complain(), exit(), and progname.
Referenced by doargs().
validate()
static void validate (void) static
Definition at line 1061 of file psort.c.
References checksize_valid(), complain(), complainx(), doexactread(), doforkall(), doopen(), doremove(), dovalidate(), exit(), fd, name, numprocs, O_RDONLY, RANDOM_MAX, and validname().
Referenced by main().
validname()
static const char* validname (int a) static
Definition at line 970 of file psort.c.
References snprintf().
Referenced by checksize_valid(), dovalidate(), and validate().
vscomplain()
static void vscomplain (char * buf, size_t len, const char * fmt, va_list ap, int err) static
Definition at line 202 of file psort.c.
References buf, err(), me, pos, progname, snprintf(), strerror(), strlen(), and vsnprintf().
Referenced by complain(), and complainx().
Variable Documentation
checksum
unsigned long checksum static
Definition at line 121 of file psort.c.
Referenced by genkeys(), and sort().
correctsize
off_t correctsize static
Definition at line 120 of file psort.c.
Referenced by checksize_bins(), checksize_merge(), genkeys(), main(), and sort().
me
int me = NOBODY static
Definition at line 124 of file psort.c.
Referenced by assemble(), bin(), doforkall(), dotest(), dovalidate(), genkeys_sub(), getmykeys(), mergebins(), seekmyplace(), sortbins(), and vscomplain().
numkeys
int numkeys = 128*1024 static
Definition at line 111 of file psort.c.
Referenced by doargs(), genkeys(), getmykeys(), main(), and seekmyplace().
numprocs
int numprocs = 4 static
Definition at line 110 of file psort.c.
Referenced by bin(), checksize_bins(), checksize_merge(), checksize_valid(), doargs(), doforkall(), genkeys(), getmykeys(), mergebins(), seekmyplace(), sort(), sortbins(), and validate().
progname
const char* progname static
Definition at line 126 of file psort.c.
Referenced by cmd_progthread(), initprogname(), runprogram(), usage(), and vscomplain().
randomseed
long randomseed = 15432753 static
Definition at line 117 of file psort.c.
Referenced by doargs(), genkeys(), and randomize().
seeds
long* seeds static
Definition at line 573 of file psort.c.
Referenced by genkeys(), and genkeys_sub().
workspace
int workspace[WORKNUM] static
Definition at line 114 of file psort.c.
Referenced by bin(), dovalidate(), genkeys_sub(), mergebins(), and sortbins().