os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/vfs.h File Reference
vfs.h File Reference
#include <array.h>
Macros
#define VFSINLINE INLINE
Functions
int vfs_setcurdir (struct vnode *dir)
int vfs_clearcurdir (void)
int vfs_getcurdir (struct vnode **retdir)
int vfs_sync (void)
int vfs_getroot (const char *devname, struct vnode **result)
const char * vfs_getdevname (struct fs *fs)
int vfs_lookup (char *path, struct vnode **result)
int vfs_lookparent (char *path, struct vnode **result, char *buf, size_t buflen)
int vfs_open (char *path, int openflags, mode_t mode, struct vnode **ret)
void vfs_close (struct vnode *vn)
int vfs_readlink (char *path, struct uio *data)
int vfs_symlink (const char *contents, char *path)
int vfs_mkdir (char *path, mode_t mode)
int vfs_link (char *oldpath, char *newpath)
int vfs_remove (char *path)
int vfs_rmdir (char *path)
int vfs_rename (char *oldpath, char *newpath)
int vfs_chdir (char *path)
int vfs_getcwd (struct uio *buf)
void vfs_bootstrap (void)
int vfs_setbootfs (const char *fsname)
void vfs_clearbootfs (void)
int vfs_adddev (const char *devname, struct device *dev, int mountable)
int vfs_addfs (const char *devname, struct fs *fs)
int vfs_mount (const char *devname, void *data, int(*mountfunc)(void *data, struct device *dev, struct fs **result))
int vfs_unmount (const char *devname)
int vfs_swapon (const char *devname, struct vnode **result)
int vfs_swapoff (const char *devname)
int vfs_unmountall (void)
DECLARRAY (vnode, VFSINLINE)
DEFARRAY (vnode, VFSINLINE)
void vfs_biglock_acquire (void)
void vfs_biglock_release (void)
bool vfs_biglock_do_i_hold (void)
Macro Definition Documentation
VFSINLINE
#define VFSINLINE INLINE
Definition at line 190 of file vfs.h.
Function Documentation
DECLARRAY()
DECLARRAY (vnode , VFSINLINE)
DEFARRAY()
DEFARRAY (vnode , VFSINLINE)
vfs_adddev()
int vfs_adddev (const char * devname, struct device * dev, int mountable)
Definition at line 482 of file vfslist.c.
References NULL, and vfs_doadd().
Referenced by attach_console_to_vfs(), config_lhd(), config_random(), and devnull_create().
vfs_addfs()
int vfs_addfs (const char * devname, struct fs * fs)
Definition at line 493 of file vfslist.c.
References NULL, and vfs_doadd().
Referenced by emufs_addtovfs(), and semfs_bootstrap().
vfs_biglock_acquire()
void vfs_biglock_acquire (void)
Definition at line 127 of file vfslist.c.
References lock_acquire(), lock_do_i_hold(), vfs_biglock, and vfs_biglock_depth.
Referenced by emufs_loadvnode(), emufs_reclaim(), sfs_creat(), sfs_domount(), sfs_fsync(), sfs_getroot(), sfs_gettype(), sfs_getvolname(), sfs_itrunc(), sfs_link(), sfs_lookparent(), sfs_lookup(), sfs_read(), sfs_reclaim(), sfs_remove(), sfs_rename(), sfs_sync(), sfs_unmount(), sfs_write(), vfs_clearbootfs(), vfs_doadd(), vfs_getcwd(), vfs_lookparent(), vfs_lookup(), vfs_mount(), vfs_setbootfs(), vfs_swapoff(), vfs_swapon(), vfs_sync(), vfs_unmount(), and vfs_unmountall().
vfs_biglock_do_i_hold()
bool vfs_biglock_do_i_hold (void)
Definition at line 164 of file vfslist.c.
References lock_do_i_hold(), and vfs_biglock.
Referenced by badnames(), findmount(), getdevice(), sfs_bmap(), sfs_metaio(), sfs_partialio(), sfs_rwblock(), vfs_getdevname(), and vfs_getroot().
vfs_biglock_release()
void vfs_biglock_release (void)
Definition at line 153 of file vfslist.c.
References KASSERT, lock_do_i_hold(), lock_release(), vfs_biglock, and vfs_biglock_depth.
Referenced by emufs_loadvnode(), emufs_reclaim(), sfs_creat(), sfs_domount(), sfs_fsync(), sfs_getroot(), sfs_gettype(), sfs_getvolname(), sfs_itrunc(), sfs_link(), sfs_lookparent(), sfs_lookup(), sfs_read(), sfs_reclaim(), sfs_remove(), sfs_rename(), sfs_sync(), sfs_unmount(), sfs_write(), vfs_clearbootfs(), vfs_doadd(), vfs_getcwd(), vfs_lookparent(), vfs_lookup(), vfs_mount(), vfs_setbootfs(), vfs_swapoff(), vfs_swapon(), vfs_sync(), vfs_unmount(), and vfs_unmountall().
vfs_bootstrap()
void vfs_bootstrap (void)
Definition at line 102 of file vfslist.c.
References devnull_create(), knowndevs, lock_create(), NULL, panic(), semfs_bootstrap(), vfs_biglock, and vfs_biglock_depth.
Referenced by boot().
vfs_chdir()
int vfs_chdir (char * path)
Definition at line 124 of file vfscwd.c.
References vfs_lookup(), vfs_setcurdir(), and VOP_DECREF.
Referenced by cmd_chdir(), and vfs_setbootfs().
vfs_clearbootfs()
void vfs_clearbootfs (void)
Definition at line 115 of file vfslookup.c.
References change_bootfs(), NULL, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by shutdown().
vfs_clearcurdir()
int vfs_clearcurdir (void)
Definition at line 103 of file vfscwd.c.
References curproc, NULL, spinlock_acquire(), spinlock_release(), and VOP_DECREF.
Referenced by shutdown().
vfs_close()
void vfs_close (struct vnode * vn)
Definition at line 116 of file vfspath.c.
References VOP_DECREF.
Referenced by createstress_thread(), dowritestress2(), fstest_read(), fstest_write(), printfile(), and runprogram().
vfs_getcurdir()
int vfs_getcurdir (struct vnode ** retdir)
Definition at line 49 of file vfscwd.c.
References curproc, ENOENT, NULL, spinlock_acquire(), spinlock_release(), and VOP_INCREF.
Referenced by getdevice(), vfs_getcwd(), and vfs_setbootfs().
vfs_getcwd()
int vfs_getcwd (struct uio * buf)
Definition at line 144 of file vfscwd.c.
References cwd, FSOP_GETVOLNAME, KASSERT, name, NULL, strlen(), UIO_READ, uio::uio_rw, uiomove(), vfs_biglock_acquire(), vfs_biglock_release(), vfs_getcurdir(), vfs_getdevname(), VOP_DECREF, and VOP_NAMEFILE.
Referenced by cmd_pwd().
vfs_getdevname()
const char* vfs_getdevname (struct fs * fs)
Definition at line 277 of file vfslist.c.
References KASSERT, knowndev::kd_fs, knowndev::kd_name, knowndevs, NULL, num, and vfs_biglock_do_i_hold().
Referenced by vfs_getcwd().
vfs_getroot()
int vfs_getroot (const char * devname, struct vnode ** result)
Definition at line 198 of file vfslist.c.
References ENODEV, ENXIO, FSOP_GETROOT, FSOP_GETVOLNAME, KASSERT, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndev::kd_vnode, knowndevs, NULL, num, strcmp(), SWAP_FS, vfs_biglock_do_i_hold(), and VOP_INCREF.
Referenced by getdevice().
vfs_link()
int vfs_link (char * oldpath, char * newpath)
Definition at line 191 of file vfspath.c.
References EXDEV, NAME_MAX, NULL, vfs_lookparent(), vfs_lookup(), vnode::vn_fs, VOP_DECREF, and VOP_LINK.
vfs_lookparent()
int vfs_lookparent (char * path, struct vnode ** result, char * buf, size_t buflen)
Definition at line 243 of file vfslookup.c.
References buf, EINVAL, getdevice(), strlen(), vfs_biglock_acquire(), vfs_biglock_release(), VOP_DECREF, and VOP_LOOKPARENT.
Referenced by vfs_link(), vfs_mkdir(), vfs_open(), vfs_remove(), vfs_rename(), vfs_rmdir(), and vfs_symlink().
vfs_lookup()
int vfs_lookup (char * path, struct vnode ** result)
Definition at line 276 of file vfslookup.c.
References getdevice(), strlen(), vfs_biglock_acquire(), vfs_biglock_release(), VOP_DECREF, and VOP_LOOKUP.
Referenced by vfs_chdir(), vfs_link(), vfs_open(), and vfs_readlink().
vfs_mkdir()
int vfs_mkdir (char * path, mode_t mode)
Definition at line 277 of file vfspath.c.
References name, NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_MKDIR.
vfs_mount()
int vfs_mount (const char * devname, void * data, int(*)(void *data, struct device *dev, struct fs **result) mountfunc)
Referenced by sfs_mount().
vfs_open()
int vfs_open (char * path, int openflags, mode_t mode, struct vnode ** ret)
Definition at line 45 of file vfspath.c.
References EINVAL, KASSERT, name, NAME_MAX, NULL, O_ACCMODE, O_CREAT, O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, vfs_lookparent(), vfs_lookup(), VOP_CREAT, VOP_DECREF, VOP_EACHOPEN, and VOP_TRUNCATE.
Referenced by createstress_thread(), dowritestress2(), fstest_read(), fstest_write(), printfile(), and runprogram().
vfs_readlink()
int vfs_readlink (char * path, struct uio * data)
Definition at line 256 of file vfspath.c.
References vfs_lookup(), VOP_DECREF, and VOP_READLINK.
vfs_remove()
int vfs_remove (char * path)
Definition at line 137 of file vfspath.c.
References name, NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_REMOVE.
Referenced by fstest_remove(), and fstest_write().
vfs_rename()
int vfs_rename (char * oldpath, char * newpath)
Definition at line 156 of file vfspath.c.
References EXDEV, NAME_MAX, NULL, vfs_lookparent(), vnode::vn_fs, VOP_DECREF, and VOP_RENAME.
vfs_rmdir()
int vfs_rmdir (char * path)
Definition at line 299 of file vfspath.c.
References name, NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_RMDIR.
vfs_setbootfs()
int vfs_setbootfs (const char * fsname)
Definition at line 71 of file vfslookup.c.
References change_bootfs(), EINVAL, NAME_MAX, snprintf(), strcat(), strchr(), strlen(), vfs_biglock_acquire(), vfs_biglock_release(), vfs_chdir(), and vfs_getcurdir().
Referenced by boot(), and cmd_bootfs().
vfs_setcurdir()
int vfs_setcurdir (struct vnode * dir)
Definition at line 71 of file vfscwd.c.
References curproc, ENOTDIR, NULL, S_IFDIR, spinlock_acquire(), spinlock_release(), VOP_DECREF, VOP_GETTYPE, and VOP_INCREF.
Referenced by vfs_chdir().
vfs_swapoff()
int vfs_swapoff (const char * devname)
Definition at line 688 of file vfslist.c.
References EINVAL, fail(), findmount(), KASSERT, knowndev::kd_fs, knowndev::kd_name, kprintf(), NULL, SWAP_FS, vfs_biglock_acquire(), and vfs_biglock_release().
vfs_swapon()
int vfs_swapon (const char * devname, struct vnode ** result)
Definition at line 586 of file vfslist.c.
References EBUSY, ENOMEM, findmount(), KASSERT, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndev::kd_vnode, kfree(), kprintf(), kstrdup(), NULL, strlen(), SWAP_FS, vfs_biglock_acquire(), vfs_biglock_release(), and VOP_INCREF.
vfs_symlink()
int vfs_symlink (const char * contents, char * path)
Definition at line 231 of file vfspath.c.
References NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_SYMLINK.
vfs_sync()
int vfs_sync (void)
Definition at line 173 of file vfslist.c.
References FSOP_SYNC, knowndev::kd_fs, knowndevs, NULL, num, SWAP_FS, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by cmd_quit(), cmd_sync(), and panic().
vfs_unmount()
int vfs_unmount (const char * devname)
Definition at line 638 of file vfslist.c.
References EINVAL, fail(), findmount(), FSOP_SYNC, FSOP_UNMOUNT, KASSERT, knowndev::kd_device, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, kprintf(), NULL, SWAP_FS, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by cmd_unmount().
vfs_unmountall()
int vfs_unmountall (void)
Definition at line 721 of file vfslist.c.
References EBUSY, FSOP_SYNC, FSOP_UNMOUNT, knowndev::kd_fs, knowndev::kd_name, knowndev::kd_rawname, knowndevs, kprintf(), NULL, num, strerror(), SWAP_FS, vfs_biglock_acquire(), and vfs_biglock_release().
Referenced by shutdown().