os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/usemtest/usemtest.c File Reference
usemtest.c File Reference
#include <sys/types.h>
#include <sys/wait.h>
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <err.h>
Data Structures
struct usem
Macros
#define ONCELOOPS 3
#define TWICELOOPS 2
#define THRICELOOPS 1
#define LOOPS (ONCELOOPS + 2*TWICELOOPS + 3*THRICELOOPS)
#define NUMJOBS 4
Functions
static void say (const char *str)
static void dowait (pid_t pid, unsigned num)
static void usem_init (struct usem *sem, const char *tag, unsigned num)
static void usem_open (struct usem *sem)
static void usem_close (struct usem *sem)
static void usem_cleanup (struct usem *sem)
static void P (struct usem *sem)
static void V (struct usem *sem)
static void child_plain (struct usem *gosem, struct usem *waitsem, unsigned num)
static void child_with_own_fd (struct usem *gosem, struct usem *waitsem, unsigned num)
static void baseparent (struct usem *gosems, struct usem *waitsems)
static void basetest (void)
static void concparent (struct usem *gosems, struct usem *waitsems)
static void conctest (void)
int main (void)
Macro Definition Documentation
LOOPS
#define LOOPS (ONCELOOPS + 2*TWICELOOPS + 3*THRICELOOPS)
Definition at line 51 of file usemtest.c.
NUMJOBS
#define NUMJOBS 4
Definition at line 52 of file usemtest.c.
ONCELOOPS
#define ONCELOOPS 3
Definition at line 48 of file usemtest.c.
THRICELOOPS
#define THRICELOOPS 1
Definition at line 50 of file usemtest.c.
TWICELOOPS
#define TWICELOOPS 2
Definition at line 49 of file usemtest.c.
Function Documentation
baseparent()
static void baseparent (struct usem * gosems, struct usem * waitsems) static
Definition at line 230 of file usemtest.c.
References NUMJOBS, ONCELOOPS, P(), putchar(), say(), THRICELOOPS, TWICELOOPS, usem_close(), usem_open(), and V().
Referenced by basetest().
basetest()
static void basetest (void) static
Definition at line 285 of file usemtest.c.
References _exit(), baseparent(), child_with_own_fd(), dowait(), err(), fork(), NUMJOBS, pids, usem_cleanup(), and usem_init().
Referenced by main().
child_plain()
static void child_plain (struct usem * gosem, struct usem * waitsem, unsigned num) static
Definition at line 197 of file usemtest.c.
References LOOPS, num, NUMJOBS, P(), say(), and V().
Referenced by child_with_own_fd(), and conctest().
child_with_own_fd()
static void child_with_own_fd (struct usem * gosem, struct usem * waitsem, unsigned num) static
Definition at line 219 of file usemtest.c.
References child_plain(), num, usem_close(), and usem_open().
Referenced by basetest().
concparent()
static void concparent (struct usem * gosems, struct usem * waitsems) static
Definition at line 320 of file usemtest.c.
References LOOPS, NUMJOBS, P(), putchar(), and V().
Referenced by conctest().
conctest()
static void conctest (void) static
Definition at line 340 of file usemtest.c.
References _exit(), child_plain(), concparent(), dowait(), err(), fork(), NUMJOBS, pids, say(), usem_cleanup(), usem_close(), usem_init(), and usem_open().
Referenced by main().
dowait()
static void dowait (pid_t pid, unsigned num) static
Definition at line 90 of file usemtest.c.
References num, pid, waitpid(), warn(), warnx(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
Referenced by basetest(), and conctest().
main()
int main (void)
Definition at line 383 of file usemtest.c.
References basetest(), conctest(), and say().
P()
static void P (struct usem * sem) static
Definition at line 162 of file usemtest.c.
References err(), errx(), usem::fd, usem::name, and read().
Referenced by baseparent(), child_plain(), and concparent().
say()
static void say (const char * str) static
Definition at line 60 of file usemtest.c.
References putchar().
Referenced by baseparent(), child_plain(), conctest(), and main().
usem_cleanup()
static void usem_cleanup (struct usem * sem) static
Definition at line 155 of file usemtest.c.
References usem::name, and remove().
Referenced by basetest(), and conctest().
usem_close()
static void usem_close (struct usem * sem) static
Definition at line 146 of file usemtest.c.
References close(), usem::fd, usem::name, and warn().
Referenced by baseparent(), child_with_own_fd(), and conctest().
usem_init()
static void usem_init (struct usem * sem, const char * tag, unsigned num) static
Definition at line 123 of file usemtest.c.
References close(), err(), usem::fd, usem::name, num, O_CREAT, O_RDWR, O_TRUNC, open(), and snprintf().
Referenced by basetest(), and conctest().
usem_open()
static void usem_open (struct usem * sem) static
Definition at line 136 of file usemtest.c.
References err(), usem::fd, usem::name, O_RDWR, and open().
Referenced by baseparent(), child_with_own_fd(), and conctest().
V()
static void V (struct usem * sem) static
Definition at line 178 of file usemtest.c.
References err(), errx(), usem::fd, usem::name, and write().
Referenced by baseparent(), child_plain(), and concparent().