os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/thread/spl.c File Reference
spl.c File Reference
#include <types.h>
#include <lib.h>
#include <cpu.h>
#include <spl.h>
#include <thread.h>
#include <current.h>
Macros
#define SPL_INLINE /* empty */
Functions
void splraise (int oldspl, int newspl)
void spllower (int oldspl, int newspl)
int splx (int spl)
Macro Definition Documentation
SPL_INLINE
#define SPL_INLINE /* empty */
Definition at line 31 of file spl.c.
Function Documentation
spllower()
void spllower (int oldspl, int newspl)
Definition at line 107 of file spl.c.
References cpu_irqon(), IPL_HIGH, IPL_NONE, KASSERT, and thread::t_iplhigh_count.
Referenced by spinlock_release(), and splx().
splraise()
void splraise (int oldspl, int newspl)
Definition at line 87 of file spl.c.
References cpu_irqoff(), IPL_HIGH, IPL_NONE, KASSERT, and thread::t_iplhigh_count.
Referenced by spinlock_acquire(), and splx().
splx()
int splx (int spl)
Definition at line 132 of file spl.c.
References spllower(), splraise(), and thread::t_curspl.
Referenced by as_activate(), ltimer_gettime(), mips_trap(), proc_addthread(), proc_remthread(), spl0(), splhigh(), thread_switch(), and vm_fault().