os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/arch/mips/thread/cpu.c File Reference
cpu.c File Reference
#include <types.h>
#include <lib.h>
#include <mips/specialreg.h>
#include <mips/trapframe.h>
#include <platform/maxcpus.h>
#include <cpu.h>
#include <thread.h>
Macros
#define SYS161_PRID_ORIG 0x000003ff
#define SYS161_PRID_2X 0x000000a1
#define GET_STATUS(x) __asm volatile("mfc0 %0,$12" : "=r" (x))
#define SET_STATUS(x) __asm volatile("mtc0 %0,$12" :: "r" (x))
Functions
void cpu_machdep_init (struct cpu *c)
static uint32_t cpu_getprid (void)
static uint32_t cpu_getfeatures (void)
static uint32_t cpu_getifeatures (void)
void cpu_identify (char *buf, size_t max)
void cpu_irqon (void)
void cpu_irqoff (void)
static void cpu_irqonoff (void)
static void wait (void)
void cpu_idle (void)
void cpu_halt (void)
Variables
vaddr_t cpustacks [MAXCPUS]
vaddr_t cputhreads [MAXCPUS]
Macro Definition Documentation
GET_STATUS
#define GET_STATUS (x) __asm volatile("mfc0 %0,$12" : "=r" (x))
Definition at line 203 of file cpu.c.
SET_STATUS
#define SET_STATUS (x) __asm volatile("mtc0 %0,$12" :: "r" (x))
Definition at line 204 of file cpu.c.
SYS161_PRID_2X
#define SYS161_PRID_2X 0x000000a1
Definition at line 111 of file cpu.c.
SYS161_PRID_ORIG
#define SYS161_PRID_ORIG 0x000003ff
Definition at line 110 of file cpu.c.
Function Documentation
cpu_getfeatures()
static uint32_t cpu_getfeatures (void) inline static
Definition at line 125 of file cpu.c.
Referenced by cpu_identify().
cpu_getifeatures()
static uint32_t cpu_getifeatures (void) inline static
Definition at line 139 of file cpu.c.
Referenced by cpu_identify().
cpu_getprid()
static uint32_t cpu_getprid (void) inline static
Definition at line 115 of file cpu.c.
Referenced by cpu_identify().
cpu_halt()
void cpu_halt (void)
Definition at line 303 of file cpu.c.
References cpu_irqoff(), and wait().
Referenced by interprocessor_interrupt(), lamebus_poweroff(), and mainbus_halt().
cpu_identify()
void cpu_identify (char * buf, size_t max)
Definition at line 152 of file cpu.c.
References buf, cpu_getfeatures(), cpu_getifeatures(), cpu_getprid(), kprintf(), snprintf(), SYS161_PRID_2X, and SYS161_PRID_ORIG.
Referenced by cpu_hatch(), and thread_start_cpus().
cpu_idle()
void cpu_idle (void)
Definition at line 293 of file cpu.c.
References cpu_irqonoff(), and wait().
Referenced by thread_switch().
cpu_irqoff()
void cpu_irqoff (void)
Definition at line 223 of file cpu.c.
References CST_IEc, GET_STATUS, and SET_STATUS.
Referenced by cpu_halt(), lamebus_poweroff(), mips_trap(), mips_usermode(), and splraise().
cpu_irqon()
void cpu_irqon (void)
Definition at line 210 of file cpu.c.
References CST_IEc, GET_STATUS, and SET_STATUS.
Referenced by spllower().
cpu_irqonoff()
static void cpu_irqonoff (void) static
Definition at line 237 of file cpu.c.
References CST_IEc, GET_STATUS, and SET_STATUS.
Referenced by cpu_idle().
cpu_machdep_init()
void cpu_machdep_init (struct cpu * c)
Definition at line 76 of file cpu.c.
References cpu::c_curthread, cpu::c_number, cpustacks, cputhreads, KASSERT, MAXCPUS, NULL, STACK_SIZE, and thread::t_stack.
Referenced by cpu_create().
wait()
static void wait (void) inline static
Definition at line 267 of file cpu.c.
Referenced by cpu_halt(), and cpu_idle().
Variable Documentation
cpustacks
vaddr_t cpustacks[MAXCPUS]
Definition at line 67 of file cpu.c.
Referenced by cpu_machdep_init(), mips_trap(), and mips_usermode().
cputhreads
vaddr_t cputhreads[MAXCPUS]
Definition at line 68 of file cpu.c.
Referenced by cpu_machdep_init(), mips_trap(), and mips_usermode().