os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/addrspace.h File Reference
addrspace.h File Reference
#include <vm.h>
#include "opt-dumbvm.h"
Data Structures
struct addrspace
Functions
struct addrspace * as_create (void)
int as_copy (struct addrspace *src, struct addrspace **ret)
void as_activate (void)
void as_deactivate (void)
void as_destroy (struct addrspace *)
int as_define_region (struct addrspace *as, vaddr_t vaddr, size_t sz, int readable, int writeable, int executable)
int as_prepare_load (struct addrspace *as)
int as_complete_load (struct addrspace *as)
int as_define_stack (struct addrspace *as, vaddr_t *initstackptr)
int load_elf (struct vnode *v, vaddr_t *entrypoint)
Function Documentation
as_activate()
void as_activate (void)
Definition at line 264 of file dumbvm.c.
References NULL, NUM_TLB, proc_getas(), splhigh(), splx(), tlb_write(), TLBHI_INVALID, and TLBLO_INVALID.
Referenced by runprogram(), thread_startup(), and thread_switch().
as_complete_load()
int as_complete_load (struct addrspace * as)
Definition at line 370 of file dumbvm.c.
References dumbvm_can_sleep().
Referenced by load_elf().
as_copy()
int as_copy (struct addrspace * src, struct addrspace ** ret)
Definition at line 387 of file dumbvm.c.
References as_create(), as_destroy(), as_prepare_load(), dumbvm_can_sleep(), DUMBVM_STACKPAGES, ENOMEM, KASSERT, memmove(), NULL, PADDR_TO_KVADDR, and PAGE_SIZE.
as_create()
struct addrspace* as_create (void)
Definition at line 238 of file dumbvm.c.
References kmalloc(), and NULL.
Referenced by as_copy(), and runprogram().
as_deactivate()
void as_deactivate (void)
Definition at line 285 of file dumbvm.c.
Referenced by proc_destroy().
as_define_region()
int as_define_region (struct addrspace * as, vaddr_t vaddr, size_t sz, int readable, int writeable, int executable)
Definition at line 291 of file dumbvm.c.
References dumbvm_can_sleep(), ENOSYS, kprintf(), PAGE_FRAME, and PAGE_SIZE.
Referenced by load_elf().
as_define_stack()
int as_define_stack (struct addrspace * as, vaddr_t * initstackptr)
Definition at line 378 of file dumbvm.c.
References KASSERT, and USERSTACK.
Referenced by runprogram().
as_destroy()
void as_destroy (struct addrspace *)
Definition at line 257 of file dumbvm.c.
References dumbvm_can_sleep(), and kfree().
Referenced by as_copy(), and proc_destroy().
as_prepare_load()
int as_prepare_load (struct addrspace * as)
Definition at line 339 of file dumbvm.c.
References as_zero_region(), dumbvm_can_sleep(), DUMBVM_STACKPAGES, ENOMEM, getppages(), and KASSERT.
Referenced by as_copy(), and load_elf().
load_elf()
int load_elf (struct vnode * v, vaddr_t * entrypoint)
Definition at line 154 of file loadelf.c.
References as_complete_load(), as_define_region(), as_prepare_load(), Elf32_Ehdr::e_entry, Elf32_Ehdr::e_ident, Elf32_Ehdr::e_machine, Elf32_Ehdr::e_phentsize, Elf32_Ehdr::e_phnum, Elf32_Ehdr::e_phoff, Elf32_Ehdr::e_type, Elf32_Ehdr::e_version, EI_CLASS, EI_DATA, EI_MAG0, EI_MAG1, EI_MAG2, EI_MAG3, EI_VERSION, ELFCLASS32, ELFDATA2MSB, ELFMAG0, ELFMAG1, ELFMAG2, ELFMAG3, EM_MACHINE, ENOEXEC, ET_EXEC, EV_CURRENT, kprintf(), load_segment(), Elf32_Phdr::p_filesz, Elf32_Phdr::p_flags, Elf32_Phdr::p_memsz, Elf32_Phdr::p_offset, Elf32_Phdr::p_type, Elf32_Phdr::p_vaddr, PF_R, PF_W, PF_X, proc_getas(), PT_LOAD, PT_MIPS_REGINFO, PT_NULL, PT_PHDR, uio_kinit(), UIO_READ, uio::uio_resid, and VOP_READ.
Referenced by runprogram().