os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/redirect/redirect.c File Reference
redirect.c File Reference
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
Macros
#define PATH_CAT "/bin/cat"
#define INFILE "redirect.in"
#define OUTFILE "redirect.out"
Functions
static int doopen (const char *path, int openflags)
static void dodup2 (int ofd, int nfd, const char *file)
static void doclose (int fd, const char *file)
static void mkfile (void)
static void chkfile (void)
static void cat (void)
int main (void)
Variables
static const char slogan [] = "CECIDI, ET NON SURGERE POSSUM!\n"
Macro Definition Documentation
INFILE
#define INFILE "redirect.in"
Definition at line 48 of file redirect.c.
OUTFILE
#define OUTFILE "redirect.out"
Definition at line 49 of file redirect.c.
PATH_CAT
#define PATH_CAT "/bin/cat"
Definition at line 47 of file redirect.c.
Function Documentation
cat()
static void cat (void) static
Definition at line 138 of file redirect.c.
References _exit(), doclose(), dodup2(), doopen(), err(), errx(), execv(), fork(), INFILE, NULL, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, OUTFILE, PATH_CAT, pid, STDIN_FILENO, STDOUT_FILENO, waitpid(), warn(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
Referenced by main().
chkfile()
static void chkfile (void) static
Definition at line 113 of file redirect.c.
References buf, doclose(), doopen(), err(), errx(), fd, O_RDONLY, OUTFILE, read(), slogan, and strlen().
Referenced by main().
doclose()
static void doclose (int fd, const char * file) static
Definition at line 83 of file redirect.c.
References close(), fd, and warnx().
Referenced by cat(), chkfile(), and mkfile().
dodup2()
static void dodup2 (int ofd, int nfd, const char * file) static
Definition at line 68 of file redirect.c.
References dup2(), err(), and errx().
Referenced by cat().
doopen()
static int doopen (const char * path, int openflags) static
Definition at line 55 of file redirect.c.
References err(), fd, and open().
Referenced by cat(), chkfile(), and mkfile().
main()
int main (void)
Definition at line 182 of file redirect.c.
References cat(), chkfile(), INFILE, mkfile(), OUTFILE, printf(), and remove().
mkfile()
static void mkfile (void) static
Definition at line 92 of file redirect.c.
References doclose(), doopen(), err(), errx(), fd, INFILE, O_CREAT, O_TRUNC, O_WRONLY, slogan, strlen(), and write().
Referenced by main().
Variable Documentation
slogan
const char slogan[] = "CECIDI, ET NON SURGERE POSSUM!\n" static
Definition at line 51 of file redirect.c.
Referenced by chkfile(), lseek_file_stdin(), and mkfile().