os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/dirconc/dirconc.c File Reference
dirconc.c File Reference
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
Macros
#define NTRIES 100 /* loop count */
#define NPROCS 5 /* actually totals 4x this +1 processes */
#define TESTDIR "dirconc"
#define NNAMES 4
#define NAMESIZE 32
Functions
static void choose_name (char *buf, size_t len)
static void say (const char *fmt,...)
static void dorename (const char *name1, const char *name2)
static void domkdir (const char *name)
static void dormdir (const char *name)
static void cleanup_rmdir (const char *name)
static void rename_proc (void)
static void mkdir_proc (void)
static void rmdir_proc (void)
static pid_t dofork (void(*func)(void))
static void run (void)
static void setup (const char *fs)
static void recursive_cleanup (const char *sofar, int depth)
static void cleanup (void)
int main (int argc, char *argv[])
Variables
static const char *const names [NNAMES]
Macro Definition Documentation
NAMESIZE
#define NAMESIZE 32
Definition at line 52 of file dirconc.c.
NNAMES
#define NNAMES 4
Definition at line 51 of file dirconc.c.
NPROCS
#define NPROCS 5 /* actually totals 4x this +1 processes */
Definition at line 48 of file dirconc.c.
NTRIES
#define NTRIES 100 /* loop count */
Definition at line 47 of file dirconc.c.
TESTDIR
#define TESTDIR "dirconc"
Definition at line 50 of file dirconc.c.
Function Documentation
choose_name()
static void choose_name (char * buf, size_t len) static
Definition at line 65 of file dirconc.c.
References buf, names, NNAMES, random(), and snprintf().
Referenced by mkdir_proc(), rename_proc(), and rmdir_proc().
cleanup()
static void cleanup (void) static
Definition at line 317 of file dirconc.c.
References chdir(), cleanup_rmdir(), recursive_cleanup(), and TESTDIR.
Referenced by any_badfd(), forkem(), main(), runtaskgroup(), and runtest().
cleanup_rmdir()
static void cleanup_rmdir (const char * name) static
Definition at line 160 of file dirconc.c.
References ENOENT, errno, getpid(), name, rmdir(), say(), and strerror().
Referenced by cleanup(), and recursive_cleanup().
dofork()
static pid_t dofork (void(*)(void) func) static
Definition at line 223 of file dirconc.c.
References errno, exit(), fork(), pid, say(), and strerror().
Referenced by run().
domkdir()
static void domkdir (const char * name) static
Definition at line 126 of file dirconc.c.
References EEXIST, ENOENT, errno, getpid(), mkdir(), name, say(), and strerror().
Referenced by mkdir_proc(), and setdir().
dorename()
static void dorename (const char * name1, const char * name2) static
Definition at line 108 of file dirconc.c.
References EINVAL, ENOENT, ENOTEMPTY, errno, getpid(), rename(), say(), and strerror().
Referenced by rename_proc().
dormdir()
static void dormdir (const char * name) static
Definition at line 143 of file dirconc.c.
References ENOENT, ENOTEMPTY, errno, getpid(), name, rmdir(), say(), and strerror().
Referenced by rmdir_proc().
main()
int main (int argc, char * argv[])
Definition at line 328 of file dirconc.c.
References atoi(), cleanup(), exit(), NULL, run(), say(), setup(), srandom(), and TESTDIR.
mkdir_proc()
static void mkdir_proc (void) static
Definition at line 193 of file dirconc.c.
References choose_name(), domkdir(), getpid(), name, NAMESIZE, NTRIES, and say().
Referenced by run().
recursive_cleanup()
static void recursive_cleanup (const char * sofar, int depth) static
Definition at line 295 of file dirconc.c.
References buf, cleanup_rmdir(), ENOENT, ENOTEMPTY, errno, getpid(), names, NAMESIZE, NNAMES, rmdir(), say(), snprintf(), and strerror().
Referenced by cleanup().
rename_proc()
static void rename_proc (void) static
Definition at line 178 of file dirconc.c.
References choose_name(), dorename(), getpid(), NAMESIZE, NTRIES, and say().
Referenced by run().
rmdir_proc()
static void rmdir_proc (void) static
Definition at line 207 of file dirconc.c.
References choose_name(), dormdir(), getpid(), name, NAMESIZE, NTRIES, and say().
Referenced by run().
run()
static void run (void) static
Definition at line 242 of file dirconc.c.
References dofork(), errno, mkdir_proc(), NPROCS, pids, rename_proc(), rmdir_proc(), say(), strerror(), waitpid(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
Referenced by main().
say()
static void say (const char * fmt, ...) static
Definition at line 94 of file dirconc.c.
References buf, STDOUT_FILENO, strlen(), va_end, va_start, vsnprintf(), and write().
Referenced by cleanup_rmdir(), dofork(), domkdir(), dorename(), dormdir(), main(), mkdir_proc(), recursive_cleanup(), rename_proc(), rmdir_proc(), run(), and setup().
setup()
static void setup (const char * fs) static
Definition at line 277 of file dirconc.c.
References chdir(), errno, exit(), mkdir(), say(), strerror(), and TESTDIR.
Referenced by main().
Variable Documentation
names
const char* const names[NNAMES] static
Initial value:
= {
    "aaaa",
    "bbbb",
    "cccc",
    "dddd",
}
Definition at line 56 of file dirconc.c.
Referenced by choose_name(), and recursive_cleanup().