os161-doc: /home/os161user/os161/os161-base-2.0.3/build/install/include/sys/stat.h File Reference
stat.h File Reference
#include <kern/stat.h>
#include <kern/stattypes.h>
Macros
#define S_ISDIR(mode) ((mode & _S_IFMT) == _S_IFDIR)
#define S_ISREG(mode) ((mode & _S_IFMT) == _S_IFREG)
#define S_ISDIR(mode) ((mode & _S_IFMT) == _S_IFDIR)
#define S_ISLNK(mode) ((mode & _S_IFMT) == _S_IFLNK)
#define S_ISIFO(mode) ((mode & _S_IFMT) == _S_IFIFO)
#define S_ISSOCK(mode) ((mode & _S_IFMT) ==_S_IFSOCK)
#define S_ISCHR(mode) ((mode & _S_IFMT) == _S_IFCHR)
#define S_ISBLK(mode) ((mode & _S_IFMT) == _S_IFBLK)
#define S_IFMT _S_IFMT
#define S_IFREG _S_IFREG
#define S_IFDIR _S_IFDIR
#define S_IFLNK _S_IFLNK
#define S_IFIFO _S_IFIFO
#define S_IFSOCK _S_IFSOCK
#define S_IFCHR _S_IFCHR
#define S_IFBLK _S_IFBLK
Functions
int fstat (int filehandle, struct stat *buf)
int stat (const char *path, struct stat *buf)
int lstat (const char *path, struct stat *buf)
int mkdir (const char *dirname, int ignore)
Macro Definition Documentation
S_IFBLK
#define S_IFBLK _S_IFBLK
Definition at line 62 of file stat.h.
S_IFCHR
#define S_IFCHR _S_IFCHR
Definition at line 61 of file stat.h.
S_IFDIR
#define S_IFDIR _S_IFDIR
Definition at line 57 of file stat.h.
S_IFIFO
#define S_IFIFO _S_IFIFO
Definition at line 59 of file stat.h.
S_IFLNK
#define S_IFLNK _S_IFLNK
Definition at line 58 of file stat.h.
S_IFMT
#define S_IFMT _S_IFMT
Definition at line 55 of file stat.h.
S_IFREG
#define S_IFREG _S_IFREG
Definition at line 56 of file stat.h.
S_IFSOCK
#define S_IFSOCK _S_IFSOCK
Definition at line 60 of file stat.h.
S_ISBLK
#define S_ISBLK (mode) ((mode & _S_IFMT) == _S_IFBLK)
Definition at line 49 of file stat.h.
S_ISCHR
#define S_ISCHR (mode) ((mode & _S_IFMT) == _S_IFCHR)
Definition at line 48 of file stat.h.
S_ISDIR [1/2]
#define S_ISDIR (mode) ((mode & _S_IFMT) == _S_IFDIR)
Definition at line 44 of file stat.h.
S_ISDIR [2/2]
#define S_ISDIR (mode) ((mode & _S_IFMT) == _S_IFDIR)
Definition at line 44 of file stat.h.
S_ISIFO
#define S_ISIFO (mode) ((mode & _S_IFMT) == _S_IFIFO)
Definition at line 46 of file stat.h.
S_ISLNK
#define S_ISLNK (mode) ((mode & _S_IFMT) == _S_IFLNK)
Definition at line 45 of file stat.h.
S_ISREG
#define S_ISREG (mode) ((mode & _S_IFMT) == _S_IFREG)
Definition at line 43 of file stat.h.
S_ISSOCK
#define S_ISSOCK (mode) ((mode & _S_IFMT) ==_S_IFSOCK)
Definition at line 47 of file stat.h.
Function Documentation
fstat()
int fstat (int filehandle, struct stat * buf)
Referenced by badbuf_fstat(), dup2_self(), fstat_badfd(), getsize(), isdir(), opendisk(), print(), try_fstat(), and xstat().
lstat()
int lstat (const char * path, struct stat * buf)
Referenced by badbuf_lstat(), lstat_badpath(), test_lstat(), and try_lstat().
mkdir()
int mkdir (const char * dirname, int ignore)
Referenced by create_testdir(), dir_test(), do_mkdir(), domkdir(), main(), mkdir_badpath(), mkdir_dot(), mkdir_dotdot(), mkdir_empty(), setup(), startup(), test5(), and try_mkdir().
stat()
int stat (const char * path, struct stat * buf)
Referenced by badbuf_stat(), getsize(), stat_badpath(), and try_stat().