os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/parallelvm/parallelvm.c File Reference
parallelvm.c File Reference
#include <sys/types.h>
#include <sys/wait.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <err.h>
Data Structures
struct matrix
struct usem
Macros
#define NJOBS 24
#define DIM 35
#define NMATS 11
#define JOBSIZE ((NMATS+1)*DIM*DIM*sizeof(int))
Functions
static void say (const char *fmt,...)
static void multiply (struct matrix *res, const struct matrix *m1, const struct matrix *m2)
static void addeq (struct matrix *m1, const struct matrix *m2)
static int trace (const struct matrix *m1)
static void populate_initial_matrixes (int mynum)
static void compute (int n)
static void computeall (int mynum)
static int answer (void)
static void go (int mynum)
static void semcreate (const char *tag, struct usem *sem)
static void semopen (struct usem *sem)
static void semclose (struct usem *sem)
static void semdestroy (struct usem *sem)
static void semP (struct usem *sem, size_t num)
static void semV (struct usem *sem, size_t num)
static int status_is_failure (int status)
static void makeprocs (bool dowait)
int main (int argc, char *argv[])
Variables
static const int right_answers [NJOBS]
static struct matrix mats [NMATS]
Macro Definition Documentation
DIM
#define DIM 35
Definition at line 51 of file parallelvm.c.
JOBSIZE
#define JOBSIZE ((NMATS+1)*DIM*DIM*sizeof(int))
Definition at line 53 of file parallelvm.c.
NJOBS
#define NJOBS 24
Definition at line 49 of file parallelvm.c.
NMATS
#define NMATS 11
Definition at line 52 of file parallelvm.c.
Function Documentation
addeq()
static void addeq (struct matrix * m1, const struct matrix * m2) static
Definition at line 127 of file parallelvm.c.
References DIM, m1, and m2.
Referenced by compute().
answer()
static int answer (void) static
Definition at line 193 of file parallelvm.c.
References mats, NMATS, and trace().
Referenced by ask_yesno(), do_move(), and go().
compute()
static void compute (int n) static
Definition at line 169 of file parallelvm.c.
References addeq(), mats, and multiply().
Referenced by computeall().
computeall()
static void computeall (int mynum) static
Definition at line 182 of file parallelvm.c.
References compute(), NMATS, and populate_initial_matrixes().
Referenced by go().
go()
static void go (int mynum) static
Definition at line 200 of file parallelvm.c.
References answer(), computeall(), exit(), getpid(), right_answers, and say().
Referenced by makeprocs().
main()
int main (int argc, char * argv[])
Definition at line 406 of file parallelvm.c.
References dowait(), makeprocs(), printf(), and strcmp().
makeprocs()
static void makeprocs (bool dowait) static
Definition at line 329 of file parallelvm.c.
References dowait(), err(), exit(), fork(), go(), JOBSIZE, NJOBS, pids, printf(), s1, s2, say(), semclose(), semcreate(), semdestroy(), semopen(), semP(), semV(), status_is_failure(), waitpid(), and warn().
Referenced by main().
multiply()
static void multiply (struct matrix * res, const struct matrix * m1, const struct matrix * m2) static
Definition at line 110 of file parallelvm.c.
References DIM, m1, m2, and matrix::m_data.
Referenced by compute(), and populate_initial_matrixes().
populate_initial_matrixes()
static void populate_initial_matrixes (int mynum) static
Definition at line 154 of file parallelvm.c.
References DIM, matrix::m_data, mats, and multiply().
Referenced by computeall().
say()
static void say (const char * fmt, ...) static
Definition at line 96 of file parallelvm.c.
References buf, STDOUT_FILENO, strlen(), va_end, va_start, vsnprintf(), and write().
Referenced by go(), and makeprocs().
semclose()
static void semclose (struct usem * sem) static
Definition at line 270 of file parallelvm.c.
References close(), and usem::fd.
Referenced by makeprocs().
semcreate()
static void semcreate (const char * tag, struct usem * sem) static
Definition at line 244 of file parallelvm.c.
References close(), err(), fd, getpid(), usem::name, O_CREAT, O_TRUNC, O_WRONLY, open(), and snprintf().
Referenced by makeprocs().
semdestroy()
static void semdestroy (struct usem * sem) static
Definition at line 277 of file parallelvm.c.
References usem::name, and remove().
Referenced by makeprocs().
semopen()
static void semopen (struct usem * sem) static
Definition at line 260 of file parallelvm.c.
References err(), usem::fd, usem::name, O_RDWR, and open().
Referenced by makeprocs().
semP()
static void semP (struct usem * sem, size_t num) static
Definition at line 284 of file parallelvm.c.
References err(), usem::fd, usem::name, num, and read().
Referenced by makeprocs().
semV()
static void semV (struct usem * sem, size_t num) static
Definition at line 296 of file parallelvm.c.
References err(), usem::fd, memset(), usem::name, num, and write().
Referenced by makeprocs().
status_is_failure()
static int status_is_failure (int status) static
Definition at line 313 of file parallelvm.c.
References WEXITSTATUS, WIFEXITED, and WIFSIGNALED.
Referenced by makeprocs().
trace()
static int trace (const struct matrix * m1) static
Definition at line 139 of file parallelvm.c.
References DIM, and m1.
Referenced by answer().
Variable Documentation
mats
struct matrix mats[NMATS] static
Definition at line 150 of file parallelvm.c.
Referenced by answer(), compute(), and populate_initial_matrixes().
right_answers
const int right_answers[NJOBS] static
Initial value:
= {
        -1337312809,
    356204544,
    -537881911,
    -65406976,
    1952063315,
    -843894784,
    1597000869,
    -993925120,
    838840559,
        -1616928768,
    -182386335,
    -364554240,
    251084843,
    -61403136,
    295326333,
    1488013312,
    1901440647,
    0,
        -1901440647,
        -1488013312,
    -295326333,
    61403136,
    -251084843,
    364554240,
}
Definition at line 55 of file parallelvm.c.
Referenced by go().