os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_remove.c File Reference
bad_remove.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void remove_dir (void)
static void remove_dot (void)
static void remove_dotdot (void)
static void remove_empty (void)
void test_remove (void)
Function Documentation
remove_dir()
static void remove_dir (void) static
Definition at line 48 of file bad_remove.c.
References create_testdir(), EISDIR, errno, remove(), report_begin(), report_check(), rmdir(), and TESTDIR.
Referenced by test_remove().
remove_dot()
static void remove_dot (void) static
Definition at line 66 of file bad_remove.c.
References EINVAL, EISDIR, errno, remove(), report_begin(), and report_check2().
Referenced by test_remove().
remove_dotdot()
static void remove_dotdot (void) static
Definition at line 77 of file bad_remove.c.
References EINVAL, EISDIR, errno, remove(), report_begin(), and report_check2().
Referenced by test_remove().
remove_empty()
static void remove_empty (void) static
Definition at line 88 of file bad_remove.c.
References EINVAL, EISDIR, errno, remove(), report_begin(), and report_check2().
Referenced by test_remove().
test_remove()
void test_remove (void)
Definition at line 98 of file bad_remove.c.
References remove_dir(), remove_dot(), remove_dotdot(), remove_empty(), and test_remove_path().