os161-doc: /home/os161user/os161/os161-base-2.0.3/build/userland/testbin/randcall/calls.c File Reference
calls.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <assert.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <err.h>
#include "extern.h"
Typedefs
typedef void(* tryfunc) (int dofork)
Functions
static void try_execv (int dofork)
static void try_waitpid (int dofork)
static void try_open (int dofork)
static void try_read (int dofork)
static void try_write (int dofork)
static void try_close (int dofork)
static void try_ioctl (int dofork)
static void try_lseek (int dofork)
static void try_fsync (int dofork)
static void try_ftruncate (int dofork)
static void try_fstat (int dofork)
static void try_remove (int dofork)
static void try_rename (int dofork)
static void try_link (int dofork)
static void try_mkdir (int dofork)
static void try_rmdir (int dofork)
static void try_chdir (int dofork)
static void try_getdirentry (int dofork)
static void try_symlink (int dofork)
static void try_readlink (int dofork)
static void try_dup2 (int dofork)
static void try_pipe (int dofork)
static void try___time (int dofork)
static void try___getcwd (int dofork)
static void try_stat (int dofork)
static void try_lstat (int dofork)
void trycalls (int asst, int dofork, int count)
Variables
static tryfunc funcs2 []
static tryfunc funcs3 []
static tryfunc funcs4 []
static tryfunc funcs5 []
static tryfunc * tables [4]
Typedef Documentation
tryfunc
typedef void(* tryfunc) (int dofork)
Definition at line 13 of file calls.c.
Function Documentation
try___getcwd()
static void try___getcwd (int dofork) static
Definition at line 686 of file calls.c.
References __getcwd(), a0, a1, buf, dofork(), err(), errno, exit(), fork(), pid, printf(), randptr(), randsize(), snprintf(), and waitpid().
try___time()
static void try___time (int dofork) static
Definition at line 657 of file calls.c.
References __time(), a0, a1, buf, dofork(), err(), errno, exit(), fork(), pid, printf(), randptr(), snprintf(), and waitpid().
try_chdir()
static void try_chdir (int dofork) static
Definition at line 483 of file calls.c.
References a0, buf, chdir(), dofork(), err(), errno, exit(), fork(), pid, printf(), randptr(), snprintf(), and waitpid().
try_close()
static void try_close (int dofork) static
Definition at line 166 of file calls.c.
References a0, buf, close(), dofork(), err(), errno, exit(), fork(), pid, printf(), randint(), snprintf(), and waitpid().
try_dup2()
static void try_dup2 (int dofork) static
Definition at line 600 of file calls.c.
References a0, a1, buf, dofork(), dup2(), err(), errno, exit(), fork(), pid, printf(), randint(), snprintf(), and waitpid().
try_execv()
static void try_execv (int dofork) static
Definition at line 17 of file calls.c.
References a0, a1, buf, dofork(), err(), errno, execv(), exit(), fork(), pid, printf(), randptr(), snprintf(), and waitpid().
try_fstat()
static void try_fstat (int dofork) static
Definition at line 311 of file calls.c.
References a0, a1, buf, dofork(), err(), errno, exit(), fork(), fstat(), pid, printf(), randint(), randptr(), snprintf(), and waitpid().
try_fsync()
static void try_fsync (int dofork) static
Definition at line 254 of file calls.c.
References a0, buf, dofork(), err(), errno, exit(), fork(), fsync(), pid, printf(), randint(), snprintf(), and waitpid().
try_ftruncate()
static void try_ftruncate (int dofork) static
Definition at line 282 of file calls.c.
References a0, a1, buf, dofork(), err(), errno, exit(), fork(), ftruncate(), pid, printf(), randint(), randoff(), snprintf(), and waitpid().
try_getdirentry()
static void try_getdirentry (int dofork) static
Definition at line 511 of file calls.c.
References a0, a1, a2, buf, dofork(), err(), errno, exit(), fork(), getdirentry(), pid, printf(), randint(), randptr(), randsize(), snprintf(), and waitpid().
try_ioctl()
static void try_ioctl (int dofork) static
Definition at line 194 of file calls.c.
References a0, a1, a2, buf, dofork(), err(), errno, exit(), fork(), ioctl(), pid, printf(), randint(), randptr(), snprintf(), and waitpid().
try_link()
static void try_link (int dofork) static
Definition at line 397 of file calls.c.
References a0, a1, buf, dofork(), err(), errno, exit(), fork(), link(), pid, printf(), randptr(), snprintf(), and waitpid().
try_lseek()
static void try_lseek (int dofork) static
Definition at line 224 of file calls.c.
References a0, a1, a2, buf, dofork(), err(), errno, exit(), fork(), lseek(), pid, printf(), randint(), randoff(), snprintf(), and waitpid().
try_lstat()
static void try_lstat (int dofork) static
Definition at line 744 of file calls.c.
References a0, a1, buf, dofork(), err(), errno, exit(), fork(), lstat(), pid, printf(), randptr(), snprintf(), and waitpid().
try_mkdir()
static void try_mkdir (int dofork) static
Definition at line 426 of file calls.c.
References a0, a1, buf, dofork(), err(), errno, exit(), fork(), mkdir(), pid, printf(), randint(), randptr(), snprintf(), and waitpid().
try_open()
static void try_open (int dofork) static
Definition at line 76 of file calls.c.
References a0, a1, a2, buf, dofork(), err(), errno, exit(), fork(), open(), pid, printf(), randint(), randptr(), snprintf(), and waitpid().
try_pipe()
static void try_pipe (int dofork) static
Definition at line 629 of file calls.c.
References a0, buf, dofork(), err(), errno, exit(), fork(), pid, pipe(), printf(), randptr(), snprintf(), and waitpid().
try_read()
static void try_read (int dofork) static
Definition at line 106 of file calls.c.
References a0, a1, a2, buf, dofork(), err(), errno, exit(), fork(), pid, printf(), randint(), randptr(), randsize(), read(), snprintf(), and waitpid().
try_readlink()
static void try_readlink (int dofork) static
Definition at line 570 of file calls.c.
References a0, a1, a2, buf, dofork(), err(), errno, exit(), fork(), pid, printf(), randptr(), randsize(), readlink(), snprintf(), and waitpid().
try_remove()
static void try_remove (int dofork) static
Definition at line 340 of file calls.c.
References a0, buf, dofork(), err(), errno, exit(), fork(), pid, printf(), randptr(), remove(), snprintf(), and waitpid().
try_rename()
static void try_rename (int dofork) static
Definition at line 368 of file calls.c.
References a0, a1, buf, dofork(), err(), errno, exit(), fork(), pid, printf(), randptr(), rename(), snprintf(), and waitpid().
try_rmdir()
static void try_rmdir (int dofork) static
Definition at line 455 of file calls.c.
References a0, buf, dofork(), err(), errno, exit(), fork(), pid, printf(), randptr(), rmdir(), snprintf(), and waitpid().
try_stat()
static void try_stat (int dofork) static
Definition at line 715 of file calls.c.
References a0, a1, buf, dofork(), err(), errno, exit(), fork(), pid, printf(), randptr(), snprintf(), stat(), and waitpid().
try_symlink()
static void try_symlink (int dofork) static
Definition at line 541 of file calls.c.
References a0, a1, buf, dofork(), err(), errno, exit(), fork(), pid, printf(), randptr(), snprintf(), symlink(), and waitpid().
try_waitpid()
static void try_waitpid (int dofork) static
Definition at line 46 of file calls.c.
References a0, a1, a2, buf, dofork(), err(), errno, exit(), fork(), pid, printf(), randint(), randptr(), snprintf(), and waitpid().
try_write()
static void try_write (int dofork) static
Definition at line 136 of file calls.c.
References a0, a1, a2, buf, dofork(), err(), errno, exit(), fork(), pid, printf(), randint(), randptr(), randsize(), snprintf(), waitpid(), and write().
trycalls()
void trycalls (int asst, int dofork, int count)
Definition at line 859 of file calls.c.
References assert, asst, count, dofork(), and tables.
Referenced by main().
Variable Documentation
funcs2
tryfunc funcs2[] static
Initial value:
= {
    try_execv,
    try_waitpid,
    try_open,
    try_read,
    try_write,
    try_close,
    try_lseek,
    try_chdir,
    try_dup2,
    try___getcwd,
    NULL
}
Definition at line 771 of file calls.c.
funcs3
tryfunc funcs3[] static
Initial value:
= {
    try_execv,
    try_waitpid,
    try_open,
    try_read,
    try_write,
    try_close,
    try_lseek,
    try_chdir,
    try_dup2,
    try___getcwd,
    NULL
}
Definition at line 785 of file calls.c.
funcs4
tryfunc funcs4[] static
Initial value:
= {
    try_execv,
    try_waitpid,
    try_open,
    try_read,
    try_write,
    try_close,
    try_lseek,
    try_fsync,
    try_ftruncate,
    try_fstat,
    try_remove,
    try_rename,
    try_mkdir,
    try_rmdir,
    try_chdir,
    try_getdirentry,
    try_dup2,
    try___getcwd,
    NULL
}
Definition at line 799 of file calls.c.
funcs5
tryfunc funcs5[] static
Initial value:
= {
    try_execv,
    try_waitpid,
    try_open,
    try_read,
    try_write,
    try_close,
    try_ioctl,
    try_lseek,
    try_fsync,
    try_ftruncate,
    try_fstat,
    try_remove,
    try_rename,
    try_link,
    try_mkdir,
    try_rmdir,
    try_chdir,
    try_getdirentry,
    try_symlink,
    try_readlink,
    try_dup2,
    try_pipe,
    try___time,
    try___getcwd,
    try_stat,
    try_lstat,
    NULL
}
Definition at line 821 of file calls.c.
tables
tryfunc* tables[4] static
Initial value:
= {
    funcs2,
    funcs3,
    funcs4,
    funcs5,
}
Definition at line 851 of file calls.c.
Referenced by trycalls().