os161-doc: /home/os161user/os161/os161-base-2.0.3/common/gcc-millicode/qdivrem.c File Reference
qdivrem.c File Reference
#include "longlong.h"
Macros
#define B ((int)1 << HALF_BITS) /* digit base */
#define COMBINE(a, b) (((unsigned int)(a) << HALF_BITS) | (b))
Typedefs
typedef unsigned int digit
Functions
static void shl (digit *p, int len, int sh)
unsigned long long __qdivrem (unsigned long long ull, unsigned long long vll, unsigned long long *arq)
Macro Definition Documentation
B
#define B ((int)1 << HALF_BITS) /* digit base */
Definition at line 45 of file qdivrem.c.
COMBINE
#define COMBINE (a, b) (((unsigned int)(a) << HALF_BITS) | (b))
Definition at line 48 of file qdivrem.c.
Typedef Documentation
digit
typedef unsigned int digit
Definition at line 54 of file qdivrem.c.
Function Documentation
__qdivrem()
unsigned long long __qdivrem (unsigned long long ull, unsigned long long vll, unsigned long long * arq)
Definition at line 68 of file qdivrem.c.
References B, COMBINE, H, HALF_BITS, HHALF, L, LHALF, uu::ll, shl(), uu::ui, uu::ull, and v1.
Referenced by __divdi3(), __moddi3(), __udivdi3(), and __umoddi3().
shl()
static void shl (digit * p, int len, int sh) static
Definition at line 271 of file qdivrem.c.
References HALF_BITS, and LHALF.
Referenced by __qdivrem().