os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/dev/lamebus/lscreen.h File Reference
lscreen.h File Reference
Data Structures
struct lscreen_softc
Functions
void lscreen_irq (void *sc)
void lscreen_write (void *sc, int ch)
Function Documentation
lscreen_irq()
void lscreen_irq (void * sc)
Definition at line 83 of file lscreen.c.
References bus_read_register, bus_write_register, ch, lscreen_softc::ls_busdata, lscreen_softc::ls_buspos, lscreen_softc::ls_devdata, lscreen_softc::ls_input, lscreen_softc::ls_lock, LSCR_IRQ_ACTIVE, LSCR_IRQ_ENABLE, LSCR_REG_CHAR, LSCR_REG_RIRQ, spinlock_acquire(), and spinlock_release().
Referenced by attach_lscreen_to_lamebus().
lscreen_write()
void lscreen_write (void * sc, int ch)
Definition at line 152 of file lscreen.c.
References bus_write_register, ch, lscreen_softc::ls_busdata, lscreen_softc::ls_buspos, lscreen_softc::ls_cx, lscreen_softc::ls_cy, lscreen_softc::ls_lock, lscreen_softc::ls_width, LSCR_REG_POSN, lscreen_char(), lscreen_newline(), mergexy(), spinlock_acquire(), and spinlock_release().
Referenced by attach_con_to_lscreen().