os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/lib/hostcompat/host-err.h File Reference
host-err.h File Reference
#include <stdarg.h>
Functions
void warn (const char *fmt,...)
void warnx (const char *fmt,...)
void err (int exitcode, const char *fmt,...)
void errx (int exitcode, const char *fmt,...)
void vwarn (const char *fmt, va_list)
void vwarnx (const char *fmt, va_list)
void verr (int exitcode, const char *fmt, va_list)
void verrx (int exitcode, const char *fmt, va_list)
Function Documentation
err()
void err (int exitcode, const char * fmt, ...)
Definition at line 176 of file err.c.
References va_end, va_start, and verr().
errx()
void errx (int exitcode, const char * fmt, ...)
Definition at line 185 of file err.c.
References va_end, va_start, and verrx().
verr()
void verr (int exitcode, const char * fmt, va_list)
Definition at line 138 of file err.c.
References __printerr(), and exit().
Referenced by err().
verrx()
void verrx (int exitcode, const char * fmt, va_list)
Definition at line 146 of file err.c.
References __printerr(), and exit().
Referenced by errx().
vwarn()
void vwarn (const char * fmt, va_list)
Definition at line 124 of file err.c.
References __printerr().
Referenced by warn().
vwarnx()
void vwarnx (const char * fmt, va_list)
Definition at line 131 of file err.c.
References __printerr().
Referenced by warnx().
warn()
void warn (const char * fmt, ...)
Definition at line 158 of file err.c.
References va_end, va_start, and vwarn().
warnx()
void warnx (const char * fmt, ...)
Definition at line 167 of file err.c.
References va_end, va_start, and vwarnx().