os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/dev/lamebus/lhd.c File Reference
lhd.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <uio.h>
#include <membar.h>
#include <synch.h>
#include <platform/bus.h>
#include <vfs.h>
#include <lamebus/lhd.h>
#include "autoconf.h"
Macros
#define LHD_REG_NSECT 0 /* Number of sectors */
#define LHD_REG_STAT 4 /* Status */
#define LHD_REG_SECT 8 /* Sector for I/O */
#define LHD_REG_RPM 12 /* Disk rotation speed (revs per minute) */
#define LHD_IDLE 0 /* Device idle */
#define LHD_WORKING 1 /* Operation in progress */
#define LHD_OK 4 /* Operation succeeded */
#define LHD_INVSECT 12 /* Invalid sector requested */
#define LHD_MEDIA 20 /* Media error */
#define LHD_ISWRITE 2 /* OR with above: I/O is a write */
#define LHD_STATEMASK 0x1d /* mask for masking out LHD_ISWRITE */
#define LHD_BUFFER 32768
Functions
static uint32_t lhd_rdreg (struct lhd_softc *lh, uint32_t reg)
static void lhd_wreg (struct lhd_softc *lh, uint32_t reg, uint32_t val)
static int lhd_code_to_errno (struct lhd_softc *lh, int code)
static void lhd_iodone (struct lhd_softc *lh, int err)
void lhd_irq (void *vlh)
static int lhd_eachopen (struct device *d, int openflags)
static int lhd_ioctl (struct device *d, int op, userptr_t data)
static int lhd_io (struct device *d, struct uio *uio)
int config_lhd (struct lhd_softc *lh, int lhdno)
Variables
static const struct device_ops lhd_devops
Macro Definition Documentation
LHD_BUFFER
#define LHD_BUFFER 32768
Definition at line 61 of file lhd.c.
LHD_IDLE
#define LHD_IDLE 0 /* Device idle */
Definition at line 52 of file lhd.c.
LHD_INVSECT
#define LHD_INVSECT 12 /* Invalid sector requested */
Definition at line 55 of file lhd.c.
LHD_ISWRITE
#define LHD_ISWRITE 2 /* OR with above: I/O is a write */
Definition at line 57 of file lhd.c.
LHD_MEDIA
#define LHD_MEDIA 20 /* Media error */
Definition at line 56 of file lhd.c.
LHD_OK
#define LHD_OK 4 /* Operation succeeded */
Definition at line 54 of file lhd.c.
LHD_REG_NSECT
#define LHD_REG_NSECT 0 /* Number of sectors */
Definition at line 46 of file lhd.c.
LHD_REG_RPM
#define LHD_REG_RPM 12 /* Disk rotation speed (revs per minute) */
Definition at line 49 of file lhd.c.
LHD_REG_SECT
#define LHD_REG_SECT 8 /* Sector for I/O */
Definition at line 48 of file lhd.c.
LHD_REG_STAT
#define LHD_REG_STAT 4 /* Status */
Definition at line 47 of file lhd.c.
LHD_STATEMASK
#define LHD_STATEMASK 0x1d /* mask for masking out LHD_ISWRITE */
Definition at line 58 of file lhd.c.
LHD_WORKING
#define LHD_WORKING 1 /* Operation in progress */
Definition at line 53 of file lhd.c.
Function Documentation
config_lhd()
int config_lhd (struct lhd_softc * lh, int lhdno)
Definition at line 277 of file lhd.c.
References bus_map_area, bus_read_register, device::d_blocks, device::d_blocksize, device::d_data, device::d_ops, ENOMEM, lhd_softc::lh_buf, lhd_softc::lh_busdata, lhd_softc::lh_buspos, lhd_softc::lh_clear, lhd_softc::lh_dev, lhd_softc::lh_done, LHD_BUFFER, lhd_devops, LHD_REG_NSECT, LHD_SECTSIZE, name, NULL, sem_create(), sem_destroy(), snprintf(), and vfs_adddev().
Referenced by tryattach_lhd_to_lamebus().
lhd_code_to_errno()
static int lhd_code_to_errno (struct lhd_softc * lh, int code) static
Definition at line 87 of file lhd.c.
References EAGAIN, EINVAL, EIO, kprintf(), lhd_softc::lh_unit, LHD_INVSECT, LHD_MEDIA, LHD_OK, and LHD_STATEMASK.
Referenced by lhd_irq().
lhd_eachopen()
static int lhd_eachopen (struct device * d, int openflags) static
Definition at line 141 of file lhd.c.
lhd_io()
static int lhd_io (struct device * d, struct uio * uio) static
Definition at line 187 of file lhd.c.
References device::d_blocks, device::d_data, EINVAL, lhd_softc::lh_buf, lhd_softc::lh_clear, lhd_softc::lh_dev, lhd_softc::lh_done, lhd_softc::lh_result, LHD_ISWRITE, LHD_REG_SECT, LHD_REG_STAT, LHD_SECTSIZE, LHD_WORKING, lhd_wreg(), membar_load_load(), membar_store_store(), P(), uio::uio_offset, UIO_READ, uio::uio_resid, uio::uio_rw, UIO_WRITE, uiomove(), and V().
lhd_ioctl()
static int lhd_ioctl (struct device * d, int op, userptr_t data) static
Definition at line 157 of file lhd.c.
References EIOCTL.
lhd_iodone()
static void lhd_iodone (struct lhd_softc * lh, int err) static
Definition at line 104 of file lhd.c.
References err(), lhd_softc::lh_done, lhd_softc::lh_result, and V().
Referenced by lhd_irq().
lhd_irq()
void lhd_irq (void * vlh)
Definition at line 116 of file lhd.c.
References lhd_code_to_errno(), LHD_IDLE, LHD_INVSECT, lhd_iodone(), LHD_MEDIA, LHD_OK, lhd_rdreg(), LHD_REG_STAT, LHD_STATEMASK, LHD_WORKING, and lhd_wreg().
Referenced by attach_lhd_to_lamebus().
lhd_rdreg()
static uint32_t lhd_rdreg (struct lhd_softc * lh, uint32_t reg) inline static
Definition at line 68 of file lhd.c.
References bus_read_register, lhd_softc::lh_busdata, and lhd_softc::lh_buspos.
Referenced by lhd_irq().
lhd_wreg()
static void lhd_wreg (struct lhd_softc * lh, uint32_t reg, uint32_t val) inline static
Definition at line 78 of file lhd.c.
References bus_write_register, lhd_softc::lh_busdata, and lhd_softc::lh_buspos.
Referenced by lhd_io(), and lhd_irq().
Variable Documentation
lhd_devops
const struct device_ops lhd_devops static
Initial value:
= {
    .devop_eachopen = lhd_eachopen,
    .devop_io = lhd_io,
    .devop_ioctl = lhd_ioctl,
}
Definition at line 267 of file lhd.c.
Referenced by config_lhd().