os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/threadprivate.h File Reference
threadprivate.h File Reference
Functions
void thread_startup (void(*entrypoint)(void *data1, unsigned long data2), void *data1, unsigned long data2)
void thread_machdep_init (struct thread_machdep *tm)
void thread_machdep_cleanup (struct thread_machdep *tm)
void switchframe_switch (struct switchframe **prev, struct switchframe **next)
void switchframe_init (struct thread *, void(*entrypoint)(void *data1, unsigned long data2), void *data1, unsigned long data2)
Function Documentation
switchframe_init()
void switchframe_init (struct thread * , void(*)(void *data1, unsigned long data2) entrypoint, void * data1, unsigned long data2)
Definition at line 55 of file switchframe.c.
References bzero(), mips_threadstart(), switchframe::sf_ra, switchframe::sf_s0, switchframe::sf_s1, switchframe::sf_s2, STACK_SIZE, thread::t_context, and thread::t_stack.
Referenced by thread_fork().
switchframe_switch()
void switchframe_switch (struct switchframe ** prev, struct switchframe ** next)
Referenced by thread_switch().
thread_machdep_cleanup()
void thread_machdep_cleanup (struct thread_machdep * tm)
Definition at line 46 of file thread_machdep.c.
References KASSERT, NULL, and thread_machdep::tm_badfaultfunc.
Referenced by thread_destroy().
thread_machdep_init()
void thread_machdep_init (struct thread_machdep * tm)
Definition at line 40 of file thread_machdep.c.
References NULL, and thread_machdep::tm_badfaultfunc.
Referenced by thread_create().
thread_startup()
void thread_startup (void(*)(void *data1, unsigned long data2) entrypoint, void * data1, unsigned long data2)
Definition at line 739 of file thread.c.
References as_activate(), exorcise(), NULL, S_RUN, spinlock_release(), spl0(), thread::t_state, thread::t_wchan_name, and thread_exit().