os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/device.h File Reference
device.h File Reference
Data Structures
struct device
struct device_ops
Macros
#define DEVOP_EACHOPEN(d, f) ((d)->d_ops->devop_eachopen(d, f))
#define DEVOP_IO(d, u) ((d)->d_ops->devop_io(d, u))
#define DEVOP_IOCTL(d, op, p) ((d)->d_ops->devop_ioctl(d, op, p))
Functions
struct vnode * dev_create_vnode (struct device *dev)
void dev_uncreate_vnode (struct vnode *vn)
void devnull_create (void)
void dev_bootstrap (void)
Macro Definition Documentation
DEVOP_EACHOPEN
#define DEVOP_EACHOPEN (d, f) ((d)->d_ops->devop_eachopen(d, f))
Definition at line 69 of file device.h.
DEVOP_IO
#define DEVOP_IO (d, u) ((d)->d_ops->devop_io(d, u))
Definition at line 70 of file device.h.
DEVOP_IOCTL
#define DEVOP_IOCTL (d, op, p) ((d)->d_ops->devop_ioctl(d, op, p))
Definition at line 71 of file device.h.
Function Documentation
dev_bootstrap()
void dev_bootstrap (void)
dev_create_vnode()
struct vnode* dev_create_vnode (struct device * dev)
Definition at line 357 of file device.c.
References dev_vnode_ops, kmalloc(), NULL, panic(), strerror(), and vnode_init().
Referenced by vfs_doadd().
dev_uncreate_vnode()
void dev_uncreate_vnode (struct vnode * vn)
Definition at line 383 of file device.c.
References dev_vnode_ops, KASSERT, kfree(), vnode::vn_ops, and vnode_cleanup().
Referenced by vfs_doadd().
devnull_create()
void devnull_create (void)
Definition at line 101 of file devnull.c.
References device::d_blocks, device::d_blocksize, device::d_data, device::d_devnumber, device::d_ops, kmalloc(), NULL, null_devops, panic(), strerror(), and vfs_adddev().
Referenced by vfs_bootstrap().