os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/schedpong/usem.c File Reference
usem.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
#include "usem.h"
Functions
void usem_init (struct usem *sem, const char *namefmt,...)
void usem_open (struct usem *sem)
void usem_close (struct usem *sem)
void usem_cleanup (struct usem *sem)
void Pn (struct usem *sem, unsigned count)
void P (struct usem *sem)
void Vn (struct usem *sem, unsigned count)
void V (struct usem *sem)
Function Documentation
P()
void P (struct usem * sem)
Definition at line 100 of file usem.c.
References Pn().
Pn()
void Pn (struct usem * sem, unsigned count)
Definition at line 85 of file usem.c.
References count, err(), errx(), usem::fd, usem::name, and read().
Referenced by P().
usem_cleanup()
void usem_cleanup (struct usem * sem)
Definition at line 79 of file usem.c.
References usem::name, and remove().
Referenced by pong_cleanup(), and runit().
usem_close()
void usem_close (struct usem * sem)
Definition at line 71 of file usem.c.
References close(), usem::fd, usem::name, and warn().
Referenced by pong(), runit(), and waitstart().
usem_init()
void usem_init (struct usem * sem, const char * namefmt, ...)
Definition at line 45 of file usem.c.
References close(), err(), usem::fd, usem::name, namefmt, O_CREAT, O_RDWR, O_TRUNC, open(), va_end, va_start, and vsnprintf().
Referenced by pong_prep(), and runit().
usem_open()
void usem_open (struct usem * sem)
Definition at line 62 of file usem.c.
References err(), usem::fd, usem::name, O_RDWR, and open().
Referenced by pong(), runit(), and waitstart().
V()
void V (struct usem * sem)
Definition at line 124 of file usem.c.
References Vn().
Vn()
void Vn (struct usem * sem, unsigned count)
Definition at line 106 of file usem.c.
References count, err(), errx(), usem::fd, memset(), usem::name, and write().
Referenced by runit(), and V().