os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/frack/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <err.h>
#include "workloads.h"
#include "main.h"
Data Structures
struct workload
Macros
#define WL(n) { .name = #n, .argname = NULL, .run.noarg = wl_##n }
#define WLA(n, a) { .name = #n, .argname = #a, .run.witharg = wl_##n }
Functions
static const struct workload * findworkload (const char *name)
static void printworkloads (void)
int main (int argc, char *argv[])
Variables
static const struct workload workloads []
static const unsigned numworkloads = sizeof(workloads) / sizeof(workloads[0])
Macro Definition Documentation
WL
#define WL (n) { .name = #n, .argname = NULL, .run.noarg = wl_##n }
Definition at line 48 of file main.c.
WLA
#define WLA (n, a) { .name = #n, .argname = #a, .run.witharg = wl_##n }
Definition at line 49 of file main.c.
Function Documentation
findworkload()
static const struct workload* findworkload (const char * name) static
Definition at line 117 of file main.c.
References name, NULL, numworkloads, strcmp(), and workloads.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 146 of file main.c.
References workload::argname, checkmode, complete(), errx(), exit(), findworkload(), workload::noarg, NULL, printworkloads(), workload::run, setcheckmode(), strcmp(), warnx(), and workload::witharg.
printworkloads()
static void printworkloads (void) static
Definition at line 131 of file main.c.
References workload::argname, name, numworkloads, printf(), and workloads.
Referenced by main().
Variable Documentation
numworkloads
const unsigned numworkloads = sizeof(workloads) / sizeof(workloads[0]) static
Definition at line 110 of file main.c.
Referenced by findworkload(), and printworkloads().
workloads
const struct workload workloads[] static
Definition at line 51 of file main.c.
Referenced by findworkload(), and printworkloads().