os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/frack/ops.c File Reference
ops.c File Reference
#include <stdint.h>
#include <unistd.h>
#include <assert.h>
#include <err.h>
#include "pool.h"
#include "data.h"
#include "do.h"
#include "check.h"
#include "ops.h"
#include "main.h"
Data Structures
struct file
struct dir
Macros
#define MAXDIRS 32
#define MAXFILES 32
Functions
void setcheckmode (int mode)
DECLPOOL (dir, MAXDIRS)
struct dir * op_opendir (unsigned name)
void op_closedir (struct dir *d)
DECLPOOL (file, MAXFILES)
struct file * op_open (unsigned testcode, unsigned name, unsigned openflags)
void op_close (struct file *f)
void op_write (struct file *f, off_t pos, off_t len)
void op_truncate (struct file *f, off_t len)
void op_mkdir (unsigned name)
void op_rmdir (unsigned name)
void op_unlink (unsigned name)
void op_link (unsigned from, unsigned to)
void op_rename (unsigned from, unsigned to)
void op_renamexd (unsigned fromdir, unsigned from, unsigned todir, unsigned to)
void op_chdir (unsigned name)
void op_chdirup (void)
void op_sync (void)
void complete (void)
Variables
static int checkmode
Macro Definition Documentation
MAXDIRS
#define MAXDIRS 32
Definition at line 69 of file ops.c.
MAXFILES
#define MAXFILES 32
Definition at line 104 of file ops.c.
Function Documentation
complete()
void complete (void)
Definition at line 310 of file ops.c.
References checkfs(), and checkmode.
Referenced by main().
DECLPOOL() [1/2]
DECLPOOL (dir , MAXDIRS)
DECLPOOL() [2/2]
DECLPOOL (file , MAXFILES)
op_chdir()
void op_chdir (unsigned name)
Definition at line 274 of file ops.c.
References check_chdir(), checkmode, do_chdir(), and name.
Referenced by makesubtree(), mkrandtree_sub(), rmrandtree_sub(), wl_mktree_sub(), wl_renamexddir(), wl_renamexdfile(), wl_renamexdsubtree(), and wl_rmtree_sub().
op_chdirup()
void op_chdirup (void)
Definition at line 285 of file ops.c.
References check_chdirup(), checkmode, and do_chdirup().
Referenced by makesubtree(), mkrandtree_sub(), rmrandtree_sub(), wl_mktree_sub(), wl_renamexddir(), wl_renamexdfile(), wl_renamexdsubtree(), and wl_rmtree_sub().
op_close()
void op_close (struct file * f)
Definition at line 157 of file ops.c.
References check_closefile(), checkmode, do_closefile(), f, and POOLFREE.
Referenced by randop(), wl_append(), wl_appendandtruncpartly(), wl_appendandtrunczero(), wl_fillhole(), wl_randupdate(), wl_rmfiledelayed(), wl_rmfiledelayedappend(), wl_rmmanyfiledelayed(), wl_rmmanyfiledelayedandappend(), wl_truncfill(), wl_trunclargersize(), wl_trunconeblock(), wl_truncsmallersize(), wl_trunczero(), writeemptyfile(), writeholeyfile(), and writeoutfile().
op_closedir()
void op_closedir (struct dir * d)
Definition at line 89 of file ops.c.
References checkmode, do_closedir(), dir::handle, dir::name, and POOLFREE.
Referenced by wl_rmdirdelayed(), and wl_rmmanydirdelayed().
op_link()
void op_link (unsigned from, unsigned to)
Definition at line 241 of file ops.c.
References check_link(), checkmode, and do_link().
Referenced by randop(), wl_linkfile(), wl_linkmanyfile(), wl_linkunlinkfile(), wl_linkunlinkseq(), wl_unlinkfile(), and wl_unlinkmanyfile().
op_mkdir()
void op_mkdir (unsigned name)
Definition at line 208 of file ops.c.
References check_mkdir(), checkmode, do_mkdir(), and name.
Referenced by makesubtree(), mkrandtree_sub(), prep(), randop(), wl_mkdir(), wl_mkmanydir(), wl_mktree_sub(), wl_renamedir(), wl_renamemanydir(), wl_renamexddir(), wl_renamexdfile(), wl_renamexdsubtree(), wl_rmdir(), wl_rmdirdelayed(), wl_rmmanydir(), and wl_rmmanydirdelayed().
op_open()
struct file* op_open (unsigned testcode, unsigned name, unsigned openflags)
Definition at line 108 of file ops.c.
References assert, check_createfile(), check_openfile(), checkmode, do_createfile(), do_openfile(), file::handle, file::name, name, O_CREAT, O_EXCL, O_TRUNC, op_truncate(), POOLALLOC, file::seq, and file::testcode.
Referenced by openfiles(), randop(), wl_append(), wl_appendandtruncpartly(), wl_appendandtrunczero(), wl_fillhole(), wl_randupdate(), wl_rmfiledelayed(), wl_rmfiledelayedappend(), wl_rmmanyfiledelayed(), wl_rmmanyfiledelayedandappend(), wl_truncfill(), wl_trunclargersize(), wl_trunconeblock(), wl_truncsmallersize(), wl_trunczero(), wl_writefileseq(), wl_writetruncseq(), writeemptyfile(), writeholeyfile(), and writeoutfile().
op_opendir()
struct dir* op_opendir (unsigned name)
Definition at line 73 of file ops.c.
References checkmode, do_opendir(), dir::handle, dir::name, name, and POOLALLOC.
Referenced by wl_rmdirdelayed(), and wl_rmmanydirdelayed().
op_rename()
void op_rename (unsigned from, unsigned to)
Definition at line 252 of file ops.c.
References check_rename(), checkmode, and do_rename().
Referenced by randop(), wl_copyandrename(), wl_renamedir(), wl_renamefile(), wl_renamemanydir(), wl_renamemanyfile(), wl_renamemanysubtree(), wl_renameseq(), and wl_renamesubtree().
op_renamexd()
void op_renamexd (unsigned fromdir, unsigned from, unsigned todir, unsigned to)
Definition at line 263 of file ops.c.
References check_renamexd(), checkmode, and do_renamexd().
Referenced by wl_renamexddir(), wl_renamexdfile(), and wl_renamexdsubtree().
op_rmdir()
void op_rmdir (unsigned name)
Definition at line 219 of file ops.c.
References check_rmdir(), checkmode, do_rmdir(), and name.
Referenced by randop(), rmrandtree_sub(), wl_rmdir(), wl_rmdirdelayed(), wl_rmmanydir(), wl_rmmanydirdelayed(), and wl_rmtree_sub().
op_sync()
void op_sync (void)
Definition at line 299 of file ops.c.
References check_sync(), checkmode, and do_sync().
Referenced by wl_append(), wl_appendandtruncpartly(), wl_appendandtrunczero(), wl_compile(), wl_copyandrename(), wl_diropseq(), wl_fillhole(), wl_genseq(), wl_linkfile(), wl_linkmanyfile(), wl_linkunlinkfile(), wl_linkunlinkseq(), wl_randupdate(), wl_renamedir(), wl_renamefile(), wl_renamemanydir(), wl_renamemanyfile(), wl_renamemanysubtree(), wl_renameseq(), wl_renamesubtree(), wl_renamexddir(), wl_renamexdfile(), wl_renamexdsubtree(), wl_rewrite(), wl_rmdir(), wl_rmdirdelayed(), wl_rmfile(), wl_rmfiledelayed(), wl_rmfiledelayedappend(), wl_rmmanydir(), wl_rmmanydirdelayed(), wl_rmmanyfile(), wl_rmmanyfiledelayed(), wl_rmmanyfiledelayedandappend(), wl_rmrandtree(), wl_rmtree(), wl_truncfill(), wl_trunclargersize(), wl_trunconeblock(), wl_truncsmallersize(), wl_truncwrite(), wl_trunczero(), wl_unlinkfile(), wl_unlinkmanyfile(), wl_writefileseq(), and wl_writetruncseq().
op_truncate()
void op_truncate (struct file * f, off_t len)
Definition at line 194 of file ops.c.
References check_truncate(), checkmode, do_truncate(), and f.
Referenced by op_open(), randtruncate(), wl_appendandtruncpartly(), wl_appendandtrunczero(), wl_truncfill(), wl_trunclargersize(), wl_trunconeblock(), wl_truncsmallersize(), and wl_trunczero().
op_unlink()
void op_unlink (unsigned name)
Definition at line 230 of file ops.c.
References check_unlink(), checkmode, do_unlink(), and name.
Referenced by randop(), rmrandtree_sub(), wl_linkunlinkfile(), wl_linkunlinkseq(), wl_mkrmseq(), wl_rmfile(), wl_rmfiledelayed(), wl_rmfiledelayedappend(), wl_rmmanyfile(), wl_rmmanyfiledelayed(), wl_rmmanyfiledelayedandappend(), wl_rmtree_sub(), wl_unlinkfile(), and wl_unlinkmanyfile().
op_write()
void op_write (struct file * f, off_t pos, off_t len)
Definition at line 169 of file ops.c.
References check_write(), checkmode, DATA_MAXSIZE, do_write(), f, and pos.
Referenced by file_randomwrite(), randwrite(), wl_append(), wl_appendandtruncpartly(), wl_appendandtrunczero(), wl_rmfiledelayedappend(), wl_rmmanyfiledelayedandappend(), writeholeyfile(), and writeoutfile().
setcheckmode()
void setcheckmode (int mode)
Definition at line 58 of file ops.c.
References check_setup(), and checkmode.
Referenced by main().
Variable Documentation
checkmode
int checkmode static
Definition at line 55 of file ops.c.
Referenced by complete(), main(), op_chdir(), op_chdirup(), op_close(), op_closedir(), op_link(), op_mkdir(), op_open(), op_opendir(), op_rename(), op_renamexd(), op_rmdir(), op_sync(), op_truncate(), op_unlink(), op_write(), and setcheckmode().