os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/bigexec/bigexec.c File Reference
bigexec.c File Reference
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <assert.h>
#include <err.h>
Macros
#define _PATH_MYSELF "/testbin/bigexec"
Functions
static void fill (char *buf, size_t buflen)
static void prepwords (void)
static void try (const char *first,...)
static void trymany (int num, const char *word)
static int check (int argc, char *argv[], const char *first,...)
static int checkmany (int argc, char *argv[], int num, const char *word)
static void dumpargs (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
static const char word8 [] = "Dalemark"
static char word4050 [4051]
static char word16320 [16321]
static char word65500 [65501]
Macro Definition Documentation
_PATH_MYSELF
#define _PATH_MYSELF "/testbin/bigexec"
Definition at line 45 of file bigexec.c.
Function Documentation
check()
static int check (int argc, char * argv[], const char * first, ...) static
Definition at line 151 of file bigexec.c.
References assert, NULL, pos, strcmp(), va_arg, va_start, and warnx().
Referenced by main().
checkmany()
static int checkmany (int argc, char * argv[], int num, const char * word) static
Definition at line 191 of file bigexec.c.
References num, and strcmp().
Referenced by main().
dumpargs()
static void dumpargs (int argc, char * argv[]) static
Definition at line 213 of file bigexec.c.
References NULL, strcmp(), strlen(), warnx(), word16320, word4050, word65500, and word8.
Referenced by main().
fill()
static void fill (char * buf, size_t buflen) static
Definition at line 57 of file bigexec.c.
References buf, name, names, random(), strcpy(), and strlen().
Referenced by prepwords().
main()
int main (int argc, char * argv[])
Definition at line 248 of file bigexec.c.
References ARG_MAX, assert, check(), checkmany(), dumpargs(), err(), NULL, prepwords(), strlen(), trymany(), warnx(), word16320, word4050, word65500, and word8.
prepwords()
static void prepwords (void) static
Definition at line 93 of file bigexec.c.
References fill(), srandom(), word16320, word4050, and word65500.
Referenced by main().
try()
static void try (const char * first, ...) static
Definition at line 106 of file bigexec.c.
References _PATH_MYSELF, assert, err(), execv(), NULL, num, va_arg, and va_start.
trymany()
static void trymany (int num, const char * word) static
Definition at line 135 of file bigexec.c.
References _PATH_MYSELF, err(), execv(), NULL, and num.
Referenced by main().
Variable Documentation
word16320
char word16320[16321] static
Definition at line 52 of file bigexec.c.
Referenced by dumpargs(), main(), and prepwords().
word4050
char word4050[4051] static
Definition at line 51 of file bigexec.c.
Referenced by dumpargs(), main(), and prepwords().
word65500
char word65500[65501] static
Definition at line 53 of file bigexec.c.
Referenced by dumpargs(), main(), and prepwords().
word8
const char word8[] = "Dalemark" static
Definition at line 50 of file bigexec.c.
Referenced by dumpargs(), and main().