os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/fs/sfs/sfs_io.c File Reference
sfs_io.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <uio.h>
#include <vfs.h>
#include <device.h>
#include <sfs.h>
#include "sfsprivate.h"
Functions
static int sfs_rwblock (struct sfs_fs *sfs, struct uio *uio)
int sfs_readblock (struct sfs_fs *sfs, daddr_t block, void *data, size_t len)
int sfs_writeblock (struct sfs_fs *sfs, daddr_t block, void *data, size_t len)
static int sfs_partialio (struct sfs_vnode *sv, struct uio *uio, uint32_t skipstart, uint32_t len)
static int sfs_blockio (struct sfs_vnode *sv, struct uio *uio)
int sfs_io (struct sfs_vnode *sv, struct uio *uio)
int sfs_metaio (struct sfs_vnode *sv, off_t actualpos, void *data, size_t len, enum uio_rw rw)
Function Documentation
sfs_blockio()
static int sfs_blockio (struct sfs_vnode * sv, struct uio * uio) static
Definition at line 228 of file sfs_io.c.
References fs::fs_data, KASSERT, SFS_BLOCKSIZE, sfs_bmap(), sfs_rwblock(), sfs_vnode::sv_absvn, uio::uio_offset, UIO_READ, uio::uio_resid, uio::uio_rw, UIO_WRITE, uiomovezeros(), and vnode::vn_fs.
Referenced by sfs_io().
sfs_io()
int sfs_io (struct sfs_vnode * sv, struct uio * uio)
Definition at line 292 of file sfs_io.c.
References KASSERT, nblocks, sfs_dinode::sfi_size, sfs_blockio(), SFS_BLOCKSIZE, sfs_partialio(), sfs_vnode::sv_dirty, sfs_vnode::sv_i, uio::uio_offset, UIO_READ, uio::uio_resid, uio::uio_rw, and UIO_WRITE.
Referenced by sfs_read(), and sfs_write().
sfs_metaio()
int sfs_metaio (struct sfs_vnode * sv, off_t actualpos, void * data, size_t len, enum uio_rw rw)
Definition at line 406 of file sfs_io.c.
References bzero(), fs::fs_data, KASSERT, memcpy(), sfs_dinode::sfi_size, SFS_BLOCKSIZE, sfs_bmap(), sfs_readblock(), sfs_writeblock(), sfs_vnode::sv_absvn, sfs_vnode::sv_dirty, sfs_vnode::sv_i, UIO_READ, UIO_WRITE, vfs_biglock_do_i_hold(), and vnode::vn_fs.
Referenced by sfs_readdir(), and sfs_writedir().
sfs_partialio()
static int sfs_partialio (struct sfs_vnode * sv, struct uio * uio, uint32_t skipstart, uint32_t len) static
Definition at line 150 of file sfs_io.c.
References bzero(), fs::fs_data, KASSERT, SFS_BLOCKSIZE, sfs_bmap(), sfs_readblock(), sfs_writeblock(), sfs_vnode::sv_absvn, uio::uio_offset, UIO_READ, uio::uio_rw, UIO_WRITE, uiomove(), vfs_biglock_do_i_hold(), and vnode::vn_fs.
Referenced by sfs_io().
sfs_readblock()
int sfs_readblock (struct sfs_fs * sfs, daddr_t block, void * data, size_t len)
Definition at line 108 of file sfs_io.c.
References KASSERT, SFS_BLOCKSIZE, sfs_rwblock(), SFSUIO, and UIO_READ.
Referenced by sfs_bmap(), sfs_domount(), sfs_freemapio(), sfs_itrunc(), sfs_loadvnode(), sfs_metaio(), and sfs_partialio().
sfs_rwblock()
static int sfs_rwblock (struct sfs_fs * sfs, struct uio * uio) static
Definition at line 60 of file sfs_io.c.
References DB_SFS, DEBUG, DEVOP_IO, EINVAL, EIO, KASSERT, kprintf(), panic(), sfs_superblock::sb_volname, SFS_BLOCKSIZE, sfs_fs::sfs_device, sfs_fs::sfs_sb, uio::uio_offset, UIO_READ, uio::uio_rw, and vfs_biglock_do_i_hold().
Referenced by sfs_blockio(), sfs_readblock(), and sfs_writeblock().
sfs_writeblock()
int sfs_writeblock (struct sfs_fs * sfs, daddr_t block, void * data, size_t len)
Definition at line 123 of file sfs_io.c.
References KASSERT, SFS_BLOCKSIZE, sfs_rwblock(), SFSUIO, and UIO_WRITE.
Referenced by sfs_bmap(), sfs_clearblock(), sfs_freemapio(), sfs_itrunc(), sfs_metaio(), sfs_partialio(), sfs_sync_inode(), and sfs_sync_superblock().