os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_ioctl.c File Reference
bad_ioctl.c File Reference
#include <sys/types.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include <stdio.h>
#include <errno.h>
#include "config.h"
#include "test.h"
Macros
#define IOCTL(fd, sym) any_ioctl_badbuf(fd, sym, #sym)
Functions
static void one_ioctl_badbuf (int fd, int code, const char *codename, void *ptr, const char *ptrdesc)
static void any_ioctl_badbuf (int fd, int code, const char *codename)
static void ioctl_badbuf (void)
static void ioctl_badcode (void)
void test_ioctl (void)
Macro Definition Documentation
IOCTL
#define IOCTL (fd, sym) any_ioctl_badbuf(fd, sym, #sym)
Definition at line 64 of file bad_ioctl.c.
Function Documentation
any_ioctl_badbuf()
static void any_ioctl_badbuf (int fd, int code, const char * codename) static
Definition at line 57 of file bad_ioctl.c.
References fd, NULL, and one_ioctl_badbuf().
Referenced by ioctl_badbuf().
ioctl_badbuf()
static void ioctl_badbuf (void) static
Definition at line 68 of file bad_ioctl.c.
References any_ioctl_badbuf().
Referenced by test_ioctl().
ioctl_badcode()
static void ioctl_badcode (void) static
Definition at line 86 of file bad_ioctl.c.
References EIOCTL, errno, ioctl(), NONEXIST_IOCTL, NULL, report_begin(), report_check(), and STDIN_FILENO.
Referenced by test_ioctl().
one_ioctl_badbuf()
static void one_ioctl_badbuf (int fd, int code, const char * codename, void * ptr, const char * ptrdesc) static
Definition at line 45 of file bad_ioctl.c.
References EFAULT, errno, fd, ioctl(), report_begin(), and report_check().
Referenced by any_ioctl_badbuf().
test_ioctl()
void test_ioctl (void)
Definition at line 96 of file bad_ioctl.c.
References ioctl_badbuf(), ioctl_badcode(), and test_ioctl_fd().