os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/farm/farm.c File Reference
farm.c File Reference
#include <unistd.h>
#include <err.h>
Macros
#define MAXPROCS 6
Functions
static void spawnv (const char *prog, char **argv)
static void waitall (void)
static void hog (void)
static void cat (void)
int main (void)
Variables
static char * hargv [2] = { (char *)"hog", NULL }
static char * cargv [3] = { (char *)"cat", (char *)"catfile", NULL }
static int pids [MAXPROCS]
static int npids
Macro Definition Documentation
MAXPROCS
#define MAXPROCS 6
Definition at line 46 of file farm.c.
Function Documentation
cat()
static void cat (void) static
Definition at line 95 of file farm.c.
References cargv, and spawnv().
Referenced by main().
hog()
static void hog (void) static
Definition at line 88 of file farm.c.
References hargv, and spawnv().
Referenced by main().
main()
int main (void)
Definition at line 101 of file farm.c.
References cat(), hog(), and waitall().
spawnv()
static void spawnv (const char * prog, char ** argv) static
Definition at line 51 of file farm.c.
References err(), execv(), fork(), npids, pid, and pids.
Referenced by cat(), and hog().
waitall()
static void waitall (void) static
Definition at line 70 of file farm.c.
References npids, pids, waitpid(), warn(), warnx(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
Referenced by main().
Variable Documentation
cargv
char* cargv[3] = { (char *)"cat", (char *)"catfile", NULL } static
Definition at line 44 of file farm.c.
Referenced by cat().
hargv
char* hargv[2] = { (char *)"hog", NULL } static
Definition at line 43 of file farm.c.
Referenced by hog().
npids
int npids static
Definition at line 47 of file farm.c.
Referenced by spawnv(), and waitall().
pids
int pids[MAXPROCS] static
Definition at line 47 of file farm.c.
Referenced by basetest(), conctest(), doforkall(), dotest(), makeprocs(), run(), runit(), spawn(), spawnv(), triple(), wait_siblings(), wait_siblings_child(), and waitall().