os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/include/unistd.h File Reference
unistd.h File Reference
#include <sys/cdefs.h>
#include <sys/types.h>
#include <kern/fcntl.h>
#include <kern/ioctl.h>
#include <kern/reboot.h>
#include <kern/seek.h>
#include <kern/time.h>
#include <kern/unistd.h>
#include <kern/wait.h>
Functions
__DEAD void _exit (int code)
int execv (const char *prog, char *const *args)
pid_t fork (void)
pid_t waitpid (pid_t pid, int *returncode, int flags)
int open (const char *filename, int flags,...)
ssize_t read (int filehandle, void *buf, size_t size)
ssize_t write (int filehandle, const void *buf, size_t size)
int close (int filehandle)
int reboot (int code)
int sync (void)
int rmdir (const char *dirname)
pid_t getpid (void)
int ioctl (int filehandle, int code, void *buf)
off_t lseek (int filehandle, off_t pos, int code)
int fsync (int filehandle)
int ftruncate (int filehandle, off_t size)
int remove (const char *filename)
int rename (const char *oldfile, const char *newfile)
int link (const char *oldfile, const char *newfile)
int chdir (const char *path)
void * sbrk (__intptr_t change)
ssize_t getdirentry (int filehandle, char *buf, size_t buflen)
int symlink (const char *target, const char *linkname)
ssize_t readlink (const char *path, char *buf, size_t buflen)
int dup2 (int filehandle, int newhandle)
int pipe (int filehandles[2])
int __time (time_t *seconds, unsigned long *nanoseconds)
ssize_t __getcwd (char *buf, size_t buflen)
int execvp (const char *prog, char *const *args)
char * getcwd (char *buf, size_t buflen)
time_t time (time_t *seconds)
Function Documentation
__getcwd()
ssize_t __getcwd (char * buf, size_t buflen)
__time()
int __time (time_t * seconds, unsigned long * nanoseconds)
Definition at line 41 of file time.c.
_exit()
__DEAD void _exit (int code)
chdir()
int chdir (const char * path)
close()
int close (int filehandle)
dup2()
int dup2 (int filehandle, int newhandle)
execv()
int execv (const char * prog, char *const * args)
execvp()
int execvp (const char * prog, char *const * args)
Definition at line 42 of file execvp.c.
References ENOENT, ENOEXEC, ENOTDIR, errno, execv(), getenv(), memcpy(), NULL, PATH_MAX, snprintf(), strchr(), and strlen().
fork()
pid_t fork (void)
fsync()
int fsync (int filehandle)
ftruncate()
int ftruncate (int filehandle, off_t size)
getcwd()
char* getcwd (char * buf, size_t buflen)
Definition at line 40 of file getcwd.c.
References __getcwd(), buf, EINVAL, errno, and NULL.
getdirentry()
ssize_t getdirentry (int filehandle, char * buf, size_t buflen)
getpid()
pid_t getpid (void)
ioctl()
int ioctl (int filehandle, int code, void * buf)
link()
int link (const char * oldfile, const char * newfile)
lseek()
off_t lseek (int filehandle, off_t pos, int code)
open()
int open (const char * filename, int flags, ...)
pipe()
int pipe (int filehandles[2])
read()
ssize_t read (int filehandle, void * buf, size_t size)
readlink()
ssize_t readlink (const char * path, char * buf, size_t buflen)
reboot()
int reboot (int code)
remove()
int remove (const char * filename)
rename()
int rename (const char * oldfile, const char * newfile)
rmdir()
int rmdir (const char * dirname)
sbrk()
void* sbrk (__intptr_t change)
symlink()
int symlink (const char * target, const char * linkname)
sync()
int sync (void)
time()
time_t time (time_t * seconds)
Definition at line 39 of file time.c.
References __time(), and NULL.
waitpid()
pid_t waitpid (pid_t pid, int * returncode, int flags)
write()
ssize_t write (int filehandle, const void * buf, size_t size)