os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/test/fstest.c File Reference
fstest.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <lib.h>
#include <uio.h>
#include <thread.h>
#include <synch.h>
#include <vfs.h>
#include <fs.h>
#include <vnode.h>
#include <test.h>
Macros
#define SLOGAN "HODIE MIHI - CRAS TIBI\n"
#define FILENAME "fstest.tmp"
#define NCHUNKS 720
#define NTHREADS 12
#define NLONG 32
#define NCREATE 24
#define MAKENAME() fstest_makename(name, sizeof(name), fs, namesuffix)
#define DEFTEST(testname)
Functions
static void init_threadsem (void)
static void rotate (char *str, int amt)
static void fstest_makename (char *buf, size_t buflen, const char *fs, const char *namesuffix)
static int fstest_remove (const char *fs, const char *namesuffix)
static int fstest_write (const char *fs, const char *namesuffix, int stridesize, int stridepos)
static int fstest_read (const char *fs, const char *namesuffix)
static void dofstest (const char *filesys)
static void readstress_thread (void *fs, unsigned long num)
static void doreadstress (const char *filesys)
static void writestress_thread (void *fs, unsigned long num)
static void dowritestress (const char *filesys)
static void writestress2_thread (void *fs, unsigned long num)
static void dowritestress2 (const char *filesys)
static void longstress_thread (void *fs, unsigned long num)
static void dolongstress (const char *filesys)
static void createstress_thread (void *fs, unsigned long num)
static void docreatestress (const char *filesys)
static int checkfilesystem (int nargs, char **args)
DEFTEST (fstest)
DEFTEST (readstress)
DEFTEST (writestress)
DEFTEST (writestress2)
DEFTEST (longstress)
DEFTEST (createstress)
int printfile (int nargs, char **args)
Variables
static struct semaphore * threadsem = NULL
Macro Definition Documentation
DEFTEST
#define DEFTEST (testname)
Value:
  int                                             \
  testname(int nargs, char **args)                \
  {                                               \
    int result;                               \
    result = checkfilesystem(nargs, args);    \
    if (result) {                             \
        return result;                    \
    }                                         \
    do##testname(args[1]);                    \
    return 0;                                 \
  }
Definition at line 698 of file fstest.c.
FILENAME
#define FILENAME "fstest.tmp"
Definition at line 54 of file fstest.c.
MAKENAME
#define MAKENAME () fstest_makename(name, sizeof(name), fs, namesuffix)
Definition at line 111 of file fstest.c.
NCHUNKS
#define NCHUNKS 720
Definition at line 55 of file fstest.c.
NCREATE
#define NCREATE 24
Definition at line 58 of file fstest.c.
NLONG
#define NLONG 32
Definition at line 57 of file fstest.c.
NTHREADS
#define NTHREADS 12
Definition at line 56 of file fstest.c.
SLOGAN
#define SLOGAN "HODIE MIHI - CRAS TIBI\n"
Definition at line 53 of file fstest.c.
Function Documentation
checkfilesystem()
static int checkfilesystem (int nargs, char ** args) static
Definition at line 679 of file fstest.c.
References EINVAL, kprintf(), and strlen().
createstress_thread()
static void createstress_thread (void * fs, unsigned long num) static
Definition at line 537 of file fstest.c.
References buf, err(), fstest_remove(), kprintf(), MAKENAME, name, NCREATE, num, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, rotate(), SLOGAN, snprintf(), strcmp(), strcpy(), strerror(), strlen(), threadsem, uio_kinit(), uio::uio_offset, UIO_READ, uio::uio_resid, UIO_WRITE, V(), vfs_close(), vfs_open(), VOP_READ, and VOP_WRITE.
Referenced by docreatestress().
DEFTEST() [1/6]
DEFTEST (createstress)
DEFTEST() [2/6]
DEFTEST (fstest)
DEFTEST() [3/6]
DEFTEST (longstress)
DEFTEST() [4/6]
DEFTEST (readstress)
DEFTEST() [5/6]
DEFTEST (writestress)
DEFTEST() [6/6]
DEFTEST (writestress2)
docreatestress()
static void docreatestress (const char * filesys) static
Definition at line 651 of file fstest.c.
References createstress_thread(), err(), init_threadsem(), kprintf(), NTHREADS, NULL, P(), panic(), strerror(), thread_fork(), and threadsem.
dofstest()
static void dofstest (const char * filesys) static
Definition at line 278 of file fstest.c.
References fstest_read(), fstest_remove(), fstest_write(), and kprintf().
dolongstress()
static void dolongstress (const char * filesys) static
Definition at line 509 of file fstest.c.
References err(), init_threadsem(), kprintf(), longstress_thread(), NTHREADS, NULL, P(), panic(), strerror(), thread_fork(), and threadsem.
doreadstress()
static void doreadstress (const char * filesys) static
Definition at line 315 of file fstest.c.
References err(), fstest_remove(), fstest_write(), init_threadsem(), kprintf(), NTHREADS, NULL, P(), panic(), readstress_thread(), strerror(), thread_fork(), and threadsem.
dowritestress()
static void dowritestress (const char * filesys) static
Definition at line 382 of file fstest.c.
References err(), init_threadsem(), kprintf(), NTHREADS, NULL, P(), panic(), strerror(), thread_fork(), threadsem, and writestress_thread().
dowritestress2()
static void dowritestress2 (const char * filesys) static
Definition at line 424 of file fstest.c.
References err(), fstest_makename(), fstest_read(), fstest_remove(), init_threadsem(), kprintf(), name, NTHREADS, NULL, O_CREAT, O_TRUNC, O_WRONLY, P(), panic(), strerror(), thread_fork(), threadsem, vfs_close(), vfs_open(), and writestress2_thread().
fstest_makename()
static void fstest_makename (char * buf, size_t buflen, const char * fs, const char * namesuffix) static
Definition at line 104 of file fstest.c.
References buf, FILENAME, KASSERT, snprintf(), and strlen().
Referenced by dowritestress2().
fstest_read()
static int fstest_read (const char * fs, const char * namesuffix) static
Definition at line 213 of file fstest.c.
References buf, err(), kprintf(), MAKENAME, name, NCHUNKS, O_RDONLY, rotate(), SLOGAN, strcmp(), strcpy(), strerror(), strlen(), uio_kinit(), uio::uio_offset, UIO_READ, uio::uio_resid, vfs_close(), vfs_open(), and VOP_READ.
Referenced by dofstest(), dowritestress2(), longstress_thread(), readstress_thread(), and writestress_thread().
fstest_remove()
static int fstest_remove (const char * fs, const char * namesuffix) static
Definition at line 115 of file fstest.c.
References buf, err(), kprintf(), MAKENAME, name, strcpy(), strerror(), and vfs_remove().
Referenced by createstress_thread(), dofstest(), doreadstress(), dowritestress2(), longstress_thread(), and writestress_thread().
fstest_write()
static int fstest_write (const char * fs, const char * namesuffix, int stridesize, int stridepos) static
Definition at line 135 of file fstest.c.
References buf, err(), KASSERT, kprintf(), MAKENAME, name, NCHUNKS, O_CREAT, O_TRUNC, O_WRONLY, pos, rotate(), SLOGAN, strcpy(), strerror(), strlen(), uio_kinit(), uio::uio_offset, uio::uio_resid, UIO_WRITE, vfs_close(), vfs_open(), vfs_remove(), and VOP_WRITE.
Referenced by dofstest(), doreadstress(), longstress_thread(), writestress2_thread(), and writestress_thread().
init_threadsem()
static void init_threadsem (void) static
Definition at line 64 of file fstest.c.
References NULL, panic(), sem_create(), and threadsem.
Referenced by docreatestress(), dolongstress(), doreadstress(), dowritestress(), and dowritestress2().
longstress_thread()
static void longstress_thread (void * fs, unsigned long num) static
Definition at line 474 of file fstest.c.
References fstest_read(), fstest_remove(), fstest_write(), kprintf(), NLONG, num, snprintf(), threadsem, and V().
Referenced by dolongstress().
printfile()
int printfile (int nargs, char ** args)
Definition at line 721 of file fstest.c.
References buf, EINVAL, kprintf(), O_RDONLY, O_WRONLY, strcpy(), strerror(), uio_kinit(), uio::uio_offset, UIO_READ, uio::uio_resid, UIO_WRITE, vfs_close(), vfs_open(), VOP_READ, and VOP_WRITE.
readstress_thread()
static void readstress_thread (void * fs, unsigned long num) static
Definition at line 304 of file fstest.c.
References fstest_read(), kprintf(), num, threadsem, and V().
Referenced by doreadstress().
rotate()
static void rotate (char * str, int amt) static
Definition at line 80 of file fstest.c.
References ch, and KASSERT.
Referenced by createstress_thread(), fstest_read(), and fstest_write().
writestress2_thread()
static void writestress2_thread (void * fs, unsigned long num) static
Definition at line 409 of file fstest.c.
References fstest_write(), kprintf(), NTHREADS, num, threadsem, and V().
Referenced by dowritestress2().
writestress_thread()
static void writestress_thread (void * fs, unsigned long num) static
Definition at line 353 of file fstest.c.
References fstest_read(), fstest_remove(), fstest_write(), kprintf(), num, snprintf(), threadsem, and V().
Referenced by dowritestress().
Variable Documentation
threadsem
struct semaphore* threadsem = NULL static
Definition at line 60 of file fstest.c.
Referenced by createstress_thread(), docreatestress(), dolongstress(), doreadstress(), dowritestress(), dowritestress2(), init_threadsem(), longstress_thread(), readstress_thread(), writestress2_thread(), and writestress_thread().