os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/compile/DUMBVM/autoconf.c File Reference
autoconf.c File Reference
#include <types.h>
#include <lib.h>
#include "autoconf.h"
Functions
static void autoconf_beep (struct beep_softc *, int)
static void autoconf_con (struct con_softc *, int)
static void autoconf_emu (struct emu_softc *, int)
static void autoconf_lhd (struct lhd_softc *, int)
static void autoconf_lrandom (struct lrandom_softc *, int)
static void autoconf_lser (struct lser_softc *, int)
static void autoconf_ltimer (struct ltimer_softc *, int)
static void autoconf_ltrace (struct ltrace_softc *, int)
static void autoconf_random (struct random_softc *, int)
static void autoconf_rtclock (struct rtclock_softc *, int)
static int tryattach_emu_to_lamebus (int devunit, struct lamebus_softc *bus, int busunit)
static int tryattach_ltrace_to_lamebus (int devunit, struct lamebus_softc *bus, int busunit)
static int tryattach_ltimer_to_lamebus (int devunit, struct lamebus_softc *bus, int busunit)
static int tryattach_lrandom_to_lamebus (int devunit, struct lamebus_softc *bus, int busunit)
static int tryattach_lhd_to_lamebus (int devunit, struct lamebus_softc *bus, int busunit)
static int tryattach_lser_to_lamebus (int devunit, struct lamebus_softc *bus, int busunit)
static int tryattach_beep_to_ltimer (int devunit, struct ltimer_softc *bus, int busunit)
static int tryattach_con_to_lser (int devunit, struct lser_softc *bus, int busunit)
static int tryattach_rtclock_to_ltimer (int devunit, struct ltimer_softc *bus, int busunit)
static int tryattach_random_to_lrandom (int devunit, struct lrandom_softc *bus, int busunit)
void autoconf_lamebus (struct lamebus_softc *bus, int busunit)
void pseudoconfig (void)
Variables
static int nextunit_beep
static int nextunit_con
static int nextunit_emu
static int nextunit_lhd
static int nextunit_lrandom
static int nextunit_lser
static int nextunit_ltimer
static int nextunit_ltrace
static int nextunit_random
static int nextunit_rtclock
Function Documentation
autoconf_beep()
static void autoconf_beep (struct beep_softc * bus, int busunit) static
Definition at line 291 of file autoconf.c.
Referenced by tryattach_beep_to_ltimer().
autoconf_con()
static void autoconf_con (struct con_softc * bus, int busunit) static
Definition at line 284 of file autoconf.c.
Referenced by tryattach_con_to_lser().
autoconf_emu()
static void autoconf_emu (struct emu_softc * bus, int busunit) static
Definition at line 365 of file autoconf.c.
Referenced by tryattach_emu_to_lamebus().
autoconf_lamebus()
void autoconf_lamebus (struct lamebus_softc * bus, int busunit)
Definition at line 316 of file autoconf.c.
References nextunit_emu, nextunit_lhd, nextunit_lrandom, nextunit_lser, nextunit_ltimer, nextunit_ltrace, tryattach_emu_to_lamebus(), tryattach_lhd_to_lamebus(), tryattach_lrandom_to_lamebus(), tryattach_lser_to_lamebus(), tryattach_ltimer_to_lamebus(), and tryattach_ltrace_to_lamebus().
Referenced by mainbus_bootstrap().
autoconf_lhd()
static void autoconf_lhd (struct lhd_softc * bus, int busunit) static
Definition at line 277 of file autoconf.c.
Referenced by tryattach_lhd_to_lamebus().
autoconf_lrandom()
static void autoconf_lrandom (struct lrandom_softc * bus, int busunit) static
Definition at line 396 of file autoconf.c.
References nextunit_random, and tryattach_random_to_lrandom().
Referenced by tryattach_lrandom_to_lamebus().
autoconf_lser()
static void autoconf_lser (struct lser_softc * bus, int busunit) static
Definition at line 298 of file autoconf.c.
References nextunit_con, and tryattach_con_to_lser().
Referenced by tryattach_lser_to_lamebus().
autoconf_ltimer()
static void autoconf_ltimer (struct ltimer_softc * bus, int busunit) static
Definition at line 372 of file autoconf.c.
References nextunit_beep, nextunit_rtclock, tryattach_beep_to_ltimer(), and tryattach_rtclock_to_ltimer().
Referenced by tryattach_ltimer_to_lamebus().
autoconf_ltrace()
static void autoconf_ltrace (struct ltrace_softc * bus, int busunit) static
Definition at line 270 of file autoconf.c.
Referenced by tryattach_ltrace_to_lamebus().
autoconf_random()
static void autoconf_random (struct random_softc * bus, int busunit) static
Definition at line 310 of file autoconf.c.
Referenced by tryattach_random_to_lrandom().
autoconf_rtclock()
static void autoconf_rtclock (struct rtclock_softc * bus, int busunit) static
Definition at line 389 of file autoconf.c.
Referenced by tryattach_rtclock_to_ltimer().
pseudoconfig()
void pseudoconfig (void)
Definition at line 407 of file autoconf.c.
Referenced by boot().
tryattach_beep_to_ltimer()
static int tryattach_beep_to_ltimer (int devunit, struct ltimer_softc * bus, int busunit) static
Definition at line 173 of file autoconf.c.
References attach_beep_to_ltimer(), autoconf_beep(), config_beep(), kprintf(), nextunit_beep, NULL, and strerror().
Referenced by autoconf_ltimer().
tryattach_con_to_lser()
static int tryattach_con_to_lser (int devunit, struct lser_softc * bus, int busunit) static
Definition at line 197 of file autoconf.c.
References attach_con_to_lser(), autoconf_con(), config_con(), kprintf(), nextunit_con, NULL, and strerror().
Referenced by autoconf_lser().
tryattach_emu_to_lamebus()
static int tryattach_emu_to_lamebus (int devunit, struct lamebus_softc * bus, int busunit) static
Definition at line 29 of file autoconf.c.
References attach_emu_to_lamebus(), autoconf_emu(), config_emu(), kprintf(), nextunit_emu, NULL, and strerror().
Referenced by autoconf_lamebus().
tryattach_lhd_to_lamebus()
static int tryattach_lhd_to_lamebus (int devunit, struct lamebus_softc * bus, int busunit) static
Definition at line 125 of file autoconf.c.
References attach_lhd_to_lamebus(), autoconf_lhd(), config_lhd(), kprintf(), nextunit_lhd, NULL, and strerror().
Referenced by autoconf_lamebus().
tryattach_lrandom_to_lamebus()
static int tryattach_lrandom_to_lamebus (int devunit, struct lamebus_softc * bus, int busunit) static
Definition at line 101 of file autoconf.c.
References attach_lrandom_to_lamebus(), autoconf_lrandom(), config_lrandom(), kprintf(), nextunit_lrandom, NULL, and strerror().
Referenced by autoconf_lamebus().
tryattach_lser_to_lamebus()
static int tryattach_lser_to_lamebus (int devunit, struct lamebus_softc * bus, int busunit) static
Definition at line 149 of file autoconf.c.
References attach_lser_to_lamebus(), autoconf_lser(), config_lser(), kprintf(), nextunit_lser, NULL, and strerror().
Referenced by autoconf_lamebus().
tryattach_ltimer_to_lamebus()
static int tryattach_ltimer_to_lamebus (int devunit, struct lamebus_softc * bus, int busunit) static
Definition at line 77 of file autoconf.c.
References attach_ltimer_to_lamebus(), autoconf_ltimer(), config_ltimer(), kprintf(), nextunit_ltimer, NULL, and strerror().
Referenced by autoconf_lamebus().
tryattach_ltrace_to_lamebus()
static int tryattach_ltrace_to_lamebus (int devunit, struct lamebus_softc * bus, int busunit) static
Definition at line 53 of file autoconf.c.
References attach_ltrace_to_lamebus(), autoconf_ltrace(), config_ltrace(), kprintf(), nextunit_ltrace, NULL, and strerror().
Referenced by autoconf_lamebus().
tryattach_random_to_lrandom()
static int tryattach_random_to_lrandom (int devunit, struct lrandom_softc * bus, int busunit) static
Definition at line 245 of file autoconf.c.
References attach_random_to_lrandom(), autoconf_random(), config_random(), kprintf(), nextunit_random, NULL, and strerror().
Referenced by autoconf_lrandom().
tryattach_rtclock_to_ltimer()
static int tryattach_rtclock_to_ltimer (int devunit, struct ltimer_softc * bus, int busunit) static
Definition at line 221 of file autoconf.c.
References attach_rtclock_to_ltimer(), autoconf_rtclock(), config_rtclock(), kprintf(), nextunit_rtclock, NULL, and strerror().
Referenced by autoconf_ltimer().
Variable Documentation
nextunit_beep
int nextunit_beep static
Definition at line 16 of file autoconf.c.
Referenced by autoconf_ltimer(), and tryattach_beep_to_ltimer().
nextunit_con
int nextunit_con static
Definition at line 17 of file autoconf.c.
Referenced by autoconf_lser(), and tryattach_con_to_lser().
nextunit_emu
int nextunit_emu static
Definition at line 18 of file autoconf.c.
Referenced by autoconf_lamebus(), and tryattach_emu_to_lamebus().
nextunit_lhd
int nextunit_lhd static
Definition at line 19 of file autoconf.c.
Referenced by autoconf_lamebus(), and tryattach_lhd_to_lamebus().
nextunit_lrandom
int nextunit_lrandom static
Definition at line 20 of file autoconf.c.
Referenced by autoconf_lamebus(), and tryattach_lrandom_to_lamebus().
nextunit_lser
int nextunit_lser static
Definition at line 21 of file autoconf.c.
Referenced by autoconf_lamebus(), and tryattach_lser_to_lamebus().
nextunit_ltimer
int nextunit_ltimer static
Definition at line 22 of file autoconf.c.
Referenced by autoconf_lamebus(), and tryattach_ltimer_to_lamebus().
nextunit_ltrace
int nextunit_ltrace static
Definition at line 23 of file autoconf.c.
Referenced by autoconf_lamebus(), and tryattach_ltrace_to_lamebus().
nextunit_random
int nextunit_random static
Definition at line 24 of file autoconf.c.
Referenced by autoconf_lrandom(), and tryattach_random_to_lrandom().
nextunit_rtclock
int nextunit_rtclock static
Definition at line 25 of file autoconf.c.
Referenced by autoconf_ltimer(), and tryattach_rtclock_to_ltimer().