os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/f_test/f_write.c File Reference
f_write.c File Reference
#include <unistd.h>
#include <stdio.h>
#include <err.h>
#include "f_hdr.h"
Macros
#define SectorSize 512
#define TMULT 50
#define FSIZE ((SectorSize + 1) * TMULT)
#define FNAME "f-testfile"
#define READCHAR 'r'
#define WRITECHAR 'w'
Functions
void subproc_write (void)
Variables
static char buffer [SectorSize+1]
Macro Definition Documentation
FNAME
#define FNAME "f-testfile"
Definition at line 49 of file f_write.c.
FSIZE
#define FSIZE ((SectorSize + 1) * TMULT)
Definition at line 47 of file f_write.c.
READCHAR
#define READCHAR 'r'
Definition at line 50 of file f_write.c.
SectorSize
#define SectorSize 512
Definition at line 44 of file f_write.c.
TMULT
#define TMULT 50
Definition at line 46 of file f_write.c.
WRITECHAR
#define WRITECHAR 'w'
Definition at line 51 of file f_write.c.
Function Documentation
subproc_write()
void subproc_write (void)
Definition at line 61 of file f_write.c.
References buffer, close(), err(), fd, FNAME, O_WRONLY, open(), printf(), SectorSize, TMULT, write(), and WRITECHAR.
Referenced by concur().
Variable Documentation
buffer
char buffer[SectorSize+1] static
Definition at line 58 of file f_write.c.
Referenced by subproc_write().