os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_dup2.c File Reference
bad_dup2.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void dup2_fd2 (int fd, const char *desc)
static void dup2_self (void)
void test_dup2 (void)
Function Documentation
dup2_fd2()
static void dup2_fd2 (int fd, const char * desc) static
Definition at line 49 of file bad_dup2.c.
References close(), desc, dup2(), EBADF, errno, fd, report_begin(), report_check(), and STDIN_FILENO.
Referenced by test_dup2().
dup2_self()
static void dup2_self (void) static
Definition at line 64 of file bad_dup2.c.
References close(), CLOSED_FD, dup2(), ENOSYS, errno, ESPIPE, fstat(), lseek(), report_aborted(), report_begin(), report_failure(), report_passed(), report_result(), report_saw_enosys(), report_skipped(), report_warnx(), sb, SEEK_CUR, and STDIN_FILENO.
Referenced by test_dup2().
test_dup2()
void test_dup2 (void)
Definition at line 126 of file bad_dup2.c.
References dup2_fd2(), dup2_self(), IMPOSSIBLE_FD, OPEN_MAX, test_dup2_fd(), and warnx().