os161-doc: /home/os161user/os161/os161-base-2.0.3/common/libc/string/memmove.c File Reference
memmove.c File Reference
#include <stdint.h>
#include <string.h>
Functions
void * memmove (void *dst, const void *src, size_t len)
Function Documentation
memmove()
void* memmove (void * dst, const void * src, size_t len)
Definition at line 49 of file memmove.c.
References memcpy().
Referenced by array_remove(), as_copy(), lscreen_newline(), main(), pipe_unaligned(), and uiomove().