os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/frack/name.c File Reference
name.c File Reference
#include <string.h>
#include <assert.h>
#include <err.h>
#include "name.h"
Macros
#define MAXNAMES 32
Functions
const char * name_get (unsigned name)
unsigned name_find (const char *namestr)
Variables
static const char *const names [MAXNAMES]
Macro Definition Documentation
MAXNAMES
#define MAXNAMES 32
Definition at line 37 of file name.c.
Function Documentation
name_find()
unsigned name_find (const char * namestr)
Definition at line 82 of file name.c.
References errx(), MAXNAMES, names, and strcmp().
Referenced by inspectdir().
name_get()
const char* name_get (unsigned name)
Definition at line 75 of file name.c.
References assert, MAXNAMES, name, and names.
Referenced by checkallfilecontents(), do_chdir(), do_closedir(), do_closefile(), do_createfile(), do_link(), do_mkdir(), do_opendir(), do_openfile(), do_rename(), do_renamexd(), do_rmdir(), do_truncate(), do_unlink(), do_write(), fsdir_add_entry(), fsdir_find_entry(), fsdir_remove_entry(), model_finddir(), model_findfile(), and printdiffs().
Variable Documentation
names
const char* const names[MAXNAMES] static
Definition at line 39 of file name.c.
Referenced by name_find(), and name_get().