os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/randcall/extern.h File Reference
extern.h File Reference
#include <sys/types.h>
Functions
void * randptr (void)
int randint (void)
off_t randoff (void)
size_t randsize (void)
void trycalls (int asst, int dofork, int count)
Function Documentation
randint()
int randint (void)
Definition at line 89 of file main.c.
References fillrand().
Referenced by try_close(), try_dup2(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_lseek(), try_mkdir(), try_open(), try_read(), try_waitpid(), and try_write().
randoff()
off_t randoff (void)
Definition at line 97 of file main.c.
References fillrand().
Referenced by try_ftruncate(), and try_lseek().
randptr()
void* randptr (void)
Definition at line 81 of file main.c.
References fillrand().
Referenced by try___getcwd(), try___time(), try_chdir(), try_execv(), try_fstat(), try_getdirentry(), try_ioctl(), try_link(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), and try_write().
randsize()
size_t randsize (void)
Definition at line 105 of file main.c.
References fillrand().
trycalls()
void trycalls (int asst, int dofork, int count)
Definition at line 859 of file calls.c.
References assert, asst, count, dofork(), and tables.
Referenced by main().