os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/syscall.h File Reference
syscall.h File Reference
#include <cdefs.h>
Functions
void syscall (struct trapframe *tf)
void enter_forked_process (struct trapframe *tf)
__DEAD void enter_new_process (int argc, userptr_t argv, userptr_t env, vaddr_t stackptr, vaddr_t entrypoint)
int sys_reboot (int code)
int sys___time (userptr_t user_seconds, userptr_t user_nanoseconds)
Function Documentation
enter_forked_process()
void enter_forked_process (struct trapframe * tf)
Definition at line 158 of file syscall.c.
enter_new_process()
__DEAD void enter_new_process (int argc, userptr_t argv, userptr_t env, vaddr_t stackptr, vaddr_t entrypoint)
Definition at line 423 of file trap.c.
References bzero(), CST_IEp, CST_IRQMASK, CST_KUp, mips_usermode(), trapframe::tf_a0, trapframe::tf_a1, trapframe::tf_a2, trapframe::tf_epc, trapframe::tf_sp, and trapframe::tf_status.
Referenced by runprogram().
sys___time()
int sys___time (userptr_t user_seconds, userptr_t user_nanoseconds)
Definition at line 39 of file time_syscalls.c.
References copyout(), gettime(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by syscall().
sys_reboot()
int sys_reboot (int code)
Definition at line 172 of file main.c.
References EINVAL, kprintf(), mainbus_halt(), mainbus_poweroff(), mainbus_reboot(), panic(), RB_HALT, RB_POWEROFF, RB_REBOOT, and shutdown().
Referenced by cmd_quit(), and syscall().
syscall()
void syscall (struct trapframe * tf)
Definition at line 79 of file syscall.c.
References ENOSYS, err(), KASSERT, kprintf(), NULL, sys___time(), SYS___time, sys_reboot(), SYS_reboot, trapframe::tf_a0, trapframe::tf_a1, trapframe::tf_a3, trapframe::tf_epc, and trapframe::tf_v0.
Referenced by mips_trap().