os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_sbrk.c File Reference
bad_sbrk.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static int try_sbrk (long val)
static void enforce_sbrk (long val, const char *desc, int err)
static void sbrk_bigpos (void)
static void sbrk_bigneg (void)
static void sbrk_neg (void)
static void sbrk_unalignedpos (void)
static void sbrk_unalignedneg (void)
void test_sbrk (void)
Function Documentation
enforce_sbrk()
static void enforce_sbrk (long val, const char * desc, int err) static
Definition at line 63 of file bad_sbrk.c.
References desc, err(), errno, report_begin(), report_check(), and try_sbrk().
Referenced by sbrk_bigneg(), sbrk_bigpos(), and sbrk_neg().
sbrk_bigneg()
static void sbrk_bigneg (void) static
Definition at line 82 of file bad_sbrk.c.
References EINVAL, and enforce_sbrk().
Referenced by test_sbrk().
sbrk_bigpos()
static void sbrk_bigpos (void) static
Definition at line 75 of file bad_sbrk.c.
References enforce_sbrk(), and ENOMEM.
Referenced by test_sbrk().
sbrk_neg()
static void sbrk_neg (void) static
Definition at line 89 of file bad_sbrk.c.
References EINVAL, and enforce_sbrk().
Referenced by test_sbrk().
sbrk_unalignedneg()
static void sbrk_unalignedneg (void) static
Definition at line 107 of file bad_sbrk.c.
References EINVAL, errno, report_begin(), report_check2(), and try_sbrk().
Referenced by test_sbrk().
sbrk_unalignedpos()
static void sbrk_unalignedpos (void) static
Definition at line 96 of file bad_sbrk.c.
References EINVAL, errno, report_begin(), report_check2(), and try_sbrk().
Referenced by test_sbrk().
test_sbrk()
void test_sbrk (void)
Definition at line 117 of file bad_sbrk.c.
References sbrk_bigneg(), sbrk_bigpos(), sbrk_neg(), sbrk_unalignedneg(), and sbrk_unalignedpos().
try_sbrk()
static int try_sbrk (long val) static
Definition at line 51 of file bad_sbrk.c.
References sbrk().
Referenced by enforce_sbrk(), sbrk_unalignedneg(), and sbrk_unalignedpos().