os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/include/stdio.h File Reference
stdio.h File Reference
#include <kern/types.h>
#include <types/size_t.h>
#include <sys/null.h>
Macros
#define EOF (-1)
Functions
int __vprintf (void(*sendfunc)(void *clientdata, const char *, size_t len), void *clientdata, const char *fmt, __va_list ap)
int printf (const char *fmt,...)
int vprintf (const char *fmt, __va_list ap)
int snprintf (char *buf, size_t len, const char *fmt,...)
int vsnprintf (char *buf, size_t len, const char *fmt, __va_list ap)
int puts (const char *)
int __puts (const char *)
int putchar (int)
int getchar (void)
Macro Definition Documentation
EOF
#define EOF (-1)
Definition at line 42 of file stdio.h.
Function Documentation
__puts()
int __puts (const char *)
Definition at line 42 of file __puts.c.
References EOF, STDOUT_FILENO, strlen(), and write().
__vprintf()
int __vprintf (void(*)(void *clientdata, const char *, size_t len) sendfunc, void * clientdata, const char * fmt, __va_list ap)
getchar()
int getchar (void)
Definition at line 39 of file getchar.c.
References ch, EOF, read(), and STDIN_FILENO.
printf()
int printf (const char * fmt, ...)
Definition at line 56 of file printf.c.
References va_end, va_start, and vprintf().
putchar()
int putchar (int)
Definition at line 41 of file putchar.c.
References ch, EOF, STDOUT_FILENO, and write().
puts()
int puts (const char *)
Definition at line 37 of file puts.c.
References __puts(), and putchar().
snprintf()
int snprintf (char * buf, size_t len, const char * fmt, ...)
Definition at line 148 of file snprintf.c.
References buf, va_end, va_start, and vsnprintf().
vprintf()
int vprintf (const char * fmt, __va_list ap)
Definition at line 69 of file printf.c.
References __printf_send(), __vprintf(), err(), and errno.
Referenced by printf().
vsnprintf()
int vsnprintf (char * buf, size_t len, const char * fmt, __va_list ap)
Definition at line 99 of file snprintf.c.
References __snprintf_send(), __vprintf(), SNP::buf, buf, SNP::buflen, and SNP::bufpos.
Referenced by snprintf().