os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/arch/mips/include/tlb.h File Reference
tlb.h File Reference
Macros
#define TLBHI_VPAGE 0xfffff000
#define TLBLO_PPAGE 0xfffff000
#define TLBLO_NOCACHE 0x00000800
#define TLBLO_DIRTY 0x00000400
#define TLBLO_VALID 0x00000200
#define TLBHI_INVALID(entryno) ((0x80000+(entryno))<<12)
#define TLBLO_INVALID() (0)
#define NUM_TLB 64
Functions
void tlb_random (uint32_t entryhi, uint32_t entrylo)
void tlb_write (uint32_t entryhi, uint32_t entrylo, uint32_t index)
void tlb_read (uint32_t *entryhi, uint32_t *entrylo, uint32_t index)
int tlb_probe (uint32_t entryhi, uint32_t entrylo)
Macro Definition Documentation
NUM_TLB
#define NUM_TLB 64
Definition at line 102 of file tlb.h.
TLBHI_INVALID
#define TLBHI_INVALID (entryno) ((0x80000+(entryno))<<12)
Definition at line 95 of file tlb.h.
TLBHI_VPAGE
#define TLBHI_VPAGE 0xfffff000
Definition at line 80 of file tlb.h.
TLBLO_DIRTY
#define TLBLO_DIRTY 0x00000400
Definition at line 86 of file tlb.h.
TLBLO_INVALID
#define TLBLO_INVALID () (0)
Definition at line 96 of file tlb.h.
TLBLO_NOCACHE
#define TLBLO_NOCACHE 0x00000800
Definition at line 85 of file tlb.h.
TLBLO_PPAGE
#define TLBLO_PPAGE 0xfffff000
Definition at line 84 of file tlb.h.
TLBLO_VALID
#define TLBLO_VALID 0x00000200
Definition at line 87 of file tlb.h.
Function Documentation
tlb_probe()
int tlb_probe (uint32_t entryhi, uint32_t entrylo)
tlb_random()
void tlb_random (uint32_t entryhi, uint32_t entrylo)
tlb_read()
void tlb_read (uint32_t * entryhi, uint32_t * entrylo, uint32_t index)
Referenced by vm_fault().
tlb_write()
void tlb_write (uint32_t entryhi, uint32_t entrylo, uint32_t index)
Referenced by as_activate(), and vm_fault().