os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/dev/lamebus/lamebus.c File Reference
lamebus.c File Reference
#include <types.h>
#include <lib.h>
#include <cpu.h>
#include <membar.h>
#include <spinlock.h>
#include <current.h>
#include <lamebus/lamebus.h>
Macros
#define CFGREG_VID 0 /* Vendor ID */
#define CFGREG_DID 4 /* Device ID */
#define CFGREG_DRL 8 /* Device Revision Level */
#define CTLREG_RAMSZ 0x200
#define CTLREG_IRQS 0x204
#define CTLREG_PWR 0x208
#define CTLREG_IRQE 0x20c
#define CTLREG_CPUS 0x210
#define CTLREG_CPUE 0x214
#define CTLREG_SELF 0x218
#define CTLCPU_CIRQE 0x000
#define CTLCPU_CIPI 0x004
#define CTLCPU_CRAM 0x300
Functions
static uint32_t read_cfg_register (struct lamebus_softc *lb, int slot, uint32_t offset)
static void write_cfg_register (struct lamebus_softc *lb, int slot, uint32_t offset, uint32_t val)
static uint32_t read_ctl_register (struct lamebus_softc *lb, uint32_t offset)
static void write_ctl_register (struct lamebus_softc *lb, uint32_t offset, uint32_t val)
static void write_ctlcpu_register (struct lamebus_softc *lb, unsigned hw_cpunum, uint32_t offset, uint32_t val)
void lamebus_find_cpus (struct lamebus_softc *lamebus)
void lamebus_start_cpus (struct lamebus_softc *lamebus)
int lamebus_probe (struct lamebus_softc *sc, uint32_t vendorid, uint32_t deviceid, uint32_t lowver, uint32_t *version_ret)
void lamebus_mark (struct lamebus_softc *sc, int slot)
void lamebus_unmark (struct lamebus_softc *sc, int slot)
void lamebus_attach_interrupt (struct lamebus_softc *sc, int slot, void *devdata, void(*irqfunc)(void *devdata))
void lamebus_detach_interrupt (struct lamebus_softc *sc, int slot)
void lamebus_mask_interrupt (struct lamebus_softc *lamebus, int slot)
void lamebus_unmask_interrupt (struct lamebus_softc *lamebus, int slot)
void lamebus_interrupt (struct lamebus_softc *lamebus)
void lamebus_poweroff (struct lamebus_softc *lamebus)
uint32_t lamebus_ramsize (void)
void lamebus_assert_ipi (struct lamebus_softc *lamebus, struct cpu *target)
void lamebus_clear_ipi (struct lamebus_softc *lamebus, struct cpu *target)
struct lamebus_softc * lamebus_init (void)
Macro Definition Documentation
CFGREG_DID
#define CFGREG_DID 4 /* Device ID */
Definition at line 44 of file lamebus.c.
CFGREG_DRL
#define CFGREG_DRL 8 /* Device Revision Level */
Definition at line 45 of file lamebus.c.
CFGREG_VID
#define CFGREG_VID 0 /* Vendor ID */
Definition at line 43 of file lamebus.c.
CTLCPU_CIPI
#define CTLCPU_CIPI 0x004
Definition at line 58 of file lamebus.c.
CTLCPU_CIRQE
#define CTLCPU_CIRQE 0x000
Definition at line 57 of file lamebus.c.
CTLCPU_CRAM
#define CTLCPU_CRAM 0x300
Definition at line 59 of file lamebus.c.
CTLREG_CPUE
#define CTLREG_CPUE 0x214
Definition at line 53 of file lamebus.c.
CTLREG_CPUS
#define CTLREG_CPUS 0x210
Definition at line 52 of file lamebus.c.
CTLREG_IRQE
#define CTLREG_IRQE 0x20c
Definition at line 51 of file lamebus.c.
CTLREG_IRQS
#define CTLREG_IRQS 0x204
Definition at line 49 of file lamebus.c.
CTLREG_PWR
#define CTLREG_PWR 0x208
Definition at line 50 of file lamebus.c.
CTLREG_RAMSZ
#define CTLREG_RAMSZ 0x200
Definition at line 48 of file lamebus.c.
CTLREG_SELF
#define CTLREG_SELF 0x218
Definition at line 54 of file lamebus.c.
Function Documentation
lamebus_assert_ipi()
void lamebus_assert_ipi (struct lamebus_softc * lamebus, struct cpu * target)
Definition at line 615 of file lamebus.c.
References cpu::c_hardware_number, CTLCPU_CIPI, lamebus, lamebus_softc::ls_uniprocessor, and write_ctlcpu_register().
Referenced by mainbus_send_ipi().
lamebus_attach_interrupt()
void lamebus_attach_interrupt (struct lamebus_softc * sc, int slot, void * devdata, void(*)(void *devdata) irqfunc)
Definition at line 351 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), spinlock_acquire(), and spinlock_release().
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), and attach_ltimer_to_lamebus().
lamebus_clear_ipi()
void lamebus_clear_ipi (struct lamebus_softc * lamebus, struct cpu * target)
Definition at line 625 of file lamebus.c.
References cpu::c_hardware_number, CTLCPU_CIPI, lamebus, lamebus_softc::ls_uniprocessor, and write_ctlcpu_register().
Referenced by mainbus_interrupt().
lamebus_detach_interrupt()
void lamebus_detach_interrupt (struct lamebus_softc * sc, int slot)
Definition at line 379 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), spinlock_acquire(), and spinlock_release().
lamebus_find_cpus()
void lamebus_find_cpus (struct lamebus_softc * lamebus)
Definition at line 128 of file lamebus.c.
References CFGREG_DID, CFGREG_VID, cpu_create(), CTLCPU_CIRQE, CTLREG_CPUS, CTLREG_SELF, lamebus, LB_CONTROLLER_SLOT, LB_VENDOR_CS161, LBCS161_UPBUSCTL, lamebus_softc::ls_uniprocessor, read_cfg_register(), read_ctl_register(), and write_ctlcpu_register().
Referenced by mainbus_bootstrap().
lamebus_init()
struct lamebus_softc* lamebus_init (void)
Definition at line 639 of file lamebus.c.
References kmalloc(), lamebus, LB_CONTROLLER_SLOT, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, lamebus_softc::ls_uniprocessor, NULL, panic(), and spinlock_init().
Referenced by mainbus_bootstrap().
lamebus_interrupt()
void lamebus_interrupt (struct lamebus_softc * lamebus)
Definition at line 433 of file lamebus.c.
References CTLREG_IRQS, KASSERT, kprintf(), lamebus, LB_NSLOTS, lamebus_softc::ls_devdata, lamebus_softc::ls_irqfuncs, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, panic(), read_ctl_register(), spinlock_acquire(), and spinlock_release().
Referenced by mainbus_interrupt().
lamebus_mark()
void lamebus_mark (struct lamebus_softc * sc, int slot)
Definition at line 310 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, panic(), spinlock_acquire(), and spinlock_release().
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), and attach_ltrace_to_lamebus().
lamebus_mask_interrupt()
void lamebus_mask_interrupt (struct lamebus_softc * lamebus, int slot)
Definition at line 403 of file lamebus.c.
References CTLREG_IRQE, KASSERT, lamebus, LB_NSLOTS, lamebus_softc::ls_lock, read_ctl_register(), spinlock_acquire(), spinlock_release(), and write_ctl_register().
lamebus_poweroff()
void lamebus_poweroff (struct lamebus_softc * lamebus)
Definition at line 582 of file lamebus.c.
References cpu_halt(), cpu_irqoff(), CTLREG_PWR, lamebus, and write_ctl_register().
Referenced by mainbus_poweroff().
lamebus_probe()
int lamebus_probe (struct lamebus_softc * sc, uint32_t vendorid, uint32_t deviceid, uint32_t lowver, uint32_t * version_ret)
Definition at line 251 of file lamebus.c.
References CFGREG_DID, CFGREG_DRL, CFGREG_VID, LB_NSLOTS, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, NULL, read_cfg_register(), spinlock_acquire(), and spinlock_release().
Referenced by attach_emu_to_lamebus(), attach_lhd_to_lamebus(), attach_lnet_to_lamebus(), attach_lrandom_to_lamebus(), attach_lscreen_to_lamebus(), attach_lser_to_lamebus(), attach_ltimer_to_lamebus(), and attach_ltrace_to_lamebus().
lamebus_ramsize()
uint32_t lamebus_ramsize (void)
Definition at line 599 of file lamebus.c.
References CTLREG_RAMSZ, NULL, and read_ctl_register().
Referenced by mainbus_ramsize().
lamebus_start_cpus()
void lamebus_start_cpus (struct lamebus_softc * lamebus)
Definition at line 197 of file lamebus.c.
References cpu_start_secondary(), CTLCPU_CRAM, CTLREG_CPUE, CTLREG_CPUS, CTLREG_SELF, lamebus, lamebus_map_area(), LB_CONTROLLER_SLOT, LB_CTLCPU_OFFSET, LB_CTLCPU_SIZE, lamebus_softc::ls_uniprocessor, membar_store_store(), read_ctl_register(), and write_ctl_register().
Referenced by mainbus_start_cpus().
lamebus_unmark()
void lamebus_unmark (struct lamebus_softc * sc, int slot)
Definition at line 330 of file lamebus.c.
References KASSERT, LB_NSLOTS, lamebus_softc::ls_lock, lamebus_softc::ls_slotsinuse, panic(), spinlock_acquire(), and spinlock_release().
lamebus_unmask_interrupt()
void lamebus_unmask_interrupt (struct lamebus_softc * lamebus, int slot)
Definition at line 416 of file lamebus.c.
References CTLREG_IRQE, KASSERT, lamebus, LB_NSLOTS, lamebus_softc::ls_lock, read_ctl_register(), spinlock_acquire(), spinlock_release(), and write_ctl_register().
read_cfg_register()
static uint32_t read_cfg_register (struct lamebus_softc * lb, int slot, uint32_t offset) inline static
Definition at line 68 of file lamebus.c.
References lamebus_read_register(), LB_CONFIG_SIZE, and LB_CONTROLLER_SLOT.
Referenced by lamebus_find_cpus(), lamebus_probe(), and read_ctl_register().
read_ctl_register()
static uint32_t read_ctl_register (struct lamebus_softc * lb, uint32_t offset) inline static
Definition at line 94 of file lamebus.c.
References LB_CONTROLLER_SLOT, and read_cfg_register().
Referenced by lamebus_find_cpus(), lamebus_interrupt(), lamebus_mask_interrupt(), lamebus_ramsize(), lamebus_start_cpus(), and lamebus_unmask_interrupt().
write_cfg_register()
static void write_cfg_register (struct lamebus_softc * lb, int slot, uint32_t offset, uint32_t val) inline static
Definition at line 81 of file lamebus.c.
References lamebus_write_register(), LB_CONFIG_SIZE, and LB_CONTROLLER_SLOT.
Referenced by write_ctl_register().
write_ctl_register()
static void write_ctl_register (struct lamebus_softc * lb, uint32_t offset, uint32_t val) inline static
Definition at line 106 of file lamebus.c.
References LB_CONTROLLER_SLOT, and write_cfg_register().
Referenced by lamebus_mask_interrupt(), lamebus_poweroff(), lamebus_start_cpus(), and lamebus_unmask_interrupt().
write_ctlcpu_register()
static void write_ctlcpu_register (struct lamebus_softc * lb, unsigned hw_cpunum, uint32_t offset, uint32_t val) inline static
Definition at line 117 of file lamebus.c.
References lamebus_write_register(), LB_CONTROLLER_SLOT, LB_CTLCPU_OFFSET, and LB_CTLCPU_SIZE.
Referenced by lamebus_assert_ipi(), lamebus_clear_ipi(), and lamebus_find_cpus().