os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/lib/libc/unix/getcwd.c File Reference
getcwd.c File Reference
#include <unistd.h>
#include <errno.h>
Functions
char * getcwd (char *buf, size_t buflen)
Function Documentation
getcwd()
char* getcwd (char * buf, size_t buflen)
Definition at line 40 of file getcwd.c.
References __getcwd(), buf, EINVAL, errno, and NULL.
Referenced by main(), startup(), and test7().