os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/thread/thread.c File Reference
thread.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <array.h>
#include <cpu.h>
#include <spl.h>
#include <spinlock.h>
#include <wchan.h>
#include <thread.h>
#include <threadlist.h>
#include <threadprivate.h>
#include <proc.h>
#include <current.h>
#include <synch.h>
#include <addrspace.h>
#include <mainbus.h>
#include <vnode.h>
Data Structures
struct wchan
Macros
#define THREADINLINE
#define THREAD_STACK_MAGIC 0xbaadf00d
Functions
DECLARRAY (cpu, static __UNUSED inline)
DEFARRAY (cpu, static __UNUSED inline)
static void thread_checkstack_init (struct thread *thread)
static void thread_checkstack (struct thread *thread)
static struct thread * thread_create (const char *name)
struct cpu * cpu_create (unsigned hardware_number)
static void thread_destroy (struct thread *thread)
static void exorcise (void)
void thread_panic (void)
void thread_shutdown (void)
void thread_bootstrap (void)
void cpu_hatch (unsigned software_number)
void thread_start_cpus (void)
static void thread_make_runnable (struct thread *target, bool already_have_lock)
int thread_fork (const char *name, struct proc *proc, void(*entrypoint)(void *data1, unsigned long data2), void *data1, unsigned long data2)
static void thread_switch (threadstate_t newstate, struct wchan *wc, struct spinlock *lk)
void thread_startup (void(*entrypoint)(void *data1, unsigned long data2), void *data1, unsigned long data2)
void thread_exit (void)
void thread_yield (void)
void schedule (void)
void thread_consider_migration (void)
struct wchan * wchan_create (const char *name)
void wchan_destroy (struct wchan *wc)
void wchan_sleep (struct wchan *wc, struct spinlock *lk)
void wchan_wakeone (struct wchan *wc, struct spinlock *lk)
void wchan_wakeall (struct wchan *wc, struct spinlock *lk)
bool wchan_isempty (struct wchan *wc, struct spinlock *lk)
void ipi_send (struct cpu *target, int code)
void ipi_broadcast (int code)
void ipi_tlbshootdown (struct cpu *target, const struct tlbshootdown *mapping)
void interprocessor_interrupt (void)
Variables
static struct cpuarray allcpus
static struct semaphore * cpu_startup_sem
Macro Definition Documentation
THREAD_STACK_MAGIC
#define THREAD_STACK_MAGIC 0xbaadf00d
Definition at line 56 of file thread.c.
THREADINLINE
#define THREADINLINE
Definition at line 34 of file thread.c.
Function Documentation
cpu_create()
struct cpu* cpu_create (unsigned hardware_number)
Definition at line 164 of file thread.c.
References allcpus, cpu::c_curthread, cpu::c_hardclocks, cpu::c_hardware_number, cpu::c_ipi_lock, cpu::c_ipi_pending, cpu::c_isidle, cpu::c_number, cpu::c_numshootdown, cpu::c_runqueue, cpu::c_runqueue_lock, cpu::c_self, cpu::c_spinlocks, cpu::c_zombies, cpu_machdep_init(), HANGMAN_ACTORINIT, INIT_CURCPU, kmalloc(), kproc, NULL, panic(), proc_addthread(), snprintf(), spinlock_init(), STACK_SIZE, strerror(), thread::t_cpu, thread::t_stack, thread_checkstack_init(), thread_create(), and threadlist_init().
Referenced by lamebus_find_cpus(), and thread_bootstrap().
cpu_hatch()
void cpu_hatch (unsigned software_number)
Definition at line 406 of file thread.c.
References buf, cpu_identify(), cpu_startup_sem, KASSERT, kprintf(), NULL, spl0(), thread_exit(), and V().
DECLARRAY()
DECLARRAY (cpu , static __UNUSED inline)
DEFARRAY()
DEFARRAY (cpu , static __UNUSED inline)
exorcise()
static void exorcise (void) static
Definition at line 298 of file thread.c.
References KASSERT, NULL, S_ZOMBIE, thread::t_state, thread_destroy(), and threadlist_remhead().
Referenced by thread_startup(), and thread_switch().
interprocessor_interrupt()
void interprocessor_interrupt (void)
Definition at line 1167 of file thread.c.
References cpu_halt(), IPI_OFFLINE, IPI_PANIC, IPI_TLBSHOOTDOWN, IPI_UNIDLE, kprintf(), spinlock_acquire(), spinlock_release(), and vm_tlbshootdown().
Referenced by mainbus_interrupt().
ipi_broadcast()
void ipi_broadcast (int code)
Definition at line 1116 of file thread.c.
References allcpus, cpu::c_self, and ipi_send().
Referenced by thread_panic(), and thread_shutdown().
ipi_send()
void ipi_send (struct cpu * target, int code)
Definition at line 1102 of file thread.c.
References cpu::c_ipi_lock, cpu::c_ipi_pending, KASSERT, mainbus_send_ipi(), spinlock_acquire(), and spinlock_release().
Referenced by ipi_broadcast(), thread_consider_migration(), and thread_make_runnable().
ipi_tlbshootdown()
void ipi_tlbshootdown (struct cpu * target, const struct tlbshootdown * mapping)
Definition at line 1133 of file thread.c.
References cpu::c_ipi_lock, cpu::c_ipi_pending, cpu::c_numshootdown, cpu::c_shootdown, IPI_TLBSHOOTDOWN, mainbus_send_ipi(), panic(), spinlock_acquire(), spinlock_release(), and TLBSHOOTDOWN_MAX.
schedule()
void schedule (void)
Definition at line 822 of file thread.c.
Referenced by hardclock().
thread_bootstrap()
void thread_bootstrap (void)
Definition at line 372 of file thread.c.
References allcpus, cpu_create(), KASSERT, kproc, and NULL.
Referenced by boot().
thread_checkstack()
static void thread_checkstack (struct thread * thread) static
Definition at line 101 of file thread.c.
References KASSERT, NULL, thread::t_stack, and THREAD_STACK_MAGIC.
Referenced by thread_exit(), and thread_switch().
thread_checkstack_init()
static void thread_checkstack_init (struct thread * thread) static
Definition at line 81 of file thread.c.
References thread::t_stack, and THREAD_STACK_MAGIC.
Referenced by cpu_create(), and thread_fork().
thread_consider_migration()
void thread_consider_migration (void)
Definition at line 848 of file thread.c.
References allcpus, cpu::c_isidle, cpu::c_number, cpu::c_runqueue, cpu::c_runqueue_lock, cpu::c_self, DB_THREADS, DEBUG, DIVROUNDUP, ipi_send(), IPI_UNIDLE, KASSERT, NULL, spinlock_acquire(), spinlock_release(), thread::t_cpu, thread::t_name, threadlist_addhead(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_isempty(), threadlist_remhead(), threadlist_remtail(), and threadlist::tl_count.
Referenced by hardclock().
thread_create()
static struct thread* thread_create (const char * name) static
Definition at line 117 of file thread.c.
References DEBUGASSERT, HANGMAN_ACTORINIT, IPL_HIGH, kfree(), kmalloc(), kstrdup(), name, NULL, S_READY, thread::t_context, thread::t_cpu, thread::t_curspl, thread::t_in_interrupt, thread::t_iplhigh_count, thread::t_listnode, thread::t_machdep, thread::t_name, thread::t_proc, thread::t_stack, thread::t_state, thread::t_wchan_name, thread_machdep_init(), and threadlistnode_init().
Referenced by cpu_create(), and thread_fork().
thread_destroy()
static void thread_destroy (struct thread * thread) static
Definition at line 265 of file thread.c.
References KASSERT, kfree(), NULL, S_RUN, thread::t_listnode, thread::t_machdep, thread::t_name, thread::t_proc, thread::t_stack, thread::t_state, thread::t_wchan_name, thread_machdep_cleanup(), and threadlistnode_cleanup().
Referenced by exorcise(), and thread_fork().
thread_exit()
void thread_exit (void)
Definition at line 779 of file thread.c.
References KASSERT, NULL, panic(), proc_remthread(), S_ZOMBIE, splhigh(), thread::t_proc, thread_checkstack(), and thread_switch().
Referenced by cmd_quit(), cpu_hatch(), cvtestthread(), fail(), and thread_startup().
thread_fork()
int thread_fork (const char * name, struct proc * proc, void(*)(void *data1, unsigned long data2) entrypoint, void * data1, unsigned long data2)
Definition at line 495 of file thread.c.
References ENOMEM, kmalloc(), name, NULL, proc_addthread(), STACK_SIZE, switchframe_init(), thread::t_cpu, thread::t_iplhigh_count, thread::t_stack, thread_checkstack_init(), thread_create(), thread_destroy(), and thread_make_runnable().
thread_make_runnable()
static void thread_make_runnable (struct thread * target, bool already_have_lock) static
Definition at line 452 of file thread.c.
References cpu::c_isidle, cpu::c_runqueue, cpu::c_runqueue_lock, cpu::c_self, ipi_send(), IPI_UNIDLE, KASSERT, S_READY, spinlock_acquire(), spinlock_do_i_hold(), spinlock_release(), thread::t_cpu, thread::t_state, and threadlist_addtail().
Referenced by thread_fork(), thread_switch(), wchan_wakeall(), and wchan_wakeone().
thread_panic()
void thread_panic (void)
Definition at line 315 of file thread.c.
References ipi_broadcast(), and IPI_PANIC.
Referenced by panic().
thread_shutdown()
void thread_shutdown (void)
Definition at line 357 of file thread.c.
References ipi_broadcast(), and IPI_OFFLINE.
Referenced by shutdown().
thread_start_cpus()
void thread_start_cpus (void)
Definition at line 427 of file thread.c.
References allcpus, buf, cpu_identify(), cpu_startup_sem, kprintf(), mainbus_start_cpus(), NULL, P(), sem_create(), and sem_destroy().
Referenced by boot().
thread_startup()
void thread_startup (void(*)(void *data1, unsigned long data2) entrypoint, void * data1, unsigned long data2)
Definition at line 739 of file thread.c.
References as_activate(), exorcise(), NULL, S_RUN, spinlock_release(), spl0(), thread::t_state, thread::t_wchan_name, and thread_exit().
thread_switch()
static void thread_switch (threadstate_t newstate, struct wchan * wc, struct spinlock * lk) static
Definition at line 562 of file thread.c.
References as_activate(), cpu_idle(), DEBUGASSERT, exorcise(), NULL, panic(), S_READY, S_RUN, S_SLEEP, S_ZOMBIE, spinlock_acquire(), spinlock_release(), splhigh(), splx(), switchframe_switch(), thread::t_context, thread::t_state, thread::t_wchan_name, thread_checkstack(), thread_make_runnable(), threadlist_addtail(), threadlist_isempty(), threadlist_remhead(), wchan::wc_name, and wchan::wc_threads.
Referenced by thread_exit(), thread_yield(), and wchan_sleep().
thread_yield()
void thread_yield (void)
Definition at line 807 of file thread.c.
References NULL, S_READY, and thread_switch().
Referenced by compute_thread(), hardclock(), and waker_thread().
wchan_create()
struct wchan* wchan_create (const char * name)
Definition at line 967 of file thread.c.
References kmalloc(), name, NULL, threadlist_init(), wchan::wc_name, and wchan::wc_threads.
Referenced by hardclock_bootstrap(), sem_create(), and setup().
wchan_destroy()
void wchan_destroy (struct wchan * wc)
Definition at line 986 of file thread.c.
References kfree(), threadlist_cleanup(), and wchan::wc_threads.
Referenced by sem_destroy().
wchan_isempty()
bool wchan_isempty (struct wchan * wc, struct spinlock * lk)
Definition at line 1082 of file thread.c.
References KASSERT, spinlock_do_i_hold(), threadlist_isempty(), and wchan::wc_threads.
wchan_sleep()
void wchan_sleep (struct wchan * wc, struct spinlock * lk)
Definition at line 1000 of file thread.c.
References KASSERT, S_SLEEP, spinlock_acquire(), spinlock_do_i_hold(), and thread_switch().
Referenced by clocksleep(), P(), and sleepalot_thread().
wchan_wakeall()
void wchan_wakeall (struct wchan * wc, struct spinlock * lk)
Definition at line 1048 of file thread.c.
References KASSERT, NULL, spinlock_do_i_hold(), thread_make_runnable(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_remhead(), and wchan::wc_threads.
Referenced by timerclock(), and waker_thread().
wchan_wakeone()
void wchan_wakeone (struct wchan * wc, struct spinlock * lk)
Definition at line 1019 of file thread.c.
References KASSERT, NULL, spinlock_do_i_hold(), thread_make_runnable(), threadlist_remhead(), and wchan::wc_threads.
Referenced by V().
Variable Documentation
allcpus
struct cpuarray allcpus static
Definition at line 67 of file thread.c.
Referenced by cpu_create(), ipi_broadcast(), thread_bootstrap(), thread_consider_migration(), and thread_start_cpus().
cpu_startup_sem
struct semaphore* cpu_startup_sem static
Definition at line 70 of file thread.c.
Referenced by cpu_hatch(), and thread_start_cpus().