os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/arch/mips/vm/ram.c File Reference
ram.c File Reference
#include <types.h>
#include <lib.h>
#include <vm.h>
#include <mainbus.h>
Functions
void ram_bootstrap (void)
paddr_t ram_stealmem (unsigned long npages)
paddr_t ram_getsize (void)
paddr_t ram_getfirstfree (void)
Variables
vaddr_t firstfree
static paddr_t firstpaddr
static paddr_t lastpaddr
Function Documentation
ram_bootstrap()
void ram_bootstrap (void)
Definition at line 46 of file ram.c.
References firstfree, firstpaddr, kprintf(), lastpaddr, mainbus_ramsize(), and MIPS_KSEG0.
Referenced by boot().
ram_getfirstfree()
paddr_t ram_getfirstfree (void)
Definition at line 146 of file ram.c.
References firstpaddr, and lastpaddr.
ram_getsize()
paddr_t ram_getsize (void)
Definition at line 128 of file ram.c.
References lastpaddr.
ram_stealmem()
paddr_t ram_stealmem (unsigned long npages)
Definition at line 95 of file ram.c.
References firstpaddr, lastpaddr, and PAGE_SIZE.
Referenced by getppages().
Variable Documentation
firstfree
vaddr_t firstfree
Definition at line 36 of file ram.c.
Referenced by ram_bootstrap().
firstpaddr
paddr_t firstpaddr static
Definition at line 38 of file ram.c.
Referenced by ram_bootstrap(), ram_getfirstfree(), and ram_stealmem().
lastpaddr
paddr_t lastpaddr static
Definition at line 39 of file ram.c.
Referenced by ram_bootstrap(), ram_getfirstfree(), ram_getsize(), and ram_stealmem().