os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/spl.h File Reference
spl.h File Reference
#include <cdefs.h>
Macros
#define SPL_INLINE INLINE
#define IPL_NONE 0
#define IPL_HIGH 1
Functions
SPL_INLINE int spl0 (void)
SPL_INLINE int splhigh (void)
int splx (int)
void splraise (int oldipl, int newipl)
void spllower (int oldipl, int newipl)
Macro Definition Documentation
IPL_HIGH
#define IPL_HIGH 1
Definition at line 78 of file spl.h.
IPL_NONE
#define IPL_NONE 0
Definition at line 77 of file spl.h.
SPL_INLINE
#define SPL_INLINE INLINE
Definition at line 37 of file spl.h.
Function Documentation
spl0()
SPL_INLINE int spl0 (void)
Definition at line 96 of file spl.h.
References IPL_NONE, and splx().
Referenced by cpu_hatch(), mainbus_bootstrap(), mips_usermode(), and thread_startup().
splhigh()
SPL_INLINE int splhigh (void)
Definition at line 103 of file spl.h.
References IPL_HIGH, and splx().
Referenced by as_activate(), hangman_check(), ltimer_gettime(), mips_trap(), panic(), proc_addthread(), proc_remthread(), shutdown(), thread_exit(), thread_switch(), and vm_fault().
spllower()
void spllower (int oldipl, int newipl)
Definition at line 107 of file spl.c.
References cpu_irqon(), IPL_HIGH, IPL_NONE, KASSERT, and thread::t_iplhigh_count.
Referenced by spinlock_release(), and splx().
splraise()
void splraise (int oldipl, int newipl)
Definition at line 87 of file spl.c.
References cpu_irqoff(), IPL_HIGH, IPL_NONE, KASSERT, and thread::t_iplhigh_count.
Referenced by spinlock_acquire(), and splx().
splx()
int splx (int)
Definition at line 132 of file spl.c.
References spllower(), splraise(), and thread::t_curspl.
Referenced by as_activate(), ltimer_gettime(), mips_trap(), proc_addthread(), proc_remthread(), spl0(), splhigh(), thread_switch(), and vm_fault().