os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/schedpong/results.c File Reference
results.c File Reference
#include <unistd.h>
#include <fcntl.h>
#include <err.h>
#include <errno.h>
#include <assert.h>
#include "results.h"
Macros
#define RESULTSFILE "endtimes"
Functions
void createresultsfile (void)
void destroyresultsfile (void)
void openresultsfile (int openflags)
void closeresultsfile (void)
void putresult (unsigned groupid, time_t secs, unsigned long nsecs)
void getresult (unsigned groupid, time_t *secs, unsigned long *nsecs)
Variables
static int resultsfile = -1
Macro Definition Documentation
RESULTSFILE
#define RESULTSFILE "endtimes"
Definition at line 39 of file results.c.
Function Documentation
closeresultsfile()
void closeresultsfile (void)
Definition at line 99 of file results.c.
References assert, close(), RESULTSFILE, resultsfile, and warn().
Referenced by runit(), and runtaskgroup().
createresultsfile()
void createresultsfile (void)
Definition at line 48 of file results.c.
References assert, close(), err(), fd, O_CREAT, O_RDWR, O_TRUNC, open(), RESULTSFILE, resultsfile, and warn().
Referenced by runit().
destroyresultsfile()
void destroyresultsfile (void)
Definition at line 68 of file results.c.
References ENOSYS, errno, remove(), RESULTSFILE, and warn().
Referenced by runit().
getresult()
void getresult (unsigned groupid, time_t * secs, unsigned long * nsecs)
Definition at line 144 of file results.c.
References assert, err(), errx(), lseek(), pos, read(), RESULTSFILE, resultsfile, and SEEK_SET.
Referenced by calcresult().
openresultsfile()
void openresultsfile (int openflags)
Definition at line 84 of file results.c.
References assert, err(), O_RDONLY, O_WRONLY, open(), RESULTSFILE, and resultsfile.
Referenced by runit(), and runtaskgroup().
putresult()
void putresult (unsigned groupid, time_t secs, unsigned long nsecs)
Definition at line 113 of file results.c.
References assert, err(), errx(), lseek(), pos, RESULTSFILE, resultsfile, SEEK_SET, and write().
Referenced by runtaskgroup().
Variable Documentation
resultsfile
int resultsfile = -1 static
Definition at line 41 of file results.c.
Referenced by closeresultsfile(), createresultsfile(), getresult(), openresultsfile(), and putresult().