os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/bin/ls/ls.c File Reference
ls.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <err.h>
Functions
static void option (int ch)
static const char * basename (const char *path)
static int isdir (const char *path)
static void printheader (const char *file)
static void print (const char *path)
static void listdir (const char *path, int showheader)
static void recursedir (const char *path)
static void listitem (const char *path, int showheader)
int main (int argc, char *argv[])
Variables
static int aopt =0
static int dopt =0
static int lopt =0
static int Ropt =0
static int sopt =0
Function Documentation
basename()
static const char* basename (const char * path) static
Definition at line 76 of file ls.c.
References strrchr().
Referenced by print().
isdir()
static int isdir (const char * path) static
Definition at line 92 of file ls.c.
References buf, close(), err(), fd, fstat(), O_RDONLY, open(), and S_ISDIR.
Referenced by check_inode_blocks(), emufs_creat(), emufs_loadvnode(), emufs_lookup(), findsub(), listitem(), pass1_inode(), and recursedir().
listdir()
static void listdir (const char * path, int showheader) static
Definition at line 193 of file ls.c.
References aopt, buf, close(), err(), fd, getdirentry(), O_RDONLY, open(), print(), printheader(), and snprintf().
Referenced by listitem(), and recursedir().
listitem()
static void listitem (const char * path, int showheader) static
Definition at line 288 of file ls.c.
References dopt, isdir(), listdir(), print(), recursedir(), and Ropt.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 302 of file ls.c.
References listitem(), and option().
option()
static void option (int ch) static
Definition at line 58 of file ls.c.
References aopt, ch, dopt, errx(), lopt, Ropt, and sopt.
Referenced by main().
print()
static void print (const char * path) static
Definition at line 135 of file ls.c.
References basename(), close(), err(), fd, fstat(), lopt, O_RDONLY, open(), printf(), S_ISBLK, S_ISCHR, S_ISDIR, S_ISLNK, S_ISREG, sopt, stat::st_blocks, stat::st_mode, stat::st_nlink, and stat::st_size.
Referenced by listdir(), and listitem().
printheader()
static void printheader (const char * file) static
Definition at line 116 of file ls.c.
References printf().
Referenced by listdir().
recursedir()
static void recursedir (const char * path) static
Definition at line 236 of file ls.c.
References aopt, buf, close(), err(), fd, getdirentry(), isdir(), listdir(), O_RDONLY, open(), Ropt, snprintf(), and strcmp().
Referenced by listitem().
Variable Documentation
aopt
int aopt =0 static
Definition at line 49 of file ls.c.
Referenced by listdir(), option(), and recursedir().
dopt
int dopt =0 static
Definition at line 50 of file ls.c.
Referenced by listitem(), and option().
lopt
int lopt =0 static
Definition at line 51 of file ls.c.
Referenced by option(), and print().
Ropt
int Ropt =0 static
Definition at line 52 of file ls.c.
Referenced by listitem(), option(), and recursedir().
sopt
int sopt =0 static
Definition at line 53 of file ls.c.
Referenced by option(), and print().