os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/schedpong/main.c File Reference
main.c File Reference
#include <sys/types.h>
#include <sys/wait.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <err.h>
#include "usem.h"
#include "tasks.h"
#include "results.h"
Macros
#define STARTSEM "sem:start"
Functions
static void nop (unsigned groupid, unsigned count)
static unsigned dowait (pid_t pid)
static void runtaskgroup (unsigned count, void(*prep)(unsigned, unsigned), void(*task)(unsigned, unsigned), void(*cleanup)(unsigned, unsigned), unsigned groupid)
static void forkem (unsigned count, void(*prep)(unsigned, unsigned), void(*task)(unsigned, unsigned), void(*cleanup)(unsigned, unsigned), unsigned groupid, pid_t *retpid)
static void waitall (pid_t *pids, unsigned numpids)
static void calcresult (unsigned groupid, time_t startsecs, unsigned long startnsecs, char *buf, size_t bufmax)
void waitstart (void)
static void runit (unsigned numthinkers, unsigned numgrinders, unsigned numponggroups, unsigned ponggroupsize)
static void usage (const char *av0)
int main (int argc, char *argv[])
Variables
struct usem startsem
Macro Definition Documentation
STARTSEM
#define STARTSEM "sem:start"
Definition at line 44 of file main.c.
Function Documentation
calcresult()
static void calcresult (unsigned groupid, time_t startsecs, unsigned long startnsecs, char * buf, size_t bufmax) static
Definition at line 189 of file main.c.
References buf, getresult(), and snprintf().
Referenced by runit().
dowait()
static unsigned dowait (pid_t pid) static
Definition at line 64 of file main.c.
References err(), pid, waitpid(), warnx(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
Referenced by runtaskgroup(), and waitall().
forkem()
static void forkem (unsigned count, void(*)(unsigned, unsigned) prep, void(*)(unsigned, unsigned) task, void(*)(unsigned, unsigned) cleanup, unsigned groupid, pid_t * retpid) static
Definition at line 148 of file main.c.
References cleanup(), count, err(), fork(), prep(), and runtaskgroup().
Referenced by runit().
main()
int main (int argc, char * argv[])
Definition at line 290 of file main.c.
References atoi(), runit(), strcmp(), and usage().
nop()
static void nop (unsigned groupid, unsigned count) static
Definition at line 53 of file main.c.
References count.
Referenced by runit().
runit()
static void runit (unsigned numthinkers, unsigned numgrinders, unsigned numponggroups, unsigned ponggroupsize) static
Definition at line 223 of file main.c.
References __time(), buf, calcresult(), closeresultsfile(), createresultsfile(), destroyresultsfile(), forkem(), grind(), nop(), O_RDONLY, openresultsfile(), pids, pong(), pong_cleanup(), pong_prep(), printf(), startsem, STARTSEM, think(), usem_cleanup(), usem_close(), usem_init(), usem_open(), Vn(), and waitall().
Referenced by main().
runtaskgroup()
static void runtaskgroup (unsigned count, void(*)(unsigned, unsigned) prep, void(*)(unsigned, unsigned) task, void(*)(unsigned, unsigned) cleanup, unsigned groupid) static
Definition at line 89 of file main.c.
References __time(), cleanup(), closeresultsfile(), count, dowait(), err(), exit(), failures, fork(), O_WRONLY, openresultsfile(), prep(), and putresult().
Referenced by forkem().
usage()
static void usage (const char * av0) static
Definition at line 277 of file main.c.
References exit(), and warnx().
Referenced by main().
waitall()
static void waitall (pid_t * pids, unsigned numpids) static
Definition at line 171 of file main.c.
References dowait(), errx(), failures, and pids.
Referenced by runit().
waitstart()
void waitstart (void)
Definition at line 211 of file main.c.
References P(), startsem, usem_close(), and usem_open().
Referenced by grind(), pong(), and think().
Variable Documentation
startsem
struct usem startsem
Definition at line 46 of file main.c.
Referenced by runit(), and waitstart().