os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/common_fds.c File Reference
common_fds.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Macros
#define T(call, rw)
#define TC(call, rw)
Enumerations
enum rwtestmodes { RW_TEST_NONE, RW_TEST_RDONLY, RW_TEST_WRONLY }
Functions
static int read_badfd (int fd)
static int write_badfd (int fd)
static int close_badfd (int fd)
static int ioctl_badfd (int fd)
static int lseek_badfd (int fd)
static int fsync_badfd (int fd)
static int ftruncate_badfd (int fd)
static int fstat_badfd (int fd)
static int getdirentry_badfd (int fd)
static int dup2_badfd (int fd)
static void dup2_cleanup (void)
static void any_badfd (int(*func)(int fd), void(*cleanup)(void), const char *callname, int fd, const char *fddesc)
static void runtest (int(*func)(int fd), void(*cleanup)(void), const char *callname, enum rwtestmodes rw)
T (read, RW_TEST_WRONLY)
T (write, RW_TEST_RDONLY)
T (close, RW_TEST_NONE)
T (ioctl, RW_TEST_NONE)
T (lseek, RW_TEST_NONE)
T (fsync, RW_TEST_NONE)
T (ftruncate, RW_TEST_RDONLY)
T (fstat, RW_TEST_NONE)
T (getdirentry, RW_TEST_WRONLY)
TC (dup2, RW_TEST_NONE)
Macro Definition Documentation
T
#define T (call, rw)
Value:
  void                                          \
  test_##call##_fd(void)                        \
  {                                             \
    runtest(call##_badfd, NULL, #call, rw); \
  }
Definition at line 211 of file common_fds.c.
TC
#define TC (call, rw)
Value:
  void                                          \
  test_##call##_fd(void)                        \
  {                                             \
    runtest(call##_badfd, call##_cleanup, #call, rw);\
  }
Definition at line 218 of file common_fds.c.
Enumeration Type Documentation
rwtestmodes
enum rwtestmodes
Enumerator
RW_TEST_NONE
RW_TEST_RDONLY
RW_TEST_WRONLY
Definition at line 48 of file common_fds.c.
Function Documentation
any_badfd()
static void any_badfd (int(*)(int fd) func, void(*)(void) cleanup, const char * callname, int fd, const char * fddesc) static
Definition at line 142 of file common_fds.c.
References cleanup(), EBADF, errno, fd, report_begin(), and report_check().
Referenced by runtest().
close_badfd()
static int close_badfd (int fd) static
Definition at line 74 of file common_fds.c.
References close(), and fd.
dup2_badfd()
static int dup2_badfd (int fd) static
Definition at line 125 of file common_fds.c.
References CLOSED_FD, dup2(), and fd.
dup2_cleanup()
static void dup2_cleanup (void) static
Definition at line 133 of file common_fds.c.
References close(), and CLOSED_FD.
fstat_badfd()
static int fstat_badfd (int fd) static
Definition at line 109 of file common_fds.c.
References fd, fstat(), and sb.
fsync_badfd()
static int fsync_badfd (int fd) static
Definition at line 95 of file common_fds.c.
References fd, and fsync().
ftruncate_badfd()
static int ftruncate_badfd (int fd) static
Definition at line 102 of file common_fds.c.
References fd, and ftruncate().
getdirentry_badfd()
static int getdirentry_badfd (int fd) static
Definition at line 117 of file common_fds.c.
References buf, fd, and getdirentry().
ioctl_badfd()
static int ioctl_badfd (int fd) static
Definition at line 81 of file common_fds.c.
References fd, ioctl(), and NULL.
lseek_badfd()
static int lseek_badfd (int fd) static
Definition at line 88 of file common_fds.c.
References fd, lseek(), and SEEK_SET.
read_badfd()
static int read_badfd (int fd) static
Definition at line 56 of file common_fds.c.
References buf, fd, and read().
runtest()
static void runtest (int(*)(int fd) func, void(*)(void) cleanup, const char * callname, enum rwtestmodes rw) static
Definition at line 157 of file common_fds.c.
References any_badfd(), cleanup(), close(), CLOSED_FD, fd, IMPOSSIBLE_FD, O_CREAT, O_RDONLY, O_WRONLY, OPEN_MAX, reopen_testfile(), RW_TEST_RDONLY, RW_TEST_WRONLY, and warnx().
T() [1/9]
T (close , RW_TEST_NONE)
T() [2/9]
T (fstat , RW_TEST_NONE)
T() [3/9]
T (fsync , RW_TEST_NONE)
T() [4/9]
T (ftruncate , RW_TEST_RDONLY)
T() [5/9]
T (getdirentry , RW_TEST_WRONLY)
T() [6/9]
T (ioctl , RW_TEST_NONE)
T() [7/9]
T (lseek , RW_TEST_NONE)
T() [8/9]
T (read , RW_TEST_WRONLY)
T() [9/9]
T (write , RW_TEST_RDONLY)
TC()
TC (dup2 , RW_TEST_NONE)
write_badfd()
static int write_badfd (int fd) static
Definition at line 64 of file common_fds.c.
References buf, fd, memset(), and write().