os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/fs/semfs/semfs_vnops.c File Reference
semfs_vnops.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <stat.h>
#include <uio.h>
#include <synch.h>
#include <thread.h>
#include <proc.h>
#include <current.h>
#include <vfs.h>
#include <vnode.h>
#include "semfs.h"
Functions
static int semfs_eachopen (struct vnode *vn, int openflags)
static int semfs_ioctl (struct vnode *vn, int op, userptr_t data)
static int semfs_gettype (struct vnode *vn, mode_t *ret)
static bool semfs_isseekable (struct vnode *vn)
static int semfs_fsync (struct vnode *vn)
static struct semfs_sem * semfs_getsembynum (struct semfs *semfs, unsigned semnum)
static struct semfs_sem * semfs_getsem (struct semfs_vnode *semv)
static void semfs_wakeup (struct semfs_sem *sem, unsigned newcount)
static int semfs_semstat (struct vnode *vn, struct stat *buf)
static int semfs_read (struct vnode *vn, struct uio *uio)
static int semfs_write (struct vnode *vn, struct uio *uio)
static int semfs_truncate (struct vnode *vn, off_t len)
static int semfs_getdirentry (struct vnode *dirvn, struct uio *uio)
static int semfs_dirstat (struct vnode *vn, struct stat *buf)
static int semfs_namefile (struct vnode *vn, struct uio *uio)
static int semfs_creat (struct vnode *dirvn, const char *name, bool excl, mode_t mode, struct vnode **resultvn)
static int semfs_remove (struct vnode *dirvn, const char *name)
static int semfs_lookup (struct vnode *dirvn, char *path, struct vnode **resultvn)
static int semfs_lookparent (struct vnode *dirvn, char *path, struct vnode **resultdirvn, char *namebuf, size_t bufmax)
static void semfs_vnode_destroy (struct semfs_vnode *semv)
static int semfs_reclaim (struct vnode *vn)
static struct semfs_vnode * semfs_vnode_create (struct semfs *semfs, unsigned semnum)
int semfs_getvnode (struct semfs *semfs, unsigned semnum, struct vnode **ret)
Variables
static const struct vnode_ops semfs_dirops
static const struct vnode_ops semfs_semops
Function Documentation
semfs_creat()
static int semfs_creat (struct vnode * dirvn, const char * name, bool excl, mode_t mode, struct vnode ** resultvn) static
Definition at line 374 of file semfs_vnops.c.
References EEXIST, ENOMEM, lock_acquire(), lock_release(), name, NULL, num, semfs_direntry::semd_name, semfs_direntry::semd_semnum, semfs::semfs_dents, semfs_direntry_create(), semfs_direntry_destroy(), semfs::semfs_dirlock, semfs_getvnode(), semfs_sem_create(), semfs_sem_destroy(), semfs_sem_insert(), semfs::semfs_sems, semfs::semfs_tablelock, semfs_sem::sems_linked, semfs_vnode::semv_semfs, strcmp(), and vnode::vn_data.
semfs_dirstat()
static int semfs_dirstat (struct vnode * vn, struct stat * buf) static
Definition at line 336 of file semfs_vnops.c.
References buf, bzero(), lock_acquire(), lock_release(), S_IFDIR, semfs::semfs_dents, semfs::semfs_dirlock, SEMFS_ROOTDIR, semfs_vnode::semv_semfs, and vnode::vn_data.
semfs_eachopen()
static int semfs_eachopen (struct vnode * vn, int openflags) static
Definition at line 49 of file semfs_vnops.c.
References EISDIR, O_ACCMODE, O_APPEND, O_RDONLY, SEMFS_ROOTDIR, semfs_vnode::semv_semnum, and vnode::vn_data.
semfs_fsync()
static int semfs_fsync (struct vnode * vn) static
Definition at line 100 of file semfs_vnops.c.
semfs_getdirentry()
static int semfs_getdirentry (struct vnode * dirvn, struct uio * uio) static
Definition at line 303 of file semfs_vnops.c.
References KASSERT, lock_acquire(), lock_release(), num, pos, semfs_direntry::semd_name, semfs::semfs_dents, semfs::semfs_dirlock, semfs_vnode::semv_semfs, strlen(), uio::uio_offset, uiomove(), and vnode::vn_data.
semfs_getsem()
static struct semfs_sem* semfs_getsem (struct semfs_vnode * semv) static
Definition at line 128 of file semfs_vnops.c.
References semfs_getsembynum(), semfs_vnode::semv_semfs, and semfs_vnode::semv_semnum.
Referenced by semfs_read(), semfs_semstat(), semfs_truncate(), and semfs_write().
semfs_getsembynum()
static struct semfs_sem* semfs_getsembynum (struct semfs * semfs, unsigned semnum) static
Definition at line 115 of file semfs_vnops.c.
References lock_acquire(), lock_release(), semfs::semfs_sems, and semfs::semfs_tablelock.
Referenced by semfs_getsem(), and semfs_remove().
semfs_gettype()
static int semfs_gettype (struct vnode * vn, mode_t * ret) static
Definition at line 77 of file semfs_vnops.c.
References S_IFDIR, S_IFREG, SEMFS_ROOTDIR, semfs_vnode::semv_semnum, and vnode::vn_data.
semfs_getvnode()
int semfs_getvnode (struct semfs * semfs, unsigned semnum, struct vnode ** ret)
Definition at line 753 of file semfs_vnops.c.
References ENOMEM, KASSERT, lock_acquire(), lock_release(), NULL, num, SEMFS_ROOTDIR, semfs::semfs_sems, semfs::semfs_tablelock, semfs_vnode_create(), semfs_vnode_destroy(), semfs::semfs_vnodes, semfs_sem::sems_hasvnode, semfs_vnode::semv_absvn, semfs_vnode::semv_semnum, vnode::vn_data, and VOP_INCREF.
Referenced by semfs_creat(), semfs_getroot(), and semfs_lookup().
semfs_ioctl()
static int semfs_ioctl (struct vnode * vn, int op, userptr_t data) static
Definition at line 67 of file semfs_vnops.c.
References EINVAL.
semfs_isseekable()
static bool semfs_isseekable (struct vnode * vn) static
Definition at line 87 of file semfs_vnops.c.
References SEMFS_ROOTDIR, semfs_vnode::semv_semnum, and vnode::vn_data.
semfs_lookparent()
static int semfs_lookparent (struct vnode * dirvn, char * path, struct vnode ** resultdirvn, char * namebuf, size_t bufmax) static
Definition at line 564 of file semfs_vnops.c.
References ENAMETOOLONG, strcpy(), strlen(), and VOP_INCREF.
semfs_lookup()
static int semfs_lookup (struct vnode * dirvn, char * path, struct vnode ** resultvn) static
Definition at line 526 of file semfs_vnops.c.
References ENOENT, lock_acquire(), lock_release(), NULL, num, semfs_direntry::semd_name, semfs_direntry::semd_semnum, semfs::semfs_dents, semfs::semfs_dirlock, semfs_getvnode(), semfs_vnode::semv_semfs, strcmp(), vnode::vn_data, and VOP_INCREF.
semfs_namefile()
static int semfs_namefile (struct vnode * vn, struct uio * uio) static
Definition at line 362 of file semfs_vnops.c.
semfs_read()
static int semfs_read (struct vnode * vn, struct uio * uio) static
Definition at line 189 of file semfs_vnops.c.
References cv_wait(), DB_SEMFS, DEBUG, lock_acquire(), lock_release(), semfs_getsem(), semfs_sem::sems_count, semfs_sem::sems_cv, semfs_sem::sems_lock, semfs_vnode::semv_semnum, uio::uio_offset, uio::uio_resid, and vnode::vn_data.
semfs_reclaim()
static int semfs_reclaim (struct vnode * vn) static
Definition at line 596 of file semfs_vnops.c.
References EBUSY, KASSERT, lock_acquire(), lock_release(), NULL, num, SEMFS_ROOTDIR, semfs_sem_destroy(), semfs::semfs_sems, semfs::semfs_tablelock, semfs_vnode_destroy(), semfs::semfs_vnodes, semfs_sem::sems_hasvnode, semfs_sem::sems_linked, semfs_vnode::semv_semfs, semfs_vnode::semv_semnum, spinlock_acquire(), spinlock_release(), vnode::vn_countlock, vnode::vn_data, and vnode::vn_refcount.
semfs_remove()
static int semfs_remove (struct vnode * dirvn, const char * name) static
Definition at line 472 of file semfs_vnops.c.
References EINVAL, ENOENT, KASSERT, lock_acquire(), lock_release(), name, NULL, num, semfs_direntry::semd_name, semfs_direntry::semd_semnum, semfs::semfs_dents, semfs_direntry_destroy(), semfs::semfs_dirlock, semfs_getsembynum(), semfs_sem_destroy(), semfs::semfs_sems, semfs::semfs_tablelock, semfs_sem::sems_hasvnode, semfs_sem::sems_linked, semfs_sem::sems_lock, semfs_vnode::semv_semfs, strcmp(), and vnode::vn_data.
semfs_semstat()
static int semfs_semstat (struct vnode * vn, struct stat * buf) static
Definition at line 161 of file semfs_vnops.c.
References buf, bzero(), lock_acquire(), lock_release(), S_IFREG, semfs_getsem(), semfs_sem::sems_count, semfs_sem::sems_linked, semfs_sem::sems_lock, semfs_vnode::semv_semnum, and vnode::vn_data.
semfs_truncate()
static int semfs_truncate (struct vnode * vn, off_t len) static
Definition at line 267 of file semfs_vnops.c.
References EFBIG, EINVAL, lock_acquire(), lock_release(), semfs_getsem(), semfs_wakeup(), semfs_sem::sems_count, semfs_sem::sems_lock, and vnode::vn_data.
semfs_vnode_create()
static struct semfs_vnode* semfs_vnode_create (struct semfs * semfs, unsigned semnum) static
Definition at line 719 of file semfs_vnops.c.
References KASSERT, kmalloc(), NULL, semfs::semfs_absfs, semfs_dirops, SEMFS_ROOTDIR, semfs_semops, semfs_vnode::semv_absvn, semfs_vnode::semv_semfs, semfs_vnode::semv_semnum, and vnode_init().
Referenced by semfs_getvnode().
semfs_vnode_destroy()
static void semfs_vnode_destroy (struct semfs_vnode * semv) static
Definition at line 585 of file semfs_vnops.c.
References kfree(), semfs_vnode::semv_absvn, and vnode_cleanup().
Referenced by semfs_getvnode(), and semfs_reclaim().
semfs_wakeup()
static void semfs_wakeup (struct semfs_sem * sem, unsigned newcount) static
Definition at line 143 of file semfs_vnops.c.
References cv_broadcast(), cv_signal(), semfs_sem::sems_count, semfs_sem::sems_cv, and semfs_sem::sems_lock.
Referenced by semfs_truncate(), and semfs_write().
semfs_write()
static int semfs_write (struct vnode * vn, struct uio * uio) static
Definition at line 231 of file semfs_vnops.c.
References DB_SEMFS, DEBUG, EFBIG, lock_acquire(), lock_release(), semfs_getsem(), semfs_wakeup(), semfs_sem::sems_count, semfs_sem::sems_lock, semfs_vnode::semv_semnum, uio::uio_offset, uio::uio_resid, and vnode::vn_data.
Variable Documentation
semfs_dirops
const struct vnode_ops semfs_dirops static
Initial value:
= {
    .vop_magic = VOP_MAGIC,
    .vop_eachopen = semfs_eachopen,
    .vop_reclaim = semfs_reclaim,
    .vop_read = vopfail_uio_isdir,
    .vop_readlink = vopfail_uio_isdir,
    .vop_getdirentry = semfs_getdirentry,
    .vop_write = vopfail_uio_isdir,
    .vop_ioctl = semfs_ioctl,
    .vop_stat = semfs_dirstat,
    .vop_gettype = semfs_gettype,
    .vop_isseekable = semfs_isseekable,
    .vop_fsync = semfs_fsync,
    .vop_mmap = vopfail_mmap_isdir,
    .vop_truncate = vopfail_truncate_isdir,
    .vop_namefile = semfs_namefile,
    .vop_creat = semfs_creat,
    .vop_symlink = vopfail_symlink_nosys,
    .vop_mkdir = vopfail_mkdir_nosys,
    .vop_link = vopfail_link_nosys,
    .vop_remove = semfs_remove,
    .vop_rmdir = vopfail_string_nosys,
    .vop_rename = vopfail_rename_nosys,
    .vop_lookup = semfs_lookup,
    .vop_lookparent = semfs_lookparent,
}
Definition at line 651 of file semfs_vnops.c.
Referenced by semfs_vnode_create().
semfs_semops
const struct vnode_ops semfs_semops static
Initial value:
= {
    .vop_magic = VOP_MAGIC,
    .vop_eachopen = semfs_eachopen,
    .vop_reclaim = semfs_reclaim,
    .vop_read = semfs_read,
    .vop_readlink = vopfail_uio_inval,
    .vop_getdirentry = vopfail_uio_notdir,
    .vop_write = semfs_write,
    .vop_ioctl = semfs_ioctl,
    .vop_stat = semfs_semstat,
    .vop_gettype = semfs_gettype,
    .vop_isseekable = semfs_isseekable,
    .vop_fsync = semfs_fsync,
    .vop_mmap = vopfail_mmap_perm,
    .vop_truncate = semfs_truncate,
    .vop_namefile = vopfail_uio_notdir,
    .vop_creat = vopfail_creat_notdir,
    .vop_symlink = vopfail_symlink_notdir,
    .vop_mkdir = vopfail_mkdir_notdir,
    .vop_link = vopfail_link_notdir,
    .vop_remove = vopfail_string_notdir,
    .vop_rmdir = vopfail_string_notdir,
    .vop_rename = vopfail_rename_notdir,
    .vop_lookup = vopfail_lookup_notdir,
    .vop_lookparent = vopfail_lookparent_notdir,
}
Definition at line 684 of file semfs_vnops.c.
Referenced by semfs_vnode_create().