os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/rmdirtest/rmdirtest.c File Reference
rmdirtest.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <limits.h>
#include <err.h>
Functions
static void startup (void)
static void killdir (void)
static void finish (void)
static void test1 (void)
static void test2 (void)
static void test3 (void)
static void test4 (void)
static void test5 (void)
static void test6 (void)
static void test7 (void)
int main (void)
Variables
static const char testdir [] = "testdir"
static char startpoint [PATH_MAX - sizeof(testdir)]
Function Documentation
finish()
static void finish (void) static
Definition at line 102 of file rmdirtest.c.
References chdir(), err(), and startpoint.
Referenced by test1(), test2(), test3(), test4(), test5(), test6(), and test7().
killdir()
static void killdir (void) static
Definition at line 85 of file rmdirtest.c.
References err(), PATH_MAX, rmdir(), snprintf(), startpoint, and testdir.
Referenced by test1(), test2(), test3(), test4(), test5(), test6(), and test7().
main()
int main (void)
Definition at line 392 of file rmdirtest.c.
References printf(), test1(), test2(), test3(), test4(), test5(), test6(), and test7().
startup()
static void startup (void) static
Definition at line 60 of file rmdirtest.c.
References chdir(), err(), getcwd(), mkdir(), NULL, startpoint, and testdir.
Referenced by test1(), test2(), test3(), test4(), test5(), test6(), and test7().
test1()
static void test1 (void) static
Definition at line 117 of file rmdirtest.c.
References finish(), killdir(), printf(), startup(), and testdir.
Referenced by main().
test2()
static void test2 (void) static
Definition at line 135 of file rmdirtest.c.
References close(), err(), fd, finish(), killdir(), O_RDONLY, open(), printf(), startup(), and testdir.
Referenced by main().
test3()
static void test3 (void) static
Definition at line 160 of file rmdirtest.c.
References buf, close(), EINVAL, EIO, ENOENT, err(), errno, errx(), fd, finish(), killdir(), O_RDONLY, open(), PATH_MAX, printf(), snprintf(), startup(), testdir, and warnx().
Referenced by main().
test4()
static void test4 (void) static
Definition at line 228 of file rmdirtest.c.
References buf, close(), EINVAL, EIO, ENOENT, err(), errno, fd, finish(), killdir(), memset(), O_CREAT, O_TRUNC, O_WRONLY, open(), printf(), startup(), warnx(), and write().
Referenced by main().
test5()
static void test5 (void) static
Definition at line 273 of file rmdirtest.c.
References EINVAL, EIO, ENOENT, err(), errno, finish(), killdir(), mkdir(), printf(), startup(), and warnx().
Referenced by main().
test6()
static void test6 (void) static
Definition at line 313 of file rmdirtest.c.
References buf, close(), EINVAL, EIO, err(), errno, errx(), fd, finish(), getdirentry(), killdir(), O_RDONLY, open(), PATH_MAX, printf(), startup(), strcmp(), and testdir.
Referenced by main().
test7()
static void test7 (void) static
Definition at line 364 of file rmdirtest.c.
References buf, EINVAL, EIO, ENOENT, err(), errno, errx(), finish(), getcwd(), killdir(), NULL, PATH_MAX, startup(), and testdir.
Referenced by main().
Variable Documentation
startpoint
char startpoint[PATH_MAX - sizeof(testdir)] static
Definition at line 51 of file rmdirtest.c.
Referenced by finish(), killdir(), and startup().
testdir
const char testdir[] = "testdir" static
Definition at line 50 of file rmdirtest.c.
Referenced by killdir(), startup(), test1(), test2(), test3(), test6(), and test7().