os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/vm/copyinout.c File Reference
copyinout.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <lib.h>
#include <setjmp.h>
#include <thread.h>
#include <current.h>
#include <vm.h>
#include <copyinout.h>
Functions
static void copyfail (void)
static int copycheck (const_userptr_t userptr, size_t len, size_t *stoplen)
int copyin (const_userptr_t usersrc, void *dest, size_t len)
int copyout (const void *src, userptr_t userdest, size_t len)
static int copystr (char *dest, const char *src, size_t maxlen, size_t stoplen, size_t *gotlen)
int copyinstr (const_userptr_t usersrc, char *dest, size_t len, size_t *actual)
int copyoutstr (const char *src, userptr_t userdest, size_t len, size_t *actual)
Function Documentation
copycheck()
static int copycheck (const_userptr_t userptr, size_t len, size_t * stoplen) static
Definition at line 118 of file copyinout.c.
References EFAULT, and USERSPACETOP.
Referenced by copyin(), copyinstr(), copyout(), and copyoutstr().
copyfail()
static void copyfail (void) static
Definition at line 100 of file copyinout.c.
References longjmp().
Referenced by copyin(), copyinstr(), copyout(), and copyoutstr().
copyin()
int copyin (const_userptr_t usersrc, void * dest, size_t len)
Definition at line 153 of file copyinout.c.
References copycheck(), copyfail(), EFAULT, memcpy(), NULL, and setjmp().
Referenced by uiomove().
copyinstr()
int copyinstr (const_userptr_t usersrc, char * dest, size_t len, size_t * actual)
Definition at line 266 of file copyinout.c.
References copycheck(), copyfail(), copystr(), EFAULT, NULL, and setjmp().
copyout()
int copyout (const void * src, userptr_t userdest, size_t len)
Definition at line 189 of file copyinout.c.
References copycheck(), copyfail(), EFAULT, memcpy(), NULL, and setjmp().
Referenced by sys___time(), and uiomove().
copyoutstr()
int copyoutstr (const char * src, userptr_t userdest, size_t len, size_t * actual)
Definition at line 299 of file copyinout.c.
References copycheck(), copyfail(), copystr(), EFAULT, NULL, and setjmp().
copystr()
static int copystr (char * dest, const char * src, size_t maxlen, size_t stoplen, size_t * gotlen) static
Definition at line 235 of file copyinout.c.
References EFAULT, ENAMETOOLONG, and NULL.
Referenced by copyinstr(), and copyoutstr().