os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/proc/proc.c File Reference
proc.c File Reference
#include <types.h>
#include <spl.h>
#include <proc.h>
#include <current.h>
#include <addrspace.h>
#include <vnode.h>
Functions
static struct proc * proc_create (const char *name)
void proc_destroy (struct proc *proc)
void proc_bootstrap (void)
struct proc * proc_create_runprogram (const char *name)
int proc_addthread (struct proc *proc, struct thread *t)
void proc_remthread (struct thread *t)
struct addrspace * proc_getas (void)
struct addrspace * proc_setas (struct addrspace *newas)
Variables
struct proc * kproc
Function Documentation
proc_addthread()
int proc_addthread (struct proc * proc, struct thread * t)
Definition at line 234 of file proc.c.
References KASSERT, NULL, proc::p_lock, proc::p_numthreads, spinlock_acquire(), spinlock_release(), splhigh(), splx(), and thread::t_proc.
Referenced by cpu_create(), and thread_fork().
proc_bootstrap()
void proc_bootstrap (void)
Definition at line 179 of file proc.c.
References kproc, NULL, panic(), and proc_create().
Referenced by boot().
proc_create()
static struct proc* proc_create (const char * name) static
Definition at line 62 of file proc.c.
References kfree(), kmalloc(), kstrdup(), name, NULL, proc::p_addrspace, proc::p_cwd, proc::p_lock, proc::p_name, proc::p_numthreads, and spinlock_init().
Referenced by proc_bootstrap(), and proc_create_runprogram().
proc_create_runprogram()
struct proc* proc_create_runprogram (const char * name)
Definition at line 194 of file proc.c.
References curproc, name, NULL, proc::p_addrspace, proc::p_cwd, proc_create(), spinlock_acquire(), spinlock_release(), and VOP_INCREF.
Referenced by common_prog().
proc_destroy()
void proc_destroy (struct proc * proc)
Definition at line 95 of file proc.c.
References as_deactivate(), as_destroy(), curproc, KASSERT, kfree(), kproc, NULL, proc::p_addrspace, proc::p_cwd, proc::p_lock, proc::p_name, proc::p_numthreads, proc_setas(), spinlock_cleanup(), and VOP_DECREF.
Referenced by common_prog().
proc_getas()
struct addrspace* proc_getas (void)
Definition at line 288 of file proc.c.
References curproc, NULL, proc::p_addrspace, proc::p_lock, spinlock_acquire(), and spinlock_release().
Referenced by as_activate(), load_elf(), runprogram(), uiomove(), and vm_fault().
proc_remthread()
void proc_remthread (struct thread * t)
Definition at line 261 of file proc.c.
References KASSERT, NULL, proc::p_lock, proc::p_numthreads, spinlock_acquire(), spinlock_release(), splhigh(), splx(), and thread::t_proc.
Referenced by thread_exit().
proc_setas()
struct addrspace* proc_setas (struct addrspace * newas)
Definition at line 308 of file proc.c.
References curproc, KASSERT, NULL, proc::p_addrspace, proc::p_lock, spinlock_acquire(), and spinlock_release().
Referenced by proc_destroy(), and runprogram().
Variable Documentation
kproc
struct proc* kproc
Definition at line 55 of file proc.c.
Referenced by cpu_create(), proc_bootstrap(), proc_destroy(), and thread_bootstrap().