os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/test/arraytest.c File Reference
arraytest.c File Reference
#include <types.h>
#include <lib.h>
#include <array.h>
#include <test.h>
Macros
#define TESTSIZE 73
#define BIGTESTSIZE 3000 /* more than one page of pointers */
#define NTH(i) ((void *)(0xb007 + 3*(i)))
Functions
static void testa (struct array *a)
int arraytest (int nargs, char **args)
int arraytest2 (int nargs, char **args)
Macro Definition Documentation
BIGTESTSIZE
#define BIGTESTSIZE 3000 /* more than one page of pointers */
Definition at line 36 of file arraytest.c.
NTH
#define NTH (i) ((void *)(0xb007 + 3*(i)))
Definition at line 37 of file arraytest.c.
TESTSIZE
#define TESTSIZE 73
Definition at line 35 of file arraytest.c.
Function Documentation
arraytest()
int arraytest (int nargs, char ** args)
Definition at line 124 of file arraytest.c.
References array_create(), array_destroy(), array_setsize(), KASSERT, kprintf(), NULL, and testa().
arraytest2()
int arraytest2 (int nargs, char ** args)
Definition at line 149 of file arraytest.c.
References array_add(), array_create(), array_destroy(), array_get(), array_num(), array_remove(), array_set(), array_setsize(), BIGTESTSIZE, KASSERT, kprintf(), NTH, and NULL.
testa()
static void testa (struct array * a) static
Definition at line 41 of file arraytest.c.
References array_add(), array_get(), array_num(), array_remove(), array_set(), array_setsize(), KASSERT, NULL, random(), and TESTSIZE.
Referenced by arraytest().