os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/schedpong/tasks.h File Reference
tasks.h File Reference
Functions
void waitstart (void)
void think (unsigned groupid, unsigned id)
void grind (unsigned groupid, unsigned id)
void pong_prep (unsigned groupid, unsigned count)
void pong_cleanup (unsigned groupid, unsigned count)
void pong (unsigned groupid, unsigned id)
Function Documentation
grind()
void grind (unsigned groupid, unsigned id)
Definition at line 144 of file grind.c.
References altcmp(), diffs(), ENOSYS, err(), errno, errx(), malloc(), NULL, qsort(), random(), RIGHT, srandom(), sum(), uintcmp(), waitstart(), and warnx().
pong()
void pong (unsigned groupid, unsigned id)
Definition at line 185 of file pong.c.
References nsems, pong_cyclic(), pong_reciprocating(), printf(), sems, usem_close(), usem_open(), and waitstart().
Referenced by runit().
pong_cleanup()
void pong_cleanup (unsigned groupid, unsigned count)
Definition at line 73 of file pong.c.
References assert, count, nsems, sems, and usem_cleanup().
Referenced by runit().
pong_prep()
void pong_prep (unsigned groupid, unsigned count)
Definition at line 59 of file pong.c.
References count, err(), MAXCOUNT, nsems, sems, and usem_init().
Referenced by runit().
think()
void think (unsigned groupid, unsigned id)
Definition at line 39 of file think.c.
References LOOPCOUNT, and waitstart().
Referenced by runit().
waitstart()
void waitstart (void)
Definition at line 211 of file main.c.
References P(), startsem, usem_close(), and usem_open().
Referenced by grind(), pong(), and think().