os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_execv.c File Reference
bad_execv.c File Reference
#include <sys/types.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static int exec_common_fork (void)
static void exec_badprog (const void *prog, const char *desc)
static void exec_emptyprog (void)
static void exec_badargs (void *args, const char *desc)
static void exec_onearg (void *ptr, const char *desc)
void test_execv (void)
Function Documentation
exec_badargs()
static void exec_badargs (void * args, const char * desc) static
Definition at line 131 of file bad_execv.c.
References desc, EFAULT, errno, exec_common_fork(), execv(), exit(), MAGIC_STATUS, report_begin(), and report_check().
Referenced by test_execv().
exec_badprog()
static void exec_badprog (const void * prog, const char * desc) static
Definition at line 93 of file bad_execv.c.
References desc, EFAULT, errno, exec_common_fork(), execv(), exit(), MAGIC_STATUS, NULL, report_begin(), and report_check().
Referenced by test_execv().
exec_common_fork()
static int exec_common_fork (void) static
Definition at line 45 of file bad_execv.c.
References err(), errno, fork(), MAGIC_STATUS, pid, report_aborted(), report_begin(), report_failure(), report_result(), report_warnx(), waitpid(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
Referenced by exec_badargs(), exec_badprog(), exec_emptyprog(), and exec_onearg().
exec_emptyprog()
static void exec_emptyprog (void) static
Definition at line 112 of file bad_execv.c.
References EINVAL, EISDIR, errno, exec_common_fork(), execv(), exit(), MAGIC_STATUS, NULL, report_begin(), and report_check2().
Referenced by test_execv().
exec_onearg()
static void exec_onearg (void * ptr, const char * desc) static
Definition at line 147 of file bad_execv.c.
References desc, EFAULT, errno, exec_common_fork(), execv(), exit(), MAGIC_STATUS, NULL, report_begin(), and report_check().
Referenced by test_execv().
test_execv()
void test_execv (void)
Definition at line 167 of file bad_execv.c.
References exec_badargs(), exec_badprog(), exec_emptyprog(), exec_onearg(), and NULL.