os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/vm.h File Reference
vm.h File Reference
#include <machine/vm.h>
Macros
#define VM_FAULT_READ 0 /* A read was attempted */
#define VM_FAULT_WRITE 1 /* A write was attempted */
#define VM_FAULT_READONLY 2 /* A write to a readonly page was attempted*/
Functions
void vm_bootstrap (void)
int vm_fault (int faulttype, vaddr_t faultaddress)
vaddr_t alloc_kpages (unsigned npages)
void free_kpages (vaddr_t addr)
void vm_tlbshootdown (const struct tlbshootdown *)
Macro Definition Documentation
VM_FAULT_READ
#define VM_FAULT_READ 0 /* A read was attempted */
Definition at line 43 of file vm.h.
VM_FAULT_READONLY
#define VM_FAULT_READONLY 2 /* A write to a readonly page was attempted*/
Definition at line 45 of file vm.h.
VM_FAULT_WRITE
#define VM_FAULT_WRITE 1 /* A write was attempted */
Definition at line 44 of file vm.h.
Function Documentation
alloc_kpages()
vaddr_t alloc_kpages (unsigned npages)
Definition at line 109 of file dumbvm.c.
References dumbvm_can_sleep(), getppages(), and PADDR_TO_KVADDR.
Referenced by allocpagerefpage(), kmalloc(), and subpage_kmalloc().
free_kpages()
void free_kpages (vaddr_t addr)
Definition at line 122 of file dumbvm.c.
Referenced by allocpagerefpage(), kfree(), subpage_kfree(), and subpage_kmalloc().
vm_bootstrap()
void vm_bootstrap (void)
Definition at line 68 of file dumbvm.c.
Referenced by boot().
vm_fault()
int vm_fault (int faulttype, vaddr_t faultaddress)
Definition at line 137 of file dumbvm.c.
References curproc, DB_VM, DEBUG, DUMBVM_STACKPAGES, EFAULT, EINVAL, KASSERT, kprintf(), NULL, NUM_TLB, PAGE_FRAME, PAGE_SIZE, panic(), proc_getas(), splhigh(), splx(), tlb_read(), tlb_write(), TLBLO_DIRTY, TLBLO_VALID, USERSTACK, VM_FAULT_READ, VM_FAULT_READONLY, and VM_FAULT_WRITE.
Referenced by mips_trap().
vm_tlbshootdown()
void vm_tlbshootdown (const struct tlbshootdown *)
Definition at line 130 of file dumbvm.c.
References panic().
Referenced by interprocessor_interrupt().