os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/include/fs.h File Reference
fs.h File Reference
Data Structures
struct fs
struct fs_ops
Macros
#define FSOP_SYNC(fs) ((fs)->fs_ops->fsop_sync(fs))
#define FSOP_GETVOLNAME(fs) ((fs)->fs_ops->fsop_getvolname(fs))
#define FSOP_GETROOT(fs, ret) ((fs)->fs_ops->fsop_getroot(fs, ret))
#define FSOP_UNMOUNT(fs) ((fs)->fs_ops->fsop_unmount(fs))
Functions
void semfs_bootstrap (void)
Macro Definition Documentation
FSOP_GETROOT
#define FSOP_GETROOT (fs, ret) ((fs)->fs_ops->fsop_getroot(fs, ret))
Definition at line 84 of file fs.h.
FSOP_GETVOLNAME
#define FSOP_GETVOLNAME (fs) ((fs)->fs_ops->fsop_getvolname(fs))
Definition at line 83 of file fs.h.
FSOP_SYNC
#define FSOP_SYNC (fs) ((fs)->fs_ops->fsop_sync(fs))
Definition at line 82 of file fs.h.
FSOP_UNMOUNT
#define FSOP_UNMOUNT (fs) ((fs)->fs_ops->fsop_unmount(fs))
Definition at line 85 of file fs.h.
Function Documentation
semfs_bootstrap()
void semfs_bootstrap (void)
Definition at line 213 of file semfs_fsops.c.
References NULL, panic(), semfs::semfs_absfs, semfs_create(), strerror(), and vfs_addfs().
Referenced by vfs_bootstrap().