os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/arch/mips/include/trapframe.h File Reference
trapframe.h File Reference
Data Structures
struct trapframe
Macros
#define EX_IRQ 0 /* Interrupt */
#define EX_MOD 1 /* TLB Modify (write to read-only page) */
#define EX_TLBL 2 /* TLB miss on load */
#define EX_TLBS 3 /* TLB miss on store */
#define EX_ADEL 4 /* Address error on load */
#define EX_ADES 5 /* Address error on store */
#define EX_IBE 6 /* Bus error on instruction fetch */
#define EX_DBE 7 /* Bus error on data load *or* store */
#define EX_SYS 8 /* Syscall */
#define EX_BP 9 /* Breakpoint */
#define EX_RI 10 /* Reserved (illegal) instruction */
#define EX_CPU 11 /* Coprocessor unusable */
#define EX_OVF 12 /* Arithmetic overflow */
Functions
__DEAD void mips_usermode (struct trapframe *tf)
Variables
vaddr_t cpustacks []
vaddr_t cputhreads []
Macro Definition Documentation
EX_ADEL
#define EX_ADEL 4 /* Address error on load */
Definition at line 85 of file trapframe.h.
EX_ADES
#define EX_ADES 5 /* Address error on store */
Definition at line 86 of file trapframe.h.
EX_BP
#define EX_BP 9 /* Breakpoint */
Definition at line 90 of file trapframe.h.
EX_CPU
#define EX_CPU 11 /* Coprocessor unusable */
Definition at line 92 of file trapframe.h.
EX_DBE
#define EX_DBE 7 /* Bus error on data load *or* store */
Definition at line 88 of file trapframe.h.
EX_IBE
#define EX_IBE 6 /* Bus error on instruction fetch */
Definition at line 87 of file trapframe.h.
EX_IRQ
#define EX_IRQ 0 /* Interrupt */
Definition at line 81 of file trapframe.h.
EX_MOD
#define EX_MOD 1 /* TLB Modify (write to read-only page) */
Definition at line 82 of file trapframe.h.
EX_OVF
#define EX_OVF 12 /* Arithmetic overflow */
Definition at line 93 of file trapframe.h.
EX_RI
#define EX_RI 10 /* Reserved (illegal) instruction */
Definition at line 91 of file trapframe.h.
EX_SYS
#define EX_SYS 8 /* Syscall */
Definition at line 89 of file trapframe.h.
EX_TLBL
#define EX_TLBL 2 /* TLB miss on load */
Definition at line 83 of file trapframe.h.
EX_TLBS
#define EX_TLBS 3 /* TLB miss on store */
Definition at line 84 of file trapframe.h.
Function Documentation
mips_usermode()
__DEAD void mips_usermode (struct trapframe * tf)
Definition at line 368 of file trap.c.
References asm_usermode(), cpu_irqoff(), cpustacks, cputhreads, KASSERT, SAME_STACK, spl0(), and STACK_SIZE.
Referenced by enter_new_process().
Variable Documentation
cpustacks
vaddr_t cpustacks[]
Definition at line 67 of file cpu.c.
Referenced by cpu_machdep_init(), mips_trap(), and mips_usermode().
cputhreads
vaddr_t cputhreads[]
Definition at line 68 of file cpu.c.
Referenced by cpu_machdep_init(), mips_trap(), and mips_usermode().