os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/badcall/bad_time.c File Reference
bad_time.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include "config.h"
#include "test.h"
Functions
static void time_badsecs (void *ptr, const char *desc)
static void time_badnsecs (void *ptr, const char *desc)
void test_time (void)
Function Documentation
test_time()
void test_time (void)
Definition at line 69 of file bad_time.c.
References time_badnsecs(), and time_badsecs().
time_badnsecs()
static void time_badnsecs (void * ptr, const char * desc) static
Definition at line 59 of file bad_time.c.
References __time(), desc, EFAULT, errno, NULL, report_begin(), and report_check().
Referenced by test_time().
time_badsecs()
static void time_badsecs (void * ptr, const char * desc) static
Definition at line 48 of file bad_time.c.
References __time(), desc, EFAULT, errno, NULL, report_begin(), and report_check().
Referenced by test_time().