os161-doc: /home/os161user/os161/os161-base-2.0.3/build/install/include/unistd.h File Reference
unistd.h File Reference
#include <sys/cdefs.h>
#include <sys/types.h>
#include <kern/fcntl.h>
#include <kern/ioctl.h>
#include <kern/reboot.h>
#include <kern/seek.h>
#include <kern/time.h>
#include <kern/unistd.h>
#include <kern/wait.h>
Functions
__DEAD void _exit (int code)
int execv (const char *prog, char *const *args)
pid_t fork (void)
pid_t waitpid (pid_t pid, int *returncode, int flags)
int open (const char *filename, int flags,...)
ssize_t read (int filehandle, void *buf, size_t size)
ssize_t write (int filehandle, const void *buf, size_t size)
int close (int filehandle)
int reboot (int code)
int sync (void)
int rmdir (const char *dirname)
pid_t getpid (void)
int ioctl (int filehandle, int code, void *buf)
off_t lseek (int filehandle, off_t pos, int code)
int fsync (int filehandle)
int ftruncate (int filehandle, off_t size)
int remove (const char *filename)
int rename (const char *oldfile, const char *newfile)
int link (const char *oldfile, const char *newfile)
int chdir (const char *path)
void * sbrk (__intptr_t change)
ssize_t getdirentry (int filehandle, char *buf, size_t buflen)
int symlink (const char *target, const char *linkname)
ssize_t readlink (const char *path, char *buf, size_t buflen)
int dup2 (int filehandle, int newhandle)
int pipe (int filehandles[2])
int __time (time_t *seconds, unsigned long *nanoseconds)
ssize_t __getcwd (char *buf, size_t buflen)
int execvp (const char *prog, char *const *args)
char * getcwd (char *buf, size_t buflen)
time_t time (time_t *seconds)
Function Documentation
__getcwd()
ssize_t __getcwd (char * buf, size_t buflen)
Referenced by getcwd(), getcwd_badbuf(), and try___getcwd().
__time()
int __time (time_t * seconds, unsigned long * nanoseconds)
Definition at line 41 of file time.c.
_exit()
__DEAD void _exit (int code)
Referenced by abort(), basetest(), cat(), conctest(), docommand(), dorm(), exit(), forkoff(), hostcompat_die(), lseek_file_stdin(), runop(), spawn(), system(), wait_parent(), and wait_siblings().
chdir()
int chdir (const char * path)
Referenced by chdir_badpath(), chdir_empty(), checkallfilecontents(), cleanup(), cmd_chdir(), do_chdir(), do_chdirup(), finish(), inspectdir(), setup(), startup(), and try_chdir().
close()
int close (int filehandle)
Referenced by big_file(), cat(), checkonefilecontents(), close_badfd(), closedisk(), closefiles(), closeit(), closeresultsfile(), concur(), copy(), create_testfile(), createresultsfile(), do_closedir(), do_closefile(), doclose(), dorm(), dup2_cleanup(), dup2_fd2(), dup2_self(), ftruncate_fd_device(), ftruncate_size_neg(), getdirentry_cleanup(), getseed(), getsize(), inspectdir(), isdir(), listdir(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), main(), mkfile(), open_empty(), open_testfile(), pipe_unaligned(), print(), read_cleanup(), readfile(), readlink_file(), recursedir(), runtest(), semclose(), semcreate(), subproc_read(), subproc_write(), test2(), test3(), test4(), test6(), try_close(), usem_close(), usem_init(), wait_siblings(), wait_siblings_child(), write_cleanup(), and xstat().
dup2()
int dup2 (int filehandle, int newhandle)
Referenced by assemble(), dodup2(), dup2_badfd(), dup2_fd2(), dup2_self(), lseek_file_stdin(), and try_dup2().
execv()
int execv (const char * prog, char *const * args)
Referenced by assemble(), cat(), exec_badargs(), exec_badprog(), exec_emptyprog(), exec_onearg(), execvp(), self(), spawn(), spawnv(), system(), try(), try_execv(), and trymany().
execvp()
int execvp (const char * prog, char *const * args)
Definition at line 42 of file execvp.c.
Referenced by docommand().
fork()
pid_t fork (void)
Referenced by basetest(), cat(), conctest(), docommand(), dofork(), dorm(), exec_common_fork(), forkem(), forkoff(), lseek_file_stdin(), main(), makeprocs(), runop(), runtaskgroup(), spawn(), spawnv(), system(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), wait_badflags(), wait_badstatus(), wait_nullstatus(), wait_parent(), wait_siblings(), and wait_unaligned().
fsync()
int fsync (int filehandle)
Referenced by fsync_badfd(), and try_fsync().
ftruncate()
int ftruncate (int filehandle, off_t size)
Referenced by do_truncate(), ftruncate_badfd(), ftruncate_fd_device(), ftruncate_size_neg(), and try_ftruncate().
getcwd()
char* getcwd (char * buf, size_t buflen)
Definition at line 40 of file getcwd.c.
Referenced by main(), startup(), and test7().
getdirentry()
ssize_t getdirentry (int filehandle, char * buf, size_t buflen)
Referenced by getdirentry_badbuf(), getdirentry_badfd(), inspectdir(), inval_read(), listdir(), readateof(), readit(), readone(), recursedir(), test6(), and try_getdirentry().
getpid()
pid_t getpid (void)
Referenced by check(), cleanup_rmdir(), domkdir(), dorename(), dormdir(), go(), hostcompat_die(), hostcompat_stop(), main(), mkdir_proc(), openfiles(), recursive_cleanup(), rename_proc(), rmdir_proc(), semcreate(), wait_parent(), wait_self(), wait_siblings(), and wait_siblings_child().
ioctl()
int ioctl (int filehandle, int code, void * buf)
Referenced by ioctl_badcode(), ioctl_badfd(), one_ioctl_badbuf(), and try_ioctl().
link()
int link (const char * oldfile, const char * newfile)
Referenced by do_link(), dohardlink(), link_badpath1(), link_badpath2(), link_dir(), link_empty1(), link_empty2(), and try_link().
lseek()
off_t lseek (int filehandle, off_t pos, int code)
Referenced by checkfilezeros(), diskread(), diskwrite(), do_write(), dobadreads(), dolseek(), doreadat0(), doreadateof(), doreadone(), dup2_self(), firstread(), getresult(), getsize(), lseek_badfd(), lseek_fd_device(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), main(), open_testfile(), putresult(), readfiledata(), readit(), tail(), try_lseek(), and wait_siblings_child().
open()
int open (const char * filename, int flags, ...)
Referenced by big_file(), cat(), checkonefilecontents(), concur(), copy(), createresultsfile(), dir_test(), do_createfile(), do_opendir(), do_openfile(), doopen(), ftruncate_fd_device(), getdirentry_setup(), getseed(), inspectdir(), isdir(), listdir(), lseek_fd_device(), main(), mkfile(), open_badflags(), open_badpath(), open_empty(), open_testfile(), opendisk(), openit(), openresultsfile(), openscratch(), print(), readfile(), recursedir(), reopen_testfile(), semcreate(), semopen(), subproc_read(), subproc_write(), test2(), test3(), test4(), test6(), try_open(), usem_init(), usem_open(), wait_siblings(), wait_siblings_child(), and xstat().
pipe()
int pipe (int filehandles[2])
Referenced by pipe_badptr(), pipe_unaligned(), and try_pipe().
read()
ssize_t read (int filehandle, void * buf, size_t size)
Referenced by big_file(), check_slogan(), checkfilezeros(), chkfile(), copy(), diskread(), docat(), doread(), getchar(), getresult(), getseed(), main(), opendisk(), P(), Pn(), read_badbuf(), read_badfd(), readfiledata(), semP(), subproc_read(), tail(), test6(), try_read(), try_reading(), and wait_siblings_child().
readlink()
ssize_t readlink (const char * path, char * buf, size_t buflen)
Referenced by readlink_badbuf(), readlink_badpath(), readlink_dir(), readlink_empty(), readlink_file(), and try_readlink().
reboot()
int reboot (int code)
Referenced by main(), and reboot_badflags().
remove()
int remove (const char * filename)
Referenced by big_file(), cleanup(), common_badpath(), concur(), destroyresultsfile(), dir_test(), do_unlink(), doremove(), dorm(), ftruncate_size_neg(), link_dir(), lseek_file_stdin(), lseek_loc_negative(), lseek_loc_pasteof(), lseek_whence_inval(), main(), open_testfile(), openscratch(), read_cleanup(), readlink_cleanup(), readlink_file(), remove_badpath(), remove_dir(), remove_dot(), remove_dotdot(), remove_empty(), rmdir_file(), semdestroy(), symlink_empty1(), try_remove(), usem_cleanup(), wait_siblings(), and write_cleanup().
rename()
int rename (const char * oldfile, const char * newfile)
Referenced by do_rename(), do_renamexd(), dorename(), rename_badpath1(), rename_badpath2(), rename_dot(), rename_dotdot(), rename_empty1(), rename_empty2(), and try_rename().
rmdir()
int rmdir (const char * dirname)
Referenced by cleanup(), cleanup_rmdir(), dir_test(), do_rmdir(), dormdir(), killdir(), link_empty2(), main(), recursive_cleanup(), remove_dir(), rename_empty2(), rmdir_badpath(), rmdir_dot(), rmdir_dotdot(), rmdir_empty(), rmdir_file(), try_rmdir(), and unsetdir().
sbrk()
void* sbrk (__intptr_t change)
Referenced by __malloc_init(), __malloc_sbrk(), check_sbrk(), dosbrk(), moremem(), setup(), test10(), test9(), and try_sbrk().
symlink()
int symlink (const char * target, const char * linkname)
Referenced by create_testlink(), dosymlink(), symlink_badpath1(), symlink_badpath2(), symlink_empty1(), symlink_empty2(), and try_symlink().
sync()
int sync (void)
Referenced by do_sync(), and main().
time()
time_t time (time_t * seconds)
Definition at line 39 of file time.c.
waitpid()
pid_t waitpid (pid_t pid, int * returncode, int flags)
Referenced by cat(), docommand(), dorm(), dowait(), exec_common_fork(), lseek_file_stdin(), makeprocs(), run(), runop(), spawn(), system(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), wait_badflags(), wait_badpid(), wait_badstatus(), wait_nullstatus(), wait_parent(), wait_self(), wait_siblings(), wait_siblings_child(), wait_unaligned(), and waitall().
write()
ssize_t write (int filehandle, const void * buf, size_t size)
Referenced by __bad_assert(), __printf_send(), __puts(), __senderr(), big_file(), complain(), complainx(), concur(), copy(), diskwrite(), do_write(), docat(), dotest(), dowrite(), flush(), lseek_file_stdin(), main(), mkfile(), open_testfile(), putchar(), putresult(), say(), semV(), subproc_write(), tail(), test4(), try_write(), V(), Vn(), wait_siblings(), write_badbuf(), write_badfd(), and write_slogan().