os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/sbin/sfsck/freemap.c File Reference
freemap.c File Reference
#include <sys/types.h>
#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <assert.h>
#include <err.h>
#include "compat.h"
#include <kern/sfs.h>
#include "utils.h"
#include "sfs.h"
#include "sb.h"
#include "freemap.h"
#include "main.h"
Functions
void freemap_setup (void)
static const char * blockusagestr (blockusage_t how, uint32_t howdesc)
void freemap_blockinuse (uint32_t block, blockusage_t how, uint32_t howdesc)
void freemap_blockfree (uint32_t block)
static int countbits (uint8_t val)
static void reportfreemap (uint32_t mapblock, uint32_t byte, uint8_t val, const char *what)
void freemap_check (void)
unsigned long freemap_blocksused (void)
Variables
static unsigned long blocksinuse = 0
static uint8_t * freemapdata
static uint8_t * tofreedata
Function Documentation
blockusagestr()
static const char* blockusagestr (blockusage_t how, uint32_t howdesc) static
Definition at line 88 of file freemap.c.
References B_DATA, B_DIRDATA, B_FREEMAPBLOCK, B_IBLOCK, B_INODE, B_PASTEND, B_SUPERBLOCK, and snprintf().
Referenced by freemap_blockinuse().
countbits()
static int countbits (uint8_t val) static
Definition at line 183 of file freemap.c.
Referenced by freemap_check().
freemap_blockfree()
void freemap_blockfree (uint32_t block)
Definition at line 162 of file freemap.c.
References freemapdata, and tofreedata.
Referenced by check_indirect_block(), and check_inode_blocks().
freemap_blockinuse()
void freemap_blockinuse (uint32_t block, blockusage_t how, uint32_t howdesc)
Definition at line 127 of file freemap.c.
References B_PASTEND, blocksinuse, blockusagestr(), EXIT_UNRECOV, freemapdata, setbadness(), tofreedata, and warnx().
Referenced by check_indirect_block(), check_inode_blocks(), freemap_setup(), and pass1_inode().
freemap_blocksused()
unsigned long freemap_blocksused (void)
Definition at line 307 of file freemap.c.
References blocksinuse.
Referenced by main().
freemap_check()
void freemap_check (void)
Definition at line 225 of file freemap.c.
References assert, countbits(), EXIT_RECOV, freemapdata, reportfreemap(), sb_freemapblocks(), setbadness(), SFS_BLOCKSIZE, sfs_readfreemapblock(), sfs_writefreemapblock(), tofreedata, and warnx().
Referenced by main().
freemap_setup()
void freemap_setup (void)
Definition at line 56 of file freemap.c.
References B_FREEMAPBLOCK, B_PASTEND, B_SUPERBLOCK, domalloc(), freemap_blockinuse(), freemapdata, sb_freemapblocks(), sb_totalblocks(), SFS_BITSPERBLOCK, SFS_BLOCKSIZE, SFS_FREEMAP_START, SFS_SUPER_BLOCK, and tofreedata.
Referenced by main().
reportfreemap()
static void reportfreemap (uint32_t mapblock, uint32_t byte, uint8_t val, const char * what) static
Definition at line 203 of file freemap.c.
References CHAR_BIT, SFS_BITSPERBLOCK, and warnx().
Referenced by freemap_check().
Variable Documentation
blocksinuse
unsigned long blocksinuse = 0 static
Definition at line 46 of file freemap.c.
Referenced by freemap_blockinuse(), and freemap_blocksused().
freemapdata
uint8_t* freemapdata static
Definition at line 47 of file freemap.c.
Referenced by freemap_blockfree(), freemap_blockinuse(), freemap_check(), freemap_setup(), and sfs_freemapio().
tofreedata
uint8_t* tofreedata static
Definition at line 48 of file freemap.c.
Referenced by freemap_blockfree(), freemap_blockinuse(), freemap_check(), and freemap_setup().