os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/f_test/f_hdr.h File Reference
f_hdr.h File Reference
Functions
void subproc_read (void)
void subproc_write (void)
Function Documentation
subproc_read()
void subproc_read (void)
Definition at line 77 of file f_read.c.
References buffer, check_buffer(), close(), err(), errx(), fd, FNAME, O_RDONLY, open(), printf(), read(), SectorSize, and TMULT.
Referenced by concur().
subproc_write()
void subproc_write (void)
Definition at line 61 of file f_write.c.
References buffer, close(), err(), fd, FNAME, O_WRONLY, open(), printf(), SectorSize, TMULT, write(), and WRITECHAR.
Referenced by concur().