os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/randcall/main.c File Reference
main.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "extern.h"
Functions
static void randchar (char *c)
static void fillrand (void *p, size_t len)
void * randptr (void)
int randint (void)
off_t randoff (void)
size_t randsize (void)
static void usage (void)
int main (int argc, char *argv[])
Function Documentation
fillrand()
static void fillrand (void * p, size_t len) static
Definition at line 71 of file main.c.
References randchar().
Referenced by randint(), randoff(), randptr(), and randsize().
main()
int main (int argc, char * argv[])
Definition at line 124 of file main.c.
References atoi(), count, dofork(), printf(), srandom(), strcmp(), trycalls(), and usage().
randchar()
static void randchar (char * c) static
Definition at line 38 of file main.c.
References CHAR_BIT, and random().
Referenced by fillrand().
randint()
int randint (void)
Definition at line 89 of file main.c.
References fillrand().
Referenced by try_close(), try_dup2(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_lseek(), try_mkdir(), try_open(), try_read(), try_waitpid(), and try_write().
randoff()
off_t randoff (void)
Definition at line 97 of file main.c.
References fillrand().
Referenced by try_ftruncate(), and try_lseek().
randptr()
void* randptr (void)
Definition at line 81 of file main.c.
References fillrand().
Referenced by try___getcwd(), try___time(), try_chdir(), try_execv(), try_fstat(), try_getdirentry(), try_ioctl(), try_link(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), and try_write().
randsize()
size_t randsize (void)
Definition at line 105 of file main.c.
References fillrand().
usage()
static void usage (void) static
Definition at line 114 of file main.c.
References exit(), and printf().
Referenced by main().