os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/frack/workloads.h File Reference
workloads.h File Reference
Functions
void wl_createwrite (const char *size)
void wl_rewrite (const char *size)
void wl_randupdate (const char *size)
void wl_truncwrite (const char *size)
void wl_makehole (const char *size)
void wl_fillhole (const char *size)
void wl_truncfill (const char *size)
void wl_append (const char *size)
void wl_trunczero (const char *size)
void wl_trunconeblock (const char *size)
void wl_truncsmallersize (const char *size)
void wl_trunclargersize (const char *size)
void wl_appendandtrunczero (const char *size)
void wl_appendandtruncpartly (const char *size)
void wl_mkfile (void)
void wl_mkdir (void)
void wl_mkmanyfile (void)
void wl_mkmanydir (void)
void wl_mktree (void)
void wl_mkrandtree (const char *seed)
void wl_rmfile (void)
void wl_rmdir (void)
void wl_rmfiledelayed (void)
void wl_rmfiledelayedappend (void)
void wl_rmdirdelayed (void)
void wl_rmmanyfile (void)
void wl_rmmanyfiledelayed (void)
void wl_rmmanyfiledelayedandappend (void)
void wl_rmmanydir (void)
void wl_rmmanydirdelayed (void)
void wl_rmtree (void)
void wl_rmrandtree (const char *seed)
void wl_linkfile (void)
void wl_linkmanyfile (void)
void wl_unlinkfile (void)
void wl_unlinkmanyfile (void)
void wl_linkunlinkfile (void)
void wl_renamefile (void)
void wl_renamedir (void)
void wl_renamesubtree (void)
void wl_renamexdfile (void)
void wl_renamexddir (void)
void wl_renamexdsubtree (void)
void wl_renamemanyfile (void)
void wl_renamemanydir (void)
void wl_renamemanysubtree (void)
void wl_copyandrename (void)
void wl_untar (void)
void wl_compile (void)
void wl_cvsupdate (void)
void wl_writefileseq (const char *seed)
void wl_writetruncseq (const char *seed)
void wl_mkrmseq (const char *seed)
void wl_linkunlinkseq (const char *seed)
void wl_renameseq (const char *seed)
void wl_diropseq (const char *seed)
void wl_genseq (const char *seed)
Function Documentation
wl_append()
void wl_append (const char * size)
Definition at line 458 of file workloads.c.
References BLOCKSIZE, f, op_close(), op_open(), op_sync(), op_write(), sizebytes(), strtosize(), file::testcode, and writenewfile().
wl_appendandtruncpartly()
void wl_appendandtruncpartly (const char * size)
Definition at line 576 of file workloads.c.
References BLOCKSIZE, f, op_close(), op_open(), op_sync(), op_truncate(), op_write(), sizebytes(), strtosize(), file::testcode, and writenewfile().
wl_appendandtrunczero()
void wl_appendandtrunczero (const char * size)
Definition at line 555 of file workloads.c.
References BLOCKSIZE, f, op_close(), op_open(), op_sync(), op_truncate(), op_write(), sizebytes(), strtosize(), file::testcode, and writenewfile().
wl_compile()
void wl_compile (void)
Definition at line 1319 of file workloads.c.
References errx(), op_sync(), SIZE_MEDIUM, SIZE_SMALL, and writenewfile().
wl_copyandrename()
void wl_copyandrename (void)
Definition at line 1291 of file workloads.c.
References op_rename(), op_sync(), SIZE_MEDIUM, writeemptyfile(), and writenewfile().
wl_createwrite()
void wl_createwrite (const char * size)
Definition at line 330 of file workloads.c.
References strtosize(), file::testcode, and writenewfile().
wl_cvsupdate()
void wl_cvsupdate (void)
Definition at line 1343 of file workloads.c.
References errx().
wl_diropseq()
void wl_diropseq (const char * seed)
Definition at line 1745 of file workloads.c.
References getnum(), NULL, op_sync(), prep(), random(), randop(), srandom(), and file::testcode.
wl_fillhole()
void wl_fillhole (const char * size)
Definition at line 415 of file workloads.c.
References f, file_randomwrite(), op_close(), op_open(), op_sync(), srandom(), strtosize(), file::testcode, and writeholeyfile().
wl_genseq()
void wl_genseq (const char * seed)
Definition at line 1772 of file workloads.c.
References getnum(), op_sync(), prep(), random(), randop(), srandom(), and file::testcode.
wl_linkfile()
void wl_linkfile (void)
Definition at line 1052 of file workloads.c.
References op_link(), op_sync(), SIZE_ONE, and writenewfile().
wl_linkmanyfile()
void wl_linkmanyfile (void)
Definition at line 1065 of file workloads.c.
References op_link(), op_sync(), SIZE_ONE, and writenewfile().
wl_linkunlinkfile()
void wl_linkunlinkfile (void)
Definition at line 1126 of file workloads.c.
References op_link(), op_sync(), op_unlink(), SIZE_ONE, and writenewfile().
wl_linkunlinkseq()
void wl_linkunlinkseq (const char * seed)
Definition at line 1511 of file workloads.c.
References getnum(), op_link(), op_sync(), op_unlink(), random(), SIZE_ONE, srandom(), file::testcode, and writenewfile().
wl_makehole()
void wl_makehole (const char * size)
Definition at line 400 of file workloads.c.
References strtosize(), file::testcode, and writeholeyfile().
wl_mkdir()
void wl_mkdir (void)
Definition at line 611 of file workloads.c.
References op_mkdir().
wl_mkfile()
void wl_mkfile (void)
Definition at line 600 of file workloads.c.
References SIZE_ONE, file::testcode, and writenewfile().
wl_mkmanydir()
void wl_mkmanydir (void)
Definition at line 635 of file workloads.c.
References op_mkdir().
wl_mkmanyfile()
void wl_mkmanyfile (void)
Definition at line 620 of file workloads.c.
References SIZE_ONE, file::testcode, and writenewfile().
wl_mkrandtree()
void wl_mkrandtree (const char * seed)
Definition at line 769 of file workloads.c.
References count, getnum(), mkrandtree_sub(), random(), srandom(), and file::testcode.
wl_mkrmseq()
void wl_mkrmseq (const char * seed)
Definition at line 1477 of file workloads.c.
References getnum(), op_unlink(), random(), SIZE_ONE, srandom(), file::testcode, and writenewfile().
wl_mktree()
void wl_mktree (void)
Definition at line 692 of file workloads.c.
References file::testcode, and wl_mktree_sub().
wl_randupdate()
void wl_randupdate (const char * size)
Definition at line 362 of file workloads.c.
References f, file_randomwrite(), op_close(), op_open(), op_sync(), srandom(), strtosize(), file::testcode, and writenewfile().
wl_renamedir()
void wl_renamedir (void)
Definition at line 1157 of file workloads.c.
References op_mkdir(), op_rename(), op_sync(), and writeemptyfile().
wl_renamefile()
void wl_renamefile (void)
Definition at line 1143 of file workloads.c.
References op_rename(), op_sync(), SIZE_ONE, writeemptyfile(), and writenewfile().
wl_renamemanydir()
void wl_renamemanydir (void)
Definition at line 1251 of file workloads.c.
References op_mkdir(), op_rename(), op_sync(), and writeemptyfile().
wl_renamemanyfile()
void wl_renamemanyfile (void)
Definition at line 1232 of file workloads.c.
References op_rename(), op_sync(), SIZE_ONE, writeemptyfile(), and writenewfile().
wl_renamemanysubtree()
void wl_renamemanysubtree (void)
Definition at line 1269 of file workloads.c.
References makesubtree(), op_rename(), op_sync(), and writeemptyfile().
wl_renameseq()
void wl_renameseq (const char * seed)
Definition at line 1550 of file workloads.c.
References getnum(), op_rename(), op_sync(), random(), SIZE_ONE, srandom(), file::testcode, and writenewfile().
wl_renamesubtree()
void wl_renamesubtree (void)
Definition at line 1169 of file workloads.c.
References makesubtree(), op_rename(), op_sync(), and writeemptyfile().
wl_renamexddir()
void wl_renamexddir (void)
Definition at line 1200 of file workloads.c.
References op_chdir(), op_chdirup(), op_mkdir(), op_renamexd(), and op_sync().
wl_renamexdfile()
void wl_renamexdfile (void)
Definition at line 1183 of file workloads.c.
References op_chdir(), op_chdirup(), op_mkdir(), op_renamexd(), op_sync(), SIZE_ONE, and writenewfile().
wl_renamexdsubtree()
void wl_renamexdsubtree (void)
Definition at line 1215 of file workloads.c.
References makesubtree(), op_chdir(), op_chdirup(), op_mkdir(), op_renamexd(), and op_sync().
wl_rewrite()
void wl_rewrite (const char * size)
Definition at line 345 of file workloads.c.
References op_sync(), strtosize(), file::testcode, writenewfile(), and writeoutfile().
wl_rmdir()
void wl_rmdir (void)
Definition at line 803 of file workloads.c.
References op_mkdir(), op_rmdir(), op_sync(), and writeemptyfile().
wl_rmdirdelayed()
void wl_rmdirdelayed (void)
Definition at line 855 of file workloads.c.
References op_closedir(), op_mkdir(), op_opendir(), op_rmdir(), op_sync(), and writeemptyfile().
wl_rmfile()
void wl_rmfile (void)
Definition at line 789 of file workloads.c.
References op_sync(), op_unlink(), SIZE_ONE, file::testcode, writeemptyfile(), and writenewfile().
wl_rmfiledelayed()
void wl_rmfiledelayed (void)
Definition at line 818 of file workloads.c.
References f, op_close(), op_open(), op_sync(), op_unlink(), SIZE_ONE, file::testcode, writeemptyfile(), and writenewfile().
wl_rmfiledelayedappend()
void wl_rmfiledelayedappend (void)
Definition at line 836 of file workloads.c.
References BLOCKSIZE, f, op_close(), op_open(), op_sync(), op_unlink(), op_write(), SIZE_SMALL, sizebytes(), file::testcode, writeemptyfile(), and writenewfile().
wl_rmmanydir()
void wl_rmmanydir (void)
Definition at line 966 of file workloads.c.
References op_mkdir(), op_rmdir(), op_sync(), and writeemptyfile().
wl_rmmanydirdelayed()
void wl_rmmanydirdelayed (void)
Definition at line 985 of file workloads.c.
References op_closedir(), op_mkdir(), op_opendir(), op_rmdir(), op_sync(), and writeemptyfile().
wl_rmmanyfile()
void wl_rmmanyfile (void)
Definition at line 871 of file workloads.c.
References op_sync(), op_unlink(), SIZE_ONE, writeemptyfile(), and writenewfile().
wl_rmmanyfiledelayed()
void wl_rmmanyfiledelayed (void)
Definition at line 891 of file workloads.c.
References op_close(), op_open(), op_sync(), op_unlink(), SIZE_ONE, file::testcode, writeemptyfile(), and writenewfile().
wl_rmmanyfiledelayedandappend()
void wl_rmmanyfiledelayedandappend (void)
Definition at line 921 of file workloads.c.
References assert, BLOCKSIZE, op_close(), op_open(), op_sync(), op_unlink(), op_write(), SIZE_SMALL, sizebytes(), file::testcode, writeemptyfile(), and writenewfile().
wl_rmrandtree()
void wl_rmrandtree (const char * seed)
Definition at line 1024 of file workloads.c.
References assert, count, getnum(), mkrandtree_sub(), op_sync(), random(), rmrandtree_sub(), and srandom().
wl_rmtree()
void wl_rmtree (void)
Definition at line 1011 of file workloads.c.
References op_sync(), wl_mktree_sub(), and wl_rmtree_sub().
wl_truncfill()
void wl_truncfill (const char * size)
Definition at line 435 of file workloads.c.
References f, file_randomwrite(), O_CREAT, O_EXCL, op_close(), op_open(), op_sync(), op_truncate(), sizebytes(), srandom(), strtosize(), and file::testcode.
wl_trunclargersize()
void wl_trunclargersize (const char * size)
Definition at line 536 of file workloads.c.
References f, nextlargersize(), op_close(), op_open(), op_sync(), op_truncate(), sizebytes(), strtosize(), file::testcode, and writenewfile().
wl_trunconeblock()
void wl_trunconeblock (const char * size)
Definition at line 499 of file workloads.c.
References BLOCKSIZE, f, op_close(), op_open(), op_sync(), op_truncate(), sizebytes(), strtosize(), file::testcode, and writenewfile().
wl_truncsmallersize()
void wl_truncsmallersize (const char * size)
Definition at line 518 of file workloads.c.
References f, nextsmallersize(), op_close(), op_open(), op_sync(), op_truncate(), sizebytes(), strtosize(), file::testcode, and writenewfile().
wl_truncwrite()
void wl_truncwrite (const char * size)
Definition at line 383 of file workloads.c.
References O_TRUNC, op_sync(), strtosize(), file::testcode, writenewfile(), and writeoutfile().
wl_trunczero()
void wl_trunczero (const char * size)
Definition at line 480 of file workloads.c.
References f, op_close(), op_open(), op_sync(), op_truncate(), strtosize(), file::testcode, and writenewfile().
wl_unlinkfile()
void wl_unlinkfile (void)
Definition at line 1083 of file workloads.c.
References op_link(), op_sync(), op_unlink(), SIZE_ONE, writeemptyfile(), and writenewfile().
wl_unlinkmanyfile()
void wl_unlinkmanyfile (void)
Definition at line 1098 of file workloads.c.
References op_link(), op_sync(), op_unlink(), SIZE_ONE, writeemptyfile(), and writenewfile().
wl_untar()
void wl_untar (void)
Definition at line 1307 of file workloads.c.
References makesubtree().
wl_writefileseq()
void wl_writefileseq (const char * seed)
Definition at line 1403 of file workloads.c.
References createfiles(), getnum(), NULL, O_CREAT, O_EXCL, op_open(), op_sync(), openfiles(), random(), randwrite(), SIZE_MEDIUM, srandom(), and file::testcode.
wl_writetruncseq()
void wl_writetruncseq (const char * seed)
Definition at line 1438 of file workloads.c.
References createfiles(), getnum(), NULL, O_CREAT, O_EXCL, op_open(), op_sync(), openfiles(), random(), randtruncate(), randwrite(), SIZE_MEDIUM, srandom(), and file::testcode.