os161-doc: /home/os161user/os161/os161-base-2.0.3/userland/testbin/crash/crash.c File Reference
crash.c File Reference
#include <stdio.h>
#include <stdint.h>
#include <unistd.h>
#include <signal.h>
#include <err.h>
Macros
#define MAGIC 123456
Typedefs
typedef void(* func) (void)
Functions
static void read_from_null (void)
static void read_from_inval (void)
static void read_from_kernel (void)
static void write_to_null (void)
static void write_to_inval (void)
static void write_to_code (void)
static void write_to_kernel (void)
static void jump_to_null (void)
static void jump_to_inval (void)
static void jump_to_kernel (void)
static void illegal_instruction (void)
static void alignment_error (void)
static void divide_by_zero (void)
static void mod_by_zero (void)
static void recurse_inf (void)
static void runop (int op)
static void ask (void)
int main (int argc, char **argv)
Variables
static int forking = 1
struct {
int ch
const char * name
func f
int sig
} ops []
Macro Definition Documentation
MAGIC
#define MAGIC 123456
Definition at line 59 of file crash.c.
Typedef Documentation
func
typedef void(* func) (void)
Definition at line 61 of file crash.c.
Function Documentation
alignment_error()
static void alignment_error (void) static
Definition at line 174 of file crash.c.
ask()
static void ask (void) static
Definition at line 346 of file crash.c.
References ch, getchar(), name, ops, printf(), and runop().
Referenced by main().
divide_by_zero()
static void divide_by_zero (void) static
Definition at line 200 of file crash.c.
illegal_instruction()
static void illegal_instruction (void) static
Definition at line 163 of file crash.c.
jump_to_inval()
static void jump_to_inval (void) static
Definition at line 146 of file crash.c.
References f.
jump_to_kernel()
static void jump_to_kernel (void) static
Definition at line 154 of file crash.c.
References f.
jump_to_null()
static void jump_to_null (void) static
Definition at line 138 of file crash.c.
References f, and NULL.
main()
int main (int argc, char ** argv)
Definition at line 373 of file crash.c.
References ask(), and runop().
mod_by_zero()
static void mod_by_zero (void) static
Definition at line 214 of file crash.c.
read_from_inval()
static void read_from_inval (void) static
Definition at line 80 of file crash.c.
read_from_kernel()
static void read_from_kernel (void) static
Definition at line 93 of file crash.c.
read_from_null()
static void read_from_null (void) static
Definition at line 67 of file crash.c.
References NULL.
recurse_inf()
static void recurse_inf (void) static
Definition at line 228 of file crash.c.
References buf.
runop()
static void runop (int op) static
Definition at line 268 of file crash.c.
References _exit(), ch, err(), errx(), fork(), forking, MAGIC, name, ok(), ops, pid, printf(), sig, waitpid(), warnx(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
Referenced by ask(), and main().
write_to_code()
static void write_to_code (void) static
Definition at line 122 of file crash.c.
write_to_inval()
static void write_to_inval (void) static
Definition at line 114 of file crash.c.
write_to_kernel()
static void write_to_kernel (void) static
Definition at line 130 of file crash.c.
write_to_null()
static void write_to_null (void) static
Definition at line 106 of file crash.c.
References NULL.
Variable Documentation
ch
int ch
Definition at line 243 of file crash.c.
Referenced by ask(), and runop().
f
func f
Definition at line 245 of file crash.c.
Referenced by jump_to_inval(), jump_to_kernel(), and jump_to_null().
forking
int forking = 1 static
Definition at line 63 of file crash.c.
Referenced by runop().
name
const char* name
Definition at line 244 of file crash.c.
Referenced by ask(), and runop().
ops
struct { ... } ops[]
Initial value:
= {
    { 'a', "read from NULL",            read_from_null,      SIGSEGV },
    { 'b', "read from invalid address", read_from_inval,     SIGSEGV },
    { 'c', "read from kernel address",  read_from_kernel,    SIGBUS },
    { 'd', "write to NULL",             write_to_null,       SIGSEGV },
    { 'e', "write to invalid address",  write_to_inval,      SIGSEGV },
    { 'f', "write to code segment",     write_to_code,       SIGSEGV },
    { 'g', "write to kernel address",   write_to_kernel,     SIGBUS },
    { 'h', "jump to NULL",              jump_to_null,        SIGSEGV },
    { 'i', "jump to invalid address",   jump_to_inval,       SIGSEGV },
    { 'j', "jump to kernel address",    jump_to_kernel,      SIGBUS },
    { 'k', "alignment error",           alignment_error,     SIGBUS },
    { 'l', "illegal instruction",       illegal_instruction, SIGILL },
    { 'm', "divide by zero",            divide_by_zero,      SIGTRAP },
    { 'n', "mod by zero",               mod_by_zero,         SIGTRAP },
    { 'o', "Recurse infinitely",        recurse_inf,         SIGSEGV },
    { 0, NULL, NULL, 0 }
}
Referenced by ask(), and runop().
sig
int sig
Definition at line 246 of file crash.c.
Referenced by hostcompat_cont(), hostcompat_die(), hostcompat_stop(), kill_curthread(), and runop().