os161-doc: /home/os161user/os161/os161-base-2.0.3/common/libc/string/strtok_r.c File Reference
strtok_r.c File Reference
#include <string.h>
Functions
char * strtok_r (char *string, const char *seps, char **context)
Function Documentation
strtok_r()
char* strtok_r (char * string, const char * seps, char ** context)
Definition at line 50 of file strtok_r.c.
References NULL, seps, strchr(), and tail().
Referenced by cmd_dispatch(), menu_execute(), and strtok().