os161-doc: /home/os161user/os161/os161-base-2.0.3/kern/vfs/vfspath.c File Reference
vfspath.c File Reference
#include <types.h>
#include <kern/errno.h>
#include <kern/fcntl.h>
#include <limits.h>
#include <lib.h>
#include <vfs.h>
#include <vnode.h>
Functions
int vfs_open (char *path, int openflags, mode_t mode, struct vnode **ret)
void vfs_close (struct vnode *vn)
int vfs_remove (char *path)
int vfs_rename (char *oldpath, char *newpath)
int vfs_link (char *oldpath, char *newpath)
int vfs_symlink (const char *contents, char *path)
int vfs_readlink (char *path, struct uio *uio)
int vfs_mkdir (char *path, mode_t mode)
int vfs_rmdir (char *path)
Function Documentation
vfs_close()
void vfs_close (struct vnode * vn)
Definition at line 116 of file vfspath.c.
References VOP_DECREF.
Referenced by createstress_thread(), dowritestress2(), fstest_read(), fstest_write(), printfile(), and runprogram().
vfs_link()
int vfs_link (char * oldpath, char * newpath)
Definition at line 191 of file vfspath.c.
References EXDEV, NAME_MAX, NULL, vfs_lookparent(), vfs_lookup(), vnode::vn_fs, VOP_DECREF, and VOP_LINK.
vfs_mkdir()
int vfs_mkdir (char * path, mode_t mode)
Definition at line 277 of file vfspath.c.
References name, NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_MKDIR.
vfs_open()
int vfs_open (char * path, int openflags, mode_t mode, struct vnode ** ret)
Definition at line 45 of file vfspath.c.
References EINVAL, KASSERT, name, NAME_MAX, NULL, O_ACCMODE, O_CREAT, O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, vfs_lookparent(), vfs_lookup(), VOP_CREAT, VOP_DECREF, VOP_EACHOPEN, and VOP_TRUNCATE.
Referenced by createstress_thread(), dowritestress2(), fstest_read(), fstest_write(), printfile(), and runprogram().
vfs_readlink()
int vfs_readlink (char * path, struct uio * uio)
Definition at line 256 of file vfspath.c.
References vfs_lookup(), VOP_DECREF, and VOP_READLINK.
vfs_remove()
int vfs_remove (char * path)
Definition at line 137 of file vfspath.c.
References name, NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_REMOVE.
Referenced by fstest_remove(), and fstest_write().
vfs_rename()
int vfs_rename (char * oldpath, char * newpath)
Definition at line 156 of file vfspath.c.
References EXDEV, NAME_MAX, NULL, vfs_lookparent(), vnode::vn_fs, VOP_DECREF, and VOP_RENAME.
vfs_rmdir()
int vfs_rmdir (char * path)
Definition at line 299 of file vfspath.c.
References name, NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_RMDIR.
vfs_symlink()
int vfs_symlink (const char * contents, char * path)
Definition at line 231 of file vfspath.c.
References NAME_MAX, vfs_lookparent(), VOP_DECREF, and VOP_SYMLINK.